dotnet/java-interop

Makefile
build-tools/scripts/mono.mk
src/java-interop/java-interop.mdproj

Now there is MonoInfo.props which is similar to JdkInfo.props.
OSX detection is as hacky as xamarin-android so far.
Recreating PR due to fork management failure at github after open-sourcing.

Add Linux build support.

---

src/Xamarin.Android.Tools.Bytecode/Tests/Xamarin.Android.Tools.Bytecode-Tests.csproj

Copy `nunit.framework.dll` to `$(OutputPath)` for
`Xamarin.Android.Tools.Bytecode-Tests` so `nunit.framework.dll` can be
found when running "out of tree" `nunit-console.exe` invocations:
$ ANDROID_SDK_PATH=... mono \
path/to/Java.Interop/packages/NUnit.Runners.2.6.3/tools/nunit-console.exe \
path/to/Java.Interop/bin/TestDebug/Xamarin.Android.Tools.Bytecode-Tests.dll
Can't find custom attr constructor image: path/to/Java.Interop/bin/TestDebug/Xamarin.Android.Tools.Bytecode-Tests.dll mtoken: 0x0a000017
...which makes me sad. :-(
Remove the `%(Reference.Private)` metadata so that `nunit.framework.dll`
is copied to `$(OutputPath)`, fixing the above error.

[Xamarin.Android.Tools.Bytecode-Tests] Copy nunit.framework to $(OutputPath)

---

build-tools/scripts/mono.mk

Commit be86e93f broke the OS X build, as `$(JI_MONO_FRAMEWORK_PATH)` was
set to a location which didn't exist.
Fix the `$(JI_MONO_FRAMEWORK_PATH)` value on OS X to a valid location.

[build-tools] Fix $(JI_MONO_FRAMEWORK_PATH) for OS X.

---

src/Xamarin.Android.Tools.Bytecode/ClassPath.cs
tools/class-parse/Program.cs

Import class-parse changes from monodroid/a438c473.
Add `class-parse --docstype=TYPE` option, to control the *type* of the
HTML Javadocs provided via `class-parse --docspath`.
This allows using a Java 6, Java 7, or Java 8 documentation scraper
instead of an Android documentation scraper.

[Xamarin.Android.Tools.bytecode] Add JavaDoc importing

---

src/Java.Interop.Tools.JavaCallableWrappers/Java.Interop.Tools.JavaCallableWrappers/JavaCallableWrapperGenerator.cs

android.app.Application is special: Android contructs it before the
mono runtime has been initialized, requiring that the
[activation constructor][0] be used for all Android.App.Application
subclasses:
[Application]
partial class MyApp : Android.App.Application {
public MyApp (IntPtr r, JniHandleOwnership transfer)
: base (r, transfer)
{
}
}
As a consequence of this, the Android.App.Application..ctor() default
constructor *is never used in normal use*, which means that the linker
is free to remove it.
This in turn means that in Release (linked) apps, *no* constructor
would be present in the `MyApp` Java Callable Wrappers, because
constructor generation requires that the binding assembly contain the
constructor to emit.
This is kinda/sorta fine, in that the Java compiler-provided default …

[Java.Interop.Tools.JavaCallableWrappers] Fix android.app.Application

---

tools/logcat-parse/Grefs.cs
tools/logcat-parse/PeerInfo.cs
tools/logcat-parse/Tests/GrefsTest.cs
tools/logcat-parse/Tests/LogcatParse-Tests.csproj
tools/logcat-parse/Tests/Resources/stdio-repeated-handles.txt

I've come across some log files which would contain *several thousand*
global references, as per the `grefc` values, but when processing via
logcat-parse `grefs.AlivePeers.Count()` would invariably return `11`,
or some other ludicrously low value given the input.
On further investigation, a problem is with repeated handle values.
Once a handle has been disposed, there's no reason why it couldn't be
reused again:
+g+ grefc 1 gwrefc 0 obj-handle 0x4a00009/L -> new-handle 0x19004aa/G from thread '(null)'(3)
-g- grefc 0 gwrefc 0 handle 0x19004aa/G from thread '(null)'(3)
+g+ grefc 1 gwrefc 0 obj-handle 0x4a00009/L -> new-handle 0x19004aa/G from thread '(null)'(3)
Unfortunately, `logcat-parse` would treat the second +g+ as if it were
an alias of the originally created instance. As such, …

[logcat-parse] Support repeated handles.

---

tools/generator/ClassGen.cs
tools/generator/CodeGenerator.cs
tools/generator/GenBase.cs
tools/generator/GenericTypeParameter.cs
tools/generator/InterfaceGen.cs
tools/generator/Method.cs
tools/generator/Parameter.cs
tools/generator/ParameterList.cs
tools/generator/StreamSymbol.cs
tools/generator/Tests/expected.ji/TestInterface/Test.ME.ITestInterface.cs
tools/generator/Tests/expected.ji/TestInterface/Test.ME.TestInterfaceImplementation.cs
tools/generator/Tests/expected/TestInterface/Test.ME.ITestInterface.cs
tools/generator/Tests/expected/TestInterface/Test.ME.TestInterfaceImplementation.cs
tools/generator/XamarinAndroidCodeGenerator.cs

Migrate multiple generator fixes from monodroid/a438c473.

[generator] Upgrade generator from monodroid/a438c473

---

Java.Interop.sln
Makefile
src/Java.Interop.Tools.JavaCallableWrappers/Java.Interop.Tools.JavaCallableWrappers/JavaCallableWrapperGenerator.cs
src/Java.Interop.Tools.JavaCallableWrappers/Test/Java.Interop.Tools.JavaCallableWrappers-Tests.csproj
src/Java.Interop.Tools.JavaCallableWrappers/Test/Java.Interop.Tools.JavaCallableWrappers/JavaCallableWrapperGeneratorTests.cs
src/Java.Interop.Tools.JavaCallableWrappers/Test/Java.Interop.Tools.JavaCallableWrappers/SupportDeclarations.cs
src/Java.Interop.Tools.JavaCallableWrappers/Test/Java.Interop.Tools.JavaCallableWrappers/TypeNameMapGeneratorTests.cs
src/Java.Interop.Tools.JavaCallableWrappers/Test/packages.config

Import the TypeNameMapGeneratorTests from monodroid/45f77081, and
write some initial unit tests for JavaCallableWrapperGenerator.

[Java.Interop.Tools.JavaCallableWrappers-Tests] Add unit tests.

---

src/Java.Interop.Tools.JavaCallableWrappers/Test/Java.Interop.Tools.JavaCallableWrappers-Tests.csproj
src/Java.Interop.Tools.JavaCallableWrappers/Test/Java.Interop.Tools.JavaCallableWrappers/JavaCallableWrapperGeneratorTests.cs
src/Java.Interop.Tools.TypeNameMappings/Java.Interop.Tools.TypeNameMappings/JniType.cs
tools/jcw-gen/App.cs

Generate Java Callable Wrappers across multiple tasks.

[jcw-gen] Generate Java Callable Wrappers in parallel.

---

src/Java.Interop.Tools.JavaCallableWrappers/Java.Interop.Tools.JavaCallableWrappers/JavaCallableWrapperGenerator.cs
src/Java.Interop.Tools.JavaCallableWrappers/Test/Java.Interop.Tools.JavaCallableWrappers/JavaCallableWrapperGeneratorTests.cs

Fixes: https://bugzilla.xamarin.com/show_bug.cgi?id=40976
Fixes: https://bugzilla.xamarin.com/show_bug.cgi?id=41342
There is a desire to *trivially* enable use of MultiDexApplication by
setting the $(AndroidEnableMultiDex) MSBuild property to True. When
False (the default), the normal Java Callable Wrapper (JCW) base class
naming logic would be used (e.g. use the `[Register]`ed type name of
the base class in the `extends` clause). This normal logic hinders
"trivial" use of MultiDexApplication, as it would require that any
custom `Android.App.Application` type be changed to instead inherit
`Android.Support.Multidex.MultiDexApplication`, and default
`MultiDexApplication` use is required to support other functionality
such as enhanced Fast Deployment.
The original fix for Bug #40976 altered …

[Java.Interop.Tools.JavaCallableWrappers] Support MultiDexApplication

---

src/Java.Interop.Tools.JavaCallableWrappers/Test/Java.Interop.Tools.JavaCallableWrappers/JavaCallableWrapperGeneratorTests.cs
tools/jcw-gen/App.cs

Partially reverst commit f0fa3c34.
The problem with f0fa3c34 is that Mono.Cecil follows the normal .NET
guidelines with respect to thread safety: static members are
thread-safe, but *instance members are not thread safe*.
Meaning accessing e.g. `TypeDefinition.Methods` isn't thread-safe.
Attempting to generate Java Callable Wrappers in parallel can result
in "bizarre" Javav code wherein not all Java members which should be
overridden are actually overidden, presumably because the
TypeDefinition of the type, some base type, or some implemented
interface, is being used concurrently from multiple threads.
Revert the Task use from commit f0fa3c34 and generate
Java Callable Wrappers sequentially, so that they're valid.

[jcw-gen] DON'T generate Java Callable Wrappers in parallel

---

Makefile

Running `make all` would fail:
make: *** No rule to make target `bin/TestDebug/Java.Interop.Tools.JavaCallableWrappers-Tests.dll', needed by `all'.
Stop.
This happened because
Java.Interop.Tools.JavaCallableWrappers-Tests.dll was part of
$(TESTS), which is a dependency of the `all` target, but there wasn't
a rule to create that file.
Add a rule to create
`bin/TestDebug/Java.Interop.Tools.JavaCallableWrappers-Tests.dll`.

[build] Fix `make all` target.

---

.gitignore
Configuration.Override.props.in
Configuration.props
README.md
build-tools/scripts/jdk.mk
build-tools/scripts/mono.mk
tools/class-parse/class-parse.csproj
tools/generator/generator.csproj
tools/logcat-parse/logcat-parse.csproj

For proper use, the [xamarin-android][xa] build needs to place various
Java.Interop utilities such as class-parse.exe and generator.exe into
`$prefix/lib/mandroid`, so that Xamarin.Android.Build.Tasks.dll will
properly verify the installation environment.
There are three ways this could be accomplished:
1. The `xamarin-android` Makefile could explicitly build these
utilities and override `$(OutputPath)`:
xbuild external/Java.Interop/tools/class-parse /p:OutputPath=`pwd`/bin/$(CONFIGURATION)/lib/mandroid
The problem with this is that we want to have the xamarin-android
build system rely on MSBuild as much as possible, and this
approach, while workable, runs counter to those desires.
2. We could add additional project configurations to control where the
output directory should be. This was …

[build] Add support for `Configuration.Override.props`

---

tools/generator/ClassGen.cs

Building [Mono.Android][0] with `msbuild` results in error MSB3105:
error MSB3105: The item
".../xamarin-android/src/Mono.Android/obj/Debug/android-23/Android.Annotation.SuppressLintAttribute.cs"
was specified more than once in the "Sources" parameter.  Duplicate
items are not supported by the "Sources" parameter.
`Android.Annotation.SuppressLintAttribute.cs` is in the `Sources`
paameter twice becuase it's listed twice within
`Mono.Android.projitems`:
<Compile Include="$(MSBuildThisFileDirectory)\Android.Annotation.SuppressLintAttribute.cs" />
<Compile Include="$(MSBuildThisFileDirectory)\Android.Annotation.SuppressLintAttribute.cs" />
The question is *why* is this file -- and other files! -- repeated?
The answer is twofold:
1. Because `android.annotation.SuppressLint` is present *twice* …

[generator] .projitems shouldn't contain duplicate filenames

---

tools/generator/Tests/BaseGeneratorTest.cs
tools/generator/Tests/Compiler.cs

A unit test failure is being reported, which unfortunately doesn't
contain enough useful context:
1) generatortests.NormalMethods.GeneratedOK :   error : .../Java.Interop/bin/TestDebug/SupportFiles/JavaObject.cs(78,17): (Location of the symbol related to previous warning)
Expected: 0
But was:  1
It's a very odd "error", in that there's no error reported, just a
mention of a "previous warning", which isn't shown.
The *cause* of this useless output is that `Compiler` "trims out" all
the "non-error" output from the compilation. This *seems* good, except
in this case it's the "useless output" that we need to make sense of
anything at all!
Revise `Compiler.Compile()` so that instead of extracting "errors" it
instead provides *all* compiler output and an indicator of whether or
not errors …

[generator-Tests] Provide more context when errors happen

---

build-tools/scripts/jdk.mk
build-tools/scripts/mono.mk

Commit b6431ac8 broke the build of `src/java-interop`:
Using task Exec from Microsoft.Build.Tasks.Exec, Microsoft.Build.Tasks.v4.0, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
Executing: gcc -g -shared -std=c99 -o "obj/libjava-interop-m32.dylib" -m32 -DDEBUG -DJI_DLL_EXPORT -DMONODEVELOP -DMONO_DLL_EXPORT -fvisibility=hidden -Wl,-undefined -Wl,suppress -Wl,-flat_namespace -L /Library/Frameworks/Mono.framework/Libraries -lmonosgen-2.0   jni.c java-interop.c java-interop-mono.c java-interop-gc-bridge-mono.c
Environment variables being passed to the tool:
jni.c:7:10: fatal error: 'jni.h' file not found
#include <jni.h>
^
1 error generated.
In file included from java-interop-mono.c:1:
./java-interop-mono.h:30:11: fatal error: 'mono/metadata/assembly.h' file not found …

[java-interop] Fix include directory specification

---

tools/generator/GenBase.cs
tools/generator/Method.cs
tools/generator/Property.cs
tools/generator/Tests/BaseGeneratorTest.cs
tools/generator/Tests/expected.ji/NormalMethods/Xamarin.Test.SomeObject.cs
tools/generator/Tests/expected.ji/Streams/Java.Lang.Throwable.cs
tools/generator/Tests/expected/NormalMethods/Xamarin.Test.SomeObject.cs
tools/generator/Tests/expected/Streams/Java.Lang.Throwable.cs

The internal Xamarin.Android CI system is reporting an error when
running the `generator` unit tests, but it's a false positive.
It's *not* a bug in `generator`. Rather, it's a bug in Mono 4.2, in
which [`CSharpCodeCompiler` treats multi-line warnings as errors][0].
Since the `generator` unit tests emit such multi-line warnings when
hiding `Java.Lang.Object.Handle` (via
`Xamarin.Test.SomeObject.Handle()`) and `System.Exception.Message`
(via `Java.Lang.Throwable.Message`), and Mono 4.2 treats the
multi-line warnings as errors, the tests fail.
There are three plausible solutions so that we don't get erroneous
reports from the `generator` tests when running on Mono 4.2:
1. Remove those tests. (Uh...no.)
2. Upgrade Mono on the CI machine to Mono 4.4, which has the fix.
3. Fix `generator` so …

[generator] Emit `new` when hiding `Handle`, `Message`

---

xa-gendarme-ignore.txt

Gendarme invocation ignores the
`Gendarme.Rules.Design.MarkAssemblyWithCLSCompliantRule` and
`Gendarme.Rules.Design.MarkAssemblyWithComVisibleRule` rules because
the PCL profile that `Java.Interop.dll` targets doesn't provide the
`CLSComplientAttribute` and `ComVislbleAttribute` custom attributes,
and so they can't be used.
Commit 782f34aa "broke" these ignores by signing `Java.Interop.dll`,
causing the PublicKeyToken to change. This in turn caused the ignores
to be ignored, which meant Gendarme now reported errors:
> This assembly is not decorated with the [CLSCompliant] attribute
> This assembly is not decorated with the [ComVisible] attribute.
Fix the PublicKeyToken in the assembly name so that the rules are
properly ignored.

[xa-fx-cop] Properly ignore Java.Interop assembly errors

---

tools/generator/Parser.cs

It should ease debugging bindings.

Generate intermediate API XML definition for post-metadata-fixup state.

---

src/Java.Interop/Documentation/Java.Interop/JniEnvironment.References.xml
src/Java.Interop/Java.Interop.csproj
src/Java.Interop/Java.Interop/JniEnvironment.References.cs
src/Java.Interop/Java.Interop/JniRuntime.JniObjectReferenceManager.cs
src/Java.Interop/Tests/Java.Interop/JniEnvironmentTests.cs

Context: https://bugzilla.xamarin.com/show_bug.cgi?id=41733
Java.Interop, like Xamarin.Android before it, assumes that it's the
only managed code that is interoperating with JNI, and the JNI object
reference accounting follows suit: "only" Java.Interop can create JNI
object references and increment the associated counts, and "only"
Java.Interop can *destroy* JNI object references and decrement the
associated counts.
...except that's not entirely true.
Case in point, Bug #41733, which is a Xamarin.Android app which
P/Invokes into the native method of a Java class,
`DemoLibrary.Java_demo_DemoLibrary_test()`.
Since this is using P/Invoke and not e.g.
`Java.Interop.JniEnvironment.InstanceMethods.CallObjectMethod()`, this
*bypases* the JNI object reference accounting which would incremement …

[Java.Interop] Add JniEnvironment.References.CreatedReference()

---

src/Java.Interop/Java.Interop/JniRuntime.JniObjectReferenceManager.cs

Context: https://bugzilla.xamarin.com/show_bug.cgi?id=42476
Bug #42476 notes that the `string.Format()` within the JNI reference
count assertions contributes to process memory allocations which the
profiler reports, and those generated `strings` are pointless because
they're not used unless the assertion fails.
This is a fair point, outside of whether or not the assertions should
be present at all...
Improve the `JniRuntime.JniObjectReferenceManager` JNI reference
assertions so that they return early if the assertion wouldn't fire.
This avoids the unnecessary string allocation.

[Java.Interop] Reduce string allocations from assertions

---

tools/generator/Tests/BaseGeneratorTest.cs

Commit 3b038a87 broke `make run-tests` because starting with 3b038a87
`generator` would emit an `api.xml.fixed` file into the output
directory, which wasn't present in the source directory. This resulted
in a unit test execution failures when running `generator-Tests.dll`:
generatortests.Adapters.GeneratedOK : Expected out/Adapters/Adapters.xml.fixed but it was not generated.
at generatortests.BaseGeneratorTest.CompareOutputs (System.String sourceDir, System.String destinationDir) [0x0004f] in .../Java.Interop/tools/generator/Tests/BaseGeneratorTest.cs:57
at generatortests.BaseGeneratorTest.Run (CodeGenerationTarget target, System.String outputPath, System.String apiDescriptionFile, System.String expectedPath, System.String[] additionalSupportPaths) [0x0004a] in …

[generator-Tests] Ignore `.fixed` files

---

src/Java.Interop.Tools.JavaCallableWrappers/Test/Java.Interop.Tools.JavaCallableWrappers/SupportDeclarations.cs

Commit b58416a5 broke compilation of
`tests/Java.Interop-Tests/Java.Interop-Tests.csproj`:
Java.Interop.Tools.JavaCallableWrappers/SupportDeclarations.cs(146,3):
error CS1729: The type `Android.Content.ContentProviderAttribute' does not contain a constructor that takes `1' arguments
The cause of the breakage is that commit b58416a5 removed the
`ContentProviderAttribute(string[])` constructor, as it isn't entirely
relevant within Java.Interop.
Fix the compilation error by using the `ContentProviderAttribute`
default constructor within `SupportDeclarations.cs`.

[Java.Interop.Tools.JavaCallableWrappers] Fix tests

---

.gitmodules

Relative paths -- used previously -- have some pros, but one large
con: it complicates submodule checkout.
For example (I assume?), [on Jenkins][0]:
FATAL: Command "git submodule update --init --recursive" returned status code 128:
stdout:
stderr: Cloning into 'lib/mono.linq.expressions'...
Permission denied (publickey).
fatal: Could not read from remote repository.
Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:jonpryor/mono.linq.expressions.git' into submodule path 'lib/mono.linq.expressions' failed
hudson.plugins.git.GitException: Command "git submodule update --init --recursive" returned status code 128:
Use `https://` submodule urls.
[0]: https://jenkins.mono-project.com/view/Xamarin.Android/job/java-interop/62/console

[build] Use `https://` urls for GIT submodules

---

.gitignore
Makefile

We're running on Jenkins!
https://jenkins.mono-project.com/view/Xamarin.Android/job/java-interop
Jenkins allows processing NUnit test output!
https://wiki.jenkins-ci.org/display/JENKINS/xUnit+Plugin
Update `make run-test` so that it logs `nunit-console` XML output into
`TestResult-*.xml` files, which embeds the unit test filename, e.g.
`TestResult-Java.Interop-Tests.xml`. This will allow the xUnit plugin
to nicely render that output.

[tests] Log NUnit XML output into TestResult-*.xml

---

src/Java.Runtime.Environment/Java.Interop/JreRuntime.cs

When `JniRuntime.CreationOptions.DestroyRuntimeOnDispose` is true,
`JavaVM::DestroyJavaVM()` will be invoked when the `JniRuntime`
instance is disposed *or* finalized.
`JreRuntime.CreateJreVM()` would *always* set
`DestroyRuntimeOnDispose` to true, because it called
`JNI_CreateJavaVM()`, so *of course* you'd want to destroy the
Java VM, right?
Which brings us to unit tests. I don't know of any "before all test
fixtures run" and "after all test fixtures run" extension points,
which means:
1. The JVM needs to be created implicitly, "on demand."
2. There's no good way to destroy the JVM created in (1) after all
tests have finished executing.
Which *really* means that the `JreRuntime` instance is *finalized*,
which sets us up for the unholy trifecta of AppDomain unloads,
finalizers, and JVM …

[Java.Runtime.Environment] Don't Destroy the JVM by default.

---

Makefile

The [unit tests are failing][0]. In particular, `make run-ptests` is
failing:
Test Error : Java.Interop.PerformanceTests.JniMethodInvocationOverheadTiming.MethodInvocationTiming
System.DllNotFoundException : NativeTiming
Fortunately, it repro's locally, and with `MONO_LOG_LEVEL=debug` set,
we see:
Mono: DllImport error loading library '.../Java.Interop/bin/TestDebug/libNativeTiming.dylib':
'dlopen(.../Java.Interop/bin/TestDebug/libNativeTiming.dylib, 9): no suitable image found.  Did find:
.../Java.Interop/bin/TestDebug/libNativeTiming.dylib: mach-o, but wrong architecture'.
Rephrasing: the unit tests are running in a 64-bit process, but
`libNativeTiming.dylib` is a *32-bit* binary, and can't be loaded.
The fix? Use [**lipo**(1)][1] to create a "fat binary", a
`libNativeTiming.dylib` that …

[build] Build `libNativeTiming.dylib` as a 32+64 native library

---

tests/NativeTiming/timing.c

When running `make run-ptests`, the output log is *spammed*:
WARNING in native method: JNI call made without checking exceptions when required to from CallStaticVoidMethod
Over a million times [^0].
Call `JNIEnv::ExcceptionClear()` after every `JNIEnv::Call*Method()`
invocation so that any pending exception is cleared (there *won't* be
a pending exception, but the JVM doesn't care), which removes all of
these warning messages.
[^0]: *Probably*. 100,000 iterations across over 12 steps should
exceed a million, unless you're on Android and the iteration count
is instead 1,000.

[NativeTiming] Clear exceptions after calling JNI methods

---

tools/generator/Tests/Compiler.cs

After upgrading to Mono 4.6, the `generator-Tests.dll` unit tests are
failing:
18) Test Failure : generatortests.Streams.GeneratedOK
/Library/Frameworks/Mono.framework/Versions/4.6.0/bin/mcs /target:library /debug+ /optimize- /out:"Mono.Andoroid"
/r:"/Users/jon/Dropbox/Developer/Java.Interop/bin/TestDebug/nunit.framework.dll"
/r:"/Users/jon/Dropbox/Developer/Java.Interop/bin/TestDebug/Java.Interop.dll"
/r:"/Library/Frameworks/Mono.framework/Versions/4.6.0/lib/mono/4.5/Facades/System.Runtime.dll"
/unsafe /noconfig  --
...
.../Java.Interop/bin/TestDebug/SupportFiles/JNIEnv.cs(6,14): error CS0234: The type or namespace name `Linq' does not exist in the namespace `System'. Are you missing `System.Core' assembly reference?
.../Java.Interop/bin/TestDebug/SupportFiles/JNIEnv.cs(7,14): error …

[generator-Tests] Reference System.Core.dll

---

src/Java.Interop.Tools.Cecil/Java.Interop.Tools.Cecil.csproj

Before this fix, it failed to build due to bogus reference resolution in
nuget somehow:
```
Java.Interop.Tools.Cecil/DirectoryAssemblyResolver.cs(99,16): error CS0012: The type `Mono.Cecil.Cil.SequencePoint' is defined in an assembly that is not referenced. Consider adding a reference to assembly `Xamarin.Android.Cecil, Version=0.9.6.0, Culture=neutral, PublicKeyToken=0738eb9f132ed756'
/sources/monodroid/monodroid/out/lib/mandroid//Java.Interop.Tools.Diagnostics.dll (Location of the symbol related to previous error)
Task "Csc" execution -- FAILED
Done building target "CoreCompile" in project "/sources/monodroid/Java.Interop/src/Java.Interop.Tools.Cecil/Java.Interop.Tools.Cecil.csproj".-- FAILED
Done building project "/sources/monodroid/Java.Interop/src/Java.Interop.Tools.Cecil/Java.Interop …
```

Fix build when Java.Interop.Tools.Cecil is built outside the tree.

---

tools/generator/ClassGen.cs
tools/generator/CodeGenerator.cs

The bug describes the situation where generator attempts to generate code
for non-generatable referenced types from assemblies.

[generator] fix bug #43883: generate only generatable code.

---

tools/generator/InterfaceGen.cs

Addresses https://bugzilla.xamarin.com/show_bug.cgi?id=40172
setOn123Listener(On123Listener) will generate event named 123, but that
is not a valid C# name and will result in compilation error. So check
that name, warn it, and do not generate event.

Invalidate automatically generated events that will have invalid name.

---

tools/generator/CodeGenerator.cs

It is to be used by msbuild tasks that splits API XML adjuster work
from BindingsGenerator and thus reduce the need to run class-parse and/or
API XML adjuster work in generator and thus reduce the chance to load
class-parse XML which is almost twice as big as api-xml-adjuster outputs.

Add "standalone API XML adjuster" mode to generator.

---

tools/generator/Method.cs
tools/generator/Property.cs

We have been blindly generating XPath metadata, but some of those are
not generated via Java code, and for such code there is no corresponding
applicable XML elements that can apply XPath metadata fixup.
So, remove them from the output.

[generator] reduce extraneous metadata XPath for non-generatable part.

---

tools/generator/ReturnValue.cs

6d161a2 caused (either regressed or exposed) another issue that generator
didn't resole the return values for enums to be EnumSymbol which gives
explicit cast from int to enum for the output expressions.
This returns managed_type (which should be enum name) for enumified return
value (IsEnumified = true).

[generator] fix enum managed return type.

---

src/Java.Interop.Tools.Cecil/Java.Interop.Tools.Cecil.csproj
src/Java.Interop.Tools.Cecil/Java.Interop.Tools.Cecil/DirectoryAssemblyResolver.cs
src/Java.Interop.Tools.Cecil/Java.Interop.Tools.Cecil/TypeDefinitionRocks.cs
src/Java.Interop.Tools.Cecil/packages.config
src/Java.Interop.Tools.Diagnostics/Java.Interop.Tools.Diagnostics.csproj
src/Java.Interop.Tools.Diagnostics/packages.config
src/Java.Interop.Tools.JavaCallableWrappers/Java.Interop.Tools.JavaCallableWrappers.csproj
src/Java.Interop.Tools.JavaCallableWrappers/Java.Interop.Tools.JavaCallableWrappers/JavaCallableWrapperGenerator.cs
src/Java.Interop.Tools.JavaCallableWrappers/Test/Java.Interop.Tools.JavaCallableWrappers-Tests.csproj
src/Java.Interop.Tools.JavaCallableWrappers/Test/packages.config
src/Java.Interop.Tools.JavaCallableWrappers/packages.config
src/Xamarin.Android.Tools.AnnotationSupport.Cecil/Xamarin.Android.Tools.AnnotationSupport.Cecil.csproj
src/Xamarin.Android.Tools.AnnotationSupport.Cecil/packages.config
tools/generator/ClassGen.cs
tools/generator/InterfaceGen.cs
tools/generator/generator.csproj
tools/generator/packages.config
tools/jcw-gen/jcw-gen.csproj
tools/jcw-gen/packages.config

Mono 4.8 has migrated to Mono.Cecil/master, based on 0.10.0, which is
API-incompatible with the previous Mono.Cecil 0.9.6.
In particular, `TypeDefinition.Interfaces` now returns a
`Collection<InterfaceImplementation>` instead of the previous
`Collection<TypeReference>`, which causes all manner of breakage.
Since the next version of Xamarin.Android will be based on Mono 4.8,
and Xamarin.Android needs Java.Interop, bump Java.Interop to use the
Mono.Cecil 0.10.x preview package, and fix the corresponding breakage.

Bump to Mono.Cecil 0.10.0-beta1-v2

---

src/Java.Interop.Tools.JavaCallableWrappers/Java.Interop.Tools.JavaCallableWrappers/JavaCallableWrapperGenerator.cs
src/Java.Interop.Tools.TypeNameMappings/Java.Interop.Tools.TypeNameMappings/JniType.cs

Commit dfed286d updated Cecil to Cecil 0.10.0-beta1-v2, which has
multiple API incompatibilities with Cecil 0.9.6.
Unfortunately, some of these incompatibilities were hidden by use of
the `.Cast<T>()` extension method, which was used because older
versions of Cecil didn't use generics at all, so the `.Cast<T>()` was
present to provide types.
Types which became wrong with Cecil 0.10.0.
The result is that when
[building xamarin-android with a newer Java.Interop][0],
[things broke][1]:
jcw-gen: System.InvalidCastException: Unable to cast object of type 'Mono.Cecil.InterfaceImplementation' to type 'Mono.Cecil.TypeReference'.
at (wrapper castclass) System.Object:__castclass_with_cache (object,intptr,intptr)
at System.Linq.Enumerable+<CastIterator>c__Iterator17`1[TResult].MoveNext () [0x00059] …

[jcw-gen] Fix InvalidCastException from Cecil upgrade

---

tools/generator/ClassGen.cs
tools/generator/CodeGenerator.cs

Fixes: https://bugzilla.xamarin.com/show_bug.cgi?id=43883
The bug describes the situation where generator attempts to generate code
for non-generatable referenced types from assemblies.

[generator] generate only generatable code. (#73)

---

tools/generator/GenBase.cs

We update possibly-enumified members after loading XML metadata, but
currently we iterate everything we loaded including managed references.
That's waste of processing, so don't do that.
(Also reduced attempts to process base types, but they did not actually
happen anyways. The relevant code is slightly simplified.)

[generator] do not try to "enumify" reflection-based types.

---

build-tools/scripts/jdk.mk

Basically this is the same kind of fix as https://github.com/xamarin/monodroid/commit/c6371f6b

Fix Java path probing issue on Linux.

---

src/Xamarin.Android.Tools.ApiXmlAdjuster/JavaApiOverrideMarkerExtensions.cs

It was running override marking step on the same object as many times as
it is inherited (say, java.lang.Object was inspected for N times by N types
in a library...).
There isn't a huge amount of perf. improvements, but as far as I tried
with api-[10..24].xml.in generation locally, the results were like:
old:
real	0m55.898s
user	0m55.508s
sys	0m0.336s
new:
real	0m53.326s
user	0m52.552s
sys	0m0.692s
(Oh, and removed some extraneous code I had there...)

[api-xml-adjuster] reduce extraneous override marking.

---

src/Java.Interop.Tools.Cecil/Java.Interop.Tools.Cecil/DirectoryAssemblyResolver.cs
src/Java.Interop.Tools.JavaCallableWrappers/Java.Interop.Tools.JavaCallableWrappers/TypeNameMapGenerator.cs
tools/generator/CodeGenerator.cs
tools/jcw-gen/App.cs

Context: https://github.com/xamarin/java.interop/pull/87#issuecomment-249227731
Context: https://bugzilla.xamarin.com/show_bug.cgi?id=44529
(Private) Bug #44529 is an `IOException` on `xamarin-android/master`
due to file sharing:
Error executing task StripEmbeddedLibraries: System.IO.IOException: Sharing violation on path .../obj/Release/linksrc/Xamarin.Android.NUnitLite.dll
at System.IO.FileStream..ctor (System.String path, System.IO.FileMode mode, System.IO.FileAccess access, System.IO.FileShare share, System.Int32 bufferSize, System.Boolean anonymous, System.IO.FileOptions options) [0x0025f] in <253a3790b2c44512bbca8669ecfc1822>:0
at System.IO.FileStream..ctor (System.String path, System.IO.FileMode mode, System.IO.FileAccess access, System.IO.FileShare share) [0x00000] in …

[Java.Interop.Tools.Cecil] Fix DirectoryAssemblyResolver.Dispose()

---

src/Java.Interop.Tools.JavaCallableWrappers/Java.Interop.Tools.JavaCallableWrappers/TypeNameMapGenerator.cs

The `TypeNameMapGenerator(IEnumerable<string>, Action<string,object[]>)`
constructor attempted to use `DirectoryAssemblyResolver` to load each
assembly provided by the `IEnumerable<string>` parameter, in-order,
*without* updating `DirectoryAssemblyResolver.SearchDirectories`.
The result is that things would only work if the assemblies were
sorted in "dependency order", e.g. `mscorlib.dll` first, and any other
assembly dependency before it's used.
Should the order be otherwise, e.g. `{System.dll, mscorlib.dll}`, then
things would horrifically break:
System.IO.FileNotFoundException: Could not load assembly 'mscorlib, Version=2.0.5.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e'. Perhaps it doesn't exist in the Mono for Android profile?
File name: 'mscorlib.dll'
at …

[Java.Interop.Tools.JavaCallableWrappers] TypeNameMapGenerator directories

---

src/Xamarin.Android.Tools.ApiXmlAdjuster/JavaApi.XmlModel.cs
src/Xamarin.Android.Tools.ApiXmlAdjuster/JavaApiOverrideMarkerExtensions.cs
src/Xamarin.Android.Tools.ApiXmlAdjuster/JavaApiTypeResolverExtensions.cs
src/Xamarin.Android.Tools.ApiXmlAdjuster/Tests/OverrideMarkerTest.cs
tools/generator/Ctor.cs
tools/generator/Field.cs
tools/generator/JavaApiDllLoaderExtensions.cs
tools/generator/Parameter.cs

Until now, ApiXmlAdjuster was trying to resolve types using
ClassGen.BaseGen property which is in fact assigned only after Validate()
step in generator. API XML analyzer work is done way before that step,
and therefore it failed to resolve types from managed code (DLL references).
Missing type hierarchy in Java type model from managed code means that
any bindings that references Mono.Android (which wouldn't?) had to rely
on insufficient hierarchy. Especially, it failed to resolve method
overrides when the target Java library types overrode methods in android.jar
indirectly.
SherlockExpandableListActivity.addContentView() was such a method.
And it had appeared as a regression from our MSBuild tests[*1].
Fixes:
- removed dependency on BaseGen in ApiXmlAdjuster. Use BaseType instead,
which …

[generator][api-xml-adjuster] Fix managed type resolution in API adjuster.

---

tools/generator/CodeGenerator.cs
tools/generator/GenBase.cs
tools/generator/GenBaseSupport.cs
tools/generator/Parser.cs

DO NOT MERGE THIS WITHOUT MERGING https://github.com/xamarin/xamarin-android/pull/249 first (yes, that PR can be merged without this)
Basically this is part of the problems reported at
https://bugzilla.xamarin.com/show_bug.cgi?id=44263
In good old jar2xml era, we marked "obfuscated" types at jar2xml so
that those types are not generated in the API XML.
class-parse is not that clever and generates everything as is.
We could make changes to api-xml-adjuster to bring back sanity, but
instead of doing it in jar2xml, we had better bring in flexibility
to obfuscation marking. That is -
- If there is obfuscated='false' attribute specification by API
metadata fixup, then do not mark as obfuscated in any case.
- If not, process any lowercase-named types and nested types as
obfuscated, such as 'a', …

[generator] (class-parse regression) mark obfuscated types in generator.

---

Makefile
build-tools/scripts/jdk.mk
build-tools/scripts/mono.mk
tests/invocation-overhead/Makefile

The `tests/invocation-overhead` build had regressed, largely becuase
it's rarely executed. Breakage was due to the fact that the JNI
headers could no longer be found, and that when running `make run`,
the "wrong" mono was being used wrt the JVM that was used (e.g. trying
to use a 32-bit mono with a 64-bit JVM).
Refactor some Makefile logic and cleanup for consistency.

[build] Fix the `invocation-overhead` build.

---

src/Xamarin.Android.Tools.ApiXmlAdjuster/JavaApi.XmlModel.cs
src/Xamarin.Android.Tools.ApiXmlAdjuster/JavaApiFixVisibilityExtensions.cs
src/Xamarin.Android.Tools.ApiXmlAdjuster/JavaApiTypeResolverExtensions.cs
src/Xamarin.Android.Tools.ApiXmlAdjuster/JavaApiXmlGeneratorExtensions.cs
src/Xamarin.Android.Tools.ApiXmlAdjuster/JavaApiXmlLoaderExtensions.cs
src/Xamarin.Android.Tools.ApiXmlAdjuster/JavaTypeName.cs
src/Xamarin.Android.Tools.ApiXmlAdjuster/JavaTypeReference.cs
src/Xamarin.Android.Tools.ApiXmlAdjuster/Tests/JavaApiTest.cs
src/Xamarin.Android.Tools.ApiXmlAdjuster/Tests/JavaApiTestHelper.cs
src/Xamarin.Android.Tools.ApiXmlAdjuster/Tests/TypeResolverTest.cs
src/Xamarin.Android.Tools.ApiXmlAdjuster/Tests/Xamarin.Android.Tools.ApiXmlAdjuster-Tests.csproj
src/Xamarin.Android.Tools.ApiXmlAdjuster/Xamarin.Android.Tools.ApiXmlAdjuster.csproj
tools/generator/JavaApiDllLoaderExtensions.cs

Fixes: https://bugzilla.xamarin.com/show_bug.cgi?id=44531
When a Java method is overriden, its parameter type or return type can be
variant, which possibly result in exposure of non-public types (returning
private class object which is derived from public type is totally valid).
It is because we blindly emit the parsed type from class-parse output
as the API XML adjuster output. It needs to be examined and adjusted to
be public (or protected) type.
jar2xml didn't have this problem because Java reflection API is clever
enough to cover that issue.
The fixes are... not cosmetic.
Basically now we use TypeReference.ToString() which used to not be
precise and ready for API XML output. So there are couple of fixes
for that. (We also want to track from which method base a parameter
or return type …

[api-xml-adjuster] method overrides cannot expose non-public types.

---

src/Xamarin.Android.Tools.Bytecode/ClassPath.cs
src/Xamarin.Android.Tools.Bytecode/JavaDocumentScraper.cs
tools/class-parse/Program.cs

With the latest Android N, Google has (again) changed API documentation
format (i.e. doclet) and that broke API XML documentation parser.
Unlike previous ones or Oracle Javadoc doclets, it is not easily matcheable
with existing regex structure. So I made not a small set of changes
to make it working.
Unlike previous ones it takes a lot more time to process (e.g. more than
minutes to process all API Level 24 docs), but better than broken.
This is required to suppport any further API Levels (like 25).
(ClassParse task has an issue that it never supported correct Javadoc
processing as it ignores doclet differences. This only changes the
default to droiddoc2 just to be able to process the latest doc.
It needs different fix.)

[class-parse] support updated DroidDoc.

---

src/Xamarin.Android.Tools.Bytecode/ClassPath.cs
src/Xamarin.Android.Tools.Bytecode/JavaDocumentScraper.cs
src/Xamarin.Android.Tools.Bytecode/Tests/ClassFileFixture.cs
src/Xamarin.Android.Tools.Bytecode/Tests/ParameterFixupApiXmlDocs.xml
src/Xamarin.Android.Tools.Bytecode/Tests/ParameterFixupTests.cs
src/Xamarin.Android.Tools.Bytecode/Tests/Xamarin.Android.Tools.Bytecode-Tests.csproj
tools/class-parse/Program.cs

The existing doc parsers are great for when the documentation is available for download publicly, however we are facing a situation with Android Support libraries where documentation available online is either lagging behind releases or is simply not updated in the usual locations for consuming.
The documentation is available on the web server, however since we can't redistribute this content, we need to distribute the information (parameter names) in an intermediate format which the binding build process can use as a source for parameter name data.
For Android Support libraries, we are starting to produce parameter names in an intermediate format which mimics the existing `api.xml` structure (albeit with much less information in the attributes).
This PR creates a parameter name doc …

api.xml doc parser

---

tools/class-parse/Program.cs

Fix a [build][0] [break][1] from commit 806082f2:
Program.cs(97,35): error CS0117: `Xamarin.Android.Tools.Bytecode.JavaDocletType' does not contain a definition for `ApiXml'
It should be referencing `_ApiXml`, not `ApiXml`.
[0]: https://jenkins.mono-project.com/view/Xamarin.Android/job/Java.Interop/94/
[1]: https://jenkins.mono-project.com/view/Xamarin.Android/job/Java.Interop/94/console

[class-parse] Fix build break from 806082f2

---

tools/generator/Parameter.cs
tools/generator/Tests/CSharpKeywords.cs
tools/generator/Tests/expected.ji/CSharpKeywords/CSharpKeywords.xml
tools/generator/Tests/expected.ji/CSharpKeywords/Mono.Android.projitems
tools/generator/Tests/expected.ji/CSharpKeywords/Xamarin.Test.CSharpKeywords.cs
tools/generator/Tests/expected.targets
tools/generator/Tests/expected/CSharpKeywords/CSharpKeywords.xml
tools/generator/Tests/expected/CSharpKeywords/Xamarin.Test.CSharpKeywords.cs
tools/generator/Tests/generator-Tests.csproj

This fixes bug #46454.
Parameter ToNative() was not escaping C# identifiers, and then it sometimes
resulted in invalid C# code.
It can be easily workarounded by metadata fixup, but also fixable.

[generator] make sure to escape non-generic parameter name for calls.

---

tools/generator/CollectionSymbol.cs
tools/generator/GenericSymbol.cs
tools/generator/IRequireGenericMarshal.cs
tools/generator/InterfaceGen.cs
tools/generator/Tests/GenericArguments.cs
tools/generator/Tests/expected.ji/GenericArguments/Com.Google.Android.Exoplayer.Drm.FrameworkMediaDrm.cs
tools/generator/Tests/expected.ji/GenericArguments/Com.Google.Android.Exoplayer.Drm.IExoMediaDrm.cs
tools/generator/Tests/expected.ji/GenericArguments/GenericArguments.xml
tools/generator/Tests/expected.ji/GenericArguments/Java.Lang.Object.cs
tools/generator/Tests/expected.targets
tools/generator/Tests/expected/GenericArguments/Com.Google.Android.Exoplayer.Drm.FrameworkMediaDrm.cs
tools/generator/Tests/expected/GenericArguments/Com.Google.Android.Exoplayer.Drm.IExoMediaDrm.cs
tools/generator/Tests/expected/GenericArguments/GenericArguments.xml
tools/generator/Tests/expected/GenericArguments/Java.Lang.Object.cs
tools/generator/Tests/generator-Tests.csproj

This fixes bug #43513.
The background for the fix is, well, complicated.
It was generating wrong code:
// This method is explicitly implemented as a member of an instantiated Com.Google.Android.Exoplayer.Drm.IExoMediaDrm
void global::Com.Google.Android.Exoplayer.Drm.IExoMediaDrm.SetOnEventListener (global::Com.Google.Android.Exoplayer.Drm.IExoMediaDrmOnEventListener p0)
{
SetOnEventListener (global::Java.Interop.JavaObjectExtensions.JavaCast<global::Com.Google.Android.Exoplayer.Drm.IExoMediaDrmOnEventListener<Java.Lang.Object>>(p0));
}
where IExoMediaDrmOnEventListener is a normally generated interface ACW
which does not have any generic parameter.
The problem is, the Java API has generic argument T.
Usually it does not matter in normal classes. But reference to an interface
type with …

[generator] fix generic parameter code generation for interface.

---

tools/generator/GenBaseSupport.cs
tools/generator/JavaApiDllLoaderExtensions.cs

AndroidSupportComponents/percent/source has some build issues that
PercentFrameLayout.LayoutParams generates wrong constructors that take
java.lang.Object as an argument. For example, for this:
https://developer.android.com/reference/android/support/percent/PercentFrameLayout.LayoutParams.html#PercentFrameLayout.LayoutParams(android.view.ViewGroup.LayoutParams)
And they resulted in build errors (which was rather fortunate; it
could be worse that the method is successfully generated with
java.lang.Object while the actual type isn't...)
Where are those weird java.lang.Object from?
Surprisingly(?), it was not about failed type resolution, but this:
https://github.com/xamarin/java.interop/commit/8dac926e
It hides nonpublic types up to java.lang.Object.
Why does it happen? Isn't …

[generator] Fix nested type visibility and findability.

---

src/Xamarin.Android.Tools.ApiXmlAdjuster/JavaApi.XmlModel.cs

ApiXmlAdjuster had been emitting red-herring warning that it cannot find
System.IO.Stream. It is not a Java type so it is by nature that it is
not found, but we had predefined type definition for that.
Turned out that it was assigned a wrong "package" and therefore the
type was never resolved. This fixes it to the right package.
Also, XmlReader could be used as a predefined type because it is
mapped from XmlPullParser (and AndroidResourceParser). So add it too.

[api-xml-adjuster] fix predefined managed types.

---

src/Xamarin.Android.Cecil/Xamarin.Android.Cecil.Mdb.csproj
src/Xamarin.Android.Cecil/Xamarin.Android.Cecil.csproj
src/Xamarin.Android.Cecil/Xamarin.Android.Cecil.targets

Eventually -- sooner rather than later? -- we'd like to support
building xamarin-android using `msbuild` instead of `xbuild`.
Unfortunately, that doesn't work, for a variety of reasons.
Appropos to `Xamarin.Android.Cecil` is that if we, from a *clean*
state, build *just*
`xamarin-android/src/Xamarin.Android.Build.Tasks/Xamarin.Android.Build.Tasks.csproj`
without a solution, the build fails because
`Xamarin.Android.Cecil.dll` and `Xamarin.Android.Cecil.Mdb.dll` cannot
be resolved or found, because they're copied into the wrong
directories.
Cleanup the `Xamarin.Android.Cecil` project files so that they
increase consistency with the other project files, e.g.
`$(OutputPath)` is `..\..\bin\$(Configuration)`, not
`bin\$(Configuration)`, which also allows a from-clean `msbuild`-based
build of …

[Xamarin.Android.Cecil] Fixups for chained MSBuild invocation

---

tools/class-parse/Mono.Options-PCL.cs
tools/class-parse/Program.cs

Running `class-parse --dump` on `java.lang.Object` would fail:
$ unzip /Library/Java/JavaVirtualMachines/jdk1.8.0_92.jdk/Contents/Home/jre/lib/rt.jar java/lang/Object.class
$ mono class-parse.exe --dump java/lang/Object.class
...
class-parse: Unable to read file 'java/lang/Object.class': Object reference not set to an instance of an object
Enabling verbose output (`class-parse -v`) didn't help:
$ mono class-parse.exe -v --dump java/lang/Object.class
System.IndexOutOfRangeException: Index was outside the bounds of the array.
at Mono.Options.Option.Parse[T] (System.String value, Mono.Options.OptionContext c) [0x0005e] in <4d78dd3d6bb745d7a994cb7587b83fb2>:0
...
Doh!
The problem with the `IndexOutOfRangeException` is a bug in
`Mono.Options-PCL.cs`: it should be using …

[class-parse] Support `class-parse --dump` on java.lang.Object

---

src/Java.Interop.Dynamic/Tests/Java.Interop.Dynamic-Tests.csproj
src/Xamarin.Android.Tools.ApiXmlAdjuster/Tests/Xamarin.Android.Tools.ApiXmlAdjuster-Tests.csproj
tests/Java.Interop-PerformanceTests/Java.Interop-PerformanceTests.csproj
tests/TestJVM/TestJVM.csproj
tools/generator/Tests/generator-Tests.csproj
tools/logcat-parse/Tests/LogcatParse-Tests.csproj

Makes sure the build works with Mono master/4.9+.

Fix mono master build

---

src/Xamarin.Android.Tools.Bytecode/AttributeInfo.cs
src/Xamarin.Android.Tools.Bytecode/Methods.cs
src/Xamarin.Android.Tools.Bytecode/Tests/IJavaInterface.xml
src/Xamarin.Android.Tools.Bytecode/Tests/IJavaInterfaceTests.cs
src/Xamarin.Android.Tools.Bytecode/Tests/JavaEnumTests.cs
src/Xamarin.Android.Tools.Bytecode/Tests/JavaType$RNC$RPNC.xml
src/Xamarin.Android.Tools.Bytecode/Tests/JavaType$RNC.xml
src/Xamarin.Android.Tools.Bytecode/Tests/JavaType.RNC.RPNCTests.cs
src/Xamarin.Android.Tools.Bytecode/Tests/JavaType.RNCTests.cs
src/Xamarin.Android.Tools.Bytecode/Tests/JavaType.xml
src/Xamarin.Android.Tools.Bytecode/Tests/JavaTypeTests.cs
src/Xamarin.Android.Tools.Bytecode/Tests/Xamarin.Android.Tools.Bytecode-Tests.csproj

Fixes: https://github.com/xamarin/java.interop/issues/106
Java 8 adds support for a `javac -parameters` option, which adds a
`MethodParameters` attribute to the `.class` file. The
`MethodParameters` attribute blob contains *reliable* parameter names,
including for abstract methods and interface methods, unlike existing
`LocalVariableTable`, which only exists for `javac -g` builds, and
only for methods with *bodies*, i.e. *not* abstract methods and
interface methods.
Add support for parsing the `MethodParameters` attribute blob.

[Xamarin.Android.Tools.Bytecode] MethodParameters Attribute parsing

---

Makefile
README.md
build-tools/scripts/mono.mk
build-tools/scripts/msbuild.mk
src/Xamarin.Android.Cecil/Xamarin.Android.Cecil.targets
src/java-interop/java-interop.mdproj
tests/invocation-overhead/Makefile

MSBuild is open source -- has been for ages -- and we'd *really* like
to migrate all things Mono to MSBuild and deprecate/remove `xbuild`.
Which means we need to ensure that all of our products build with
`msbuild`. [Which unfortunately isn't the case in `Java.Interop`][0]:
MSB3375: The file "../../bin/Release/Xamarin.Android.Cecil.dll" does not exist.
...
Java.Interop/MarshalMemberBuilder.cs(9,20): error CS0234:
The type or namespace name `Expressions' does not exist in the namespace `Java.Interop'. Are you missing an assembly reference?
...
36 Warning(s)
69 Error(s)
For starters, bring Java.Interop into aligntment/convention with the
[`xamarin-android` repo][1], so that `$(MSBUILD)` is the Make variable
to specify the MSBuild engine to use, not `$(XBUILD)`, and allow
`$(V)` to set …

Support building with `msbuild`

---

tools/generator/ApiVersionsSupport.cs
tools/generator/CodeGenerator.cs

When we fill [Available (ApiSince = x)] we load api-versions.xml and
checks if the mentioned Java member exists. But there are cases that
those members should not really exist (e.g. we merge API while we don't
for api-versions - we simply can't, there is no per-level api-versions).
Missing members should be checked elsewhere, not here, so remove those
extraneous (and mostly spurious) warnings.

[generator] remove extra warnings on missing methods for api-versions check.

---

src/Xamarin.Android.Tools.ApiXmlAdjuster/JavaApiTypeResolverExtensions.cs
src/Xamarin.Android.Tools.ApiXmlAdjuster/JavaTypeName.cs
src/Xamarin.Android.Tools.ApiXmlAdjuster/Tests/JavaApiTest.cs

We have fixed nested generic type name crashes[*1] at 769f9444, but
that was only to fix the crash. The resulting type name was not parsed
correctly - namely, the resulting type name dropped the remainings after
the first generic arguments list i.e. in `A<b>.C<d>`, `.C<d>` part had
dropped.
The cause of the problem is somewhat deep, as JavaTypeName and
JavaTypeReference do not consider the possibility that both the nested
generic parent and child have generic arguments.
Anyhow in JavaTypeName now we store the expected information, by
having (hacky) `GenericParent` property to store the expected information.
Now it comes with a test so that it should prove the purpose of the change.
[*1] https://bugzilla.xamarin.com/show_bug.cgi?id=46344

[api-xml-adjuster] further fix on generic nested type name parsing.

---

.gitmodules

Xamarin.Android 7.1 ("Cycle 9") needs to use cecil/cycle9 for
consistency with other products (e.g. Mono).
Bump the commit refs accordingly.

Bump to cecil/cycle9/2b39856e

---

Makefile
src/Xamarin.Android.Tools.ApiXmlAdjuster/JavaApiNonBindableStripper.cs
src/Xamarin.Android.Tools.ApiXmlAdjuster/Xamarin.Android.Tools.ApiXmlAdjuster.csproj
tools/generator/ApiXmlAdjuster.cs
tools/generator/Tests-Core/api-cp.xml
tools/generator/Tests-Core/expected.cp/GeneratedFiles.projitems
tools/generator/Tests-Core/expected.cp/Java.Interop.__TypeRegistrations.cs
tools/generator/Tests-Core/expected.cp/Java.Lang.Object.cs
tools/generator/Tests-Core/expected.cp/Xamarin.Test.Invalidnames.InvalidNameMembers.cs
tools/generator/Tests-Core/expected.cp/__NamespaceMapping__.cs
tools/generator/Tests-Core/fields-cp.xml
tools/generator/Tests-Core/methods-cp.xml

Related: https://bugzilla.xamarin.com/show_bug.cgi?id=46344#c12
class-parse has brought another problem; it generates fields and methods
that are compiler-generated and should not have been written to XML
in the first place.
class-parse has no idea on how to deal with them, so kill them in
api-xml-adjuster instead.

[generator] strip fields and methods that have '$' in the name.

---

tools/generator/GenBaseSupport.cs
tools/generator/Tests-Core/api-cp.xml
tools/generator/Tests-Core/expected.cp/GeneratedFiles.projitems
tools/generator/Tests-Core/expected.cp/Java.Interop.__TypeRegistrations.cs
tools/generator/Tests-Core/expected.cp/Java.Lang.String.cs
tools/generator/Tests-Core/expected.cp/Xamarin.Test.Invalidnames.In.cs

This is a fixup for c51469e, as well as bugfix for:
https://bugzilla.xamarin.com/show_bug.cgi?id=51337
What's happening behind bug #51337 was this:
BINDINGSGENERATOR:  warning BG8800: Unknown parameter
type org.osmdroid.ResourceProxy.bitmap in method GetBitmap
in managed type OsmDroid.DefaultResourceProxyImpl.
This was, because, "bitmap" is all lowercased and was marked as obfuscated
(because, WHY NAME A CLASS ALL IN LOWERCASE!?).
Such classes should not exist, or should be marked as "obfuscated='false'".
However what bug #51337 implies is that people are not going to make
this additional markup for generator improvements.
What this generator change does is then - a hack. A hack to mark "classes
with very short names" as obfuscated, instead of "all lowercase or number".
As commented on …

[generator] less aggressive obfuscation marking.

---

src/Xamarin.Android.Tools.Bytecode/JavaDocumentScraper.cs

It was using String.Split(char[]) instead of .Split(string[]) which means
that with "&nbsp;" the input can be split by any of '&', n,b,s,p and ';'.
Also, Javadoc8 parameters can contain <a> tags, which need to be removed.

[class-parse] fix Java8 javadoc regex matches and parameter name retrieval.

---

tools/generator/EnumMappings.cs
tools/generator/Tests-Core/expected.ji/Android.Text.SpanTypes.cs
tools/generator/Tests-Core/expected/Android.Text.SpanTypes.cs
tools/generator/Tests/SupportFiles/IntDefinitionAttribute.cs
tools/generator/Tests/expected/EnumerationFixup/Xamarin.Test.SomeValues.cs
tools/generator/Tests/generator-Tests.csproj

DO NOT MERGE THIS WITHOUT MERGING https://github.com/xamarin/xamarin-android/pull/444, it depends on Mono.Android.dll updates.
It will be helpful when people read binding dlls and understand the enum
conversion, as well as tooling.

[generator] add [IntDefinition (JniField = ...)] everywhere.

---

src/Java.Interop.Tools.Cecil/Java.Interop.Tools.Cecil.csproj
src/Java.Interop.Tools.Diagnostics/Java.Interop.Tools.Diagnostics.csproj
src/Java.Interop.Tools.JavaCallableWrappers/Java.Interop.Tools.JavaCallableWrappers.csproj
src/Java.Interop/Java.Interop.csproj
src/Xamarin.Android.Cecil/Xamarin.Android.Cecil.Mdb.csproj
src/Xamarin.Android.Cecil/Xamarin.Android.Cecil.csproj
src/Xamarin.Android.Tools.AnnotationSupport.Cecil/Xamarin.Android.Tools.AnnotationSupport.Cecil.csproj
src/Xamarin.Android.Tools.AnnotationSupport/Xamarin.Android.Tools.AnnotationSupport.csproj
src/Xamarin.Android.Tools.ApiXmlAdjuster/Xamarin.Android.Tools.ApiXmlAdjuster.csproj
tools/generator/generator.csproj
tools/jcw-gen/jcw-gen.csproj

Debug symbols are needed to get line numbers in stack traces, which is
a handy feature even for Release binaries...

[build] Generate debug symbols in Release configuration

---

src/Xamarin.Android.Tools.Bytecode/XmlClassDeclarationBuilder.cs

Fixes: https://github.com/xamarin/java.interop/issues/129
The System.Double/Single ["Round-trip Format Specifier"][0] varies by
culture, so cultures which use `,` as the decimal separator character
use `,` within e.g. `42.0.ToString("r")`.
For example, the Java declaration:
class E {
public static final double V = 42.5;
}
on french systems would result in `class-parse` emitting:
<field name="V" value="42,5" .../>
which, when run through `generator`, emits:
public const double V = (double) 42,5;
...which promptly fails with a CS1001. Oops.
Fix our `double` and `float` serialization in
`XmlClassDeclarationBuilder` so that `CultureInfo.InvariantCulture` is
used, which ensures that `.` is the decimal separator character,
ensuring that `class-parse` and `generator` output is as expected.
[0]: …

[class-parse] Use InvariantCulture to format floating-point values

---

src/Xamarin.Android.Tools.ApiXmlAdjuster/JavaApi.XmlModel.cs
src/Xamarin.Android.Tools.ApiXmlAdjuster/JavaApiXmlLoaderExtensions.cs

It is because some types have Class<T> as some arguments to the contructor
and to resolve that T the API describes it.

[api-xml-adjuster] api-O.xml.in will have <typeParameters> in <constructor>

---

src/Java.Interop.Tools.JavaCallableWrappers/Java.Interop.Tools.JavaCallableWrappers/TypeNameMapGenerator.cs

A "funny" [^0] thing happened when trying to
[update xamarin-android to use a newer Java.Interop][0]: while all the
tests passed, the macOS+xbuild PR builder -- which actually runs the
unit tests -- was *really slow*: [2 hr 26 minutes to run][1], vs. a
more [normal 53 minutes][2].
Ouch.
@radekdoulik tried to verify that it wasn't
c794fabb; *that* build took [1 hr 42 min][3].
*Something* between cecil/d0cb2b7 and cecil/0d05ab1 caused this, but
we don't know what, and even if we knew, that might not matter.
That said, we have found two apparent factors in the slowdown:
1. Using `ReaderParameters.ReadingMode` to `ReadingMode.Immediate`
(084e9f7f), and
2. Setting `ReaderParameters.ReadSymbols` to `true`.
There also appears to be something "wrong" with the `.pdb` files that
Roslyn on macOS is …

[Java.Interop.Tools.JavaCallableWrappers] Use ReadingMode.Deferred

---

src/Xamarin.Android.Cecil/Xamarin.Android.Cecil.targets

A problem with any build system are "cascading rebuilds": when a
project changes and is rebuilt, that requires that all projects which
depend on it are *also* rebuilt. The end result is that if a "core"
project changes, everything else in the solution will need to be
rebuilt, *just in case* something "important" changed.
MSBuild (and make!) use file timestamps to determine whether or not
targets should be re-executed. Consequently, the way to avoid
cascading rebuilds is to ensure that assembly timestamps don't change
unless they have to, e.g. they were actually rebuilt.
[The MSBuild `<Target/>` element][0] can use the `@Inputs` and
`@Outputs` attributes to control when a target is run, relying on file
timestamps to determine when a target needs to be rerun.
Enter …

[Xamarin.Android.Cecil] Fix project rebuilds

---

src/Xamarin.Android.Tools.Bytecode/Tests/ParameterFixupApiXmlDocs.xml
src/Xamarin.Android.Tools.Bytecode/Tests/ParameterFixupFromDocs.xml

The `ParameterFixupTests.XmlDeclaration_FixedUpFromDocumentation()` and
`ParameterFixupTests.XmlDeclaration_FixedUpFromApiXmlDocumentation()`
tests read a `java.util.Collection.class` file that contains no
parameter name information, and uses XML and/or "JavaDoc" HTML
documentation to ascertain the correct parameter names.
For better or worse, parameter names are *not* part of any Java ABI,
and thus can change over time.
Which is what happened here: these tests were originally written
against the Android documentation for API-18. Since then, the docs for
API-24 have *changed the parameter names* for the `Collection.add(E)`
method, changing the parameter name from `object` to `e`.
Update the expected paramater names when reading docs from
`$ANDROID_SDK_PATH` so that the API-24 names are …

[Xamarin.Android.Tools.Bytecode-Tests] Update for API-24 docs

---

src/Xamarin.Android.Tools.Bytecode/AttributeInfo.cs

While processing a version of `cardview-v7.jar`,
`class-parse --dump` was throwing a `NullReferenceException`:
$ mkdir cardview-v7
$ cd cardview-v7
$ unzip ../cardview-v7.jar
$ mono …/class-parse.exe -v --dump android/support/v7/widget/CardView.class >/dev/null
class-parse: Unable to read file 'android/support/v7/widget/CardView.class': System.NullReferenceException: Object reference not set to an instance of an object
at Xamarin.Android.Tools.Bytecode.InnerClassInfo.ToString ()
...
The `NullReferenceException` is because one of the `InnerClassInfo`
values which `InnerClassInfo.ToString()` references is `null`.
After fixing, we see:
Attributes Count: 2
0: Unknown[SourceFile](2)
1: InnerClasses(Count=7,
InnerClass(InnerClass='android/support/v7/widget/CardView$1', OuterClass='', …

[Xamarin.Android.Tools.Bytecode] Handle null InnerClassInfo values

---

tools/jcw-gen/jcw-gen.csproj

Context: https://github.com/mono/Embeddinator-4000
Context: https://github.com/xamarin/Java.Interop/commit/b6431ac85042960ba28dfb19f0be19573745d968
Embeddinator-4000 is an in-progress utility to easily allow
Java/C/Objective-C/etc. to consume .NET CIL. For example, it would be
desirable to be able to "export" a `.dll` into an Android `.aar` file,
so that Java developers using Android Studio can consume and use
managed assemblies in a straightforward manner.
Part of making this work will be to generate Java "bindings" of an
assembly.
"Funny" thing: we already partially have that: `jcw-gen.exe` will take
an assembly and generate Java Callable Wrappers for `Java.Lang.Object`
subclasses from that assembly. Aside from the base class requirement,
this is (more or less) what Embeddinator-4000 …

[jcw-gen] Build `jcw-gen.exe` into `$(UtilityOutputFullPath)`

---

src/Xamarin.Android.Tools.ApiXmlAdjuster/JavaApiTypeResolverExtensions.cs

Constructors had been considered to NOT reference generic type parameters
because Java syntax does not allow them. However, its argument types could
be java.lang.Class<T> in class-parse output XML (which I guess is because
class-parse tries to be as simple-and-stupid as it can be?) and every
difficulty is thrown toward api-xml-adjuster. Hence it is corrected here.
Note that it was not the first time that generic constructor arguments
have been taken care as a valid input (0ec431e).

[api-xml-adjuster] constructors could reference generic type parameters.

---

src/utils/EnumMappings.Xml.cs
src/utils/XmlExtensions.cs
tools/generator/ApiFixup.cs
tools/generator/ClassGen.cs
tools/generator/Ctor.cs
tools/generator/EnumMappings.cs
tools/generator/Field.cs
tools/generator/GenBaseSupport.cs
tools/generator/GenericParameterDefinition.cs
tools/generator/InterfaceGen.cs
tools/generator/Method.cs
tools/generator/MethodBase.cs
tools/generator/Parameter.cs
tools/generator/Parser.cs
tools/generator/Report.cs

(Two commits can be merged into one.)

[generator] switch to xlinq

---

src/Java.Interop.Tools.Cecil/Java.Interop.Tools.Cecil/DirectoryAssemblyResolver.cs

fixes
```
Tasks/LinkAssemblies.cs(103,41): error CS1503: Argument 1: cannot convert from 'System.Collections.IDictionary' to 'System.Collections.Generic.Dictionary<string, Mono.Cecil.AssemblyDefinition>'
```
in xamarin-android

ToResolverCache should return a Dictionary

---

Makefile
build-tools/scripts/jdk.mk
src/Java.Runtime.Environment/Java.Runtime.Environment.dll.config.in

In order to do so we need to configure everything so that the
native libjvm is found by the runtime. This patch adds detection
logic as well as modifies the dllmap to work on Linux in addition
to OSX.

Make tests run on Linux

---

src/java-interop/java-interop-gc-bridge-mono.c
src/java-interop/java-interop.mdproj

Java.Interop native code is built with `-std=c99` which, on Linux,
makes the `strdup(3)` and `realpath(3)` functions undeclared (they're not
part of the C99 standard). This posesa problem since both of them
return pointers and the assumed return value for an undeclared
function is an `int` - when running on a 64-bit system the "integer"
is cast to a pointer so that the high 32-bits of the resulting value
are set to 1 thus creating an invalid pointer.
This commit makes sure both functions are declared.
The commit also removes call to `gettid` which does not have a
wrapper in glibc and should be called directly using `syscall(2)`

Fix stack overflow when running on Linux

---

tools/generator/ClassGen.cs
tools/generator/CodeGenerator.cs
tools/generator/InterfaceGen.cs
tools/generator/Tests/InterfaceMethodsConflict.cs
tools/generator/Tests/expected.ji/InterfaceMethodsConflict/InterfaceMethodsConflict.xml
tools/generator/Tests/expected.ji/InterfaceMethodsConflict/Java.Interop.__TypeRegistrations.cs
tools/generator/Tests/expected.ji/InterfaceMethodsConflict/Java.Lang.Object.cs
tools/generator/Tests/expected.ji/InterfaceMethodsConflict/Xamarin.Test.II1.cs
tools/generator/Tests/expected.ji/InterfaceMethodsConflict/Xamarin.Test.II2.cs
tools/generator/Tests/expected.ji/InterfaceMethodsConflict/Xamarin.Test.SomeObject.cs
tools/generator/Tests/expected.ji/InterfaceMethodsConflict/Xamarin.Test.SomeObject2.cs
tools/generator/Tests/expected.ji/InterfaceMethodsConflict/__NamespaceMapping__.cs
tools/generator/Tests/expected.targets
tools/generator/Tests/expected/InterfaceMethodsConflict/InterfaceMethodsConflict.xml
tools/generator/Tests/expected/InterfaceMethodsConflict/Java.Interop.__TypeRegistrations.cs
tools/generator/Tests/expected/InterfaceMethodsConflict/Java.Lang.Object.cs
tools/generator/Tests/expected/InterfaceMethodsConflict/Xamarin.Test.II1.cs
tools/generator/Tests/expected/InterfaceMethodsConflict/Xamarin.Test.II2.cs
tools/generator/Tests/expected/InterfaceMethodsConflict/Xamarin.Test.SomeObject.cs
tools/generator/Tests/expected/InterfaceMethodsConflict/Xamarin.Test.SomeObject2.cs
tools/generator/Tests/expected/InterfaceMethodsConflict/__NamespaceMapping__.cs
tools/generator/Tests/generator-Tests.csproj

There are classes that implement more than one interfaces that share an
identical methods (which share the same name and the same JNI signature).
For example, java.nio.AsynchronousFileChannel implements Closeable and
AsynchronousChannel, both of which contain `close()` method.
Only one `Close()` should be generated for that class.

[generator] do not generate identical methods to previously generated ones.

---

src/Java.Interop/java/com/xamarin/java_interop/internal/JavaProxyThrowable.java

Android's Zygote process, responsible for starting and initializing
of every app as well as catching any application crashes (exceptions
not handled by the app, most of the time), special-cases application
exceptions of types Java.Lang.Error and Java.Lang.Exception (and their
derivatives) and this may cause issues with automatic crash reporting
recently added to the Google's Developer Console. The automatically collected
reports do not contain the full trace of our exceptions.

Make JavaProxyThrowable inherit Java.Lang.Error

---

tools/generator/Tests-Core/expected.cp/Java.Lang.Object.cs
tools/generator/Tests-Core/expected.cp/Java.Lang.String.cs
tools/generator/Tests-Core/expected.cp/Xamarin.Test.Invalidnames.In.cs
tools/generator/Tests-Core/expected.cp/Xamarin.Test.Invalidnames.InvalidNameMembers.cs
tools/generator/Tests-Core/expected.ji/Android.Text.SpannableStringInternal.cs
tools/generator/Tests-Core/expected.ji/Android.Views.View.cs
tools/generator/Tests-Core/expected.ji/Java.Lang.Object.cs
tools/generator/Tests-Core/expected/Android.Text.SpannableStringInternal.cs
tools/generator/Tests-Core/expected/Android.Views.View.cs
tools/generator/Tests-Core/expected/Java.Lang.Object.cs

Commit https://github.com/xamarin/java.interop/commit/b292931362fa0bfc90e3facf30bc767fe89a3dea
introduced changes that broke the generator core tests but, somehow,
the tests wouldn't fail neither on the local machine nor on Jenkis.
The breakage became apparent only on Wrench and this commit updates
the core template files to match the current generator behavior.

Update more generator tests for the recent changes

---

tools/generator/ApiTransform.cs

Until now, we (well, I) had been patient to deal with methodmap enumification
which *requires* distinction between class and interface by adding
"[Interface]" mark on interfaces. It was just to distinguish "class" and
"interface" elements under "package" element.
But... why do we need that? Performance? The impact should be actually
trivial. It can be just anything, we identify an element by @name.
On the other hand, it is very annoying to exactly specify "class" or
"interface" very carefully, because if I make a mistake then the mapping
results in a warning that then I have to carefully check.
Just reduce such chances for errors by requiring less-error-prone XPath.
It should save everyone.

[generator] reduce error-prone enumification XPath.

---

src/Java.Interop.Tools.JavaCallableWrappers/Java.Interop.Tools.JavaCallableWrappers/JavaCallableWrapperGenerator.cs
src/Java.Interop.Tools.JavaCallableWrappers/Test/Java.Interop.Tools.JavaCallableWrappers/JavaCallableWrapperGeneratorTests.cs
src/Java.Interop.Tools.JavaCallableWrappers/Test/Java.Interop.Tools.JavaCallableWrappers/SupportDeclarations.cs

Context: https://github.com/mono/Embeddinator-4000
Embeddinator-4000 will bring a lot more developers to consume C#
objects from their Java code. One pain point here is that all
constructors are generating `throws java.lang.Throwable` regardless of
the `[Export]` declaration. Looking into it further, there was also the
issue if you declared an empty Type[], jcw-gen was not handling that
case.
Changes:
- Added `ThrowsDeclaration` property for reuse, which also handles the
case of empty `Type[]`
- Constructors now use `ThrowsDeclaration` along with methods
- New test cases: a class with constructors with plain `[Export]` and a
class with `[Export]` declaring `Throws`
- Expanded methods test case: method with `Throws` and method with
`Throws` and an empty `Type[]`

[jcw-gen] constructors need to respect ExportAttribute

---

.gitmodules

- fixes #58511, #58173
- the fix in cecil:
commit 362e2bb00fa693d04c2d140a4cd313eb82c78d95
Author: Radek Doulik <rodo@xamarin.com>
Date:   Thu Jun 22 21:53:55 2017 +0200
fix reading scope start
- in case when the mdb file is out of sync, we might endup with
start_instruction being null
- it is regression introduced by
7c8e0f767d7b2f652a430e4e26f1d98a20f9e125

bump cecil and switch to mono-2017-04 to get mdb reading fix

---

tools/generator/SymbolTable.cs

Fixes: https://bugzilla.xamarin.com/show_bug.cgi?id=56436
`generator` relies on the existance of a mapping from Java types to
managed types which bind the Java type. The `generator --ref` option
will cause `generator` to make this mapping based on the managed types
from an assembly, and the mapping in turn is handled by `[Register]`
and related custom attributes:
namespace Android.Runtime {
[Register ("java/util/Collection", DoNotRegisterAcw=true)]
partial class JavaCollection {
}
}
For better or worse, nothing enforces that there be only one such
mapping, It is thus possible to have multiple types partake in the
mapping process:
namespace Java.Util {
[Register ("java/util/Collection", DoNotRegisterAcw=true)]
partial interface ICollection {
}
}
A Java type is *aliased* when two or more …

[generator] Better support aliased types

---

.gitignore
src/Java.Interop.Tools.JavaCallableWrappers/Test/Java.Interop.Tools.JavaCallableWrappers-Tests.csproj
src/Java.Interop.Tools.JavaCallableWrappers/Test/packages.config
src/Xamarin.Android.Tools.AnnotationSupport/Xamarin.Android.Tools.AnnotationSupport.csproj

- .gitignore the .vs/ directory for VS 2017
- One project was using a different version of NUnit than the rest,
caused NUnit runner to crash on Windows
- One project was missing `TargetFrameworkVersion`, which causes a build
failure on Windows

[windows] general fixes for building on Windows

---

tools/generator/SymbolTable.cs

Context: https://github.com/xamarin/xamarin-android/pull/732
Commit d7dfa0bb [broke][1] the
`xamarin-android/tests/CodeGen-Binding/Xamarin.Android.McwGen-Tests`
build, as it started treating `Android.Graphics.Color` as a normal
type, instead of the special-cased behavior it should have:
[1]: https://jenkins.mono-project.com/job/xamarin-android-pr-builder/1324/
error CS0452: The type 'Color' must be a reference type in order to use it as parameter 'T' in the generic type or method 'Object.GetObject<T>(IntPtr, JniHandleOwnership)'
error CS1503: Argument 1: cannot convert from 'Android.Graphics.Color' to 'Android.Runtime.IJavaObject'
The problem is that this code pattern:
static int n_UseColors_I (IntPtr jnienv, IntPtr native__this, int native_p0)
{
global::Com.Xamarin.Android.Bxc4288 __this …

[generator] Don't register invariant+excluded types

---

src/Java.Interop.Tools.TypeNameMappings/Java.Interop.Tools.TypeNameMappings/JniType.cs
tools/generator/ClassGen.cs
tools/generator/CodeGenerator.cs
tools/generator/Ctor.cs
tools/generator/Field.cs
tools/generator/GenBaseSupport.cs
tools/generator/InterfaceGen.cs
tools/generator/Method.cs
tools/generator/MethodBase.cs
tools/generator/Parameter.cs
tools/generator/generator.csproj

Fixes: https://bugzilla.xamarin.com/show_bug.cgi?id=57828
The #runtime team is attempting to update xamarin-android to use the
[mono/2017-06][0] and [mono/2017-08][1] (and...) branches, and when
doing so they are seeing a unit test fail in
`Xamarin.Android.Build.Tests.BuildTest.GeneratorValidateMultiMethodEventName()`:
no `BG850*` warnings are expected but they are produced.
After much analysis, the cause of ght `BG850*` warnings is that
the mono/2017-06 branch introduces a non-generic "overload" of
`System.Collections.Generic.KeyValuePair`:
namespace System.Collections.Generic {
// New with mono/2017-06
partial class KeyValuePair {
public static KeyValuePair<TKey, TValue> Create<TKey, TValue>(TKey key, TValue value);
}
// Existing since forever
partial struct KeyValuePair<TKey, TValue> { …

[generator] Only skip generic "overloads" of bound types

---

tools/generator/InterfaceGen.cs

Without this, abstract classes that implement java.time.chrono.Chronology
fail to bind because they will try to implement those static properties
as instance (this check had been done for methods, but not for properties).

[generator] do not emit static properties as instance.

---

src/Java.Interop.Tools.Cecil/Java.Interop.Tools.Cecil/DirectoryAssemblyResolver.cs
src/Java.Interop.Tools.Diagnostics/Java.Interop.Tools.Diagnostics/Diagnostic.cs
src/Java.Interop.Tools.JavaCallableWrappers/Java.Interop.Tools.JavaCallableWrappers/JavaTypeScanner.cs
src/Java.Interop.Tools.JavaCallableWrappers/Java.Interop.Tools.JavaCallableWrappers/TypeNameMapGenerator.cs
src/Java.Interop.Tools.JavaCallableWrappers/Test/Java.Interop.Tools.JavaCallableWrappers/TypeNameMapGeneratorTests.cs
src/Java.Interop/Documentation/Java.Interop/IJavaPeerable.xml
tools/jcw-gen/App.cs

Context: https://bugzilla.xamarin.com/show_bug.cgi?id=56819
Nothing *prevents* "anybody" from custom implementing `IJavaObject`:
class MyBadClass : Android.Runtime.IJavaObject {
public IntPtr Handle {
get {return IntPtr.Zero;}
}
public void Dispose () {}
}
The problem is that the above doesn't actually work: the
`IJavaObject.Handle` value contains the JNI Object Reference to pass
into JNI. The above code will thus result in always passing `null`
into Java code, which could result in a `NullPointerException`, but
will always result in *not* doing what was intended.
While it is *theoretically* possible to manually implement
`IJavaObject`, it's not something *I* would want to contemplate, nor
is it for the faint of heart, so long ago we decided to emit a warning
if we encounter a type which: …

[Java.Interop.Tools.JavaCallableWrappers] Error on bad IJavaObject

---

README.md
build-tools/scripts/jdk.mk
src/Java.Interop.Export/Tests/Export-Tests.projitems
src/Java.Interop/Java.Interop.csproj
src/Java.Interop/Java.Interop.targets
src/Java.Interop/Tests/Interop-Tests.projitems
src/java-interop/java-interop.mdproj
tests/PerformanceTests/PerformanceTests.projitems

Windows machines do not include Java in their path by default, so it is
a better experience to not require it for the build.
Changes:
- `JdkInfo.props` will include `JavaCPath` and `JarPath`
- We can customize `JavaCPath` and `JarPath` as needed on Windows
- `jdk.mk` generates these values as `javac` and `jar` for existing
platforms
- Cleaned up `JNIEnvGenPath` and places that hardcoded `Configuration`
What will need to happen downstream in Xamarin.Android:
- `Configuration.OperatingSystem.props` and `JdkInfo.props` will set
`JavaCPath` and `JarPath` for Windows
- Changes to `PrepareWindows.targets` will be needed

[windows] preparation for not requiring java in PATH

---

tools/generator/Method.cs
tools/generator/Tests/SupportFiles/Android_Runtime_CharSequence.cs
tools/generator/Tests/SupportFiles/Java_Lang_ICharSequence.cs
tools/generator/Tests/SupportFiles/Java_Lang_String.cs
tools/generator/Tests/expected.ji/TestInterface/Test.ME.ITestInterface.cs
tools/generator/Tests/expected.ji/TestInterface/Test.ME.TestInterfaceImplementation.cs
tools/generator/Tests/expected/TestInterface/Test.ME.ITestInterface.cs
tools/generator/Tests/expected/TestInterface/Test.ME.TestInterfaceImplementation.cs
tools/generator/Tests/expected/TestInterface/TestInterface.xml
tools/generator/Tests/generator-Tests.csproj

Fixes: https://bugzilla.xamarin.com/show_bug.cgi?id=59472
Assume you have the following Java method:
```java
class Example {
public static CharSequence identity(CharSequence value) {
return value;
}
}
```
When binding `Example.identity()`, we will *rename* it to have a
`Formatted` suffix, and "overload" it with a `string` overload:
```csharp
partial class Example {
public static ICharSequence IdentityFormatted (ICharSequence value)
{
// ...
}
public static string Identity (string value)
{
// ...
}
}
```
The purpose of this overloading is to make it easier to call the
method from C# code. It's not currently possible for interfaces to
contain static methods, which in turn means it's not possible for
interfaces to contain conversion operators. Thus, if a C# developer
wants to do: …

[generator] Fix Formatted() overloads & parameter aliases

---

.gitmodules

For consistency with mono/2017-06, which xamarin-android/d15-5 uses.

Bump to cecil/mono-2017-06/c0eb983d

---

tools/generator/GenBase.cs

It had annoyed me by reporting warnings on android.app.Notification.Action
as "Android.App.Action", which doesn't exist. It was due to careless use of
GenBase.Name combined with GenBase.Namespace which never cared about nested
types.

[generator] fix bogus type name in warnings for duplicate fields.

---

src/Java.Runtime.Environment/Java.Runtime.Environment.csproj
src/Xamarin.Android.Tools.Bytecode/Tests/Xamarin.Android.Tools.Bytecode-Tests.csproj
tools/generator/Tests/BaseGeneratorTest.cs
tools/generator/Tests/Compiler.cs

`Java.Interop.sln` did not compile on Windows:
- `Java.Runtime.Environment.dll.config` can be conditional, I don't
think it is needed on Windows
- `Bytecode-Tests.csproj` needs to use `$(JavaCPath)` instead of `javac`
`generator-Tests` were not passing:
- `BaseGeneratorTest` needs to ignore line endings when comparing files
- also fixed a typo
- `Compiler` was not able to locate `System.Runtime.dll` on Windows. It
turns out there is not a `Facades` directory on Windows (just a flat
directory), so added a `Directory.Exists` check

[tests] various fixes for Windows

---

Makefile
build-tools/scripts/RunNUnitTests.targets

The end goal here is to easily enable running tests on Windows. To
enable this, a new `build-tools/scripts/RunNUnitTests.targets` file is
needed. The `Makefile` will invoke this file so we aren't duplicating
anything.
We will continue with this approach in xamarin/xamarin-android, so
running unit tests is simpler on Windows there, too.
Run all tests:
```
msbuild build-tools/scripts/RunNUnitTests.targets
```
Filter based on the `--run` switch:
```
msbuild build-tools/scripts/RunNUnitTests.targets /p:Run=Java.Interop
```
Run tests on specific assemblies:
```
msbuild build-tools\scripts\RunNUnitTests.targets /p:TestAssembly="bin\TestDebug\Java.Interop.Tools.JavaCallableWrappers-Tests.dll;bin\TestDebug\LogcatParse-Tests.dll"
```
`make` commands should remain unchanged. Existing environment …

[tests] migrate nunit-console commands to MSBuild

---

src/Xamarin.Android.Tools.ApiXmlAdjuster/JavaApi.XmlModel.cs
src/Xamarin.Android.Tools.ApiXmlAdjuster/JavaApiXmlGeneratorExtensions.cs
src/Xamarin.Android.Tools.ApiXmlAdjuster/JavaApiXmlLoaderExtensions.cs
src/Xamarin.Android.Tools.Bytecode/ClassPath.cs
tools/class-parse/Program.cs

https://github.com/xamarin/xamarin-android/pull/824 added some code to
api-merge to handle "platform" attributes on <api> element, but those
attributes on api-\*.xml.in were not automatically generated. That means,
every time we regenerate api-\*.xml.in from api-xml-adjuster, those files
are invalid and causes build breakages.
Add more code in class-parse and api-xml-adjuster so that they can be
automatically added, depending on the command line.

[class-parse][api-xml-adjuster] add "platform" number on <api> element.

---

README.md

It's no longer required since 3bf9326ef030a4615735f6c0e5b3074abd62f8f7. Also cleanup build requirements since none of it is necessary anymore.

Remove mentions of osx-setup from README

---

Configuration.Override.props.in
build-tools/scripts/jdk.mk

If you don't have the legacy Java6 installed then the call to JNI_CreateJavaVM() will result in a popup requesting you to install it and abort, even if you call the libjvm.dylib that's included as part of JDK8.
According to https://github.com/originell/jpype/issues/160 and https://bugs.openjdk.java.net/browse/JDK-7131356 this is a Java8 bug and the recommended fix is to call into libjli.dylib instead.
Indeed this fixes the issue and the popup no longer shows up.

Call into libjli.dylib instead of libjvm.dylib to fix legacy Java SE 6 popup on OSX

---

.gitignore
Java.Interop.sln
Makefile
build-tools/scripts/RunNUnitTests.targets
src/Java.Interop.BootstrapTasks/Java.Interop.BootstrapTasks.csproj
src/Java.Interop.BootstrapTasks/Java.Interop.BootstrapTasks/SetEnvironmentVariable.cs
src/Java.Interop.BootstrapTasks/Properties/AssemblyInfo.cs
tests/PerformanceTests/TimingTests.cs

This ensures the following values are set on Windows:
- MONO_TRACE_LISTENER
- JAVA_INTEROP_GREF_LOG
- JAVA_INTEROP_LREF_LOG
This also cleans up what needs to be done downstream in xamarin-android:
https://github.com/xamarin/xamarin-android/pull/949
This required a new `Java.Interop.BootstrapTasks` project
that adds a `SetEnvironmentVariable` MSBuild task.
This will be useful down the road, for setting up "prepare"
steps in this repo for Windows.
Mono 5.8 also seems to have introduced a slowness in the
PerformanceTests, included a fix to allow more digits in
the time elapsed. This prevents a test failure on Mono 5.8.
Also minor updates to `.gitignore` file.

[tests] ported environment variables to MSBuild

---

gendarme-ignore.txt
src/Java.Interop/Java.Interop/JniEnvironment.Errors.cs
src/Java.Interop/Java.Interop/JniRuntime.cs

Checked and handled the Gendarme reports with **Severity:
[Critical,High]** (`make fxcop` output)
In one case refactored the `JniRuntime.RaisePendingException` method
to reuse code by calling `JniEnvironment.Exceptions.Throw`.

[Java.Interop] Took care about Critical and High Gendarme reports

---

src/Xamarin.Android.Tools.ApiXmlAdjuster/JavaApiXmlGeneratorExtensions.cs
src/Xamarin.Android.Tools.ApiXmlAdjuster/Tests/OverrideMarkerTest.cs
src/Xamarin.Android.Tools.ApiXmlAdjuster/XmlUtil.cs

This should be part or all of fixing bug #59770.

[api-xml-adjuster] generate type parameters in <constructor>.

---

gendarme-ignore.txt
src/Java.Interop/Java.Interop/JavaArray.cs
src/Java.Interop/Java.Interop/JavaObjectArray.cs
src/Java.Interop/Java.Interop/JavaProxyThrowable.cs
src/Java.Interop/Java.Interop/JniBuiltinMarshalers.cs
src/Java.Interop/Java.Interop/JniBuiltinMarshalers.tt
src/Java.Interop/Java.Interop/JniRuntime.JniMarshalMemberBuilder.cs
src/Java.Interop/Java.Interop/JniRuntime.JniValueManager.cs
src/Java.Interop/Java.Interop/JniStringValueMarshaler.cs
src/Java.Interop/Java.Interop/JniValueMarshaler.cs
src/Java.Interop/Java.Interop/ManagedPeer.cs
src/Java.Interop/Tests/Java.Interop/JavaObjectTest.cs
src/Java.Runtime.Environment/Java.Interop/MonoRuntimeValueManager.cs

* Gendarme.Rules.Performance.AvoidRepetitiveCastsRule
M:Java.Interop.JniValueMarshaler`1<T> Java.Interop.JniRuntime/JniValueManager::GetValueMarshaler()
Refactored to cast only once and made shorter
* Gendarme.Rules.Performance.AvoidUnsealedUninheritedInternalTypeRule
Sealed the classes
* Gendarme.Rules.Design.AvoidVisibleFieldsRule
T:Java.Interop.JavaArray`1
The field is only used from internal methods, thus changed the field itself to internal.
* Gendarme.Rules.Correctness.CheckParametersNullityInVisibleMethodsRule
M:System.Linq.Expressions.Expression Java.Interop.JniValueMarshaler::ReturnObjectReferenceToJni(Java.Interop.Expressions.JniValueMarshalerContext,System.String,System.Linq.Expressions.Expression)
Check for context being null
After these we are down to 124 remaining Gendarme …

[Java.Interop] More Gendarme related cleaning

---

build-tools/scripts/RunNUnitTests.targets

Context:
https://github.com/xamarin/java.interop/blob/master/Makefile#L149
When we ported the NUnit tests from `Makefile` to `MSBuild`, there was
a target missing that copies `libjava-interop.dylib` from `bin/Debug`
to `bin/TestDebug`. It went unnoticed on Windows, because these tests
are not passing yet there.

[tests] adding missing copy command to MSBuild test targets

---

build-tools/scripts/RunNUnitTests.targets

Context: https://github.com/xamarin/xamarin-android/blob/master/build-tools/scripts/RunTests.targets#L50
Context: https://devdiv.visualstudio.com/DevDiv/Default/_build/index?buildId=1138588&_a=summary&tab=ms.vss-test-web.test-result-details
On Windows, the Java.Interop tests are not getting the `ANDROID_SDK_PATH`
environment variable set. This is somehow working on macOS, but I think
it might be simpler in this case to pass in the `AndroidSdkDirectory`
property from `RunTests.targets` in xamarin-android.
This approach worked when testing locally. I will need to bump Java.Interop
and make one further change in xamarin-android to pass in
`AndroidSdkDirectory`. This will get a few skipped tests in Java.Interop
running and passing on Windows.

[tests] fix for ANDROID_SDK_PATH

---

src/Java.Interop/Java.Interop/JniType.cs

Context: https://github.com/xamarin/xamarin-android/pull/1027
Context: https://jenkins.mono-project.com/job/xamarin-android-pr-builder/2048/
Commit 7d511631 changed the visibility of
`JniType.RegisterNativeMethods()` from `public` to `internal`, in an
effort to reduce the likelihood of "user error" from calling
`JNIEnv::RegisterNatives()` multiple times, as
`JNIEnv::RegisterNatives()` invocations are *replacements*, not
"additive"; calling it more than once is *generally* Wrong™.
*Unfortunately*, `JniType.RegisterNativeMethods()` is part of the
public and shipping API, so we can't remove it, as seen in the
[xamarin-android PR build][pr2048] output:
[pr2048]: https://jenkins.mono-project.com/job/xamarin-android-pr-builder/2048/consoleText
ABI BREAK IN: Java.Interop.dll
<div>
<h2>Namespace …

[Java.Interop] JniType.RegisterNativeMethods() is public

---

src/Xamarin.Android.Tools.Bytecode/JavaParameterNamesLoader.cs
src/Xamarin.Android.Tools.Bytecode/Tests/ParameterDescription.txt
src/Xamarin.Android.Tools.Bytecode/Tests/ParameterFixupFromDescriptionText.xml
src/Xamarin.Android.Tools.Bytecode/Tests/ParameterFixupTests.cs
src/Xamarin.Android.Tools.Bytecode/Tests/Xamarin.Android.Tools.Bytecode-Tests.csproj
src/Xamarin.Android.Tools.Bytecode/Tests/java/com/xamarin/NestedInterface.java

When there is a method that takes one or more parameters that are generic
instances whose type definition contains more than one type parameters
(e.g. `java.util.Map<K,V>`), they resulted in java.util.Map<X,Y> whereas
API XML contains java.util.Map<X, Y> (notice the extra space between generic
arguments) and method type matching failed.
We should not change parameter definitions format (it is clearly declared
to NOT contain spaces within generic arguments), so expand that at loader.

[class-parse] Fix Java parameter loader for generics involved methods.

---

tools/generator/InterfaceGen.cs
tools/generator/Tests/BaseGeneratorTest.cs
tools/generator/Tests/Compiler.cs
tools/generator/Tests/Interfaces.cs
tools/generator/Tests/NormalMethods.cs
tools/generator/Tests/expected.ji/Adapters/Xamarin.Test.IAdapter.cs
tools/generator/Tests/expected.ji/Adapters/Xamarin.Test.ISpinnerAdapter.cs
tools/generator/Tests/expected.ji/GenericArguments/Com.Google.Android.Exoplayer.Drm.IExoMediaDrm.cs
tools/generator/Tests/expected.ji/NestedTypes/Xamarin.Test.NotificationCompatBase.cs
tools/generator/Tests/expected.ji/TestInterface/Test.ME.IGenericInterface.cs
tools/generator/Tests/expected.ji/TestInterface/Test.ME.ITestInterface.cs
tools/generator/Tests/expected.ji/java.lang.Enum/Java.Lang.IComparable.cs
tools/generator/Tests/expected/Adapters/Xamarin.Test.IAdapter.cs
tools/generator/Tests/expected/Adapters/Xamarin.Test.ISpinnerAdapter.cs
tools/generator/Tests/expected/GenericArguments/Com.Google.Android.Exoplayer.Drm.IExoMediaDrm.cs
tools/generator/Tests/expected/NestedTypes/Xamarin.Test.NotificationCompatBase.cs
tools/generator/Tests/expected/TestInterface/Test.ME.IGenericInterface.cs
tools/generator/Tests/expected/TestInterface/Test.ME.ITestInterface.cs
tools/generator/Tests/expected/java.lang.Enum/Java.Lang.IComparable.cs

Context: https://github.com/xamarin/AndroidSupportComponents
When compiling the Xamarin support libraries from source, its binding
projects generate thousands of warnings. Most of these warnings are
noise that could be fixed, and `generator` is just overdue for some
improvement.
My first steps to improve this:
- By default `generator-Tests` should fail if there is a C# compiler
warning
- Add an `AllowWarnings` option for `BaseGeneratorTest`, since there
are a few tests that generate C# compiler warnings that aren’t
addressed yet. The hope is this feature could be dropped from the tests
eventually.
- Fix the most common warning: `Invoker` types have a warning of a
missing `new` keyword on the generated `class_ref` field
Since `Java.Lang.Object` has a static `class_ref` property, all …

[generator] fix C# compiler warning in every Invoker

---

tools/generator/ClassGen.cs
tools/generator/JavaInteropCodeGenerator.cs
tools/generator/Method.cs
tools/generator/Parameter.cs
tools/generator/Property.cs
tools/generator/Tests/Interfaces.cs
tools/generator/Tests/expected.ji/TestInterface/Java.Lang.String.cs
tools/generator/Tests/expected.ji/TestInterface/Mono.Android.projitems
tools/generator/Tests/expected.ji/TestInterface/Test.ME.GenericObjectPropertyImplementation.cs
tools/generator/Tests/expected.ji/TestInterface/Test.ME.GenericStringPropertyImplementation.cs
tools/generator/Tests/expected.ji/TestInterface/Test.ME.IGenericPropertyInterface.cs
tools/generator/Tests/expected.ji/TestInterface/Test.ME.ITestInterface.cs
tools/generator/Tests/expected.ji/TestInterface/Test.ME.TestInterfaceImplementation.cs
tools/generator/Tests/expected.targets
tools/generator/Tests/expected/TestInterface/Test.ME.GenericObjectPropertyImplementation.cs
tools/generator/Tests/expected/TestInterface/Test.ME.GenericStringPropertyImplementation.cs
tools/generator/Tests/expected/TestInterface/Test.ME.IGenericPropertyInterface.cs
tools/generator/Tests/expected/TestInterface/Test.ME.ITestInterface.cs
tools/generator/Tests/expected/TestInterface/Test.ME.TestInterfaceImplementation.cs
tools/generator/Tests/expected/TestInterface/TestInterface.xml
tools/generator/XamarinAndroidCodeGenerator.cs

In the case of a generic interface `IFoo<T>`, generator creates:
- C# interface `IFoo` that uses `Java.Lang.Object` for `T`
- C# classes implementing `IFoo` will have the appropriate generic
types swapped out for `T`/`Java.Lang.Object`
- Therefore, C# classes implementing `IFoo` need to explicitly
implement everything in `IFoo` using `Java.Lang.Object` instead of the
generic type
Whew!
So this was already working for methods, but not properties. This adds
an  equivalent implementation for properties.
Also fixed a few warnings in the process:
- `java.lang.String` in some tests needed to be marked as `final`
- `Invokers` do not need to generate `string` overloads for
`java.lang.CharSequence`
- all interfaces needed to declare `class_ref` as `new` in XA
- all interfaces needed to declare …

[generator] explicitly implemented properties for generic interfaces

---

Makefile

Github seems to have changed their download URLs, our old URL is no
longer working:
https://cloud.github.com/downloads/spouliot/gendarme/gendarme-2.10-bin.zip
If I go to the download page:
https://github.com/spouliot/gendarme/downloads
The URL looks like it should now be:
https://github.com/downloads/spouliot/gendarme/gendarme-2.10-bin.zip
However, after this it still failed due to Github wanting to redirect.
I had to add a `-L` switch to the `curl` command to allow redirects.
I think we can close #220 in favor of this.

[build] fix gendarme download

---

src/Java.Interop.NamingCustomAttributes/Android.App/InstrumentationAttribute.cs
src/Java.Interop.NamingCustomAttributes/Android.Content/BroadcastReceiverAttribute.cs
src/Java.Interop.NamingCustomAttributes/Android.Content/ContentProviderAttribute.cs
src/Java.Interop.NamingCustomAttributes/Android.Runtime/RegisterAttribute.cs
src/Java.Interop.NamingCustomAttributes/Java.Interop.NamingCustomAttributes.projitems
src/Java.Interop.NamingCustomAttributes/Java.Interop/IJniNameProviderAttribute.cs
src/Java.Interop.Tools.JavaCallableWrappers/Java.Interop.Tools.JavaCallableWrappers/JavaCallableWrapperGenerator.cs
src/Java.Interop.Tools.JavaCallableWrappers/Test/Android.App/ActivityAttribute.cs
src/Java.Interop.Tools.JavaCallableWrappers/Test/Android.App/ApplicationAttribute.cs
src/Java.Interop.Tools.JavaCallableWrappers/Test/Android.App/InstrumentationAttribute.cs
src/Java.Interop.Tools.JavaCallableWrappers/Test/Android.App/ServiceAttribute.cs
src/Java.Interop.Tools.JavaCallableWrappers/Test/Android.Content/BroadcastReceiverAttribute.cs
src/Java.Interop.Tools.JavaCallableWrappers/Test/Android.Content/ContentProviderAttribute.cs
src/Java.Interop.Tools.JavaCallableWrappers/Test/Java.Interop.Tools.JavaCallableWrappers-Tests.csproj
src/Java.Interop.Tools.JavaCallableWrappers/Test/Java.Interop.Tools.JavaCallableWrappers/SupportDeclarations.cs
src/Java.Interop.Tools.TypeNameMappings/Java.Interop.Tools.TypeNameMappings/JavaNativeTypeManager.cs

This overlaps https://github.com/xamarin/java.interop/pull/219 so only either of this or that can be applied, but this goes one step further and completely removes Android.* attributes from Java.Interop codebase.
There are still tests that depend on those types, so they are moved to the test csproj.

Reduce Android.* dependencies from this not-only-about-Android repo, take 2

---

tools/generator/InterfaceGen.cs
tools/generator/Tests/Adapters.cs
tools/generator/Tests/GenericArguments.cs
tools/generator/Tests/InterfaceMethodsConflict.cs
tools/generator/Tests/Interfaces.cs
tools/generator/Tests/Java_Lang_Enum.cs
tools/generator/Tests/NestedTypes.cs
tools/generator/Tests/NormalMethods.cs
tools/generator/Tests/expected.ji/Adapters/Xamarin.Test.IAdapter.cs
tools/generator/Tests/expected.ji/Adapters/Xamarin.Test.ISpinnerAdapter.cs
tools/generator/Tests/expected.ji/GenericArguments/Com.Google.Android.Exoplayer.Drm.IExoMediaDrm.cs
tools/generator/Tests/expected.ji/NestedTypes/Xamarin.Test.NotificationCompatBase.cs
tools/generator/Tests/expected.ji/TestInterface/Test.ME.IGenericInterface.cs
tools/generator/Tests/expected.ji/TestInterface/Test.ME.IGenericPropertyInterface.cs
tools/generator/Tests/expected.ji/TestInterface/Test.ME.ITestInterface.cs
tools/generator/Tests/expected.ji/java.lang.Enum/Java.Lang.IComparable.cs
tools/generator/Tests/expected/Adapters/Xamarin.Test.IAdapter.cs
tools/generator/Tests/expected/Adapters/Xamarin.Test.ISpinnerAdapter.cs
tools/generator/Tests/expected/GenericArguments/Com.Google.Android.Exoplayer.Drm.IExoMediaDrm.cs
tools/generator/Tests/expected/NestedTypes/Xamarin.Test.NotificationCompatBase.cs
tools/generator/Tests/expected/TestInterface/Test.ME.IGenericInterface.cs
tools/generator/Tests/expected/TestInterface/Test.ME.IGenericPropertyInterface.cs
tools/generator/Tests/expected/TestInterface/Test.ME.ITestInterface.cs
tools/generator/Tests/expected/java.lang.Enum/Java.Lang.IComparable.cs

Context: #217
When testing generator from xamarin-android/master, I noticed that
building a binding project has some *new* warnings:
```
obj/Debug/generated/src/GoogleAnalytics.Tracking.ILogger.cs(159,14): warning CS0109:
The member 'ILoggerInvoker.class_ref' does not hide an accessible member.
The new keyword is not required.
```
Binding project: https://github.com/jonathanpeppers/GoogleAnalytics/tree/master/GoogleAnalytics.Droid
This was due to a change made in #217, I was *tricked* by how warnings
operate differently in `generator-Tests` than what happens in a real
Xamarin.Android binding project.
The difference is:
- `generator-Tests` put everything in one assembly
- Real binding projects have `Java.Lang.*` and Android types in a
separate assembly
This means that some members that are …

[generator] fixed new warnings introduced

---

src/Java.Interop.Tools.Cecil/Java.Interop.Tools.Cecil/TypeDefinitionRocks.cs
src/Java.Interop.Tools.JavaCallableWrappers/Java.Interop.Tools.JavaCallableWrappers/JavaCallableWrapperGenerator.cs
src/Java.Interop.Tools.JavaCallableWrappers/Java.Interop.Tools.JavaCallableWrappers/TypeNameMapGenerator.cs
src/Java.Interop.Tools.JavaCallableWrappers/Test/Java.Interop.Tools.JavaCallableWrappers/JavaCallableWrapperGeneratorTests.cs
src/Java.Interop.Tools.JavaCallableWrappers/Test/Java.Interop.Tools.JavaCallableWrappers/TypeNameMapGeneratorTests.cs
src/Java.Interop.Tools.TypeNameMappings/Java.Interop.Tools.TypeNameMappings/JavaNativeTypeManager.cs

Context: https://bugzilla.xamarin.com/show_bug.cgi?id=61073
The Java-to-Managed typemaps list types such as:
```
android/app/Activity
Android.App.Activity, Mono.Android, Version=0.0.0.0, Culture=neutral,
PublicKeyToken=84e04ff9cfb79065
```
Let’s assume you have an Android project with the following
assembly-level attribute:
```
[assembly:AssemblyVersion("1.0.0.*")]
```
Then on *every* build, the typemap is invalidated because your version
number has been incremented.
The fix here is to use the assembly’s short name via `GetName ().Name`
or Mono.Cecil’s equivalent `AssemblyDefinition.Name.Name`. So the above
typemap would only be `Android.App.Activity, Mono.Android`. These
changes needed to happen in both `JavaNativeTypeManager` and
`TypeNameMapGenerator`.
The final fix is to find *every* …

[jcw-gen] use Assembly Name instead of FullName for typemaps

---

build-tools/scripts/jdk.mk

Context:
https://stackoverflow.com/questions/47627499/does-android-studio-3-support-java-9-for-android-development
At the current time, we will not be able to use JDK 9 for Android. Some
of our build agents (VSTS), now have JDK 9 installed, so we need to
make a few changes to make sure JDK 8 is picked up instead.
Changes:
- Create a `JI_MAX_JDK` option, as a way for `xamarin-android` to
exclude JDK 9
- Create new `JI_JAVAC_PATH` and `JI_JAR_PATH` make variables, which
will be the full path to `javac` and `jar`
- Use `awk` to filter on <= `JI_MAX_JDK`
- Use `sed` to find the JDK version number, see options of folder names
below
- `sort -n` should be used to sort numerically
- Set `JI_JAVAC_PATH` and `JI_JAR_PATH` to their full paths
- Support both `Darwin` and `Linux`, Windows support is …

[build] option to filter by JI_MAX_JDK on make prepare

---

Makefile
src/Java.Interop/Java.Interop.csproj

Added Gendarme Configuration, to build Java.Interop.dll with mcs
compiler in a separate output directory bin/Gendarme
Updated fxcop rule in the Makefile to let gendarme use mcs compiled
version with .mdb symbols file to have source file line information
again.

[gendarme] Build Java.Interop.dll with mdb debug information

---

gendarme-ignore.txt

Added more types to ignore list of
Gendarme.Rules.Maintainability.VariableNamesShouldNotMatchFieldNamesRule,
we just ignore that rule.

[Java.Interop] Ignore VariableNamesShouldNotMatchFieldNamesRule matches

---

gendarme-ignore.txt

Ignore ListsAreStronglyTypedRule for array marshaling types, which do
not support Add, Insert and Remove methods (they throw unsupported
exception in the abstract base class JavaArray<T>).
Thus there's not much sense in adding strongly typed versions just to
throw unsupported exception there as well.

[Java.Interop] Ignore ListsAreStronglyTypedRule

---

gendarme-ignore.txt

The reason is still the same, to avoid Java.Interop namespace
polution, so that code completion is well aranged.

[Java.Interop] Ignore 2 more types for AvoidVisibleNestedTypesRule

---

gendarme-ignore.txt

Also added method, where is the reflection used, to the description.
The other method is not around anymore, so removed it.

[Java.Interop] Updated gendarme list after method name change

---

gendarme-ignore.txt
src/Java.Interop/Java.Interop/JniRuntime.JniMarshalMemberBuilder.cs

System.Void
Java.Interop.JniRuntime::SetMarshalMemberBuilder(Java.Interop.JniRuntime/CreationOptions)
tries to load optional Export assembly. We don't care about the
problem loading it and pressume it is missing when exception is
caught.
Also added debug output in case we were able to load the assembly,
which might be handly while tracing issues in marshaling.

[Java.Interop] Ignore swallowing exceptions for optional assembly load

---

gendarme-ignore.txt

Looks like Gendarme bug, the TArray is used for the cast, so it is not
unused.

[Java.Interop] Ignore AvoidMethodWithUnusedGenericTypeRule

---

gendarme-ignore.txt

Added them to the gendarme ignore list with an explanation.

[Java.Interop] Checked remaining disposed exception defects

---

src/Java.Interop/Java.Interop/JniRuntime.JniValueManager.cs
src/Java.Runtime.Environment/Java.Interop/MonoRuntimeValueManager.cs

Catched by Gendarme's
https://github.com/spouliot/gendarme/wiki/Gendarme.Rules.Exceptions.UseObjectDisposedExceptionRule(2.10)

[Java.Interop] Check for disposed state in JniValueManager methods

---

gendarme-ignore.txt

These are generated by the compiler and thus out of our control. These are also only generated by the mcs compiler and not by csc (Roslyn)
Gendarme reported 4 defects for
https://github.com/spouliot/gendarme/wiki/Gendarme.Rules.Performance.UseStringEmptyRule(2.10)

[Java.Interop] Ignore warnings for anonymous types

---

gendarme-ignore.txt

We still use the same PCL profile which doesn't contain
Type.EmptyTypes

[Java.Interop] Ignore another report of UseTypeEmptyTypesRule

---

gendarme-ignore.txt

Gendarme reports defect with
https://github.com/spouliot/gendarme/wiki/Gendarme.Rules.Performance.AvoidLargeStructureRule(2.10).
I think we cannot reduce the size of the state struct. The reported
size (54 bytes) is even larger than a real size as it contains
`Java.Interop.JniArgumentValue` field, whose size is calculated wrong
by Gendarme. It is probably larger than 16 bytes though.

[Java.Interop] Ignore Gendarme's warning of JniValueMarshalerState size

---

src/Java.Interop/Java.Interop/JavaException.cs

This simplifies the code a bit and also makes Gendarme happier about
the JavaException class, so that it doesn't issue
https://github.com/spouliot/gendarme/wiki/Gendarme.Rules.Maintainability.AvoidLackOfCohesionOfMethodsRule(2.10)
defect anymore.

[Java.Interop] Use auto-implemented properties in JavaException

---

src/Java.Interop/Java.Interop/JavaObject.cs

This simplifies the code a bit and also makes Gendarme happier about
the JavaException class, so that it doesn't issue
https://github.com/spouliot/gendarme/wiki/Gendarme.Rules.Maintainability.AvoidLackOfCohesionOfMethodsRule(2.10)
defect anymore.

[Java.Interop] Use auto-implemented properties in JavaObject

---

src/Java.Interop.Tools.TypeNameMappings/Java.Interop.Tools.TypeNameMappings/JavaNativeTypeManager.cs

Commit
https://github.com/xamarin/java.interop/commit/cb161d2031ac06f39b82e2d0d3f4ea1c60996afa
introduced a regression described in
https://github.com/xamarin/xamarin-android/issues/1149#issuecomment-356091294
The signature of the `InitializeCreator` method was wrongly calculated
as `()Ljava/lang/Object;` instead of original
`()Lmd59b7a7576784821ea63294fbca8600da1/Creator_1;`
The reason for that is, that
https://github.com/xamarin/java.interop/commit/cb161d2031ac06f39b82e2d0d3f4ea1c60996afa#diff-9e153905b02dbe50c0e0b874ba40bf3eR262
started using `IEnumerable<T>::OfType<T>`, which traverses
inheritance, unlike the original `Type::GetCustomAttributes` called
with `inherit = false`.
Thus for the `Creator<Player>` we got the `RegisterAttribute` from the
parent type `Java.Lang.Object` which …

[Java.Interop] Fix JNI signature generating

---

gendarme-ignore.txt

Added `Java.Interop.JavaArray<T>`, `Java.Interop.JavaProxyThrowable`
and `Java.Interop.Expressions.VariableCollection` to the list. These
don't follow the suggested[1] naming by design.
Also sorted the list of types for the UseCorrectSuffixRule rule.
[1] https://github.com/spouliot/gendarme/wiki/Gendarme.Rules.Naming.UseCorrectSuffixRule(2.10)

[Java.Interop] Ignore Gendarme's suffixes suggestions

---

gendarme-ignore.txt

Ignore
https://github.com/spouliot/gendarme/wiki/Gendarme.Rules.BadPractice.PreferSafeHandleRule(2.10)
for these types for performance reasons.

[Java.Interop] Ignore Gendarme's SafeHandle rule

---

gendarme-ignore.txt

Both of the types reported contain field, which needs to remain
static.

[Java.Interop] Ignore Gendarme's PreferLiteralOverInitOnlyFieldsRule

---

src/Java.Interop/Java.Interop/JniValueMarshaler.cs

This was reported by
https://github.com/spouliot/gendarme/wiki/Gendarme.Rules.Design.OperatorEqualsShouldBeOverloadedRule(2.10)
and
https://github.com/spouliot/gendarme/wiki/Gendarme.Rules.Performance.OverrideValueTypeDefaultsRule(2.10)
rules.

[Java.Interop] Implement == != operators for JniValueMarshallerState

---

gendarme-ignore.txt

Ignore
https://github.com/spouliot/gendarme/wiki/Gendarme.Rules.Design.UseCorrectDisposeSignaturesRule(2.10)
for `JniArrayElements`. We don't need the virtual `Dispose` method
here as we control the inheritance by having single internal
constructor. Thus it cannot be subclassed outside of
`Java.Interop.dll`.

[Java.Interop] Ignore dispose rule for JniArrayElements

---

gendarme-ignore.txt

It is thrown in the `public override T this [int index]` method, which
is completely fine according to the documentation[0].
It was reported by the DoNotThrowInUnexpectedLocationRule[1]
[0] https://msdn.microsoft.com/library/system.collections.ilist.item(v=vs.110).aspx
[1] https://github.com/spouliot/gendarme/wiki/Gendarme.Rules.Exceptions.DoNotThrowInUnexpectedLocationRule(2.10)

[Java.Interop] Silence Gendarme about ArgumentOutOfRangeException

---

src/Java.Interop/Java.Interop/JavaPrimitiveArrays.tt

In the commit
https://github.com/xamarin/java.interop/commit/b0497dd478f181078b8b10739a12ead5d5369238
I forgot to change the `JavaPrimitiveArrays.tt` source template, which
is used to generate `JavaPrimitiveArrays.cs` source files.

[Java.Interop] Rename _ToArray in .tt as well

---

gendarme-ignore.txt
src/Java.Interop/Java.Interop/JavaArray.cs
src/Java.Interop/Java.Interop/JavaPrimitiveArrays.cs
src/Java.Interop/Java.Interop/JavaPrimitiveArrays.tt
tests/PerformanceTests/TimingTests.cs

While reviewing
https://github.com/spouliot/gendarme/wiki/Gendarme.Rules.Exceptions.DoNotThrowInUnexpectedLocationRule(2.10)
reported for JniArrayElements::Elements we discussed the issue with
Jonathan Pryor and came out with this API change to use `return ref` instead of returning `IntPtr`.

[Java.Interop] Use ref return for elements access

---

build-tools/scripts/jdk.mk

We're trying to build xamarin-android on a VSTS macOS instance which
has multiple Java JDKs installed, including JDK 9.
The problem is that the Android SDK and JDK 9 don't get along. The
`xamarin-android/tests/CodeGen-Binding/Xamarin.Android.LibraryProjectZip-LibBinding`
build invokes `gradlew`, `gradlew` uses whatever `java` is in `$PATH`,
and when using JDK 9 `gradlew` fails:
Executing: ./gradlew assembleDebug --stacktrace
...
org.gradle.api.ProjectConfigurationException: A problem occurred configuring project ':library'.
...
Caused by: org.gradle.internal.event.ListenerNotificationException:
Failed to notify project evaluation listener.
...
Caused by: java.lang.NoClassDefFoundError: javax/xml/bind/annotation/XmlSchema
...
Caused by: java.lang.ClassNotFoundException: …

[build] Generate $(JdkBinPath)` property

---

tools/generator/CodeGenerator.cs
tools/generator/InterfaceGen.cs
tools/generator/Tests/expected.ji/GenericArguments/Com.Google.Android.Exoplayer.Drm.IExoMediaDrm.cs
tools/generator/Tests/expected/GenericArguments/Com.Google.Android.Exoplayer.Drm.IExoMediaDrm.cs

This fixes https://github.com/xamarin/xamarin-android/issues/1138
It is quite corner case, where ... arguments are used in interfaces that
can be converted to events.
Parameter types cannot be simply used for fields and parameters because
they cannot take "params" as their modifiers.
The real code fix should be in Parameter.cs, but that would require
a lot of changes unlike this tiny fix.

method parameter type may contain "params " and cannot be used by fields.

---

src/Java.Interop/Java.Interop/JniRuntime.cs

The dispose method of Runtime class wasn't working right when called
from finalizer.
That usually doesn't happen on Android, so it wasn't noticed until
now. It can happen even on Android though, when calling
System.Environment.Exit method.
In that case, the JniEnvironment's Info ThreadLocal object is already
disposed, so we cannot use it. It is also used in
JniObjectReference.Dispose so we should not try to call that as well.

[Java.Interop] Fix Runtime's Dispose method

---

src/Java.Interop/Java.Interop/JniRuntime.cs

Context: https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=1374566
Commit b4d44e4b has a nasty corner case around `JniRuntime`
construction: it can go *boom*.
Imagine the following:
1. A JVM environment in which `com.xamarin.java_interop.ManagedPeer`
is *not* in `$CLASSPATH` or otherwise available from
`JNIEnv::FindClass()`.
2. `JniRuntime` is constructed within the environment of (1).
Expected behavior: some form of exception stating that `ManagedPeer`
couldn't be found.
Actual behavior: a `NullReferenceException` (?!):
System.TypeInitializationException: The type initializer for 'Java.Interop.ManagedPeer' threw an exception. --->
System.NullReferenceException: Object reference not set to an instance of an object
at …

[Java.Interop] Call ManagedPeer.Init() last in JniRuntime

---

.gitmodules

Preparation & Harmonization for d15-7 branching.
There are no significant changes between cecil/mono-2017-10/76ffcda
(via commit 57d5d514) and cecil/mono-2017-12/1afa0668, because they're
the same tree! (76ffcda is a merge commit for 1afa0668.)

Bump to cecil/mono-2017-12/1afa0668

---

src/Java.Interop.Tools.Cecil/Java.Interop.Tools.Cecil/DirectoryAssemblyResolver.cs

Context https://github.com/xamarin/xamarin-android/issues/1154
One of the problems we currently face is that our build system
resolves `ref` netstandard libraries. With the current cache
system, onces an assembly has been loaded into the Cecil cache
it only ever uses that assembly. We might need to replace the
current cached version with a new one if we detect a `ref` and
need to reload the `lib`.

[Java.Interop.Tools.Cecil] Change DirectoryAssemblyResolver to allow forced loading.

---

.gitignore
build-tools/scripts/RunNUnitTests.targets

To get our desired behavior on VSTS, we have to:
- Make sure our call to NUnit returns a failing exit code
- Set the "Continue on Error" option in VSTS
- Add a step at the end of our build definition in VSTS to fail the
build if any issues ocurred
To make this work, we have to change our `<Exec />` task usage to
`ContinueOnError="ErrorAndContinue"`.
I tested the VSTS behavior upstream in xamarin-android, see a build here:
https://devdiv.visualstudio.com/DevDiv/_build/index?buildId=1478269
Other changes:
- Added `Resource.designer.cs` to .gitignore to match xamarin-android

[build] fix for unit tests to run on VSTS

---

src/Java.Interop/Java.Interop/JniRuntime.JniMarshalMemberBuilder.cs
tools/jnimarshalmethod-gen/App.cs
tools/jnimarshalmethod-gen/Xamarin.Android.Tools.JniMarshalMethodGenerator.csproj
tools/jnimarshalmethod-gen/packages.config

Updated the generator to generate helper marshaling methods for
classes implementing `Java.Interop.IJavaPeerable` interface and their
methods with `Android.Runtime.RegisterAttribute` custom
attribute. Plus `__RegisterNativeMembers` method to register these
methods during runtime.
It is part of https://github.com/xamarin/xamarin-android/projects/1
project.
The JniRuntime.JniMarshalMemberBuilder.cs change is a workaround for
BCL bug, which causes this exception:
Error: jnimarshalmethod-gen: Unable to process assembly '/Users/rodo/Projects/xatemplateaot/xatemplateaot/obj/Debug/android/assets/Mono.Android.dll'
Index was outside the bounds of the array.
System.IndexOutOfRangeException: Index was outside the bounds of the array.
at System.Attribute.InternalParamGetCustomAttributes …

[jnimarshalmethod-gen] Generate helpers for methods with Register CA

---

tools/generator/Tests/BaseGeneratorTest.cs

I've been doing all my development on Windows lately (as a way to
experience what our Windows userbase encounters). One of the painpoints
of working on generator is the fact that the failing assertion message
is not very useful. I changed the message to a valid powershell command,
which seems inherently more useful on Windows.
This allows me to just paste error into powershell and view the diff
like macOS/linux users can do with the unix/bash command.

[tests] better assertion failure for Windows devs

---

tools/generator/ClassGen.cs
tools/generator/CodeGenerator.cs
tools/generator/GenBase.cs
tools/generator/Tests/AccessModifiers.cs
tools/generator/Tests/expected.ji/AccessModifiers/Mono.Android.projitems
tools/generator/Tests/expected.ji/AccessModifiers/Xamarin.Test.BasePublicClass.cs
tools/generator/Tests/expected.ji/AccessModifiers/Xamarin.Test.ExtendPublicClass.cs
tools/generator/Tests/expected.ji/AccessModifiers/Xamarin.Test.PublicClass.cs
tools/generator/Tests/expected.ji/AccessModifiers/Xamarin.Test.PublicFinalClass.cs
tools/generator/Tests/expected.targets
tools/generator/Tests/expected/AccessModifiers/AccessModifiers.xml
tools/generator/Tests/expected/AccessModifiers/Xamarin.Test.BasePublicClass.cs
tools/generator/Tests/expected/AccessModifiers/Xamarin.Test.ExtendPublicClass.cs
tools/generator/Tests/expected/AccessModifiers/Xamarin.Test.PublicClass.cs
tools/generator/Tests/expected/AccessModifiers/Xamarin.Test.PublicFinalClass.cs
tools/generator/Tests/generator-Tests.csproj

Fixes #168
Java allows public classes to inherit from "package-private" classes, in
which case the `public` & `protected` members of the "package-private"
class are visible within the public class:
// Java
/* package */ abstract class SpannableStringInternal {
public void getChars(int start, int end, char[] dest, int off);
// ...
}
public class SpannableString extends SpannableStringInternal {
// ...
}
The problem is that `generator` didn't properly support this construct,
and *skips* binding of "package-private" types, resulting in generated
C# code such as:
// C#
public partial class SpannableString : SpannableStringInternal {
// CS0246: The type or namespace name `SpannableStringInternal` could not be found
}
This could be worked aroudn via Metadata by making the "package-private" …

[generator] better support for "package-private" classes

---

build-tools/scripts/RunNUnitTests.targets

Make the stacktraces in the nunit tests more useful by passing
`--debug` to mono to have line numbers in the error reports.
Example output:
```
Errors and Failures:
1) Test Error : Java.InteropTests.MarshalMemberBuilderTest.AddExportMethods
System.MissingMethodException : void Java.Interop.JniObjectReference.Dispose(Java.Interop.JniObjectReference)
at (wrapper managed-to-native) Java.Interop.NativeMethods.java_interop_jnienv_call_void_method(intptr,intptr&,intptr,intptr)
at Java.Interop.JniEnvironment+InstanceMethods.CallVoidMethod (Java.Interop.JniObjectReference instance, Java.Interop.JniMethodInfo method) [0x00060] in /Users/rodo/git/java.interop/src/Java.Interop/Java.Interop/JniEnvironment.g.cs:11620
at Java.InteropTests.MarshalMemberBuilderTest.AddExportMethods () [0x0010d] in …
```

[tests] Run nunit tests in debug mode, so that we get line numbers

---

Makefile
build-tools/scripts/mono.mk
src/Java.Interop/Java.Interop/JniRuntime.JniTypeManager.cs
tools/jnimarshalmethod-gen/App.cs
tools/jnimarshalmethod-gen/TypeMover.cs
tools/jnimarshalmethod-gen/Xamarin.Android.Tools.JniMarshalMethodGenerator.csproj

Move the generated marshaling methods back to the original assembly in
the nested classes.
So for example a `MainActivity` class, derived from
`Android.App.Activity`, which overrides `OnCreate` method, will get
new nested class named `__<$>_jni_marshal_methods`. The nested class
will contain these helper methods:
```
System.Void n_onCreate_Landroid_os_Bundle_(System.IntPtr,System.IntPtr,System.IntPtr)
System.Void __RegisterNativeMembers(Java.Interop.JniNativeMethodRegistrationArguments)
```
These methods will be used during the native type registration.

[jnimarshalmethod-gen] Move generated helpers to the original assembly

---

tools/jnimarshalmethod-gen/App.cs
tools/jnimarshalmethod-gen/TypeMover.cs

Replace the `Type.GetType (string)` call with `typeof (...)`. Example
improved method:
```
[JniAddNativeMethodRegistration]
public static void __RegisterNativeMembers (JniNativeMethodRegistrationArguments args)
{
Type typeFromHandle = typeof(MainActivity.__<$>_jni_marshal_methods);
args.AddRegistrations (new JniNativeMethodRegistration[] {
new JniNativeMethodRegistration ("n_onCreate", "(Landroid/os/Bundle;)V", Delegate.CreateDelegate (typeof(Action<IntPtr, IntPtr, IntPtr>), typeFromHandle, "n_onCreate_Landroid_os_Bundle_"))
});
}
```
Also refactor the code a bit to improve speed.

[jnimarshalmethod-gen] Improve generated __RegisterNativeMembers

---

.gitignore
Before.Java.Interop.sln.targets
README.md
build-tools/scripts/PrepareWindows.targets
src/Java.Interop.BootstrapTasks/Java.Interop.BootstrapTasks.csproj
src/Java.Interop.BootstrapTasks/Java.Interop.BootstrapTasks/DownloadUri.cs
src/Java.Interop.BootstrapTasks/Java.Interop.BootstrapTasks/JdkInfo.cs
src/Java.Interop.BootstrapTasks/Java.Interop.BootstrapTasks/RegistryEx.cs

Context: https://github.com/xamarin/xamarin-android/blob/master/build-tools/scripts/PrepareWindows.targets
Similar to what was setup in `xamarin-android`, this enables Windows
developers to build via:
msbuild Java.Interop.sln /t:Prepare
Following this you can build the solution as you would expect in
Windows (or use an IDE):
msbuild Java.Interop.sln
Steps needed to "prepare" Java.Interop:
- `git submodule update`
- Build `Java.Interop.BootstrapTasks`
- Download NuGet to `.nuget/NuGet.exe`
- NuGet restore `Java.Interop.sln`
- Run a `JdkInfo` task to get the Java SDK directories on Windows
To implement this, I had to:
- Add `PrepareWindows.targets` and `Before.Java.Interop.sln.targets`
- Port the `JdkInfo` and `DownloadUri` tasks from `xamarin-android`
- Port some code from …

[build] setup PrepareWindows.targets

---

tools/generator/Tests/SupportFiles/RegisterAttribute.cs
tools/generator/Tests/Unit-Tests/ManagedTests.cs
tools/generator/Tests/Unit-Tests/XmlTests.cs
tools/generator/Tests/generator-Tests.csproj

As I begin refactoring `generator`, it looks like I will be making
changes to `ManagedClassGen` and `XmlClassGen` as well as the various
other types that use either Mono.Cecil or XDocument to represent a type
in `generator`.
These are the first examples of unit tests that can be written against
these classes, and are just simple smoke tests for now.
ManagedTests
- C# types defined in a namespace at the top of the file
- Copies the current test assembly to `%TEMP%`, and loads it via Mono.Cecil
- Mono.Cecil holds a lock on the file, so it was causing some issues
with my IDE if I opened the current assembly with Mono.Cecil
- Had to change the build action for `SupportFiles\RegisterAttribute` so
I could use the type within the test assembly. It is still copied to the
output directory for the …

[generator] initial unit tests for Xml* and Managed* classes

---

src/Java.Interop/Java.Interop/JniNativeMethodRegistrationArguments.cs

The methods part of `JniNativeMethodRegistrationArguments` is not
needed in most common case, where the marshaling methods generated by
jnimarshalmethod-gen are used.
This will save an unnecessary allocations in XA, when registering
native methods.

[Java.Interop] Allow null methods in registration arguments

---

gendarme-ignore.txt
src/Java.Interop/Java.Interop/JniRuntime.JniTypeManager.cs

In case of generated nested types, named `__<$>_jni_marshal_methods`,
we don't need to check all of the methods, just use the
`__RegisterNativeMembers` one.
This saves many GetCustomAttribute calls and should also be faster
than iterating over all methods of given type.
Also updated `TryRegisterNativeMembers` signature in the gendarme
ignore list.

[Java.Interop] Improve lookup of register method

---

tools/jnimarshalmethod-gen/TypeMover.cs

Do not move empty marshaling classes to the originating
assembly. These classes exist only as hosting classes for their
nested marshaling classes.
We have these, because we create the same class hierarchy in the
*-JniMarshalMethod assembly as is present in the originating
assembly. So some of the classes we create contain only nested
classes with marshal methods, but don't contain any marshal
methods itself. Like `Java.Interop.TypeManager` and
`Java.Interop.TypeManager+JavaTypeManager`.
When we are moving the marshal methods back to the originating
assembly, we don't need to create the `__<$>_jni_marshal_methods`
nested classes in the types, which don't have any marshal
methods (these are the "empty" classes on the *-JniMarshalMethod
side), so in the `Java.Interop.TypeManager` class for …

[jnimarshalmethod-gen] Do not move "empty" classes

---

tools/jnimarshalmethod-gen/App.cs
tools/jnimarshalmethod-gen/TypeMover.cs

This options tells the tool to generate the marshal methods only for
the given types. It comes handy when working with big assemblies like
`Mono.Android` and one is interested only in results for the given
types.
The option takes *regex* pattern as input and matches types name against it.
Also updated the help messages.

[jnimarshalmethod-gen] Added -t option

---

src/Java.Interop/Java.Interop/JniRuntime.JniTypeManager.cs
src/Java.Interop/java/com/xamarin/java_interop/internal/JavaProxyThrowable.java

Do not throw the `NotSupportedException` exception in
`JniRuntime+JniTypeManager::RegisterNativeMembers` anymore. Throwing
that exception ment that every type to be registered had to have
register method to register marshaling methods, even when there were
no methods to register.
With recent changes by
https://github.com/xamarin/java.interop/commit/3f96359469b09602dc69bfa4b658a27c9128f243,
where we started to throw that exception again, we run into issues as
JavaProxyThrowable didn't have the *empty* register method
anymore. That led to a crash in the PropagateException tests, where
JavaProxyThrowable needed to be ready, but wasn't becase its
registration failed and thrown the exception, which cannot be
propagated because we didn't have JavaProxyThrowable in valid state.
To provide a way …

[Java.Interop] Do not throw in RegisterNativeMembers

---

tools/generator/ClassGen.cs
tools/generator/Method.cs
tools/generator/MethodBase.cs
tools/generator/Tests/Unit-Tests/ManagedTests.cs
tools/generator/Tests/Unit-Tests/XmlTests.cs

Context 4ec5d4e
In improving our support for "package-private" classes, I had to add a
check to compare if two methods have the same signature. The expression
was of the form:
m.Name == baseMethod.Name && m.Parameters.JavaSignature == baseMethod.Parameters.JavaSignature
The problem with this is that the `JavaSignature` property can throw an
NRE if one of the parameter types is unknown, or only becomes valid
later on in generator's process. Instead I need to only rely on the
original Java information here, and loop over the parameters individually.
To fix this:
- Create a `bool Matches (MethodBase other)` method in `MethodBase`
- Override `Matches` in `Method`, also check the return type
- Add some unit tests for these scenarios for both `XmlMethod` and
`ManagedMethod`

[generator] fix for NRE in `FixupAccessModifiers`

---

Makefile
src/Java.Interop.Tools.Cecil/Java.Interop.Tools.Cecil/DirectoryAssemblyResolver.cs
tools/jnimarshalmethod-gen/App.cs
tools/jnimarshalmethod-gen/TypeMover.cs

Update the originating assembly instead of creating a *new* one,
called `<AssemblyName>-new.dll`
I expected I would need to load the originating assembly in the
separate AppDomain, but instead it was enough to load it with cecil
with reading parameters having `ReadWrite = true`.
Because the referenced assemblies might not be writable, we need to
keep loading them as read only, thus with default `ReadWrite = false`.
For that I added new method to our cecil assembly resolver, to add
existing assembly definition to its cache. We first read the
originating assemblies as *ReadWrite* and add them to the resolver
cache.

[jnimarshalmethod-gen] Update the originating assembly

---

Makefile
tools/jnimarshalmethod-gen/App.cs

We don't want to leave the `*-JniMarshalMethods.dll` files behind, so
we need to delete them, once the methods are moved back to the
originating assemblies.
Because the dynamic assembly builder needs to save the temporary
assembly, we need it to use `AssemblyBuilderAccess.Save`, which means
the assembly cannot be unloaded from the domain.
Thus we do the work in separate `AppDomain` and unload the whole
domain at the end, so that the temporary files are not locked
anymore. A bit of refactoring was needed for that.
There is also new `--keeptemp` option to enable the old behavior and
keep the temporary files.
And finally the help message is printed when no arguments
supplied. Plus new error message in case no assemblies were specified.

[jnimarshalmethod-gen] Delete the temporary files

---

tools/jnimarshalmethod-gen/TypeMover.cs

When looking for matching instructions pattern in
`__RegisterNativeMembers` method, we want to also allow `ldc.i4`
instructions here. So that we update the methods with more than 128
method registrations correctly.
Until now we were only matching instructions like `ldc.i4.[0-8]`,
`ldc.i4.s` and missed the `ldc.i4` which are used for integer values
greater than 127.

[jnimarshalmethod-gen] Do not miss ldc.i4

---

build-tools/scripts/msbuild.mk

[`xbuild` is deprecated][0], and has been deprecated for over a year.
[0]: https://www.mono-project.com/docs/about-mono/releases/5.0.0/#xbuild
Update `$(MSBUILD)` so that we build with `msbuild` by default,
not `xbuild`.

[build] Use `msbuild` by default, not `xbuild`

---

tools/generator/ClassGen.cs
tools/generator/CodeGenerator.cs
tools/generator/Field.cs
tools/generator/GenBase.cs
tools/generator/GenBaseSupport.cs
tools/generator/GenericParameterDefinition.cs
tools/generator/GenericParameterList.cs
tools/generator/GenericSymbol.cs
tools/generator/JavaApiDllLoaderExtensions.cs
tools/generator/Parameter.cs
tools/generator/Parser.cs
tools/generator/ReturnValue.cs
tools/generator/SymbolTable.cs
tools/generator/Tests/Unit-Tests/ManagedTests.cs
tools/generator/Tests/Unit-Tests/SupportTypes.cs
tools/generator/Tests/Unit-Tests/XmlTests.cs

While refactoring/writing tests for `generator` some issues arise
because `SymbolTable` is `static`.
At the begin and end of each test, we would like to begin with a clean
state. Unfortunately if `SymbolTable` is static, symbols are leftover
from any previous tests. This both introduces different behavior
depending on the ordering of tests, as well as potential interference
between tests.
Changes:
- `SymbolTable` is non-static, several helper methods that were
"stateless" were left to be static
- Added a property to `CodeGenerationOptions` to hold an instance of
`SymbolTable` since this object is already passed through most of
`generator`
- There were a few places I had to add additional parameters to pass the
instance of `CodeGenerationOptions` through
- The constructor for …

[generator] SymbolTable is no longer static

---

src/Java.Interop.Export/Java.Interop/MarshalMemberBuilder.cs
tools/jnimarshalmethod-gen/App.cs

We use it in the `jnimarshalmethod-gen` and will also use it from the
XA's Xamarin.Android.Build.Tasks, to avoid code duplication.
It also removes trailing '_' from marshal methods names of java
methods without arguments.

[Java.Interop.Export] Add GetMarshalMethodName to MarshalMemberBuilder

---

tools/generator/CodeGenerator.cs
tools/generator/Tests/Unit-Tests/AdjusterTests.cs
tools/generator/Tests/Unit-Tests/ManagedTests.cs
tools/generator/Tests/generator-Tests.csproj

Context: https://github.com/xamarin/java.interop/commit/19bcca50934ff7a2464e8d6170eadbba10c2b266
One of the side-effects of 19bcca5 was that `Validate` *has* to be
called in order for `ManagedClassGen` and `ManagedInterfaceGen` to be
initialized properly. Otherwise, properties such as `JavaName` are
going to return `null`.
I added a call to `Validate` in `CodeGenerator.ProcessReferencedType`,
and additionally added a new test class for the `Adjuster` class. For
now, it is verifying this regression is fixed, but should be expanded
down the road to get better test coverage around the `Adjuster` class.

[generator] fix regression for types from assemblies

---

tools/jnimarshalmethod-gen/Xamarin.Android.Tools.JniMarshalMethodGenerator.csproj

Set `$(OutputPath)` to `$(UtilityOutputFullPath)`, so that it is
available in the Xamarin.Android installation.
The `$(UtilityOutputFullPath)` is overriden in
`Configuration.Override.props` by XA.

[jnimarshalmethod-gen] Update OutputPath

---

tools/generator/ClassGen.cs
tools/generator/CodeGenerator.cs
tools/generator/GenBaseSupport.cs
tools/generator/InterfaceGen.cs
tools/generator/Tests/Unit-Tests/ManagedTests.cs

Context: https://github.com/xamarin/java.interop/commit/84014f4a735f65c3aa666597f05ce6de7d984bb6
Context: https://github.com/xamarin/java.interop/commit/19bcca50934ff7a2464e8d6170eadbba10c2b266
In trying to make the `SymbolTable` class non-static, there was one
place in the `GenBaseSupport` class that needed to use the
`SymbolTable`. My first attempt to workaround this was to move some of
the logic in `GenBaseSupport`'s constructor to an `OnValidate` method.
Unfortunately this breaks alot of things, since it requires `Validate`
to be called for any `ManagedClassGen` or `ManagedInterfaceGen`.
Things are further complicated when you try a large set of input, such
as what happens during `xamarin-android`'s build. Calling `Validate`
was getting exceptions such as: …

[generator] fix regression for types from assemblies, take 2!

---

src/Java.Interop.Tools.JavaCallableWrappers/Java.Interop.Tools.JavaCallableWrappers/TypeNameMapGenerator.cs
src/Java.Interop.Tools.JavaCallableWrappers/Test/Java.Interop.Tools.JavaCallableWrappers/TypeNameMapGeneratorTests.cs

Fixes https://github.com/xamarin/xamarin-android/issues/1431
If we end up with an empty mapping dictionary the following
exception is thrown.
System.InvalidOperationException: Sequence contains no elements
at System.Linq.Enumerable.Max(IEnumerable`1 source)
at Java.Interop.Tools.JavaCallableWrappers.TypeNameMapGenerator.WriteBinaryMapping(Stream o, Dictionary`2 mapping)
at Java.Interop.Tools.JavaCallableWrappers.TypeNameMapGenerator.WriteJavaToManaged(Stream output)
at Xamarin.Android.Tasks.GenerateJavaStubs.UpdateWhenChanged(String path, Action`1 generator)
at Xamarin.Android.Tasks.GenerateJavaStubs.WriteTypeMappings(List`1 types)
at Xamarin.Android.Tasks.GenerateJavaStubs.Run(DirectoryAssemblyResolver res)
at Xamarin.Android.Tasks.GenerateJavaStubs.Execute()
at …

[Java.Interop.Tools.JavaCallableWrappers] Fix Exception in GenerateJavaStubs

---

tools/generator/Property.cs
tools/generator/Tests/Unit-Tests/SupportTypes.cs

Context: https://jenkins.mono-project.com/job/xamarin-android-pr-builder/3070/testReport/junit/Xamarin.Android.Build.Tests/BindingBuildTest/MergeAndroidManifest___Debug/
Upstream in xamarin-android, `generator` created a property such as:
public new override unsafe string Message {
This is not valid C#, so we shouldn't emit `new override` in any case.
I also noticed a mistake in `TestClass`, it should be setting
`this.BaseType` to `baseType`.

[generator] prevent generation of `new override` properties

---

tools/jnimarshalmethod-gen/App.cs
tools/jnimarshalmethod-gen/TypeMover.cs

Do not add new `__<$>_jni_marshal_methods` nested classes in case they
already exists.
Added `-f` option to force regeneration when desired. In that case,
remove existing `__<$>_jni_marshal_methods` classes and generate new
ones.

[jnimarshalmethod-gen] Add -f option

---

tools/generator/ApiXmlAdjuster.cs
tools/generator/CodeGenerator.cs
tools/generator/JavaApiDllLoaderExtensions.cs
tools/generator/Tests/Unit-Tests/AdjusterTests.cs

Context: https://github.com/xamarin/xamarin-android/pull/1633#issuecomment-387069574
Turning `SymbolTable` into a non-`static` class (19bcca50) broke all
manner of things when trying to integrate with xamarin-android --
partially fixed by 84014f4a, 2004ef86, and b19bc60f -- yet we *still*
can't bump, because Java.Interop/b19bc60f causes the
[`BindingBuildTest/RemoveEventHandlerResolution()` unit test fails][0].
[0]: https://jenkins.mono-project.com/job/xamarin-android-pr-builder/3075/testReport/junit/Xamarin.Android.Build.Tests/BindingBuildTest/RemoveEventHandlerResolution___Debug/
error CS0115: 'SherlockPreferenceActivity.OnTitleChanged(ICharSequence, int)': no suitable method found to override
Further investigation determined that the CS0115 occurred because
during the binding project …

[generator] Copy ClassGen into JavaClass

---

src/Java.Interop/Java.Interop/JniValueMarshaler.cs

https://github.com/xamarin/java.interop/commit/4a4e2e85da7f0c17d16486cd498f5781374476fd
modified `JniValueMarshalerContext` constructor by adding `vm`
parameter with default value. That would break existing compiled code,
when `Java.Intreop.dll` is updated and the code is not recompiled.
So get rid of the default parameter value and add back the old
constructor and let it use the new one.

[Java.Interop] Get JniValueMarshalerContext constructor back

---

src/java-interop/java-interop-mono.c
src/java-interop/java-interop-mono.h

Allow building content of libjava-interop as part of host android
runtime lib in XA.
Use `monodroid_get_dylib ()->` instead of `mono.` as `mono` declared
in
https://github.com/xamarin/xamarin-android/blob/master/src/monodroid/jni/monodroid-glue.c#L452
is static.
Enable using `dylib-mono.*` when `DYLIB_MONO` is defined.

[libjava-interop] Allow building of it from XA

---

Makefile

Context: https://stackoverflow.com/a/40974417/132442
In 4d5d2ff, I modified our C# NUnit tests so that line endings are
ignored. However, there is a `run-test-generator-core` target used
upstream in the `monodroid` build. In order to function the same as
our C# tests, it also should ignore line endings. I found the weirdly
named `--strip-trailing-cr` option for `diff` allows these tests to
perform a diff and ignore line endings. Note, that it does more than
ignoring a trailing CR, it ignores line endings in both files...
Other changes:
- `generator/Tests/expected.targets` was removed in 33f01d8, but there
were some lines in our `Makefile` updating it. These should not be
needed anymore.

[build] fix for run-test-generator-core make target

---

src/Xamarin.Android.Tools.Bytecode/Tests/Xamarin.Android.Tools.Bytecode-Tests.csproj

The `BuildClasses` target constantly executes:
$ msbuild /v:diag
$ msbuild /v:diag
...
Building target "BuildClasses" partially, because some output files are out of date with respect to their input files.
[TestJar: Input=java/com/xamarin/NestedInterface.java, Output=obj/Debug/classes/NestedInterface.class] Output file does not exist.
The *cause* of the above message is because the `Outputs` attribute
used `%(RecursiveDir)`, which was *empty* for `NestedInterface.java`,
as the full path was explicitly provided.  (No wildcards were used.)
As it happens, that `@(TestJar)` entry wasn't required *anyway*, as
`NestedInterface.java` was also pulled in via the wild-card include.
Remove the `java\com\xamarin\NestedInterface.java` entry, which allows
`BuildClasses` Inputs & Outputs to behave as …

[Xamarin.Android.Tools.Bytecode-Tests] Fix BuildClasses

---

src/java-interop/java-interop-gc-bridge-mono.c
src/java-interop/java-interop-logger.c
src/java-interop/java-interop-logger.h
src/java-interop/java-interop-util.c
src/java-interop/java-interop-util.h

It makes it possible to build it in XA for `mxe-Win32:mxe-Win64` host
ABI's.
Also moved utf8/16 helper functions from XA to
`java-interop-util.[ch]`

[java-interop] Implemented Windows version of ji_realpath

---

Makefile
build-tools/scripts/PrepareWindows.targets
build-tools/scripts/jdk.mk
build-tools/scripts/jdk.targets
src/Java.Interop.BootstrapTasks/Java.Interop.BootstrapTasks.csproj
src/Java.Interop.BootstrapTasks/Java.Interop.BootstrapTasks/JdkInfo.cs
src/Java.Interop.BootstrapTasks/Java.Interop.BootstrapTasks/OS.cs

Fixes: https://github.com/xamarin/xamarin-android/issues/1493
On some machines, `make prepare` fails:
build-tools/scripts/jdk.mk:130: *** missing separator.  Stop.
make: *** [prepare-external] Error 2
Eventually, we "found" the "cause": This make fragment:
$(shell ls -dtr $(_DARWIN_JDK_FALLBACK_DIRS) | sort | tail -1)
was dying a terrible horrible no good death:
_DARWIN_JDK_ROOT=/Library/Java/JavaVirtualMachines/jdk1.8.0_161.jdk
kkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkkin/sh: 49m: command not found
[Turns Out™][0], **ls**(1) should be *avoided*, as its output is
*unsafe* (I'm not sure *why*, and I'm not able to repro the above
failure on my machine, but it's *clearly* bad).
[0]: http://mywiki.wooledge.org/ParsingLs
Why are we using **ls**(1)?  To sort by timestamp, via `ls -dtr`.
What's the …

[build] Don't use ls(1) to find JDK paths

---

Makefile
src/Java.Runtime.Environment/Java.Runtime.Environment.dll.config.in

Make it possible to inject *dllmap*'s into
`src/Java.Runtime.Environment/Java.Runtime.Environment.dll.config` by
providing `Java.Runtime.Environment.Override.dllmap` file in
Java.Interop root directory
In case the file is missing, the line containing
`@JAVA_RUNTIME_ENVIRONMENT_DLLMAP@` is removed.

[Java.Runtime.Environment] Allow injection of dllmap's to config

---

src/java-interop/java-interop-gc-bridge-mono.c

Case sensitivity rears its head, in the form of building
xamarin-android under Linux with MXE enabled:
$ "/usr/bin/x86_64-w64-mingw32-gcc" ...
…/xamarin-android/external/Java.Interop/src/java-interop/java-interop-gc-bridge-mono.c:13:10: fatal error: FileAPI.h: No such file or directory
#include <FileAPI.h> (TaskId:1199)
^~~~~~~~~~~ (TaskId:1199)
compilation terminated. (TaskId:1199)
Change the `<FileAPI.h>` into a platform-neutral `<fileapi.h>` so that
the header can be found when building under Linux.

[java-interop] Fix casing of <fileapi.h>

---

Configuration.props
README.md
src/Xamarin.Android.Cecil/Xamarin.Android.Cecil.targets

There is a philosophically confusing question due to the interaction
between the Java.Interop, xamarin-android, and mono repos:
Which repo "owns" Cecil?
The Java.Interop repo has a Cecil submodule.
The mono repo has a Cecil submodule. (*Two*, if you count the indirect
one from the Linker submodule, but that shouldn't be used.)
The xamarin-android repo references both Java.Interop & mono.
If we have a fix in Cecil, what all needs bumping?
A present, the answer is *everything*, because the mono reference is
included into a variety of mono-built utilities (*as source*, not an
assembly), while the Java.Interop reference built into
`Xamarin.Android.Cecil.dll` and used by the Xamarin.Android build
process.
This is somewhat confusing, and means that more work needs to be done
to apply fixes …

[build] Allow overriding Cecil location

---

src/java-interop/java-interop-gc-bridge-mono.c

The monodroid's DylibMono is initialized in
[`Java_mono_android_Runtime_init`][1] and thus not avaiable for
standalone Java.Interop consumers, like `jnimarshalmethod-gen.exe`.
Let `libjava-interop` have its own DylibMono instance and initialize
it on first call to mono functions.
We might rethink that once we start using libjava-interop's GC bridge
in monodroid.
[1]: https://github.com/xamarin/xamarin-android/blob/master/src/monodroid/jni/monodroid-glue.c#L3703

[libjava-interop] Use own DylibMono instance

---

Makefile

Update the `make preapre` target so that the file
`src/Java.Runtime.Environment/Java.Runtime.Environment.dll.config`
is created.
This is more consistent.

[build] prepare creates Java.Runtime.Environment.dll.config

---

src/Xamarin.Android.Tools.ApiXmlAdjuster/JavaApi.XmlModel.cs
src/Xamarin.Android.Tools.ApiXmlAdjuster/JavaApiXmlGeneratorExtensions.cs
src/Xamarin.Android.Tools.ApiXmlAdjuster/JavaApiXmlLoaderExtensions.cs
src/Xamarin.Android.Tools.ApiXmlAdjuster/Tests/OverrideMarkerTest.cs

class-parse emits a number of useful attributes which contain information about
the JNI signatures, return and parameter types etc. Currently, API XML adjuster
removes them from its output.
The information in extended attributes is (will be) useful for code generation
and thus this commit makes sure that all of them made it to the adjusted XML.

Don't omit the extended API description attributes

---

src/java-interop/java-interop-mono.h

Do not redefine MONO_API `#define`'s for mono's header files. This fixes the
warnings like this one:
```
In file included from java-interop-mono.c:2:
In file included from ./java-interop-mono.h:30:
In file included from /Library/Frameworks/Mono.framework/Headers/mono-2.0/mono/metadata/assembly.h:8:
In file included from /Library/Frameworks/Mono.framework/Headers/mono-2.0/mono/utils/mono-error.h:8:
/Library/Frameworks/Mono.framework/Headers/mono-2.0/mono/utils/mono-publib.h(52,9): warning GE1D896A7: 'MONO_API_EXPORT' macro redefined [-Wmacro-redefined] [/Users/rodo/git/java.interop/src/java-interop/java-interop.csproj]
#define MONO_API_EXPORT __attribute__ ((__visibility__ ("default")))
^
./java-interop.h:14:11: note: previous definition is here
#define MONO_API_EXPORT __attribute__ …
```

[java-interop] Do not redefine MONO_API*

---

src/Xamarin.Android.Tools.ApiXmlAdjuster/JavaApiXmlGeneratorExtensions.cs
src/Xamarin.Android.Tools.ApiXmlAdjuster/JavaApiXmlLoaderExtensions.cs

Commit 0881accd [broke][0] the [build][1] via unit test failure:
System.Exception : /var/folders/l8/73t5whsx7dj5v5gh_bn7zxlr0000gn/T/tmp28cf44e7.tmp (5,5): Element 'constructor' requires attribute 'jni-signature'
at Xamarin.Android.Tools.ApiXmlAdjuster.XmlUtil.GetRequiredAttribute (System.Xml.XmlReader reader, System.String name)
at Xamarin.Android.Tools.ApiXmlAdjuster.JavaApiLoaderExtensions.LoadMemberAttributes (Xamarin.Android.Tools.ApiXmlAdjuster.JavaMember member, System.Xml.XmlReader reader)
...
This was generated from e.g. `make run-test-generator-core` and
processing a "legacy" file in the form of
`tools/generator/Tests-Core/api-cp.xml` (whereby "legacy" means
"didn't contain the newly required `//constructor/@jni-signature`
XML attribute).
There are two plausible fixes:
1. Update …

[Xamarin.Android.Tools.ApiXmlAdjuster] Attributes are optional

---

Makefile
gendarme-ignore.txt
src/Java.Interop.BootstrapTasks/Java.Interop.BootstrapTasks/JdkInfo.cs
src/Java.Interop/Java.Interop/JniRuntime.cs
src/Java.Runtime.Environment/Java.Interop/JreRuntime.cs
src/Java.Runtime.Environment/Java.Runtime.Environment.dll.config.in
src/java-interop/java-interop-jvm.c
src/java-interop/java-interop-jvm.h
tests/TestJVM/TestJVM.cs
tools/jnimarshalmethod-gen/App.cs

There is a (*yugely* important) "philosophical" problem with using
`Java.Runtime.Environment.dll.config` to specify the location of the
`jvm.dll` to load, as originated in commit caca88d6:
It cannot possibly work *reliably* on any machine *other than* the
build machine.
This is the case because the
`/configuration/dllmap[@dll='jvm.dll']/@target` value comes from the
value of `$(JI_JVM_PATH)`, which is a `make` variable generated during
`make prepare` (see also 4bd9297f).  As such, the only way this can
work on an end-users machine is if the end user has the same JDK
version installed as the machine which generated
`Java.Runtime.Environment.dll.config`, which is *highly* unlikely.
(Not everyone on the Xamarin.Android team has the same JDK version!)
The only sane course of action, then, is …

[java-interop] Require dynamic JVM loading

---

src/Android.Interop/Tests/Android.Interop-Tests.csproj
src/Android.Interop/Tests/jni/Application.mk

Starting with Android NDK r17, armeabi is *removed*, meaning that we
cannot build anything with armeabi anymore.
xamarin-android changes will follow.

Remove armeabi from build.

---

build-tools/scripts/RunNUnitTests.targets

Context: https://jenkins.mono-project.com/job/xamarin-android-pr-builder/3640/
Commit d1cce190 broke unit test execution within xamarin-android,
as d1cce190 requires that the path to `jvm.dll` be specified within
the `$JI_JVM_PATH` environment variable, but `RunNUnitTests.targets`
never set or exported that environment variable.
The result is that `$JI_JVM_PATH` wasn't set, causing tests to fail:
OneTimeSetUp: System.TypeInitializationException : The type initializer for 'Java.InteropTests.JavaVMFixture' threw an exception.
----> System.NotSupportedException : The JDK supports creating at most one JVM per process, ever; do you have a JVM running already, or have you already created (and destroyed?) one? (JNI_CreateJavaVM returned -1002).
Code -1002 is `JAVA_INTEROP_JVM_FAILED_NOT_LOADED`, …

[tests] Export JI_JVM_PATH in NUnit tests

---

tools/generator/ClassGen.cs
tools/generator/InterfaceGen.cs

Context: https://github.com/xamarin/xamarin-android/pull/1998#issuecomment-408234197
Context: https://github.com/xamarin/monodroid/commit/2c515356d9a671f729aff2e81c4c2f6184749722
Long ago, `generator` was written to consume API XML descriptions
provided by Google.  This approach worked reasonably well until
Honeycomb, at which point Google didn't provide an XML API description
when the API-H `android.jar` was released.
The fix was `jar2xml`, which used Java Reflection around `android.jar`
to generate a similar API XML description which `generator` could use.
`jar2xml` in turn had its own share of problems, which resulted in
`class-parse`, which had a *different* share of problems. :-)
The original hope was that `generator` could directly use
`class-parse` output.  Turns out, it wasn't …

[generator] Don't special case `synthetic` methods

---

tools/jnimarshalmethod-gen/App.cs

Create a dictionary of cecil types at the beginning, instead of
searching through the whole module every time we need to find a type.
That saves about 12 seconds from 48, when running it on
`Mono.Android.dll`
Output of the `time` command:
Before       47.67 real        47.90 user         2.00 sys
After        35.52 real        35.57 user         2.07 sys

[jnimarshalmethod-gen] optimize type lookup

---

tools/jnimarshalmethod-gen/TypeMover.cs

Clear the type caches between moving types in multiple
assemblies. (note to myself, in case we want to process and move
multiple assemblies in parallel, we would need to make the caches per
TypeMover instance)
Also fix debug prints, where `Console::WriteLine (...)` reference
needs to be imported.

[jnimarshalmethod-gen] Fix multiple assemblies processing

---

tools/jnimarshalmethod-gen/App.cs

Do not miss registered methods with custom attributes without named
arguments. Which can happen, when we load assemblies without symbols.
Our current register attribute detection logic was looking for named arguments only and missed register attributes in the assemblies without symbols. The fix fallbacks to arguments order in case we don't find the names. Like we do in other places, here for example https://github.com/xamarin/xamarin-android/blob/master/src/Xamarin.Android.Build.Tasks/Linker/MonoDroid.Tuner/Extensions.cs#L159-L161
Fixes https://github.com/xamarin/java.interop/issues/356
For some types we miss some of the registered methods. That leads to problems during registration and later crashes, like here with `CellAdapter` type:
I/mono-stdout( 2532): Registering JNI marshal methods …

[jnimarshalmethod-gen] Do not miss registered methods

---

tools/jnimarshalmethod-gen/App.cs

The new option allows to specify which types are processed by a
*profile* with the list of types (regex patterns) to process.
It is similar to specify multiple `-t` options.

[jnimarshalmethod-gen] Add -p|--profile option

---

.gitignore
src/Java.Interop/Java.Interop.Net45.props
src/Java.Interop/Java.Interop.PCL.props
src/Java.Interop/Java.Interop.csproj
src/Java.Interop/Java.Interop.targets

Fixes: http://work.devdiv.io/667174
When building a "Hello World" Xamarin.Android app, I noticed the
following in the build log:
Adding assembly reference for Java.Interop, Version=0.1.0.0, Culture=neutral, PublicKeyToken=84e04ff9cfb79065, recursively...
Adding assembly reference for System.Runtime, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a, recursively...
Adding assembly reference for System.ComponentModel.Composition, Version=2.0.5.0, Culture=neutral, PublicKeyToken=b77a5c561934e089, recursively...
Adding assembly reference for System.Diagnostics.Debug, Version=4.0.10.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a, recursively...
Adding assembly reference for System.Threading, Version=4.0.10.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a, recursively... …

[build] option for Java.Interop to be built as non-PCL

---

src/Java.Interop/Java.Interop.csproj

Context: https://github.com/xamarin/xamarin-android/pull/2105#issuecomment-416582929
To build `Java.Interop.csproj` as `MonoAndroid,v1.0`, we need to set
the following properties:
<PropertyGroup>
<TargetFrameworkIdentifier>MonoAndroid</TargetFrameworkIdentifier>
<TargetFrameworkVersion>v1.0</TargetFrameworkVersion>
<TargetFrameworkRootPath>$(XAInstallPrefix)xbuild-frameworks</TargetFrameworkRootPath>
</PropertyGroup>
Currently it looks like `$(TargetFrameworkVersion)` is the only one we
can't modify downstream in `xamarin-android`.

[Java.Interop] allow $(TargetFrameworkVersion) to be passed in

---

build-tools/Java.Interop.BootstrapTasks/Java.Interop.BootstrapTasks/JdkInfo.cs

The Microsoft OpenJDK package does *not* contain the `includes`
directory, or `jdk.h`, or anything else needed to build native code.
Consequently, it is not useful for *building* Java.Interop.
Update the `<JdkInfo/>` task to require that `JdkInfo.IncludePath`
includes directories.  (We don't currently check that `jdk.h` exists,
but we could do so in the future if necessary.)  This causes the
Microsoft OpenJDK package to be *skipped* during `make prepare`,
causing the Java.Interop build to instead use a "system" JDK
installation which *does* provide the `include` directories.

[Java.Interop.BootstrapTasks] <JdkInfo/> requires `include` dir

---

tools/jnimarshalmethod-gen/App.cs
tools/jnimarshalmethod-gen/TypeMover.cs

That helps to process the assembly faster.
Process `Mono.Android.dll` times:
Before:
whole       37.34 real        37.29 user         2.04 sys
types        7.02 real         6.54 user         1.17 sys
After:
whole       33.84 real        34.99 user         1.01 sys
types        4.41 real         4.76 user         0.36 sys
Where *whole* means process all types in the assembly and *types*
means use the `--types` option to process only listed types.
The listed types:
#
Android.Runtime.UncaughtExceptionHandler
Java.Interop.TypeManager\+JavaTypeManager
Android.Views.View\+IOnClickListenerImplementor
#
Android.Animation.ValueAnimator\+IAnimatorUpdateListenerImplementor
Java.Lang.Thread\+RunnableImplementor

[jnimarshalmethod-gen] Ask cecil to read assemblies to the memory

---

Configuration.props
Makefile
src/Java.Interop/Java.Interop.csproj

Context: https://github.com/xamarin/java.interop/pull/368
Addressing the comments in #368, this removes more unused build targets, etc.

[build] remove remaining $XA_INTEGRATION variables

---

Makefile
src/java-interop/java-interop.csproj
tests/NativeTiming/NativeTiming.cproj

Xcode 10.0 deprecates compiling of 32bit applications.
The macOS 10.14 SDK no longer contains support for compiling
32-bit applications. If developers need to compile for i386, Xcode
9.4 or earlier is required. (39858111)
So just build 64bit everywhere.

Do not build 32bit native libraries

---

src/Java.Interop/Java.Interop/JavaPrimitiveArrays.cs
src/Java.Interop/Java.Interop/JavaPrimitiveArrays.tt
src/Java.Interop/Java.Interop/JniValueMarshaler.cs

Fixes https://github.com/xamarin/java.interop/issues/373
Added `CreateMarshaledValue` method to primitive arrays, which calls
`CreateValue` on the static `ArrayMarshaler` field.
Overriden the `CreateParameterToManagedExpression` in the primitive
arrays `ValueMarshaler` nested classes to use the new method.
Another posibility would be to make
`JniValueMarshaler::CreateValue(IntPtr, Type)` public and primitive
arrays `ArrayMarshaler` as well. That might be too much, so chose just
to add public method to the primitive array classes.
The new marshal method body is also simplified compared to the previous
one and removes allocation of new `ValueMarshaler` instance per marshal
method call. An example marshal method:
using Java.Interop;
using System;
public static bool n_onStateChange_[I (IntPtr …

[Java.Interop] Fix primitive arrays marshaling

---

src/Java.Interop.Export/Tests/Java.Interop/ExportTest.cs
src/Java.Interop.Export/Tests/Java.Interop/MarshalMemberBuilderTest.cs
src/Java.Interop.Export/Tests/java/com/xamarin/interop/export/ExportType.java
tools/jnimarshalmethod-gen/TypeMover.cs

Sometimes we ask for updated method declared in type without
generic parameters set and that led to issue where we ended with
different generic type than we wanted.
So for example in the registration methods we sometime ended with
wrong Action constructor. `Action<IntPtr, IntPtr, IntPtr, Single>`
instead of `Action<IntPtr, IntPtr, int, int>`.
The fixed registration method:
[JniAddNativeMethodRegistration]
public static void __RegisterNativeMembers (JniNativeMethodRegistrationArguments args)
{
Console.WriteLine ("Registering JNI marshal methods in Xamarin.Forms.Platform.Android.PlatformRenderer");
args.AddRegistrations (new JniNativeMethodRegistration[3] {
new JniNativeMethodRegistration ("n_dispatchTouchEvent", "(Landroid/view/MotionEvent;)Z", new Func<IntPtr, IntPtr, IntPtr, bool> …

[jnimarshalmethod-gen] Do not use method cache for generic types

---

src/Java.Interop.Export/Tests/Java.Interop/MarshalMemberBuilderTest.cs
src/Java.Interop/Java.Interop/JniRuntime.JniValueManager.cs
src/Java.Interop/Java.Interop/JniValueMarshaler.cs
src/Java.Interop/Tests/Java.Interop/JniValueMarshalerContractTests.cs

Fixes https://github.com/xamarin/java.interop/issues/374
Also refactor the code generation to not create `_handle` variable
when returning value to JNI
Example generated marshal method:
using Android.OS;
using Android.Views;
using Java.Interop;
using System;
public static IntPtr n_onCreateView_Landroid_view_LayoutInflater_Landroid_view_ViewGroup_Landroid_os_Bundle_ (IntPtr __jnienv, IntPtr __this, IntPtr inflater, IntPtr container, IntPtr savedInstanceState)
{
JniTransition jniTransition = new JniTransition (__jnienv);
JniRuntime runtime = default(JniRuntime);
global::Android.Views.View view = default(global::Android.Views.View);
try {
runtime = JniEnvironment.Runtime;
JniRuntime.JniValueManager valueManager = runtime.ValueManager;
valueManager.WaitForGCBridgeProcessing (); …

[Java.Interop] Do not dispose live references on return to JNI

---

tools/jnimarshalmethod-gen/App.cs

Fix https://github.com/xamarin/java.interop/issues/381
I am getting `ReflectionTypeLoadException` when getting
`Assembly:DefinedTypes` property. Looks like it is result of bumping
mono in XA to mono-2018-06 branch.
Unfortunately I am unable to reproduce it locally, so this patch adds
handling code for that exception, processes the loaded types and
reports the load type exceptions as warnings. Let see how it works on
build machines and what are the load exceptions we are getting
nowadays.

[jnimarshalmethod-gen] Handle ReflectionTypeLoadException

---

tools/jnimarshalmethod-gen/App.cs

The previous try to fix
https://github.com/xamarin/java.interop/issues/381 didn't
work. (https://github.com/xamarin/java.interop/commit/adf4c48531259aa8f555c872df9bb5509f8a4c72)
The reason is that we don't get the exception when calling
`assembly.DefinedTypes`, but later during traversal of the enumerable.
So instead of using the `DefinedTypes`, use `GetTypes ()` directly as
the exception comes from it. That should hopefuly allow us to handle
it here.
Related reflection sources:
https://github.com/mono/mono/blob/ab3c897d6851ccf75e840d8b767aafa0d0a32d53/mcs/class/corlib/System.Reflection/Assembly.cs#L1023-L1029

[jnimarshalmethod-gen] Update the types traversal

---

tools/jnimarshalmethod-gen/App.cs

Fixes https://github.com/xamarin/java.interop/issues/384
Sort the methods before generating marshal methods. Sort them so that
methods with name containing the interface name are at the end.
During processing check whether we already have a marshal method with
the same name. (note that the name contains parameter types)
When sorting methods so that interface implementation methods are
last, use `MethodDefinition:HasOverrides` to identify interface
implementations.
Introduce new cache to map reflection methods to cecil method
definitions. Example cache hit ratio:
~ 92% (1210/1318)
when generating marshal methods for
`Mono.Android.dll:Java.Nio.CharBuffer*` types.

[jnimarshalmethod-gen] Avoid creating duplicate marshal methods

---

src/Java.Interop/Java.Interop/JniRuntime.JniValueManager.cs

Before going to use the proxy object marshaler, try to check the
implemented interfaces for custom marshaler.
It will be used in XA to marshal IJavaObject based objects, which do
not implement IJavaPeerable.
That will make it possible to fix
https://github.com/xamarin/java.interop/issues/388

[Java.Interop] Additional marshaler lookup

---

src/Java.Interop.Tools.Cecil/Java.Interop.Tools.Cecil/TypeDefinitionRocks.cs
src/Java.Interop.Tools.TypeNameMappings/Java.Interop.Tools.TypeNameMappings/JavaNativeTypeManager.cs

Context: https://github.com/xamarin/xamarin-android/pull/2349
This commit introduces a new extension method `GetAssemblyName()` that
provides the assembly name portion of
`GetPartialAssemblyQualifiedName()` so that `GenerateJavaStubs` doesn't
have to do any string splitting to get the assembly name for warning
XA4214.

[jcw-gen] List assembly names for managed type conflicts

---

src/java-interop/java-interop-logger.c
src/java-interop/java-interop-logger.h

**NOTE: XA bump to use this PR must first make a change to `monodroid-glue.cc` to call `init_logging_categories`**
Logging is currently initialized from within the Xamarin.Android C++ glue by
calling the `init_categories` function and passing it an override directory name
where the logging system can store {L,G}REF log files, if reference logging is
enabled. However, this poses a problem that we can initialize logging (and thus
categories, as configured by the user) only after we know the list of override
directories and so any attempt to log timing information (using the `LOG_TIMING`
category) before that point would yield no output.
To fix it, this commit removes the {L,G}REF logging initialization code to a new
function, `init_reference_logging`, which is called when XA determines the …

Split logging initialization into two functions

---

src/java-interop/java-interop-logger.c
src/java-interop/java-interop-logger.h

Calls to `log_{info,debug}` may sometimes take parameters which will have to be
processed (functions called, memory allocated etc) even though the category the
calls use is disabled. This is because the category check is done inside the
`log_*` functions. This commit makes it slightly faster by wrapping the log call
in a macro which performs the check before calling the function, thus saving
some time. In Xamarin.Android native runtime this approach saved between 17 and
21ms (!) of startup time.

Make logging calls slightly faster for disabled categories

---

src/java-interop/java-interop-logger.c
src/java-interop/java-interop-logger.h
src/java-interop/java-interop.csproj

NOTE: XA should be updated before bumping to JI with this change
Implements first part of https://github.com/xamarin/java.interop/issues/397
The `java-interop-logger.c` was not used to build java-interop shared
library. Thus any usage of `log_*` functions led to crash, because the
function was missing. Like:
dyld: lazy symbol binding failed: Symbol not found: _log_error
Referenced from: /Users/rodo/git/java.interop/bin/Debug/libjava-interop.dylib
Expected in: flat namespace
dyld: Symbol not found: _log_error
Referenced from: /Users/rodo/git/java.interop/bin/Debug/libjava-interop.dylib
Expected in: flat namespace
Stacktrace:
at <unknown> <0xffffffff>
at (wrapper managed-to-native) Java.Interop.NativeMethods.java_interop_jvm_load (string) [0x00013] in <ce3946f6ded84ae7a635a712310f3fc9>:0
at …

[java-interop] Added missing logger implementation

---

tools/generator/Parameter.cs

Context: https://github.com/xamarin/AndroidSupportComponents/tree/AndroidX
When binding AndroidX, the components team are hitting a
`NullReferenceException` from `generator.exe`:
Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
at MonoDroid.Generation.Parameter.get_IsGeneric() in java.interop\tools\generator\Parameter.cs:line 68
at MonoDroid.Generation.Parameter.Equals(Parameter other) in java.interop\tools\generator\Parameter.cs:line 164
at MonoDroid.Generation.ParameterList.Equals(ParameterList l1, ParameterList l2) in java.interop\tools\generator\ParameterList.cs:line 19
at MonoDroid.Generation.GenBase.<>c__DisplayClass148_0.<FixupMethodOverrides>b__1(Method mm) in java.interop\tools\generator\GenBase.cs:line 814
at …

[generator] fix NRE encountered when binding AndroidX

---

tools/generator/Parameter.cs

This reverts commit 2e682251c3942f2323ec39b21830b39fd74bbf67.
I neglected to test this change in `Mono.Android.csproj`!
```
obj\Debug\android-28\mcw\Java.Time.Temporal.ChronoUnit.cs(284,50): error CS0234: The type or namespace name 'ITemporal' does not exist in the namespace 'Java.Time.Temporal' (are you missing an assembly reference?) [C:\Users\jopepper\Desktop\Git\xamarin-android\src\Mono.Android\Mono.Android.csproj]
obj\Debug\android-28\mcw\Java.Time.Temporal.ChronoUnit.cs(284,99): error CS0234: The type or namespace name 'ITemporal' does not exist in the namespace 'Java.Time.Temporal' (are you missing an assembly reference?) [C:\Users\jopepper\Desktop\Git\xamarin-android\src\Mono.Android\Mono.Android.csproj]
obj\Debug\android-28\mcw\Java.Time.Temporal.ChronoUnit.cs(299,56): error …
```

Revert "[generator] fix NRE encountered when binding AndroidX (#396)"

---

src/Java.Interop/Java.Interop/JniRuntime.JniMarshalMemberBuilder.cs

The probing for `Java.Interop.Export.dll` performed within
`JniRuntime.SetMarshalMemberBuilder()` can be costly if the
`Java.Interop.Export.dll` assembly isn't present or cannot be found,
which is *always* the case (currently) in Xamarin.Android, adding --
depending on device and profiler in use -- ~100ms to app startup (!).
Add a new `JniRuntime.CreationOptions.UseMarshalMemberBuilder`
property which controls whether `Java.Interop.Export.dll` is loaded
*at all*.  If true -- the default -- then `JniRuntime` *will* attempt
to load `Java.Interop.Export.dll`, allowing the
`JniRuntime.MarshalMemberBuilder` property to not throw a
`NotSupportedException`.
If `JniRuntime.CreationOptions.UseMarshalMemberBuilder` is false --
which will become the default in Xamarin.Android -- then …

[Java.Interop] Make `Java.Interop.Export` use optional

---

src/Java.Interop.Tools.JavaCallableWrappers/Java.Interop.Tools.JavaCallableWrappers/JavaCallableWrapperGenerator.cs

Context: https://github.com/xamarin/xamarin-android/pull/2505#issuecomment-445374019
In a world order where we are creating less temp files in
Xamarin.Android, it would be nice to leverage an overload of
`JavaCallableWrapperGenerator` that uses a `TextWriter` in memory.
Currently we are doing:
//jti is a JavaCallableWrapperGenerator instance
jti.Generate (outputPath);
//Then later in our MSBuild task
foreach (var file in Directory.GetFiles (temp, "*", SearchOption.AllDirectories)) {
...
MonoAndroidHelper.CopyIfChanged (file, dest);
}
So this is slower than it could be:
1. Writes to a bunch of temp files.
2. Recurses the directory where all these temp files exist.
3. Does a hash comparison of the contents of the source and
destination.
4. Copies the file if needed.
5. Deletes all the temp …

[jcwgen] add public method for GetDestinationPath

---

src/Java.Interop.Tools.Cecil/Java.Interop.Tools.Cecil/CustomAttributeProviderRocks.cs
src/Java.Interop.Tools.Cecil/Java.Interop.Tools.Cecil/MethodDefinitionRocks.cs
src/Java.Interop.Tools.Cecil/Java.Interop.Tools.Cecil/TypeDefinitionRocks.cs
src/Java.Interop.Tools.JavaCallableWrappers/Java.Interop.Tools.JavaCallableWrappers/JavaCallableWrapperGenerator.cs

Context: https://docs.microsoft.com/en-us/visualstudio/profiling/beginners-guide-to-performance-profiling
Using the CPU usage tool in Visual Studio (profiler), I could see the
percentage of time spent in various methods during the
`<GenerateJavaStubs/>` task.
The first "hot spot" I found was this `FirstOrDefault` call in
`JavaCallableWrapperGenerator`:
var baseMethods = GetBaseMethods (minfo);
var baseRegiteredMethod = baseMethods.FirstOrDefault (m => GetRegisterAttributes (m).Any ());
`GetBaseMethods` was another method in this class:
static IEnumerable<MethodDefinition> GetBaseMethods (MethodDefinition method)
{
MethodDefinition bmethod;
while ((bmethod = method.GetBaseDefinition ()) != method) {
method = bmethod;
yield return method;
}
}
I was able to flatten out the LINQ usage here, …

[jcwgen] perf improvements

---

build-tools/scripts/PrepareWindows.targets

Context: https://github.com/xamarin/xamarin-android/pull/2463
When running:
msbuild Java.Interop.sln /t:Prepare
We are hitting a similar error on the latest version of NuGet that we
saw in Xamarin.Android:
src\java-interop\java-interop.csproj(29,3): error MSB4019:
The imported project "bin\BuildDebug\JdkInfo.props" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.
It seems the latest version of NuGet will fail if it encounters an
`<Import/>` on a file that does not yet exist.
Pinning our build to use NuGet 4.7.1 solves this problem, and we
should be able to update NuGet deliberately in the future.

[build] use NuGet 4.7.1

---

src/Java.Interop/Java.Interop/JniRuntime.cs
src/Java.Runtime.Environment/Java.Interop/JreRuntime.cs
src/java-interop/java-interop-jvm.c
src/java-interop/java-interop-jvm.h
tests/PerformanceTests/TimingTests.cs

Fixes (partially?) https://github.com/xamarin/java.interop/issues/403
Make sure we use the right calling convention by using JNICALL.
Do not force `CallingConvention.Cdecl` in pinvokes, as these are
different on Windows. Rather stay with the platform defaults.

Use right calling convention for JNI calls

---

build-tools/jnienv-gen/jnienv-gen.csproj

Downstream in monodroid, we are getting a build failure such as:
Generator.cs(4,14): error CS0234: The type or namespace name 'Linq' does not exist in the namespace 'System' (are you missing an assembly reference?)
Generator.cs(222,10): error CS0246: The type or namespace name 'HashSet<>' could not be found (are you missing a using directive or an assembly reference?)
Looking at `jnienv-gen.csproj` `$(TargetFrameworkVersion)` was
completely missing?
I am not sure how this has been working.

[jnienv-gen] missing TargetFrameworkVersion

---

src/Java.Interop/Java.Interop-MonoAndroid.csproj
src/Java.Interop/Java.Interop.csproj
src/Java.Interop/Properties/AssemblyInfo.cs

Downstream in xamarin/xamarin-android, running:
msbuild Xamarin.Android.sln
msbuild Xamarin.Android.sln /p:Configuration=Release
You run into an odd build error:
obj\Release\netstandard2.0\Java.Interop.AssemblyInfo.cs(14,12): error CS0579: Duplicate 'System.Reflection.AssemblyCompanyAttribute' attribute
obj\Release\netstandard2.0\Java.Interop.AssemblyInfo.cs(15,12): error CS0579: Duplicate 'System.Reflection.AssemblyConfigurationAttribute' attribute
obj\Release\netstandard2.0\Java.Interop.AssemblyInfo.cs(16,12): error CS0579: Duplicate 'System.Reflection.AssemblyCopyrightAttribute' attribute
obj\Release\netstandard2.0\Java.Interop.AssemblyInfo.cs(17,12): error CS0579: Duplicate 'System.Reflection.AssemblyFileVersionAttribute' attribute …

[build] Java.Interop-MonoAndroid wildcards too much

---

tools/generator/CodeGenerator.cs
tools/generator/InterfaceGen.cs
tools/generator/Tests-Core/expected.ji/Android.Text.ISpannable.cs
tools/generator/Tests-Core/expected.ji/Android.Text.ISpanned.cs
tools/generator/Tests-Core/expected.ji/Android.Views.View.cs
tools/generator/Tests-Core/expected/Android.Text.ISpannable.cs
tools/generator/Tests-Core/expected/Android.Text.ISpanned.cs
tools/generator/Tests-Core/expected/Android.Views.View.cs
tools/generator/Tests/Integration-Tests/Adapters.cs
tools/generator/Tests/expected.ji/Adapters/Xamarin.Test.IAdapter.cs
tools/generator/Tests/expected.ji/Adapters/Xamarin.Test.ISpinnerAdapter.cs
tools/generator/Tests/expected.ji/GenericArguments/Com.Google.Android.Exoplayer.Drm.IExoMediaDrm.cs
tools/generator/Tests/expected.ji/InterfaceMethodsConflict/Xamarin.Test.II1.cs
tools/generator/Tests/expected.ji/InterfaceMethodsConflict/Xamarin.Test.II2.cs
tools/generator/Tests/expected.ji/NestedTypes/Xamarin.Test.NotificationCompatBase.cs
tools/generator/Tests/expected.ji/TestInterface/Test.ME.IGenericInterface.cs
tools/generator/Tests/expected.ji/TestInterface/Test.ME.IGenericPropertyInterface.cs
tools/generator/Tests/expected.ji/TestInterface/Test.ME.ITestInterface.cs
tools/generator/Tests/expected.ji/java.lang.Enum/Java.Lang.IComparable.cs
tools/generator/Tests/expected/Adapters/Xamarin.Test.IAdapter.cs
tools/generator/Tests/expected/Adapters/Xamarin.Test.ISpinnerAdapter.cs
tools/generator/Tests/expected/GenericArguments/Com.Google.Android.Exoplayer.Drm.IExoMediaDrm.cs
tools/generator/Tests/expected/InterfaceMethodsConflict/Xamarin.Test.II1.cs
tools/generator/Tests/expected/InterfaceMethodsConflict/Xamarin.Test.II2.cs
tools/generator/Tests/expected/NestedTypes/Xamarin.Test.NotificationCompatBase.cs
tools/generator/Tests/expected/TestInterface/Test.ME.IGenericInterface.cs
tools/generator/Tests/expected/TestInterface/Test.ME.IGenericPropertyInterface.cs
tools/generator/Tests/expected/TestInterface/Test.ME.ITestInterface.cs
tools/generator/Tests/expected/java.lang.Enum/Java.Lang.IComparable.cs

The code for interface `Invoker` types elicits a CS0108 warning on the
`class_ref` field, e.g.
Xamarin.Test.IAdapter.cs(26,10): warning CS0108:
`Xamarin.Test.IAdapterInvoker.class_ref' hides inherited member `Java.Lang.Object.class_ref'.
Use the new keyword if hiding was intended.
This happens because `Java.Lang.Object` has a `class_ref` field, and
the `Invoker` type also has one:
namespace Java.Lang {
partial class Object {
internal static IntPtr class_ref {get;}
}
}
namespace Xamarin.Test {
partial class IAdapterInvoker : Java.Lang.Object, IAdapter {
IntPtr class_ref;
}
}
Simple enough, right?  Just always always emit `new IntPtr class_ref`
and the warning is removed.
There's a problem with this simple solution: there are *two ways* that
`generator`-emitted source code is used:
1. When …

[generator] Remove CS0108 warning for `*Invoker.class_ref`

---

tools/generator/CodeGenerator.cs
tools/generator/GenBase.cs
tools/generator/Tests/Integration-Tests/GenericArguments.cs
tools/generator/Tests/Integration-Tests/InterfaceMethodsConflict.cs
tools/generator/Tests/Integration-Tests/Interfaces.cs
tools/generator/Tests/Integration-Tests/Java_Lang_Enum.cs
tools/generator/Tests/Integration-Tests/NestedTypes.cs
tools/generator/Tests/Integration-Tests/NormalMethods.cs
tools/generator/Tests/expected.ji/NormalMethods/Xamarin.Test.SomeObject.cs
tools/generator/Tests/expected/NormalMethods/Xamarin.Test.SomeObject.cs

When a Java method is declared which has a name matching a method name
from a C# base class, a CS0108 warning is produced:
Xamarin.Test.SomeObject.cs(77,31): warning CS0108:
`Xamarin.Test.SomeObject.GetType()' hides inherited member `object.GetType()'.
Use the new keyword if hiding was intended
Fix this by updating `GenBase.RequiresNew()` to have a more complete
set of member names from `System.Object` and `System.Exception`, and
calling `GenBase.RequiresNew()` from
`CodeGenerator.WriteMethodAbstractDeclaration()` so that `new` is
emitted for `GetType()` and other methods.
Additionally, the `NormalMethods.cs` test also contains obsolete
methods, which results in CS0618 warnings:
Xamarin.Test.SomeObject.cs(317,18): warning CS0618:
`Xamarin.Test.SomeObject.ObsoleteMethod()' is obsolete: …

[generator] Remove CS0108 warning for inherited methods

---

tools/jnimarshalmethod-gen/App.cs

Improves https://github.com/xamarin/xamarin-android/issues/2419
Change the behavior in case we find an existing
`__<$>_jni_marshal_methods` class. Skip the whole assembly instead of
just the type.
Updated the warning message to report the assembly name. This can be
still overriden by using `-f`.
This also means the number of these warnings is significanly reduced
to one per assembly, instead one per type in case we try to generate
the methods for assemblies which were already processed and thus
contain the marshaling classes.

[jnimarshalmethod-gen] Do not generate in already processed assemblies

---

src/Xamarin.Android.Tools.AnnotationSupport/AndroidAnnotationsSupport.cs
src/Xamarin.Android.Tools.AnnotationSupport/Xamarin.Android.Tools.AnnotationSupport.csproj
src/Xamarin.Android.Tools.AnnotationSupport/packages.config

Context: https://issuetracker.google.com/issues/116182838
Google shipped invalid (not well-formed) XML annotation documents in
the `platform-tools` 28.0.1 package, with `<` present within element
attributes:
<item name="android.view.View void addFocusables(java.util.ArrayList<android.view.View>, int) 1">
Note the `java.util.ArrayList<android.view.View>` within the
`//item/@name` attribute value, and that the `<` isn't escaped.
This invalid XML prevents System.Xml from loading the
`annotations.xml` documents, with errors similar to:
android/view/annotations.xml failed: '<', hexadecimal value 0x3C, is an invalid attribute character. Line 206, position 71
This commit takes advantage of the forgiving nature of the
HtmlAgilityPack HTML parser -- which loads those files fine -- and
makes it …

[generator] Fix loading broken annotation XML

---

src/Java.Interop/Java.Interop/JavaPrimitiveArrays.cs
src/Java.Interop/Java.Interop/JavaPrimitiveArrays.tt
src/Java.Interop/Java.Interop/JniBuiltinMarshalers.cs
src/Java.Interop/Java.Interop/JniBuiltinMarshalers.tt
src/Java.Interop/Java.Interop/JniRuntime.JniTypeManager.cs
src/Java.Interop/Java.Interop/JniRuntime.JniValueManager.cs

The static constructor of JniRuntime class took relatively long to
JIT. It also initializes bunch of static arrays, while some of them
are not used during the startup.
So using the lazy initialization we save time in array creation and
also in less code to JIT.
The lazy initialization helps improve the startup time.
XA template times on Pixel XL 2
Before:
Time:    321ms Message: Runtime.init: end, total time; elapsed: 0s:224::473824
Time:    316ms Message: Runtime.init: end, total time; elapsed: 0s:224::390855
Time:    305ms Message: Runtime.init: end, total time; elapsed: 0s:223::397210
Time:    313ms Message: Runtime.init: end, total time; elapsed: 0s:229::617471
Time:    304ms Message: Runtime.init: end, total time; elapsed: 0s:221::623355
After:
Time:    315ms Message: Runtime.init: …

[Java.Interop] Lazy initialization of JniRuntime static array fields

---

Makefile

With enough finagling, Visual Studio for Mac 8.0 (build 2479) is able
to build `Java.Interop.sln`.  (And there was much rejoicing!)
Now, about that finagling...
This process doesn't work:
1. Run `make prepare`
2. Open `Java.Interop.sln` within Visual Studio for Mac.
3. Press Command+B or click Build > Build All
Step (3) fails:
src/java-interop/java-interop.targets(5,5): Error MSB3073:
The command "gcc -g -shared -m64 -std=c99 -o "../../bin/Debug/libjava-interop.dylib" …" exited with code 1.
The problem is that `java-interop.targets` "requires" that
`bin/BuildDebug/MonoInfo.props` exist, otherwise `@(MonoIncludePath)`,
`$(MonoFrameworkPath)`, and `$(MonoLibs)` won't be defined, which is
why the above `gcc` command fails.
Fix the `make prepare` target so that `MonoInfo.props` is created. …

[build] `make prepare` creates `MonoInfo.props`

---

src/Xamarin.Android.Tools.Bytecode/ClassPath.cs

Instead of requiring a path on the filesystem, allow a stream. This will allow direct reading from .aar files without having to extract the .jar first.

Allow .jar files to be read from a Stream

---

build-tools/Java.Interop.BootstrapTasks/Java.Interop.BootstrapTasks.csproj

Context: http://build.devdiv.io/2532642
Changes: https://github.com/xamarin/xamarin-android-tools/compare/9e78d6e...66d445c
As part of this change, anything referencing
`Xamarin.Android.Tools.AndroidSdk.csproj` neeeds to be using a
`TargetFrameworkVersion` of `v4.7.1`.
This will solve a build failure currently happening in
xamarin-android:
warning MSB3274: The primary reference "E:\A\_work\1345\s\external\xamarin-android-tools\bin\Release\Xamarin.Android.Tools.AndroidSdk.dll" could not be resolved because it was built against the ".NETFramework,Version=v4.7.1" framework. This is a higher version than the currently targeted framework ".NETFramework,Version=v4.6.1". [E:\A\_work\1345\s\external\Java.Interop\build-tools\Java.Interop.BootstrapTasks\Java.Interop.BootstrapTasks.csproj]
... …

Bump to xamarin/xamarin-android-tools/master@66d445c

---

src/Java.Interop/Java.Interop/JniFieldInfo.cs
src/Java.Interop/Java.Interop/JniMethodInfo.cs

Commit 69d2c998 contained an oversight: in a Release build, in which
`DEBUG` isn't defined, `JniFieldInfo.ToString()` and
`JniMethodInfo.ToString()` will throw a `NotSupportedException`
because they use the `Name` and `Signature` properties, which always
throw `NotSupportedException` in the Release configuration.
This renders `.ToString()` useless.  Doh!
Fix `JniFieldInfo.ToString()` and `JniMethodInfo.ToString()` so that
in Release configurations they don't access the `Name` or `Signature`
properties, preventing `.ToString()` from throwing.

[Java.Interop] JniMethodInfo.ToString() shouldn't throw

---

src/Xamarin.Android.Cecil/Xamarin.Android.Cecil.targets

Looks like the use of Restore target is not enough
here. https://jenkins.mono-project.com/job/xamarin-android-pr-pipeline-release/1141/console
We need to do restore using the solution file.

Fix cecil build once more

---

src/java-interop/java-interop-gc-bridge-mono.cc
src/java-interop/java-interop-util.cc

The `__STDC_FORMAT_MACROS` define is to have `PRId64` defined by `inttypes.h`.
Few more casts when allocating memory.

[java-interop] Few more fixes for mxe-Win[32|64] builds in XA

---

Configuration.props
src/Xamarin.Android.Cecil/Xamarin.Android.Cecil.targets

Current XA/master doesn't work with JI/master, because the version of
`mono/external/cecil` doesn't have `Debug` configuration in
`Mono.Cecil.sln`. Unlike the newer cecil used in `mono/2019-06`.
Thus failing with:
(ValidateSolutionConfiguration target) ->
/Users/rodo/git/xa3/external/mono/external/cecil/Mono.Cecil.sln.metaproj : error MSB4126: The specified solution configuration "Debug|Any CPU" is invalid. Please specify a valid solution configuration using the Configuration and Platform properties (e.g. MSBuild.exe Solution.sln /p:Configuration=Debug /p:Platform="Any CPU") or leave those properties blank to use the default solution configuration. [/Users/rodo/git/xa3/external/mono/external/cecil/Mono.Cecil.sln]
To overcome that we introduce new `CecilRestoreConfiguration`
property, …

Make JI build with current XA/master

---

tools/generator/ClassGen.cs
tools/generator/Tests/expected.ji/Constructors/Mono.Android.projitems
tools/generator/Tests/expected/Constructors/Constructors.xml
tools/generator/Tests/expected/Constructors/Xamarin.Test.SomeObject2.cs

We are mistakenly `return`ing when we want to skip generating a `ctor` instead of `continue`ing.  This causes an ordering issue where desired constructors may or may not be generated based on their position in the xml file.

[generator] Ensure all intended ctors get generated.

---

tools/generator/ApiVersionsSupport.cs

Using an `ILookup` instead of constantly recalculating this `IEnumerable` causes this step duration to drop from ~30s generating `Mono.Android.dll` to ~0.3s.

[generator] Use an ILookup for better performance.

---

tools/generator/CodeGenerationOptions.cs
tools/generator/CodeGenerator.cs
tools/generator/Java.Interop.Tools.Generator.ObjectModel/GenBase.cs
tools/generator/Utilities/AncestorDescendantCache.cs
tools/generator/generator.csproj

Finding the descendants of a GenBase is relatively expensive.  Caching the results causes the `UpdateEnums` step to drop from ~9.5s generating `Mono.Android.dll` to ~1s.

[generator] Cache finding descendants of a GenBase.

---

tools/generator/Java.Interop.Tools.Generator.CodeGeneration/EnumGenerator.cs
tools/generator/Java.Interop.Tools.Generator.Transformation/EnumMappings.cs
tools/generator/Tests-Core/expected.ji/Android.Text.SpanTypes.cs
tools/generator/Tests-Core/expected/Android.Text.SpanTypes.cs
tools/generator/Tests/Unit-Tests/EnumGeneratorExpectedResults/WriteBasicEnum.txt
tools/generator/Tests/Unit-Tests/EnumGeneratorExpectedResults/WriteEnumWithGens.txt
tools/generator/Tests/Unit-Tests/EnumGeneratorExpectedResults/WriteFlagsEnum.txt
tools/generator/Tests/Unit-Tests/EnumGeneratorTests.cs
tools/generator/Tests/expected/EnumerationFixup/Xamarin.Test.SomeValues.cs
tools/generator/Tests/generator-Tests.csproj
tools/generator/generator.csproj

Encapsulate the generation of the enum files to `EnumGenerator`.  This helps make it testable and easier to ensure it is thread-safe.  With it being thread-safe we can now generate these files in parallel.  On my 6 core machine, this reduces the time taken from ~5.5s to ~1.1s.

[generator] Encapsulate and parallelize enum generation.

---

tools/generator/CodeGenerator.cs

#446 removed Cecil usage from the step that generates the type `.cs` files, which was the remaining thread-safety issue.  This PR enables generating those files in parallel.
This results in a nice performance win, particularly for projects binding a lot of types:
Scenario | Original | This PR
------------ | ------------- | -
Mono.Android.dll | 16423ms | 11506ms
Jar2Xml | 5517ms | 5309ms
Class-Parse | 15511ms | 15615ms

[generator] Enable parallel type generation.

---

tools/generator/Extensions/ManagedExtensions.cs
tools/generator/Java.Interop.Tools.Generator.Importers/CecilApiImporter.cs
tools/generator/Tests/Unit-Tests/ManagedExtensionsTests.cs
tools/generator/Tests/Unit-Tests/ManagedTests.cs
tools/generator/Tests/generator-Tests.csproj

One of the issues trying to bind the BouncyCastle .jar in #424 is that we write generic types with invalid signatures, like:
```
public List`1<string> MyProperty { get; set; }
```
This is how a Cecil type reference `FullName` is returned.  Since this notation is not useful to us, this PR strips the arity while reading the assembly.
This results in the proper type syntax:
```
public List<string> MyProperty { get; set; }
```

[generator] Strip arity from Cecil imported generic types.

---

tools/generator/CodeGenerationOptions.cs
tools/generator/CodeGenerator.cs
tools/generator/Java.Interop.Tools.Generator.CodeGeneration/JavaInteropCodeGenerator.cs
tools/generator/Java.Interop.Tools.Generator.CodeGeneration/XamarinAndroidCodeGenerator.cs
tools/generator/Java.Interop.Tools.Generator.Importers/CecilApiImporter.cs
tools/generator/Java.Interop.Tools.Generator.Importers/XmlApiImporter.cs
tools/generator/Java.Interop.Tools.Generator.ObjectModel/GenBase.cs
tools/generator/Java.Interop.Tools.Generator.ObjectModel/InterfaceGen.cs
tools/generator/Java.Interop.Tools.Generator.ObjectModel/Parameter.cs
tools/generator/Java.Interop.Tools.Generator.ObjectModel/Symbols/ArraySymbol.cs
tools/generator/Java.Interop.Tools.Generator.ObjectModel/Symbols/CharSequenceSymbol.cs
tools/generator/Java.Interop.Tools.Generator.ObjectModel/Symbols/CollectionSymbol.cs
tools/generator/Java.Interop.Tools.Generator.ObjectModel/Symbols/GenericTypeParameter.cs
tools/generator/Java.Interop.Tools.Generator.ObjectModel/Symbols/StreamSymbol.cs
tools/generator/Java.Interop.Tools.Generator.ObjectModel/Symbols/StringSymbol.cs
tools/generator/Java.Interop.Tools.Generator.ObjectModel/Symbols/SymbolTable.cs
tools/generator/Java.Interop.Tools.Generator.ObjectModel/Symbols/XmlPullParserSymbol.cs
tools/generator/Java.Interop.Tools.Generator.ObjectModel/Symbols/XmlResourceParserSymbol.cs
tools/generator/Tests/Unit-Tests/AdjusterTests.cs
tools/generator/Tests/Unit-Tests/TypeNameUtilitiesTests.cs
tools/generator/Tests/generator-Tests.csproj
tools/generator/Utilities/TypeNameUtilities.cs
tools/generator/generator.csproj

Binding projects typically reference most of the Mono.Android profile, which get passed into generator as reference assemblies:
```
mscorlib.dll
Java.Interop.dll
Mono.Android.dll
System.Core.dll
System.dll
System.Runtime.dll
System.Xml.dll
```
`generator` uses Cecil to reflect over these assemblies and build an in-memory model of the types.  However, the majority of these types are not referenced by the `jar` the user is binding.  For [BetterPickers](https://github.com/xamarin/XamarinComponents/tree/master/Android/BetterPickers/source/BetterPickers), 11632 types are imported, but only 529 are used.
This PR creates the `BaseGen` for these classes but does not iterate through the Constructors/Methods/Properties/Fields unless the type is actually used.  These types are added directly to the …

[generator] Lazily populate members on referenced types.

---

tools/generator/CodeGenerator.cs

Reverts xamarin/java.interop#447
Revert parallel type generation.  There are some deeper thread-safety issues that will have to be resolved before this can safely be enabled.  These take the form of `CodeGenerator` manipulating the object model while it is writing.
For example:
https://github.com/xamarin/java.interop/blob/master/tools/generator/Java.Interop.Tools.Generator.CodeGeneration/CodeGenerator.cs#L1437-L1440
```
string pname = property.Setter.Parameters [0].Name;
property.Setter.Parameters [0].Name = "value";
WriteMethodBody (property.Setter, indent + "\t\t");
property.Setter.Parameters [0].Name = pname;
```
This caused a test to sporadically fail on CI, but the pipeline is hiding test errors so it wasn't noticed.

Revert "[generator] Enable parallel type generation."

---

tools/generator/Java.Interop.Tools.Generator.Importers/XmlApiImporter.cs
tools/generator/Tests/Unit-Tests/XmlApiImporterTests.cs
tools/generator/Tests/generator-Tests.csproj

One issue with the BouncyCastle .jar in #424 is that it contains this field:
```
public static final int _3DES_EDE_CBC
```
We studly-case Java field names, however that removes underscores and we end up with `3desEdeCbc`, which is invalid C#.  This PR preserves a starting underscore if there was one and the resulting name starts with a number.  (`_3desEdeCbc` for this case.)

[generator] Ensure studly-case doesn't produce invalid C# field name.

---

tools/generator/Java.Interop.Tools.Generator.ObjectModel/Symbols/SymbolTable.cs

The way we use a `SymbolTable` is to fully populate it with types and then perform lots of lookups on it.  We can optimize this by building a lookup cache when we start accessing the types and then using it for all subsequent lookups.
If any additional types are added to the table, we clear the cache so it will be rebuilt.  In practice this doesn't happen often, so we are not constantly rebuilding the cache. (In testing the most we build the cache is twice, out of thousands of accesses.)
Scenario | Original | This PR
------------ | ------------- | -
jar2xml | 2645ms | 782ms
class-parse | 5563ms | 2555ms

[generator] Use a lookup cache in SymbolTable to find types.

---

src/Java.Interop/Tests/Java.Interop/JavaArrayContract.cs
src/Java.Interop/Tests/Java.Interop/JavaExceptionTests.cs
src/Java.Interop/Tests/Java.Interop/JavaObjectArrayTest.cs
src/Java.Interop/Tests/Java.Interop/JavaObjectTest.cs
src/Java.Interop/Tests/Java.Interop/JniRuntime.JniValueManagerTests.cs
src/Java.Interop/Tests/Java.Interop/JniTypeManagerTests.cs
src/Java.Interop/Tests/Java.Interop/JniTypeTest.cs
src/Java.Interop/Tests/Java.Interop/TestType.cs
src/Java.Interop/Tests/Java.Interop/TestTypeTests.cs

Context: https://github.com/xamarin/xamarin-android/pull/3393
Allow the Java.Interop unit tests to be consumed by Xamarin.Android.
In particular, this means:
* "Proper" exceptions such as `Java.Lang.ClassNotFoundException` are
thrown, not "based" `JavaException` types.
* `Xamarin.Android.NUnitLite.dll` doesn't provide
`[OneTimeSetUpAttribute]`/etc., so use
`[TestFixtureSetUpAttribute]` instead.
* Xamarin.Android doesn't currently support
`Java.Interop.MarshalMemberBuilder`, so any tests which require it
will not work.  "Hide" those behind
`#if !NO_MARSHAL_MEMBER_BUILDER_SUPPORT`.

[Java.Interop-Tests] Allow consumption by Xamarin.Android

---

tools/generator/GenerationInfo.cs
tools/generator/Tests-Core/expected.cp/GeneratedFiles.projitems
tools/generator/Tests-Core/expected.ji/GeneratedFiles.projitems
tools/generator/Tests-Core/expected/GeneratedFiles.projitems
tools/generator/Tests/expected.ji/AccessModifiers/Mono.Android.projitems
tools/generator/Tests/expected.ji/Adapters/Mono.Android.projitems
tools/generator/Tests/expected.ji/Android.Graphics.Color/Mono.Android.projitems
tools/generator/Tests/expected.ji/Arrays/Mono.Android.projitems
tools/generator/Tests/expected.ji/CSharpKeywords/Mono.Android.projitems
tools/generator/Tests/expected.ji/Constructors/Mono.Android.projitems
tools/generator/Tests/expected.ji/NestedTypes/Mono.Android.projitems
tools/generator/Tests/expected.ji/NonStaticFields/Mono.Android.projitems
tools/generator/Tests/expected.ji/NormalMethods/Mono.Android.projitems
tools/generator/Tests/expected.ji/NormalProperties/Mono.Android.projitems
tools/generator/Tests/expected.ji/ParameterXPath/Mono.Android.projitems
tools/generator/Tests/expected.ji/StaticFields/Mono.Android.projitems
tools/generator/Tests/expected.ji/StaticMethods/Mono.Android.projitems
tools/generator/Tests/expected.ji/StaticProperties/Mono.Android.projitems
tools/generator/Tests/expected.ji/Streams/Mono.Android.projitems
tools/generator/Tests/expected.ji/TestInterface/Mono.Android.projitems
tools/generator/Tests/expected.ji/java.lang.Enum/Mono.Android.projitems
tools/generator/Tests/expected.ji/java.lang.Object/Mono.Android.projitems
tools/generator/Tests/expected.ji/java.util.List/Mono.Android.projitems

Change our `.projitems` to remove an extraneous slash:
```
- <Compile Include="$(MSBuildThisFileDirectory)\Android.Accounts.Account.cs" />
+ <Compile Include="$(MSBuildThisFileDirectory)Android.Accounts.Account.cs" />
```
This slash causes our files to get interpreted as:
```
...\src\Mono.Android\obj\Debug\android-29\mcw\\Android.Accounts.Account.cs
```
This is valid-ish and builds fine, but when building `Mono.Android.dll` we also add files via this in `Mono.Android.targets`:
```
<ItemGroup>
<Compile Include="$(_FullIntermediateOutputPath)\mcw\**\*.cs" KeepDuplicates="False" />
</ItemGroup>
```
The extra slash is enough to prevent the `KeepDuplicates` from working correctly, so the file is added twice to `<Compile>`.  This results in ~3k warnings of `Duplicate source file specified` when …

[generator] Remove extraneous slash when creating .projitems.

---

src/Java.Interop.Tools.Cecil/Java.Interop.Tools.Cecil/MethodDefinitionRocks.cs
tools/generator/Java.Interop.Tools.Generator.ObjectModel/GenericParameterDefinition.cs

Fixed places that used GenericParameterConstraint assuming it was a TypeReference.
Cecil changed GPC to have a TypeReference (ConstraintType)  property be available as opposed to
inherit from it.

Bumped cecil to mono/cecil@cb6c1ca 

---

src/java-interop/java-interop-gc-bridge-mono.cc
src/java-interop/java-interop-mono.h

Xamarin.Android no longer uses `dlopen/dlsym` to load Mono symbols on the
runtime, instead it links libmonosgen-2.0 directly. In effect, the `DylibMono`
class and all the associated workarounds, code etc are going away. This commit
removes `DylibMono` use from `Java.Interop`

Drop dependency on DylibMono when building for Xamarin.Android

---

tools/generator/Java.Interop.Tools.Generator.CodeGeneration/CodeGenerator.cs
tools/generator/Java.Interop.Tools.Generator.ObjectModel/GenBase.cs
tools/generator/Java.Interop.Tools.Generator.ObjectModel/InterfaceGen.cs
tools/generator/Tests/expected.ji/AccessModifiers/Mono.Android.projitems
tools/generator/Tests/expected/AccessModifiers/AccessModifiers.xml
tools/generator/Tests/expected/AccessModifiers/Xamarin.Test.IExtendedInterface.cs
tools/generator/Tests/expected/AccessModifiers/Xamarin.Test.TestClass.cs
tools/generator/Tests/generator-Tests.csproj

Java allows public classes/interfaces to inherit/implements from "package-private" interfaces, in
which case the `public` & `protected` members of the "package-private"
interface are visible within the public class:
```
// Java
/* package */ interface BaseInterface {
void foo();
// ...
}
public interface TestInterface extends BaseInterface {
// ...
}
public class TestClass implements TestInterface {
// ...
}
or
public class TestClass implements BaseInterface {
// ...
}
```
The problem is that `generator` didn't properly support this construct,
and *skips* binding of "package-private" types, resulting in generated
C# code such as:
// C#
public partial interface TestInterface : BaseInterface {
// CS0234: The type or namespace name `BaseInterface` does not exist in the namespace
}
Support …

[generator] better support for package-private interfaces

---

src/Xamarin.Android.Tools.Bytecode/AttributeInfo.cs
src/Xamarin.Android.Tools.Bytecode/ClassFile.cs
src/Xamarin.Android.Tools.Bytecode/Tests/ExpectedInnerClassInfo.cs
src/Xamarin.Android.Tools.Bytecode/Tests/ExpectedMethodDeclaration.cs
src/Xamarin.Android.Tools.Bytecode/Tests/ExpectedTypeDeclaration.cs
src/Xamarin.Android.Tools.Bytecode/Tests/IJavaInterface.xml
src/Xamarin.Android.Tools.Bytecode/Tests/JavaAnnotation.xml
src/Xamarin.Android.Tools.Bytecode/Tests/JavaEnum.xml
src/Xamarin.Android.Tools.Bytecode/Tests/JavaType$1.xml
src/Xamarin.Android.Tools.Bytecode/Tests/JavaType$ASC.xml
src/Xamarin.Android.Tools.Bytecode/Tests/JavaType$PSC.xml
src/Xamarin.Android.Tools.Bytecode/Tests/JavaType$RNC$RPNC.xml
src/Xamarin.Android.Tools.Bytecode/Tests/JavaType$RNC.xml
src/Xamarin.Android.Tools.Bytecode/Tests/JavaType.1Tests.cs
src/Xamarin.Android.Tools.Bytecode/Tests/JavaType.xml
src/Xamarin.Android.Tools.Bytecode/Tests/JavaTypeTests.cs
src/Xamarin.Android.Tools.Bytecode/Tests/NonGenericGlobalType.xml
src/Xamarin.Android.Tools.Bytecode/Tests/ParameterFixup.xml
src/Xamarin.Android.Tools.Bytecode/Tests/ParameterFixupFromDescriptionText.xml
src/Xamarin.Android.Tools.Bytecode/Tests/ParameterFixupFromDocs.xml
src/Xamarin.Android.Tools.Bytecode/Tests/Xamarin.Android.Tools.Bytecode-Tests.csproj
src/Xamarin.Android.Tools.Bytecode/Tests/java/com/xamarin/JavaType.java
src/Xamarin.Android.Tools.Bytecode/XmlClassDeclarationBuilder.cs

Context: https://github.com/xamarin/java.interop/issues/466
While looking at `class-parse --dump` output for various
Kotlin-compiled `.class` files, providing support for the
`EnclosingMethod` and `SourceFile` annotation blobs looks to be
useful.
Add support for parsing the `EnclosingMethod` and `SourceFile`
annotations.
Update the generated XML so that the `SourceFile` annotation is
avaialble from the `//class/@source-file-name` or
`//interface/@source-file-name` attributes.
Update the generated XML so that the `EnclosingMethod` annotation is
available from these new attributes on `//class` or `//interface`:
* `enclosing-method-jni-type`: The JNI signature of the type
declaring the enclosing method.
* `enclosing-method-name`: The name of the enclosing method.
* …

[Xamarin.Android.Tools.Bytecode] Add EnclosingMethod, SourceFile

---

build-tools/xamarin-android-docimporter-ng/generate.sh
tools/generator/Java.Interop.Tools.Generator.CodeGeneration/CodeGenerator.cs
tools/generator/Java.Interop.Tools.Generator.ObjectModel/Method.cs
tools/generator/Tests/Unit-Tests/CodeGeneratorExpectedResults/Common/WriteInterfaceListenerEventWithHandlerArgument.txt
tools/generator/Tests/Unit-Tests/CodeGeneratorTests.cs
tools/generator/Tests/generator-Tests.csproj

On these changes: 
- Update generate.sh script to include Api 29
- During "on boarding" of api 29, we found a bug on the generator where Event handlers are not generate if the java methods contains handler argument as second argument.
The fix is to allow/consider methods with the second argument named handler and add a helper method that will always pass null as the handler internally. This will avoid that we manually add this support for all events matching this criteria.
here is an example of how the event handler will look like:
```
public event EventHandler<Android.Media.AudioRoutingOnRoutingChangedEventArgs> RoutingChanged {
add {
global::Java.Interop.EventHelper.AddEventHandler<Android.Media.IAudioRoutingOnRoutingChangedListener, …
```

Generator changes to support api level 29 and fixes to support extended events

---

src/Java.Interop.Export/Tests/Java.Interop/ExportTest.cs
src/Java.Interop.Export/Tests/Java.Interop/MarshalMemberBuilderTest.cs
src/Java.Interop/Java.Interop/JniRuntime.JniValueManager.cs
tools/jnimarshalmethod-gen/App.cs

When bumping xamarin-android to java.interop/master, we are hitting a
failure:
Instance property 'PeerReference' is not defined for type 'Android.Widget.IListAdapter'
Parameter name: propertyName
System.ArgumentException: Instance property 'PeerReference' is not defined for type 'Android.Widget.IListAdapter'
Parameter name: propertyName
at System.Linq.Expressions.Expression.Property (System.Linq.Expressions.Expression expression, System.String propertyName) [0x00051] in <9536922a6deb4f2dbdd3b7dedc620be3>:0
at Java.Interop.JavaPeerableValueMarshaler.CreateIntermediaryExpressionFromManagedExpression (Java.Interop.Expressions.JniValueMarshalerContext context, System.Linq.Expressions.ParameterExpression sourceValue) [0x0002e] in external/Java.Interop/src/Java.Interop/Java.Interop/JniRuntime.Jn …

[jnimarshalmethod-gen] fixes for interfaces

---

src/java-interop/java-interop-gc-bridge-mono.cc
src/java-interop/java-interop-mono.h

Context: https://github.com/xamarin/xamarin-android/pull/3504
Context: https://github.com/xamarin/xamarin-android/pull/3223
When bumping xamarin-android/master to 2abfc1e0, the build broke
because of commit 285a32b3:
In file included from /Users/vsts/agent/2.155.1/work/1/s/external/Java.Interop/src/java-interop/java-interop-mono.cc:2:
../../../../../external/Java.Interop/src/java-interop/java-interop-mono.h:10:11: fatal error: 'mono/metadata/assembly.h' file not found
#include <mono/metadata/assembly.h>
^~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
We need to continue supporting the DylibMono backend for integration
purposes (xamarin/xamarin-android#3504) *while also* allowing for the
*removal* of DylibMono (xamarin/xamarin-android#3223).
Attempt to support these divergent needs by …

[java-interop] Selectively keep DylibMono for Xamarin.Android

---

Makefile
src/Java.Interop/Tests/Java.Interop/JniValueMarshalerContractTests.cs

Commit ffbb2dc4 introduced a unit test failure, as it overlooked
updating an "expected" string within the test
`Java.InteropTests.JniValueMarshaler_IJavaPeerable_ContractTests.CreateReturnValueFromManagedExpression()`.
The more important question is this: why was that test failure missed?
Turns Out™ that our unit test infrastructure is "dodgy": it was
possible for tests to fail while the overall `make run-all-tests`
target reported success!
For example, as of commit ffbb2dc4 we *know* that
`Java.Interop-Tests.dll` will report a test failure.  Yet, if we
run `make run-tests` such that a different (successful) unit test
assembly follows it, no error is reported:
$ make run-tests TESTS="bin/TestDebug/Java.Interop-Tests.dll bin/TestDebug/Java.Interop.Export-Tests.dll"
... …

[tests] Fix test semantics, JniValueMarshalerContractTests

---

src/java-interop/java-interop-gc-bridge-mono.cc

Context: https://github.com/xamarin/xamarin-android/pull/3504
Context: https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=2950467&view=results
Commit 5fe28cdd didn't go far enough.  While the xamarin-android build
is no longer trying to include `<mono/metadata/assembly.h>`, we get a
new set of compilation errors:
/Users/vsts/agent/2.155.1/work/1/s/external/Java.Interop/src/java-interop/java-interop-gc-bridge-mono.cc(34,2): error GF2D19E48: unknown type name 'MonoClass'; did you mean 'xamarin::android::MonoClass'?
MonoClass          *klass;
^~~~~~~~~
xamarin::android::MonoClass
../../../jni/dylib-mono.h:101:31: note: 'xamarin::android::MonoClass' declared here
typedef struct _MonoClass {} MonoClass;
^
This is because the `using namespace xamarin::android` on …

[java-interop] Xamarin.Android host compilation fixes

---

src/Xamarin.Android.Tools.ApiXmlAdjuster/JavaApiXmlLoaderExtensions.cs
src/Xamarin.Android.Tools.ApiXmlAdjuster/XmlUtil.cs

Context: https://github.com/xamarin/xamarin-android/pull/3223
Context: https://jenkins.mono-project.com/job/xamarin-android-pr-pipeline-debug/619/
Commit a30523e2 breaks the xamarin-android build, as it introduces new
XML attributes to `class-parse` output which
`Xamarin.Android.Tools.ApiXmlAdjuster` doesn't appreciate:
System.Exception: …/xamarin-android/bin/BuildDebug/api/api-10.xml.class-parse (16,7): Element 'class' has an unexpected attribute: 'source-file-name'. Expected attributes are: source-file-name
at Xamarin.Android.Tools.ApiXmlAdjuster.XmlUtil.CheckExtraneousAttributes (System.String elementName, System.Xml.XmlReader reader, System.String[] expected)
at Xamarin.Android.Tools.ApiXmlAdjuster.JavaApiLoaderExtensions.LoadTypeAttributes …

[ApiXmlAdjuster] Add additional expected attributes

---

src/Xamarin.Android.Tools.Bytecode/ClassFile.cs
src/Xamarin.Android.Tools.Bytecode/XmlClassDeclarationBuilder.cs

Context: https://github.com/xamarin/xamarin-android/pull/3504
Context: https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=2951424&view=ms.vss-test-web.build-test-results-tab&runId=7990780&resultId=100107&paneView=attachments
The attempt to bump the Java.Interop submodule within xamarin-android
hit a snag, as unit tests failed:
The "ClassParse" task failed unexpectedly.
System.NullReferenceException: Object reference not set to an instance of an object
at Xamarin.Android.Tools.Bytecode.ClassFile.TryGetEnclosingMethodInfo (System.String& declaringClass, System.String& declaringMethod, System.String& declaringDescriptor)
at Xamarin.Android.Tools.Bytecode.XmlClassDeclarationBuilder.GetEnclosingMethod ()
at Xamarin.Android.Tools.Bytecode.XmlClassDeclarationBuilder.ToXElement ()
at …

[Xamarin.Android.Tools.Bytecode] Allow null enclosing method

---

build-tools/jnienv-gen/jnienv-gen.csproj
src/Java.Interop/Java.Interop.csproj
src/Java.Interop/Java.Interop.targets

Java.Interop had a custom MSBuild target that builds
`jnienv-gen.csproj`:
<Target Name="BuildJnienvGen"
Inputs="..\..\build-tools\jnienv-gen\jnienv-gen.csproj"
Outputs="$(JNIEnvGenPath)\jnienv-gen.exe">
<MSBuild
Projects="..\..\build-tools\jnienv-gen\jnienv-gen.csproj"
/>
</Target>
The problem with this, is if any `.cs` files change in
`jnienv-gen.csproj`, then this target will not run.
Instead we should be able to use `<ProjectReference/>` with
`%(ReferenceOutputAssembly)=False`, and everything should "just work".

[build] Java.Interop should use <ProjectReference/> for jnienv-gen

---

src/Java.Interop/Java.Interop-MonoAndroid.csproj

In f7d97c2, I forgot to update `Java.Interop-MonoAndroid.csproj`,
which was failing with:
"external\Java.Interop\src\Java.Interop\Java.Interop-MonoAndroid.csproj" (default target) (29) ->
Microsoft.Common.CurrentVersion.targets(837,7):
error MSB4057: The target "BuildJnienvGen" does not exist in the project.
We need to remove the `BuildJnienvGen` MSBuild target since it no
longer exists.

[build] remove BuildJnienvGen from Java.Interop-MonoAndroid.csproj

---

tools/jnimarshalmethod-gen/App.cs

Do not open the assemblies as `ReadWrite` when using `-o` option. It
is not needed as they will not be overwritten and may be read only.

[jnimarshalmethod-gen] Do not open assemblies for writting with -o

---

Makefile
tools/jnimarshalmethod-gen/App.cs

Instead of trying to create it in the location of the original
assembly as that might not be writable.

[jnimarshalmethod-gen] When using -o DIR, put temp assembly in DIR

---

tools/generator/Java.Interop.Tools.Generator.CodeGeneration/CodeGenerator.cs
tools/generator/Java.Interop.Tools.Generator.ObjectModel/InterfaceGen.cs
tools/generator/Tests/Unit-Tests/CodeGeneratorExpectedResults/JavaInterop1/WriteStaticInterfaceMethod.txt
tools/generator/Tests/Unit-Tests/CodeGeneratorExpectedResults/JavaInterop1/WriteStaticInterfaceProperty.txt
tools/generator/Tests/Unit-Tests/CodeGeneratorExpectedResults/XAJavaInterop1/WriteStaticInterfaceMethod.txt
tools/generator/Tests/Unit-Tests/CodeGeneratorExpectedResults/XAJavaInterop1/WriteStaticInterfaceProperty.txt
tools/generator/Tests/Unit-Tests/DefaultInterfaceMethodsTests.cs
tools/generator/Tests/generator-Tests.csproj

Using the new DIM support we can now also support static interface methods/properties.
Example:
```java
public interface StaticMethodsInterface
{
static int foo () { return 10; }
static int getValue () { return 3; }
static void setValue (int value) { }
}
```
Can now be invoked:
```csharp
[Test]
public void TestStaticMethods ()
{
Assert.AreEqual (10, IStaticMethodsInterface.Foo ());
Assert.AreEqual (3, IStaticMethodsInterface.Value);
Assert.DoesNotThrow (() => IStaticMethodsInterface.Value = 5);
}
```

[generator] Use DIM to support static interface methods.

---

tools/generator/Java.Interop.Tools.Generator.CodeGeneration/CodeGenerator.cs
tools/generator/Tests/Unit-Tests/CodeGeneratorTestBase.cs
tools/generator/Tests/Unit-Tests/DefaultInterfaceMethodsTests.cs

Given this Java hierarchy:
```java
public interface DefaultMethodsInterface
{
default int getBar () { return 2; }
}
public class EmptyOverrideClass implements DefaultMethodsInterface
{
}
public class ImplementedChainOverrideClass extends EmptyOverrideClass
{
@Override
public int getBar () { return 100; }
}
```
We are generating the `Bar` property improperly as `override`:
```csharp
public override unsafe int Bar { get { ... } }
```
In C# you do not `override` a DIM, you need to declare it as `virtual`.  (see https://github.com/dotnet/csharplang/issues/2757)
We need to see if we are "overriding" a property and not use `override` if it is a DIM.
```csharp
public virtual unsafe int Bar { get { ... } }
```

[generator] Fix DIM error when subclassing a class that inherits an interface with a DIM method

---

tools/generator/Java.Interop.Tools.Generator.CodeGeneration/CodeGenerator.cs
tools/generator/Tests/Unit-Tests/CodeGeneratorExpectedResults/JavaInterop1/WriteInterface.txt
tools/generator/Tests/Unit-Tests/CodeGeneratorExpectedResults/JavaInterop1/WriteStaticInterfaceMethod.txt
tools/generator/Tests/Unit-Tests/CodeGeneratorExpectedResults/XAJavaInterop1/WriteInterface.txt
tools/generator/Tests/Unit-Tests/CodeGeneratorExpectedResults/XAJavaInterop1/WriteStaticInterfaceMethod.txt
tools/generator/Tests/Unit-Tests/CodeGeneratorExpectedResults/XamarinAndroid/WriteInterface.txt
tools/generator/Tests/expected.ji/TestInterface/Test.ME.ITestInterface.cs
tools/generator/Tests/expected/TestInterface/Test.ME.ITestInterface.cs

The `*InterfaceConsts` classes we originally generated have been marked as `[Obsolete]` for at least 3 years:
```csharp
[Obsolete ("Use the 'MyInterface' type. This type will be removed in a future release.")]
public abstract class MyInterfaceConsts : MyInterface { }
```
It's time to tighten the screws a little bit and make this an error.
```csharp
[Obsolete ("Use the 'MyInterface' type. This type will be removed in a future release.", error: true)]
public abstract class MyInterfaceConsts : MyInterface { }
```
Related to #436.

[generator] Ratchet [Obsolete] *InterfaceConsts classes up to an error.

---

tools/generator/Java.Interop.Tools.Generator.CodeGeneration/CodeGenerator.cs
tools/generator/Tests/Unit-Tests/CodeGeneratorExpectedResults/JavaInterop1/WriteClass.txt
tools/generator/Tests/Unit-Tests/CodeGeneratorExpectedResults/JavaInterop1/WriteClassProperties.txt
tools/generator/Tests/Unit-Tests/CodeGeneratorExpectedResults/JavaInterop1/WriteStaticInterfaceProperty.txt
tools/generator/Tests/Unit-Tests/CodeGeneratorExpectedResults/XAJavaInterop1/WriteClass.txt
tools/generator/Tests/Unit-Tests/CodeGeneratorExpectedResults/XAJavaInterop1/WriteClassProperties.txt
tools/generator/Tests/Unit-Tests/CodeGeneratorExpectedResults/XAJavaInterop1/WriteStaticInterfaceProperty.txt
tools/generator/Tests/Unit-Tests/CodeGeneratorExpectedResults/XamarinAndroid/WriteClass.txt
tools/generator/Tests/Unit-Tests/CodeGeneratorExpectedResults/XamarinAndroid/WriteClassProperties.txt
tools/generator/Tests/expected.ji/StaticProperties/Xamarin.Test.SomeObject.cs
tools/generator/Tests/expected/StaticProperties/Xamarin.Test.SomeObject.cs

Default interface member static properties do not need to mention a
*connector-method* within the `[Register]` custom attribute.
Connector-methods are only for method *overrides*, and static methods
cannot be overridden.
Additionally, the connector method-related "glue" code isn't emitted,
so the connector-method value doesn't exist.
Update default interface member static property generation to mirror
that of [class static member generation][0] and emit the empty string
(`string.Empty`) as the conector method for static properties.
[0]: https://github.com/xamarin/java.interop/blob/fe13b1655d8a979f281cf923c97c9e0bf58dc614/tools/generator/Java.Interop.Tools.Generator.CodeGeneration/CodeGenerator.cs#L1376-L1377

[generator] Don't [Register] a Connector for static properties.

---

src/Java.Interop.Tools.JavaCallableWrappers/Java.Interop.Tools.JavaCallableWrappers.csproj
src/Java.Interop.Tools.JavaCallableWrappers/Java.Interop.Tools.JavaCallableWrappers/Crc64.cs
src/Java.Interop.Tools.JavaCallableWrappers/Test/Java.Interop.Tools.JavaCallableWrappers-Tests.csproj
src/Java.Interop.Tools.JavaCallableWrappers/Test/Java.Interop.Tools.JavaCallableWrappers/Crc64Tests.cs
src/Java.Interop.Tools.JavaCallableWrappers/Test/Java.Interop.Tools.JavaCallableWrappers/JavaNativeTypeManagerTests.cs
src/Java.Interop.Tools.TypeNameMappings/Java.Interop.Tools.TypeNameMappings/JavaNativeTypeManager.cs

Context: https://github.com/xamarin/xamarin-android/issues/1580
FIPS-compliant Windows 10 machines will throw an exception if the
`System.Security.Cryptography.MD5` class is used. We are not using
this for cryptography, but for naming collisions in Java package
names.
Therefore we can switch to using `CRC64` instead of `MD5`. A simple
implementation using a lookup table will suffice for our purposes.
I also expanded the enum:
enum PackageNamingPolicy {
LowercaseHash = 0,
Lowercase = 1,
LowercaseWithAssemblyName = 2,
LowercaseMD5 = LowercaseHash,
LowercaseCrc64 = 3,
}
It will currently default to `MD5` as before, but can be changed to
`LowercaseCrc64` as needed. At some point we might also change the
default value of `LowercaseHash`.
Further changes will need to be made upstream in …

Add CRC64 and new PackageNamingPolicy

---

src/Java.Interop.Tools.JavaCallableWrappers/Java.Interop.Tools.JavaCallableWrappers/Crc64.cs
src/Java.Interop.Tools.JavaCallableWrappers/Test/Java.Interop.Tools.JavaCallableWrappers/Crc64Tests.cs
src/Java.Interop.Tools.JavaCallableWrappers/Test/Java.Interop.Tools.JavaCallableWrappers/JavaNativeTypeManagerTests.cs

When testing out the new hash function, I found a collision:
Hash ("") == Hash(new byte[32])
Both values were `00-00-00-00-00-00-00-00`.
It seems that a value of length 0 would get the same hash as an empty
`byte[]`.
Two changes to the algorithm:
* The `crc` value starts at `ulong.MaxValue`. Many CRC algorithms do
this.
* XOR the length of the bytes. Many CRC algorithms XOR a constant
value at the end, but using the `length` should provide further
uniqueness.
This should lessen the chance for collisions.

[crc64] changes to fix a collision

---

src/Xamarin.Android.Tools.ApiXmlAdjuster/JavaApiXmlGeneratorExtensions.cs

Context: https://github.com/xamarin/java.interop/issues/466
In an effort to get people unblocked on binding Kotlin libraries in 16.4 Preview 2, this PR simply guards against the NRE generated.  It does not attempt to figure out the underlying problem and generate better code.
This at least lets people get past the crash so they can do fixups in `metadata.xml` to continue.  I will be making our Kotlin bindings more "correct" in future sprints.  (This NRE happens before the `metadata` stage so there's nothing a user can currently do.)

[ApiXmlAdjuster] Guard against NRE when writing generic constraints.

---

tools/logcat-parse/GrefParseOptions.cs
tools/logcat-parse/Grefs.cs
tools/logcat-parse/PeerInfo.cs
tools/logcat-parse/Tests/GrefsTest.cs

Context: https://github.com/xamarin/xamarin-android/issues/3706
A memory leak in an app is reported.
What Do We Do™?  We enable GREF logging and use `logcat-parse`!
GREF logging is enabled via the `debug.mono.log` Android system
property, by having it include `gref`:
adb shell setprop debug.mono.log gref,timing,
When GREF logging is enabled, the app will write a `grefs.txt` file
into the `.__override__` directory.  Launch the app, use it for
awhile, then extract the `grefs.txt` file:
adb shell run-as ActivityRecreateTest.ActivityRecreateTest cat files/.__override__/grefs.txt > grefs.txt
Once you have `grefs.txt`, use `logcat-parse.exe` to read it:
$ mono /Library/Frameworks/Xamarin.Android.framework/Versions/Current/lib/xamarin.android/xbuild/Xamarin/Android/logcat-parse.exe grefs.txt
// …

[logcat-parse] Various semantic bugfixes

---

tools/generator/Java.Interop.Tools.Generator.Importers/XmlApiImporter.cs
tools/generator/Tests/Unit-Tests/XmlApiImporterTests.cs

Context: #464 issues 1 and 2.
Kotlin allows hyphens in class/member names.  Replace them with underscores for the managed name so we generate valid C# names.

[generator] Replace hyphens in managed names.

---

src/Xamarin.Android.Tools.Bytecode/Annotation.cs
src/Xamarin.Android.Tools.Bytecode/AnnotationElementValue.cs
src/Xamarin.Android.Tools.Bytecode/AttributeInfo.cs
src/Xamarin.Android.Tools.Bytecode/Xamarin.Android.Tools.Bytecode.csproj

(Copied from #467)
Context: #466
While investigating issue #466, I ran across an "oddity" within the
type `kotlin/collections/AbstractCollection\$toString\$1.class`:
```
<api api-source="class-parse">
<package name="kotlin.collections" jni-name="kotlin/collections">
<class
name="AbstractCollection.toString.1"
jni-signature="Lkotlin/collections/AbstractCollection$toString$1;">
<implements
name="kotlin.jvm.functions.Function1"
name-generic-aware="kotlin.jvm.functions.Function1&lt;E, java.lang.CharSequence&gt;"
jni-type="Lkotlin/jvm/functions/Function1&lt;TE;Ljava/lang/CharSequence;&gt;;" />
<method
name="invoke"
jni-signature="(Ljava/lang/Object;)Ljava/lang/CharSequence;">
<parameter
name="it"
type="E"
jni-type="TE;" />
</method>
</class>
</package>
</api>
```
(Abbreviated output).
What's …

[Xamarin.Android.Tools.Bytecode] Support Runtime[In]VisibleAnnotations

---

Makefile

Context: https://build.azdo.io/3182458
Our build is currently failing with:
CSC : error CS1617: Invalid -langversion option `7.3'. It must be `ISO-1', `ISO-2', Default, Latest or value in range 1 to 7.2
I think this is due to:
/p:CscToolExe=`which mcs`
We need to use `mcs`, because `gendarme` does not yet support portable
`.pdb` files. However, it also appears that it does not support C# 7.2.
If we set `/p:LangVersion=Default`, it may select a usable C# version.
Things might continue to work as long as we don't use a C# 7.3
feature.
Then we got to the next failure:
Microsoft.CSharp.Core.targets(59,5): error : error CS2001: Source file `/analyzerconfig:/Users/runner/runners/2.159.2/work/1/s/.editorconfig' could not be found
The error is a …

[build] fix usage of /p:CscToolExe=`which mcs`

---

src/java-interop/java-interop.targets

We need to enable fPIC so we can build Java.Interop on Linux Ubuntu

Enabling fPIC on build

---

src/Java.Interop.Tools.JavaCallableWrappers/Java.Interop.Tools.JavaCallableWrappers/Crc64.cs
src/Java.Interop.Tools.JavaCallableWrappers/Test/Java.Interop.Tools.JavaCallableWrappers/JavaCallableWrapperGeneratorTests.cs
src/Java.Interop.Tools.JavaCallableWrappers/Test/Java.Interop.Tools.JavaCallableWrappers/JavaNativeTypeManagerTests.cs
src/Java.Interop.Tools.JavaCallableWrappers/Test/Java.Interop.Tools.JavaCallableWrappers/TypeNameMapGeneratorTests.cs
src/Java.Interop.Tools.TypeNameMappings/Java.Interop.Tools.TypeNameMappings/JavaNativeTypeManager.cs
tools/generator/Tests/Integration-Tests/BaseGeneratorTest.cs
tools/generator/Tests/generator-Tests.csproj

This adds `[Obsolete]` (with `error:true`) to:
* `PackageNamingPolicy.LowercaseHash`
* `PackageNamingPolicy.LowercaseMD5`
If these values are encountered at runtime a `NotSupportedException`
will be thrown.
Most of the remaining changes were updates to tests. Upstream in
xamarin/xamarin-android, we will likely need to emit a new build error
with an error code.
Other changes:
* I removed a place `BaseGeneratorTest.cs` was using `MD5.Create()`.
* This exposed a place we need to reset the initial state of `Crc64`
when an instance is reused for hashing.

[Java.Interop.Tools.JavaCallableWrappers] remove all usage of MD5

---

.vscode/extensions.json
.vscode/launch.json
.vscode/settings.json
.vscode/tasks.json
Java.Interop.code-workspace

vscode files to enable build/debug/run tests from inside the vscode ide

Add vscode files so we can build/debug/test from inside the vscode ide

---

tools/generator/Java.Interop.Tools.Generator.ObjectModel/Symbols/ArraySymbol.cs
tools/generator/Tests/Unit-Tests/CodeGeneratorTests.cs

If a method parameter contains a dollar sign, we sometimes escape it properly and sometimes we do not:
```
public unsafe global::Okio.ByteString Of (byte[] _this_toByteString_, int offset, int byteCount)
{
...
if ($this$toByteString != null) {
JNIEnv.CopyArray (native__this_toByteString_, $this$toByteString);
JNIEnv.DeleteLocalRef (native__this_toByteString_);
}
```
That contains both `_this_toByteString_` and `$this$toByteString`.
This PR ensures all instances use the same `opt.GetSafeIdentifier (string)` escaping method.

[generator] Ensure all usages of parameter names are escaped the same.

---

Makefile
src/java-interop/java-interop.targets
tests/invocation-overhead/Makefile

We recently changed the build options to enable fPIC on Linux builds (see https://github.com/xamarin/java.interop/commit/10ba45ab4575c3ac9bca82082039fcc910670586), but there was a couple of places still missing.
The `src/java-interop` build fails on Linux Ubuntu 19.10:
gcc -g -shared -m64 -o bin/TestDebug/libNativeTiming.so tests/NativeTiming/timing.c -I/usr/lib/jvm/java-1.8.0-openjdk-amd64/include -I/usr/lib/jvm/java-1.8.0-openjdk-amd64/include/linux
/usr/bin/ld: /tmp/ccmuRrxZ.o: relocation R_X86_64_PC32 against symbol `foo_void_timing' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: final link failed: nonrepresentable section on output
collect2: error: ld returned 1 exit status
Update the Linux build to use `gcc -fPIC` so that `src/java-interop` can be …

Enabling fPIC on Linux build - part 2

---

build-tools/automation/azure-pipelines.yaml

Port existing Windows and Mac Azure pipelines to a single YAML based pipeline.
New pipeline:
https://devdiv.visualstudio.com/DevDiv/_build?definitionId=12262&_a=summary

[build] Set up YAML Azure pipeline.

---

tools/generator/Java.Interop.Tools.Generator.CodeGeneration/CodeGenerator.cs
tools/generator/Java.Interop.Tools.Generator.Importers/XmlApiImporter.cs
tools/generator/Java.Interop.Tools.Generator.ObjectModel/ClassGen.cs
tools/generator/Java.Interop.Tools.Generator.ObjectModel/GenBase.cs
tools/generator/Java.Interop.Tools.Generator.ObjectModel/InterfaceGen.cs
tools/generator/Tests/expected.ji/TestInterface/Mono.Android.projitems
tools/generator/Tests/expected.ji/TestInterface/__NamespaceMapping__.cs
tools/generator/Tests/expected/TestInterface/ClassWithoutNamespace.cs
tools/generator/Tests/expected/TestInterface/IInterfaceWithoutNamespace.cs
tools/generator/Tests/expected/TestInterface/TestInterface.xml

Generator currently generates invalid code if we try to bind a java library that contains classes/interfaces defined without/outside a java package.
The current behavior generates the following invalid code:
```
namespace  {
// Metadata.xml XPath class reference: path="/api/package[@name='']/class[@name='Animal']"
[global::Android.Runtime.Register ("/Animal", DoNotGenerateAcw=true)]
public partial class Animal : global::Java.Lang.Object {
...
```
that will fail to build for obvious reasons.
Fix is to validate that classes and interfaces belong to a package/namespace. In case namespace does not exist, we should generate class or interface without any namespace.
Tests were added to validate scenario
tracking issue: https://github.com/xamarin/java.interop/issues/519

Support for Empty namespace name for java classes without package

---

src/Java.Interop/Tests/Java.Interop/JavaBooleanArrayContractTests.cs
src/Java.Interop/Tests/Java.Interop/JavaCharArrayContractTests.cs
src/Java.Interop/Tests/Java.Interop/JavaDoubleArrayContractTests.cs
src/Java.Interop/Tests/Java.Interop/JavaInt16ArrayContractTests.cs
src/Java.Interop/Tests/Java.Interop/JavaInt32ArrayContractTests.cs
src/Java.Interop/Tests/Java.Interop/JavaInt64ArrayContractTests.cs
src/Java.Interop/Tests/Java.Interop/JavaPrimitiveArrayContract.cs
src/Java.Interop/Tests/Java.Interop/JavaSByteArrayContractTests.cs
src/Java.Interop/Tests/Java.Interop/JavaSingleArrayContractTests.cs
src/Java.Interop/Tests/Java.Interop/JniEnvironmentTests.cs
src/Java.Interop/Tests/Java.Interop/JniTransitionTest.cs

Context: https://github.com/xamarin/xamarin-android/pull/3393
Context: https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3247796&view=ms.vss-test-web.build-test-results-tab&runId=9790200&resultId=100160&paneView=debug
In attempting to get Xamarin.Android to run the full compliement of
Java.Interop unit tests, there is one set of tests which are still
failing: the `JavaPrimitiveArrayContract.Constructor_Exceptions()`
tests fail because the *linker* is executed, and the linker is
removing the constructors which `Constructor_Exceptions()` relies on.
Make `JavaPrimitiveArrayContract` linker-safe, and instead of using
`System.Type.GetConstructor()` to get the constructor, introduce new
`abstract` methods on `JavaPrimitiveArrayContract.CreateCollection()`
which create instances of …

[Java.Interop-Tests] Remove Reflection from JavaPrimitiveArrayContract

---

src/Java.Interop/GlobalSuppressions.cs
src/Java.Interop/Java.Interop/JniRuntime.JniObjectReferenceManager.cs

We removed the public constructor from abstract class `Java.Interop.JniRuntime.JniObjectReferenceManager` in https://github.com/xamarin/java.interop/pull/523.  This change is fine, but it triggered the API Compatibility check.
Because we are in the middle of replacing that check with something else it's easier to simply revert this change for now.

[Java.Interop] Revert removing public constructor from abstract class to appease api checker.

---

src/Xamarin.Android.Tools.ApiXmlAdjuster/JavaApi.XmlModel.cs
src/Xamarin.Android.Tools.ApiXmlAdjuster/JavaApiXmlGeneratorExtensions.cs
src/Xamarin.Android.Tools.ApiXmlAdjuster/JavaApiXmlLoaderExtensions.cs
src/Xamarin.Android.Tools.Bytecode/Annotation.cs
src/Xamarin.Android.Tools.Bytecode/AttributeInfo.cs
src/Xamarin.Android.Tools.Bytecode/XmlClassDeclarationBuilder.cs
tests/Xamarin.Android.Tools.Bytecode-Tests/NullableAnnotationTests.cs
tests/Xamarin.Android.Tools.Bytecode-Tests/Xamarin.Android.Tools.Bytecode-Tests.csproj
tests/Xamarin.Android.Tools.Bytecode-Tests/java/android/annotation/NonNull.java
tests/Xamarin.Android.Tools.Bytecode-Tests/java/com/xamarin/NotNullClass.java
tests/generator-Tests/Unit-Tests/AdjusterTests.cs

First part of https://github.com/xamarin/java.interop/issues/468.
This adds support for reading `@NotNull/@NonNull` annotations from Java and putting them into `api.xml`.  It does not add logic to consume them.
Adds `not-null` attribute to `api.xml` for Fields and Parameters:
```
<field 
deprecated="not deprecated" 
final="true" 
name="CREATOR" 
jni-signature="Landroid/os/Parcelable$Creator;" 
not-null="true" 
static="true" 
transient="false" 
type="android.os.Parcelable.Creator" 
type-generic-aware="android.os.Parcelable.Creator&lt;android.app.DirectAction&gt;" 
visibility="public" 
volatile="false" />
<parameter 
name="handler" 
type="android.os.Handler" 
jni-type="Landroid/os/Handler;" 
not-null="true" />
```
Adds `return-not-null` attribute to `api.xml` for Methods:
```
<method …
```

[XAT.Bytecode] Add support for reading NotNull metadata into api.xml.

---

.gitmodules
Java.Interop.sln
src/Java.Interop.Dynamic/Java.Interop.Dynamic.csproj
src/Java.Interop.Dynamic/Java.Interop.Dynamic/DynamicJavaClass.cs
src/Java.Interop.Dynamic/Java.Interop.Dynamic/DynamicJavaInstance.cs
src/Java.Interop.Dynamic/Java.Interop.Dynamic/JavaClassInfo.cs
src/Java.Interop.Dynamic/Java.Interop.Dynamic/JavaConstructorInfo.cs
src/Java.Interop.Dynamic/Java.Interop.Dynamic/JavaFieldInfo.cs
src/Java.Interop.Dynamic/Java.Interop.Dynamic/JavaInstanceProxy.cs
src/Java.Interop.Dynamic/Java.Interop.Dynamic/JavaMethodBase.cs
src/Java.Interop.Dynamic/Java.Interop.Dynamic/JavaMethodInfo.cs
src/Java.Interop.Dynamic/Java.Interop.Dynamic/JniMetaObject.cs
tests/Java.Interop-Tests/Java.Interop-Tests.csproj
tests/Java.Interop.Dynamic-Tests/Java.Interop.Dynamic-Tests.csproj
tests/Java.Interop.Dynamic-Tests/Java.Interop/DynamicJavaClassTests.cs
tests/Java.Interop.Dynamic-Tests/Java.Interop/DynamicJavaInstanceTests.cs
tests/Java.Interop.Export-Tests/Java.Interop.Export-Tests.csproj

`Mono.Linq.Expressions` is available as `netstandard2.0` NuGet package.  Since we only use it for tests and it hasn't changed in 3+ years it seems more reasonable to use the NuGet package instead of a git submodule.

Consume Mono.Linq.Expressions as a NuGet instead of a submodule

---

tests/generator-Tests/Unit-Tests/KotlinFixupsTests.cs
tests/generator-Tests/Unit-Tests/XmlApiImporterTests.cs
tools/generator/CodeGenerator.cs
tools/generator/Java.Interop.Tools.Generator.Importers/XmlApiImporter.cs
tools/generator/Java.Interop.Tools.Generator.ObjectModel/MethodBase.cs
tools/generator/Java.Interop.Tools.Generator.Transformation/KotlinFixups.cs
tools/generator/generator.csproj

There are cases where Kotlin generates Java methods that are not allowed Java identifier names:
```
public void foo-WZ4Q5Ns(int) { }
```
We already change the name to `Foo ()` so C# can compile the method, and JNI allows us to call the method correctly.  However we cannot allow the user to override this method because we cannot create the Java override in the JCW.
```
public void foo-WZ4Q5Ns(int) { }
```
In this case we need to mark the method as non-virtual to prevent the user from overriding it.

[generator] Mark Kotlin-mangled methods as non-virtual (#534)

---

src/Java.Interop/Java.Interop/JniType.cs
tests/Java.Interop-Tests/Java.Interop/JavaExceptionTests.cs
tests/Java.Interop-Tests/Java.Interop/JniTypeTest.cs

Context: https://github.com/xamarin/xamarin-android/pull/3393
When running the `JniTypeTest.Name()` unit test within Xamarin.Android,
sometimes the unit test runner process would crash.  The crash is
*more* likely in Release runtimes:
F o.Android_Test: java_vm_ext.cc:570] JNI DETECTED ERROR IN APPLICATION: use of invalid jobject 0xc58fa798
F o.Android_Test: java_vm_ext.cc:570]     from void crc64f295cabbf85394f5.TestSuiteInstrumentation.n_onStart()
F o.Android_Test: runtime.cc:630] Runtime aborting...
What was particularly odd about this crash was that after enabling
both GREF and LREF logging, there was no handle 0xc58fa798!
Where was this invalid handle coming from?
Turns Out™, 0xc58fa798 isn't a handle.  Instead, it's a parameter
mismatch!
Commit 9f380ebb had a bug. …

[Java.Interop-Tests] Fix JniTypeTest.Name() missing argument

---

src/Java.Interop.Tools.Diagnostics/Java.Interop.Tools.Diagnostics/Diagnostic.cs
src/Java.Interop.Tools.JavaCallableWrappers/Java.Interop.Tools.JavaCallableWrappers/JavaCallableWrapperGenerator.cs
tests/Java.Interop.Tools.JavaCallableWrappers-Tests/Java.Interop.Tools.JavaCallableWrappers/JavaCallableWrapperGeneratorTests.cs
tests/Java.Interop.Tools.JavaCallableWrappers-Tests/Java.Interop.Tools.JavaCallableWrappers/SupportDeclarations.cs

Context: #534 
There are cases where Kotlin generates Java methods that are not allowed Java identifier names:
```
abstract class Bar {
abstract void foo-WZ4Q5Ns(int);
}
interface IBar {
void foo-WZ4Q5Ns(int);
}
```
In this case we cannot allow the user to implement the class as the mangled method cannot be implemented.  We still need the class to be bound because there might be a Kotlin-created subclass
that needs the base class to exist.
There's no foolproof way to mark these as "not implementable".  The best we can do for now is to detect if the user implements them in `GenerateJavaStubs` and give an informative error at that point.
This PR adds this error:
```
error XA4213: Cannot override Kotlin-generated method 'foo-WZ4Q5Ns' because it 
is not a valid Java method name. This method …
```

[JCW] Throw error if user tries to override a Kotlin name-mangled method. (#534)

---

src/Java.Interop/Java.Interop/JniEnvironment.cs
src/Java.Interop/Java.Interop/JniObjectReference.cs
src/Java.Interop/Java.Interop/JniType.cs

Context: https://github.com/xamarin/xamarin-android/blob/master/Documentation/guides/profiling.md#profiling-managed-code
I noticed the following when profiling startup in the Blank
Xamarin.Forms app template:
Method call summary
Total(ms) Self(ms)      Calls Method name
2        2       6470 Java.Interop.JniObjectReference:get_Handle ()
6        4       4043 Java.Interop.JniObjectReference:get_IsValid ()
1        1       3881 Java.Interop.JniEnvironmentInfo:get_Runtime ()
12        3       3084 Java.Interop.JniEnvironment:get_CurrentInfo ()
5        3       3084 Java.Interop.JniEnvironmentInfo:get_IsValid ()
9        1       1634 Java.Interop.JniEnvironment:get_EnvironmentPointer ()
4        0        797 Java.Interop.JniEnvironment:get_Runtime ()
2        0        672 …

[Java.Interop] apply AggressiveInlining where profiler shows calls

---

.vscode/extensions.json

The [T4 Support][0] Visual Studio Code extension provides syntax
highlighting for T4 files, such as
`src/Java.Interop/Java.Interop/JavaPrimitiveArrays.tt` and other T4
files included within the repo.
[0]: https://marketplace.visualstudio.com/items?itemName=zbecknell.t4-support

[vs-code] Recommend the zbecknell.t4-support extension

---

src/Java.Interop/Java.Interop/JavaObjectArray.cs
src/Java.Interop/Java.Interop/JniRuntime.JniValueManager.cs

Context: https://github.com/xamarin/xamarin-android/pull/3393
When attempting to execute the `Java.Interop-Tests.dll` unit tests
within Xamarin.Android, some of the `JavaObjectArray<T>` unit tests
would fail because the linker was removing the default constructor for
the `JavaObjectArray<T>.ValueMarshaler` type, and that type was only
created via `Activator.CreateInstance()` (aka "Reflection"):
Test 'Java.InteropTests.JavaObjectArray_Int32ArrayArray_ContractTest.CollectionContract`1.Clear' failed: System.MissingMethodException : Default constructor not found for type Java.Interop.JavaObjectArray`1+ValueMarshaler[[System.Int32[], mscorlib, Version=2.0.5.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]]
at System.RuntimeType.CreateInstanceMono (System.Boolean nonPublic, System.Boolean …

[Java.Interop] Better linker-friendly JavaObjectArray<T>.ValueMarshaler

---

tests/Java.Interop-Tests/Java.Interop/JniValueMarshalerContractTests.cs

Context: https://github.com/xamarin/xamarin-android/commit/130905e1612f1c3f41b6b233056cae2753270630
Context: https://github.com/xamarin/QualityAssurance/pull/3478
We've recently started running `Java.Interop` tests on an Android target
as part of the `Mono.Android-Tests` suite. This has introduced some
seemingly harmless failures[0] when building this suite on Windows and
then running it on Android. We can fix this by converting line endings
before comparing strings.
[0]:
01-02 16:18:11.949 I/NUnit   (23743): Failed tests:
01-02 16:18:11.949 I/NUnit   (23743): 1) Java.InteropTests.JniValueMarshaler_Boolean_ContractTests.JniValueMarshalerContractTests`1.CreateReturnValueFromManagedExpression (Java.Interop-Tests)
01-02 16:18:11.949 I/NUnit   (23743):   Expected string length 111 but was 99. …

[tests] Convert to Unix style line endings

---

src/Java.Interop/Java.Interop/JniPeerMembers.JniInstanceFields.cs
src/Java.Interop/Java.Interop/JniPeerMembers.JniInstanceMethods.cs
src/Java.Interop/Java.Interop/JniPeerMembers.JniStaticFields.cs
src/Java.Interop/Java.Interop/JniPeerMembers.JniStaticMethods.cs

Context: https://docs.microsoft.com/en-us/dotnet/standard/base-types/best-practices-strings#ordinal-string-operations
When profiling startup for a Xamarin.Forms app, I noticed some heavy
calls to `Dictionary`:
Total(ms) Self(ms)      Calls Method name
392       49      14826 System.Collections.Generic.Dictionary`2<TKey_REF, TValue_REF>:FindEntry (TKey_REF)
377       18      12744 System.Collections.Generic.Dictionary`2<TKey_REF, TValue_REF>:TryGetValue (TKey_REF,TValue_REF&)
129       14       3827 System.Collections.Generic.Dictionary`2<TKey_REF, TValue_REF>:TryInsert (TKey_REF,TValue_REF,System.Collections.Generic.InsertionBehavior)
Quite a few of these are coming from Java.Interop itself, and I
noticed we were using the default constructor for `Dictionary`. This
means we are using a …

[Java.Interop] use StringComparer.Ordinal for Dictionary

---

tests/generator-Tests/Unit-Tests/SymbolTableTests.cs
tools/generator/Java.Interop.Tools.Generator.ObjectModel/Symbols/SymbolTable.cs

Context: https://github.com/xamarin/java.interop/issues/543
In https://github.com/xamarin/java.interop/pull/450 we began stripping the arity from Cecil imported types so that we wouldn't write invalid types like `System.Collections.Generic.IList'1<string>`, resulting in the correctly formed `System.Collections.Generic.IList<string>`.
However when we try to resolve these types in the SymbolTable we only look at the type name, ignoring the generic types.  In this case we are looking for `System.Collections.Generic.IList` but the type is stored in the symbol table with the arity to disambiguate types like `Action'1` and `Action'2`.  Therefore our lookup fails because the table key is `System.Collections.Generic.IList'1`.
With this PR, if the type is not found in the table and there are …

[generator] Fix issue where generic types couldn't be found in SymbolTable (#543)

---

src/Java.Interop/Java.Interop/JavaArray.cs
src/Java.Interop/Java.Interop/JniPeerMembers.cs
src/Java.Interop/Java.Interop/JniRuntime.JniTypeManager.cs
src/Java.Interop/Java.Interop/JniRuntime.JniValueManager.cs
src/Java.Interop/Java.Interop/JniRuntime.cs
src/Java.Interop/Java.Interop/JniValueMarshalerAttribute.cs
src/Java.Interop/Java.Interop/ManagedPeer.cs

Java.Interop used to be a PCL, but is now a netstandard 2.0 library.
We make use of `IntrospectionExtensions.GetTypeInfo`:
https://github.com/mono/mono/blob/c5b88ec4f323f2bdb7c7d0a595ece28dae66579c/mcs/class/referencesource/mscorlib/system/reflection/introspectionextensions.cs#L24
https://github.com/mono/mono/blob/c5b88ec4f323f2bdb7c7d0a595ece28dae66579c/mcs/class/corlib/ReferenceSources/RuntimeType.cs
This is a "compat layer", because some of the System.Reflection APIs
are different for PCLs and netstandard 1.x.
If we remove these calls, and just use the regular `System.Type` APIs
the code is simpler and makes less method calls.
API differences to mention:
* `TypeInfo.GetDeclaredNestedType` is equivalent to
`Type.GetNestedTypes(BindingFlags.Public | BindingFlags.NonPublic)`
* …

[Java.Interop] remove Type.GetTypeInfo() calls

---

src/Java.Interop/Java.Interop/JniRuntime.JniTypeManager.cs
tests/TestJVM/TestJVM.cs

When profiling with `adb setprop debug.mono.profile log:alloc`, I
noticed the following allocations:
Allocation summary
Bytes      Count  Average Type name
84840        505      168 Java.Interop.JniRuntime.JniTypeManager.<CreateGetTypeSignaturesEnumerator>d__11
24096        502       48 Android.Runtime.AndroidTypeManager.<GetSimpleReferences>d__1
This was using the Xamarin.Forms integration project in xamarin-android:
https://github.com/xamarin/xamarin-android/tree/master/tests/Xamarin.Forms-Performance-Integration
100K of memory allocations are a bit much, so seemed like it might help
to reduce these.
I made a version of both `JniTypeManager.CreateTypeSignatures` and
`AndroidTypeManager.GetSimpleReferences` that return a single value
instead of an `IEnumerable` and `yield return`.
Other …

[Java.Interop] remove IEnumerable iterators called at startup

---

src/Java.Interop.Tools.TypeNameMappings/Java.Interop.Tools.TypeNameMappings/JavaNativeTypeManager.cs

Context: https://github.com/jonathanpeppers/Benchmarks/blob/cc3f2fb1c8f34c30b5b89b2a2b7e327ab7743bb1/Benchmarks/FullyQualifiedName.cs
I found `Assembly.GetName().Name` is somewhat slow compared to using
`Assembly.FullName` and a `Substring`.
It was an order of magnitude faster on .NET framework on Windows:
Intel Core i9-9900K CPU 3.60GHz, 1 CPU, 16 logical and 8 physical cores
[Host]     : .NET Framework 4.7.2 (CLR 4.0.30319.42000), 32bit LegacyJIT-v4.8.4075.0
Method |      Mean |     Error |    StdDev | Gen 0/1k Op | Allocated Memory/Op |
---------------- |----------:|----------:|----------:|------------:|--------------------:|
Substring |  92.05 ns | 0.1823 ns | 0.1616 ns |      0.0168 |                88 B |
AssemblyGetName | 949.68 ns | 1.9551 ns | 1.8288 ns |      0.0896 | …

[Java.Interop.Tools.TypeNameMappings] remove Assembly.GetName().Name usage

---

tests/generator-Tests/Unit-Tests/CodeGeneratorExpectedResults/JavaInterop1/WriteKotlinUnsignedArrayTypeMethodsClass.txt
tests/generator-Tests/Unit-Tests/CodeGeneratorExpectedResults/JavaInterop1/WriteKotlinUnsignedArrayTypePropertiesClass.txt
tools/generator/Java.Interop.Tools.Generator.ObjectModel/Symbols/ArraySymbol.cs

Context: #556 
Companion XA PR: https://github.com/xamarin/xamarin-android/pull/4119
Call new `JNIEnv.NewArray (...)` overloads that explicitly take unsigned types instead of doing `JNIEnv.NewArray ((int[])(object)value`.  This allows users to get a linker time error if they are using an older Java.Interop.dll that does not support unsigned types instead of a runtime error.

[generator] Call explicit unsigned NewArray methods. (#556)

---

tests/generator-Tests/Unit-Tests/CodeGeneratorTests.cs
tools/generator/Java.Interop.Tools.Generator.CodeGeneration/CodeGenerator.cs

Fixes: #565
In a case with generics, we were not renaming the property setter parameter to `value` which meant it was left as `p0` which is not valid C#.
Before:
```
set {
Selection = JavaCast<Long> (p0);
}
```
Now:
```
set {
Selection = JavaCast<Long> (value);
}
```

[generator] Fix case not renaming property setter parameter to "value"

---

tests/generator-Tests/Unit-Tests/GenBaseTests.cs
tools/generator/Java.Interop.Tools.Generator.CodeGeneration/CodeGenerator.cs
tools/generator/Java.Interop.Tools.Generator.ObjectModel/GenBase.cs

Today when a generated member has the same name as a method on `System.Object` we generate the method with a `new` in order to hide the base member.  However we only compare via the method name and not the method signature, meaning we add more `new` than is necessary.
For example this creates a warning because `new` is not needed:
```
// Org.Json.JSONArray.cs
public new virtual unsafe string ToString (int indentSpaces) { ... }
```
```
warning CS0109: The member 'JSONArray.ToString(int)' does not hide an accessible member. The new keyword is not required.
```
These are the methods from `System.Object` that we currently check against:
```csharp
"Boolean Equals(System.Object)"
"Boolean Equals(System.Object, System.Object)"    // static
"Boolean ReferenceEquals(System.Object, System.Object)" …
```

[generator] Be smarter about when members with same names need "new".

---

tests/generator-Tests/Unit-Tests/SealedProtectedFixupsTests.cs
tools/generator/CodeGenerator.cs
tools/generator/Java.Interop.Tools.Generator.Transformation/SealedProtectedFixups.cs
tools/generator/generator.csproj

When generating API-29 `Mono.Android.dll` we get ~12 warnings that we are declaring a new `protected` member in a `sealed` class:
```
warning CS0628: 'HttpHost.Hostname': new protected member declared in sealed class
```
The C# compiler makes these members `private` anyways, so we can change `generator` to make them `private` to eliminate the warning without being a breaking change.  The value in continuing to bind them as `private` as opposed to removing them is that they could be used by custom code in `partial` classes.

[generator] Change protected members in sealed classes to private.

---

.vscode/launch.json
tests/generator-Tests/Unit-Tests/CodeGeneratorTests.cs
tests/generator-Tests/Unit-Tests/SupportTypes.cs
tests/generator-Tests/expected/EnumerationFixup/EnumerationFixup.xml
tests/generator-Tests/expected/EnumerationFixup/Xamarin.Test.DeprecatedItems.cs
tools/generator/Java.Interop.Tools.Generator.CodeGeneration/CodeGenerator.cs
tools/generator/Java.Interop.Tools.Generator.Importers/XmlApiImporter.cs
tools/generator/Java.Interop.Tools.Generator.ObjectModel/Field.cs
tools/generator/Java.Interop.Tools.Generator.Transformation/EnumMap.cs
tools/generator/generator.sln

We are generating fields that have been marked as obsolete for a long time.
In the effort to remove all fields that now we believe should not be part of our API, we are marking then as obsolete Error=True so we can remove them in the next release.
Here are some scenarios these changes are addressing:
We should [Obsolete(error:true)] "interface proxy" types such as Android.Content.ComponentCallbacks2, which contains fields for the android.content.ComponentCallbacks2 interface and lives "alongside" the Android.Content.IComponentCallbacks2 interface. Additionally, all of these fields should be moved into the appropriate C# interface, e.g. every field within Android.Content.ComponentCallbacks2 should reside in the Android.Content.IComponentCallbacks2 type, using C#8 default interface members. …

Marking constant fields that will be removed in the next version as Obsolete error

---

src/Java.Interop/Java.Interop/JniRuntime.JniTypeManager.cs

While profiling Xamarin.Android app startup, we observed that lots of
time is spent in `GetCustomAttributes()` invocations.
We can reduce startup time by moving the
`JniTypeManager.GetSimpleReference()` to *before* the
`type.GetCustomAttribute<JniTypeSignatureAttribute>()` invocation.
This would allow `AndroidTypeManager` to be involved earlier, avoiding
the need for Reflection & custom attribute lookup.

[Java.Interop] Call GetSimpleReference before custom attrs

---

build-tools/automation/azure-pipelines.yaml

Context: https://feedback.devdiv.io/922217
Context: https://build.azdo.io/3484060
.NET Core 3.1.102 dropped yesterday and broke the build with:
Download URL for .Net Core sdk version 3.1.102 could not be found for the following OS platforms (rid): osx-x64,osx-x64
It appears using `3.1.x` broke...
We don't know how long this will be broken, so let's use what
xamarin-android is using, which appears to be working:
https://github.com/xamarin/xamarin-android/blob/87ee20c59a09ba4314f4226e1c77ee2331c3f09f/build-tools/automation/azure-pipelines.yaml#L51

[build] target .NET Core 3.1.100

---

src/Java.Interop.Tools.Cecil/Java.Interop.Tools.Cecil/MethodDefinitionRocks.cs
src/Java.Interop.Tools.Cecil/Java.Interop.Tools.Cecil/TypeDefinitionCache.cs
src/Java.Interop.Tools.Cecil/Java.Interop.Tools.Cecil/TypeDefinitionRocks.cs
src/Java.Interop.Tools.JavaCallableWrappers/Java.Interop.Tools.JavaCallableWrappers/JavaCallableWrapperGenerator.cs
src/Java.Interop.Tools.JavaCallableWrappers/Java.Interop.Tools.JavaCallableWrappers/JavaTypeScanner.cs
src/Java.Interop.Tools.JavaCallableWrappers/Java.Interop.Tools.JavaCallableWrappers/TypeNameMapGenerator.cs
src/Java.Interop.Tools.TypeNameMappings/Java.Interop.Tools.TypeNameMappings/JavaNativeTypeManager.cs
tests/Java.Interop.Tools.JavaCallableWrappers-Tests/Java.Interop.Tools.JavaCallableWrappers/JavaCallableWrapperGeneratorTests.cs
tests/Java.Interop.Tools.JavaCallableWrappers-Tests/Java.Interop.Tools.JavaCallableWrappers/TypeNameMapGeneratorTests.cs
tools/generator/CodeGenerator.cs
tools/jcw-gen/App.cs
tools/jnimarshalmethod-gen/App.cs
tools/jnimarshalmethod-gen/TypeMover.cs

I was profiling builds with the Mono profiler and noticed:
Method call summary
Total(ms) Self(ms)      Calls Method name
70862       97      89713 Java.Interop.Tools.Cecil.DirectoryAssemblyResolver:Resolve (Mono.Cecil.AssemblyNameReference,Mono.Cecil.ReaderParameters)
Almost 90K calls? What is that coming from???
61422 calls from:
Java.Interop.Tools.Cecil.TypeDefinitionRocks/<GetTypeAndBaseTypes>d__1:MoveNext ()
Java.Interop.Tools.Cecil.TypeDefinitionRocks:GetBaseType (Mono.Cecil.TypeDefinition)
Mono.Cecil.TypeReference:Resolve ()
Mono.Cecil.ModuleDefinition:Resolve (Mono.Cecil.TypeReference)
Mono.Cecil.MetadataResolver:Resolve (Mono.Cecil.TypeReference)
Java.Interop.Tools.Cecil.DirectoryAssemblyResolver:Resolve (Mono.Cecil.AssemblyNameReference)
Ok, this jogged my memory. Stephane …

[Java.Interop.Tools.Cecil] cache TypeReference.Resolve() calls

---

tests/generator-Tests/expected/AccessModifiers/AccessModifiers.xml
tools/generator/CodeGenerator.cs

Fixes #572.
Do not generate bindings for `package-private` nested types to match logic for top level classes.

[generator] Do not generate bindings for package-private nested types [#572]

---

tests/generator-Tests/expected.ji/AccessModifiers/Xamarin.Test.PublicClass.cs
tests/generator-Tests/expected/AccessModifiers/AccessModifiers.xml
tests/generator-Tests/expected/AccessModifiers/Xamarin.Test.PublicClass.cs
tools/generator/CodeGenerator.cs

In #575, we stopped binding nested types that are **not** `public` or `internal`, however we also need to bind nested types that are `protected`.
Note that internally `protected` is stored as `protected internal` due to:
https://github.com/xamarin/java.interop/blob/master/tools/generator/Java.Interop.Tools.Generator.Importers/XmlApiImporter.cs#L143-L144

[generator] Bind protected nested types.

---

src/Java.Interop.Tools.Cecil/Java.Interop.Tools.Cecil/TypeDefinitionRocks.cs

Using the Mono profiler, I found:
Allocation summary
Bytes      Count  Average Type name
7636736      59662      128 System.Func<Mono.Cecil.TypeDefinition,System.Boolean>
3685952      57593       64 Java.Interop.Tools.Cecil.TypeDefinitionRocks.<GetTypeAndBaseTypes>d__3
The stack traces of these are from:
2498944 bytes from:
Xamarin.Android.Tasks.GenerateJavaStubs:Run (Java.Interop.Tools.Cecil.DirectoryAssemblyResolver)
Xamarin.Android.Tasks.ManifestDocument:Merge (Microsoft.Build.Utilities.TaskLoggingHelper,Java.Interop.Tools.Cecil.TypeDefinitionCache,System.Collections.Generic.List`1<Mono.Cecil.TypeDefinition>,string,bool,string,System.Collections.Generic.IEnumerable`1<string>)
Xamarin.Android.Tasks.ManifestDocument:GetGenerator …

[Java.Interop.Tools.Cecil] remove System.Linq in IsSubclassOf

---

Java.Interop.sln

Context: https://github.com/dotnet/project-system/issues/1821
Once you start mixing in SDK-style projects into a solution VS2017/VS2019 changes all the project type GUIDs in the solution file every time it saves.  This is arguably a bug, but after 3 years it doesn't seem like it's going to be fixed.
Time to stop fighting it and just let VS have its way.

[Java.Interop.sln] Let VS update the project type guids.

---

tests/generator-Tests/Unit-Tests/CodeGeneratorExpectedResults/JavaInterop1/WriteInterfaceDefaultMethod.txt
tests/generator-Tests/Unit-Tests/CodeGeneratorExpectedResults/JavaInterop1/WriteInterfaceDefaultProperty.txt
tests/generator-Tests/Unit-Tests/CodeGeneratorExpectedResults/JavaInterop1/WriteInterfaceDefaultPropertyGetterOnly.txt
tests/generator-Tests/Unit-Tests/CodeGeneratorExpectedResults/JavaInterop1/WriteStaticInterfaceMethod.txt
tests/generator-Tests/Unit-Tests/CodeGeneratorExpectedResults/JavaInterop1/WriteStaticInterfaceProperty.txt
tests/generator-Tests/Unit-Tests/CodeGeneratorExpectedResults/XAJavaInterop1/WriteInterfaceDefaultMethod.txt
tests/generator-Tests/Unit-Tests/CodeGeneratorExpectedResults/XAJavaInterop1/WriteInterfaceDefaultProperty.txt
tests/generator-Tests/Unit-Tests/CodeGeneratorExpectedResults/XAJavaInterop1/WriteInterfaceDefaultPropertyGetterOnly.txt
tests/generator-Tests/Unit-Tests/CodeGeneratorExpectedResults/XAJavaInterop1/WriteStaticInterfaceMethod.txt
tests/generator-Tests/Unit-Tests/CodeGeneratorExpectedResults/XAJavaInterop1/WriteStaticInterfaceProperty.txt
tools/generator/Java.Interop.Tools.Generator.CodeGeneration/CodeGenerator.cs
tools/generator/Java.Interop.Tools.Generator.CodeGeneration/JavaInteropCodeGenerator.cs

Context #509.
We have never used explicit `private` modifiers on class members due to the [Mono Coding Guidelines](https://www.mono-project.com/community/contributing/coding-guidelines/), as `private` is the default.  However, when working with DIM on interfaces members, the default is `public`.  This results in our plumbing members like `_members` and `static Delegate cb_DoSomething;` being exposed as part of the interface's public API.
This commit makes private interface members explicitly `private`.

[generator] Make DIM invoking plumbing private.

---

src/Java.Interop/Java.Interop-MonoAndroid.csproj

Context: https://github.com/microsoft/msbuild/commit/67991edee76d433b744ceb593f554e2bbeb6b9a0
Context: https://github.com/xamarin/xamarin-android/pull/4219
Context: https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3497481&view=logs&s=1afc3bfe-122c-538b-e9ad-2a86c2efcfef&j=96fd57f5-f69e-53c7-3d47-f67e6cf9b93e
A "funny" thing happened in xamarin/xamarin-android#4219 in trying to
use the latest mono/2020-02 branch: the build failed:
"…/xamarin-android/external/Java.Interop/src/Java.Interop/Java.Interop.csproj" (default target) (25:3) ->
obj/Release/netstandard2.0/.NETStandard,Version=v2.0.AssemblyAttributes.cs(4,12):
error CS0579: Duplicate 'global::System.Runtime.Versioning.TargetFrameworkAttribute' attribute
`Java.Interop.csproj` failed to build, …

[Java.Interop] Alter $(BaseIntermediateOutputPath) for x-a

---

src/Java.Interop/Java.Interop-MonoAndroid.csproj

After https://github.com/xamarin/java.interop/commit/95712a2fc58a9c52ee0f53eea5bbd29d12f21385 we now hit the opposite condition.
The SDK-style build of Java.Interop.csproj generates "obj/Release/netstandard2.0/.NETStandard,Version=v2.0.AssemblyAttributes.cs" which is now included by the `<Compile Include="**\*.cs" />` in Java.Interop-MonoAndroid.csproj.
Changing the `BaseIntermediateOutputPath` is more complicated for SDK-style projects due to the way the common targets are imported: https://github.com/microsoft/msbuild/issues/1603. The easiest fix is adding back the removal of .cs files in obj/.

Remove obj/ from Compile in Java.Interop-MonoAndroid.csproj

---

tests/generator-Tests/Unit-Tests/CodeGeneratorExpectedResults/JavaInterop1/WriteNestedInterfaceTypes.txt
tests/generator-Tests/Unit-Tests/CodeGeneratorExpectedResults/JavaInterop1/WriteUnnestedInterfaceTypes.txt
tests/generator-Tests/Unit-Tests/CodeGeneratorExpectedResults/XAJavaInterop1/WriteNestedInterfaceTypes.txt
tests/generator-Tests/Unit-Tests/CodeGeneratorExpectedResults/XAJavaInterop1/WriteUnnestedInterfaceTypes.txt
tests/generator-Tests/Unit-Tests/CodeGeneratorTests.cs
tests/generator-Tests/Unit-Tests/DefaultInterfaceMethodsTests.cs
tests/generator-Tests/Unit-Tests/InterfaceConstantsTests.cs
tests/generator-Tests/Unit-Tests/KotlinFixupsTests.cs
tests/generator-Tests/Unit-Tests/XmlApiImporterTests.cs
tests/generator-Tests/Unit-Tests/XmlTests.cs
tools/generator/CodeGenerationOptions.cs
tools/generator/CodeGenerator.cs
tools/generator/CodeGeneratorOptions.cs
tools/generator/Java.Interop.Tools.Generator.CodeGeneration/CodeGenerator.cs
tools/generator/Java.Interop.Tools.Generator.Importers/XmlApiImporter.cs
tools/generator/Java.Interop.Tools.Generator.ObjectModel/GenBase.cs
tools/generator/Java.Interop.Tools.Generator.ObjectModel/InterfaceGen.cs
tools/generator/Java.Interop.Tools.Generator.Transformation/Parser.cs

Traditionally we have not been able to support types nested inside an interface, as C# did not allow it.  Cases like this:
```
My.Namespace.IParent.IChild
```
had to be bound as:
```
My.Namespace.IParentChild
```
With the addition of DIM in C#8, interfaces can now created with nested types.  However this is a breaking changes if you've already been generating the old style types.  
Therefore we add a new flag `--lang-features=nested-interface-types` that defaults to `false` to preserve compatibility.  Opting in to this flag will nest all interface types.
Additionally, users may have bindings that need to mix nested and unnested interface types.  For example, `Mono.Android.dll` contains a decade of APIs that cannot be broken, however **new** APIs can be nested correctly, producing a …

[generator] Support using DIM to nest interface types.

---

src/Java.Interop.Tools.Diagnostics/Java.Interop.Tools.Diagnostics/Diagnostic.cs
src/Java.Interop.Tools.JavaCallableWrappers/Java.Interop.Tools.JavaCallableWrappers/JavaCallableWrapperGenerator.cs
tests/Java.Interop.Tools.JavaCallableWrappers-Tests/Java.Interop.Tools.JavaCallableWrappers/JavaCallableWrapperGeneratorTests.cs

Renumber XA4213 to XA4217 to remove a conflict with an earlier usage of
XA4213 in [xamarin-android][0].
[0]: https://github.com/xamarin/xamarin-android/blob/1a6fcff8a5a68bc2b53afa948176dea9681ff0d0/src/Xamarin.Android.Build.Tasks/Utilities/ManifestDocument.cs#L323

[Java.Interop.Tools.JavaCallableWrappers] Renumber XA4213 to XA4217

---

tools/generator/CodeGenerator.cs
tools/generator/CodeGeneratorOptions.cs

Context: https://github.com/xamarin/xamarin-android/pull/4356#issuecomment-594990011
A "funny" thing was found with API-R: the Android SDK
`platforms/android-R/data/api-versions.xml` file is *missing* members
present in previous API versions, e.g.
`java.lang.StringBuilder.trimToSize()` is not mentioned in API-R,
while it *is* mentioned in API-29 and the "global"
`platform-tools/api/api-versions.xml`.
Try to improve sanity for this conundrum by allowing
`generator --apiversions` to be specified multiple times, e.g. this
diff to apply to xamarin-android:
diff --git a/src/Mono.Android/Mono.Android.targets b/src/Mono.Android/Mono.Android.targets
index 8735c2ae..baae759b 100644
--- a/src/Mono.Android/Mono.Android.targets
+++ b/src/Mono.Android/Mono.Android.targets
@@ -78,10 +78,13 @@ …

[generator] Allow multiple `generator --apiversions`

---

tests/generator-Tests/Unit-Tests/CodeGeneratorExpectedResults/JavaInterop1/WriteNestedInterfaceClass.txt
tests/generator-Tests/Unit-Tests/CodeGeneratorExpectedResults/XAJavaInterop1/WriteNestedInterfaceClass.txt
tests/generator-Tests/Unit-Tests/DefaultInterfaceMethodsTests.cs
tools/generator/Java.Interop.Tools.Generator.ObjectModel/InterfaceGen.cs

In #589 we stopped mangling names of interfaces nested inside interfaces.  However we need to expand this fix to support classes nested inside interfaces as well.
That is, previously we were doing this:
```
My.Namespace.IMyInterfaceMyClass
```
Now we correctly leave the name nested:
```
My.Namespace.IMyInterface.MyClass
```

[generator] Fix names of classes nested in an interface.

---

tests/TestJVM/TestJVM.cs

Context: https://github.com/xamarin/xamarin-android/pull/4302
Context: https://github.com/xamarin/java.interop/pull/582
Java.Interop tests use their own runtime which doesn't know about the
results of Xamarin.Android's build process scanning for the presence of
the `JniAddNativeMethodRegistration` custom attribute. In addition,
Java.Interop's Java type scanner (for typemaps) does not include in its
results the types in `Java.Interop-Tests` which derive from
`Java.Interop.JavaObject` (which is **functionally** equivalent to
Xamarin.Android's `Java.Lang.Object`) and, thus, the scan doesn't notice
that the custom attribute mentioned above is used by a few test classes.
In effect, two tests fail with a similar exception:
Java.Lang.LinkageError : No implementation found for void …

Force looking for the [JniAddNativeMethodRegistration] attribute

---

src/Java.Interop.Tools.Cecil/Java.Interop.Tools.Cecil/DirectoryAssemblyResolver.cs

Context: https://www.jetbrains.com/profiler/
I have been playing with dotTrace, and it displayed the following as
the no. 4 top "hot path" during a build of the Xamarin.Forms
integration project:
0.08%   DirectoryGetFile  •  376/0 ms  •  Java.Interop.Tools.Cecil.DirectoryAssemblyResolver.DirectoryGetFile(String, String)
0.08%   SearchDirectory  •  Java.Interop.Tools.Cecil.DirectoryAssemblyResolver.SearchDirectory(String, String)
0.08%   Resolve  •  Java.Interop.Tools.Cecil.DirectoryAssemblyResolver.Resolve(AssemblyNameReference, ReaderParameters)
0.05%   RunTask  •  262 of 376 ms  •  Xamarin.Android.Tasks.LinkAssembliesNoShrink.RunTask
0.02%   Resolve  •  114 of 376 ms  •  Java.Interop.Tools.Cecil.DirectoryAssemblyResolver.Resolve(AssemblyNameReference)
As seen in b81cfbb9, …

[Java.Interop.Tools.Cecil] use File.Exists instead of DirectoryGetFile

---

Makefile

Ever since commit dec2e390, *every* **make**(1) target would result in
running `nuget restore`, e.g.:
$ make run-tests TESTS=bin/TestDebug/Java.Interop.Tools.JavaSource-Tests.dll
nuget restore
...
The `nuget restore` was both time consuming and irrelevant, and meant
that `make` targets which *should* have been fast -- like `make all`,
which shouldn't do anything after the initial `make prepare all`,
would instead take multiple seconds to complete.
Why was `nuget restore` always being invoked?
$ make -d -n run-tests
...
Must remake target `packages/NUnit.3.11.0/NUnit.3.11.0.nupkg'.
nuget restore
What happened is that commit dec2e390 changed various projects to be
Short-Form SDK projects, which in turn alters the `packages` directory
structure: instead of e.g. …

[build] Remove extraneous `nuget restore`s

---

tests/generator-Tests/Unit-Tests/CodeGeneratorExpectedResults/JavaInterop1/ObsoleteInterfaceAlternativeClass.txt
tests/generator-Tests/Unit-Tests/CodeGeneratorExpectedResults/XAJavaInterop1/ObsoleteInterfaceAlternativeClass.txt
tests/generator-Tests/Unit-Tests/DefaultInterfaceMethodsTests.cs
tools/generator/Java.Interop.Tools.Generator.CodeGeneration/CodeGenerator.cs

Context: #509. 
Due to our legacy workarounds for the C# shortcoming of not being able to place constants or members on interfaces, every interface with those members creates two additional "alternative" classes to provide users access to the members originally on the interface.
For example, the Java interface `android.os.Parcelable` creates:
* `interface IParcelable` containing the interface declaration
* `class ParcelableConsts` containing the constants that are on `Parcelable`
* `class Parcelable` contains the constants and static members that are on `Parcelable`
Now that we can support members on interfaces, we would like to start the process of removing these interface alternatives.
The XXXXConsts classes have been `[Obsolete]` for over 5 years, and have been `[Obsolete (iserror: …

[generator] When using interface-constants, remove or obsolete interface alternatives.

---

tests/generator-Tests/Unit-Tests/DefaultInterfaceMethodsTests.cs
tools/generator/Java.Interop.Tools.Generator.CodeGeneration/CodeGenerator.cs
tools/generator/Java.Interop.Tools.Generator.Importers/XmlApiImporter.cs
tools/generator/Java.Interop.Tools.Generator.ObjectModel/InterfaceGen.cs

Context: #509 
In #600 we began cleaning up our existing "alternative" hacks for bindings that use the new C#8 DIM features.  However, as we add new API interfaces we will continue to generate new `[Obsolete]` "alternative" classes.  We do not need to add new already-obsolete API to our bindings.
This PR creates a new attribute for `<interface>` elements called `@no-alternatives`.  When this attribute is set to `true` we will not generate the alternative classes for this interface.
This will be used in `Mono.Android.dll` like this:
```
<attr api-since="30" path="/api/package/interface[contains(@merge.SourceFile,'api-30.xml.in')]" name="no-alternatives">true</attr>
```
This will keep any new interfaces added in API-30 from creating `[Obsolete]` alternative classes.
This diff …

[generator] Add api flag "no-alternatives" to skip generating interface member alternatives.

---

src/Java.Interop.Tools.JavaCallableWrappers/Java.Interop.Tools.JavaCallableWrappers/IdentifierValidator.cs
tools/generator/CodeGenerationOptions.cs
tools/generator/Utilities/TypeNameUtilities.cs
tools/generator/generator.csproj

The `netcoreapp3.1` target framework doesn't include `System.CodeDom`.
Remove use of CSharpCodeGenerator.

[generator] Add netcoreapp3.1 support

---

src/java-interop/java-interop.csproj
tests/Java.Interop-PerformanceTests/Java.Interop-PerformanceTests.csproj
tests/Java.Interop-Tests/Java.Interop-Tests.csproj
tests/Java.Interop.Export-Tests/Java.Interop.Export-Tests.csproj

In https://github.com/xamarin/java.interop/pull/605, we created a `Directory.Build.props` file which automatically imports several things for all projects.  The projects that are still manually importing these same files are creating duplicate warnings like:
```
tests\Java.Interop-Tests\Java.Interop-Tests.csproj(33,3): 
Warning MSB4011: "d:\a\1\s\bin\BuildRelease\JdkInfo.props" cannot be imported again. It was already imported at "d:\a\1\s\Directory.Build.props (13,3)". This is most likely a build authoring error. This subsequent import will be ignored. 
```
This doesn't fix the `jnienv-gen.csproj` warnings, they will be fixed when the project is converted to sdk-style.

Remove <Imports> now covered by Directory.Build.props.

---

src/Java.Interop.Tools.JavaCallableWrappers/Java.Interop.Tools.JavaCallableWrappers/IdentifierValidator.cs
tests/Java.Interop.Tools.JavaCallableWrappers-Tests/Java.Interop.Tools.JavaCallableWrappers/IdentifierValidatorTests.cs
tests/generator-Tests/Tests-Core/api.xml
tests/generator-Tests/Tests-Core/expected.ji/Android.Views.View.cs
tests/generator-Tests/Tests-Core/expected/Android.Views.View.cs

Context: https://github.com/xamarin/xamarin-android/pull/4431
Commit e7c5f54a added `IdentifierValidator.IsValidIdentifier()`,
replacing use of `CSharpCodeProvider.IsValidIdentifier()`, and this
change caused a unit test failure within xamarin-android:
// Xamarin.Android.Build.Tests.BuildTest.GeneratorValidateEventName
obj/Debug/generated/src/Com.Xamarin.Testing.Test.cs(350,29,350,32): error CS1001: Identifier expected
The line in question?
public event EventHandler 123 {
Oops.
It Turns Out™ that `IdentifierValidator.IsValidIdentifier("123")`
returned True, so we attempted to create an event named `123`, which
the C# compiler Does Not Like.
Fix `IdentifierValidator.IsValidIdentifier()` by using a new
`IsValidIdentifierRegex` regex to match against identifiers, instead
of attempting to …

[Java.Interop.Tools.JavaCallableWrappers] Fix IsValidIdentifier()

---

tools/generator/CodeGenerator.cs

When a binding project references another binding project, the list of references assemblies can contain duplicates, particularly `mscorlib`:
```
[0]: "C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Preview\\Common7\\IDE\\ReferenceAssemblies\\Microsoft\\Framework\\MonoAndroid\\v1.0\\mscorlib.dll"
[1]: "C:\\code\\XamarinComponents\\Android\\BetterPickers\\source\\AndroidSwitchBackport\\bin\\Debug\\AndroidSwitchBackport.dll"
[2]: "C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Preview\\Common7\\IDE\\ReferenceAssemblies\\Microsoft\\Framework\\MonoAndroid\\v1.0\\Java.Interop.dll"
[3]: "C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Preview\\Common7\\IDE\\ReferenceAssemblies\\Microsoft\\Framework\\MonoAndroid\\v9.0\\Mono.Android.dll"
[4]: "C:\\Program Files …
```

[generator] Don't process duplicate reference assemblies.

---

Directory.Build.props

When `Directory.Build.props` is imported by MSBuild, the
`$(Configuration)` property will only be defined if it was excplitily
provided on the command line.  As such, when building the repo when
using **make**(1), it builds:
$ make prepare
$ make all
After `make all`, if we attempt to manually build a single `.csproj`,
it may fail:
$ msbuild tests/Java.Interop-Tests/Java.Interop-Tests.csproj
...
BuildInteropTestJar:
"" -source 1.6 -target 1.6 -bootclasspath "" -d "obj/Debug/it-classes" -classpath …
…: error MSB3073: The command """ -source 1.6 -target 1.6 …" exited with code 127.
Building a single `.csproj` works if the `Configuration` property is
explicitly provided:
$ msbuild tests/Java.Interop-Tests/Java.Interop-Tests.csproj /p:Configuration=Debug
Update `Directory.Build.props` so that …

[build] Provide a default $(Configuration) value

---

Directory.Build.props
build-tools/jnienv-gen/jnienv-gen.csproj
src/Java.Interop/Directory.Build.targets
src/Java.Interop/Java.Interop-MonoAndroid.csproj
src/Java.Interop/Java.Interop.csproj

`Java.Interop.dll` is already a .NET Standard 2.0 library, which is
already compatible with .NETCoreApp,Version=3.1.  Why does it need to
be built against `netcoreapp3.1` framework?
Consistent Assembly References.
`Java.Interop.dll` was originally a PCL, and before it became a
.NET Standard 2.0 library in commit 85be94f3, we added support to
build `Java.Interop.dll` as a `MonoAndroid`-profile assembly in commit
893562cb, as doing so reduced the assemblies referenced from the PCL
version from 15 assemblies (`System.Runtime`, `System.Collections`, …)
down to *3* assemblies: `mscorlib`, `System`, `System.Core`.  Reducing
the number of assemblies referenced improved build and deploy times.
In the .NET Standard 2.0 world order, `Java.Interop.dll` now has *one*
assembly reference: …

[Java.Interop, jnienv-gen] Add netcoreapp3.1 support

---

Directory.Build.props
build-tools/jnienv-gen/jnienv-gen.csproj
samples/Hello/Hello.csproj
src/Java.Interop.Dynamic/Java.Interop.Dynamic.csproj
src/Java.Interop.Export/Java.Interop.Export.csproj
src/Java.Interop.GenericMarshaler/Java.Interop.GenericMarshaler.csproj
src/Java.Interop.Tools.Cecil/Java.Interop.Tools.Cecil.csproj
src/Java.Interop.Tools.JavaCallableWrappers/Java.Interop.Tools.JavaCallableWrappers.csproj
src/Java.Interop/Java.Interop.csproj
src/Java.Runtime.Environment/Java.Runtime.Environment.csproj
src/Xamarin.Android.Tools.AnnotationSupport.Cecil/Xamarin.Android.Tools.AnnotationSupport.Cecil.csproj
src/Xamarin.Android.Tools.AnnotationSupport/Xamarin.Android.Tools.AnnotationSupport.csproj
src/Xamarin.Android.Tools.Bytecode/Xamarin.Android.Tools.Bytecode.csproj
tests/Java.Interop-PerformanceTests/Java.Interop-PerformanceTests.csproj
tests/Java.Interop-Tests/Java.Interop-Tests.csproj
tests/Java.Interop.Dynamic-Tests/Java.Interop.Dynamic-Tests.csproj
tests/Java.Interop.Export-Tests/Java.Interop.Export-Tests.csproj
tests/Java.Interop.Tools.JavaCallableWrappers-Tests/Java.Interop.Tools.JavaCallableWrappers-Tests.csproj
tests/Java.Interop.Tools.JavaSource-Tests/Java.Interop.Tools.JavaSource-Tests.csproj
tests/TestJVM/TestJVM.csproj
tests/Xamarin.Android.Tools.ApiXmlAdjuster-Tests/Xamarin.Android.Tools.ApiXmlAdjuster-Tests.csproj
tests/Xamarin.Android.Tools.Bytecode-Tests/Xamarin.Android.Tools.Bytecode-Tests.csproj
tests/generator-Tests/generator-Tests.csproj
tests/logcat-parse-Tests/logcat-parse-Tests.csproj
tools/class-parse/class-parse.csproj
tools/generator/generator.csproj
tools/jcw-gen/jcw-gen.csproj
tools/jnimarshalmethod-gen/Xamarin.Android.Tools.JniMarshalMethodGenerator.csproj
tools/logcat-parse/logcat-parse.csproj
tools/param-name-importer/param-name-importer.csproj

@jpobst mentioned that when building projects within this repo, the
first build would succeed while the second build would fail, because
`IncrementalClean` would remove files created by the first build.
```
Metadata file 'C:\code\xamarin-android\bin\Debug\lib\xamarin.android\xbuild\Xamarin\Android\generator.exe' could not be opened -- PE image doesn't contain managed metadata.	
```
The reason this happens is because when a project is multitargeted, we
have things setup such that all the `$(TargetFramework)` builds
*share* the same `$(IntermediateOutputPath)`, and thus they step on
each other's toes.
Solve this by defining `$(IntermediateOutputPath)` so that
`netcoreapp3.1` builds use `obj\$(Configuration)-$(TargetFramework)`,
while non-`netcoreapp3.1` builds use the "legacy" …

[build] Consistent $(IntermediateOutputPath) values

---

build-tools/scripts/PrepareWindows.targets

The version of `NuGet.exe` that is downloaded during `msbuild Java.Interop /t:Prepare` on Windows is unable to load all the needed assemblies in order to complete a restore:
```
C:\code\xamarin-android\external\Java.Interop\build-tools\scripts\..\..\.nuget\NuGet.exe restore Java.Interop.sln
MSBuild auto-detection: using msbuild version '16.6.0.15501' from 'C:\Program Files (x86)\Microsoft Visual Studio\201  9\Preview\MSBuild\Current\bin'.
Error parsing solution file at C:\code\xamarin-android\external\Java.Interop\Java.Interop.sln: Exception has been thrown by the target of an invocation.  The project file could not be loaded. Could not load file or assembly 'Microsoft.Build.Framework, Version=15.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The …
```

[PrepareWindows] Use an updated version of NuGet.exe.

---

src/Java.Interop.Tools.Cecil/Java.Interop.Tools.Cecil/DirectoryAssemblyResolver.cs

Context https://github.com/xamarin/xamarin-android/issues/2120
When building an app and using an Obfuscator you wne up with allot
of warnings like.
warning : Failed to read 'obj\Release\90\android\assets\DotfuscatorForms.Android.dll' with debugging symbols. Retrying to load it without it. Error details are logged below.
warning : Mono.Cecil.Cil.SymbolsNotMatchingException: Symbols were found but are not matching the assembly
These are probably the result of the Obfuscation process since the
assembly changed. However the warning was NOT useful or more
importantly... actionable by the user. It is just noise. It might
be useful for the developers writing the Java.Interop tooling itself.
So rather than a warning , lets change it to be `Verbose`. This will
allow it up show up in full …

[Java.Interop.Tools.Cecil] Change DirectoryAssemblyResolver Warning to Diagnostic Output

---

src/Java.Interop.Tools.JavaCallableWrappers/Java.Interop.Tools.JavaCallableWrappers/Crc64.cs
tests/Java.Interop.Tools.JavaCallableWrappers-Tests/Java.Interop.Tools.JavaCallableWrappers/Crc64Tests.cs
tests/Java.Interop.Tools.JavaCallableWrappers-Tests/Java.Interop.Tools.JavaCallableWrappers/JavaCallableWrapperGeneratorTests.cs
tests/Java.Interop.Tools.JavaCallableWrappers-Tests/Java.Interop.Tools.JavaCallableWrappers/JavaNativeTypeManagerTests.cs
tests/Java.Interop.Tools.JavaCallableWrappers-Tests/Java.Interop.Tools.JavaCallableWrappers/TypeNameMapGeneratorTests.cs

Context: 9b88ce79f231136a41eca197e0fb154baa6a6a44
9b88ce79 implements a splice-by-8 version of the CRC64 algorithm which
processes 8 bytes per loop iteration. However, the code had a subtle bug
which resulted in the same CRC calculated for different strings and made
some of Xamarin.Android tests to fail. The following strings yielded the
same checksum value:
* obj/Debug/lp/10/jl/bin/classes.jar
* obj/Debug/lp/11/jl/bin/classes.jar
* obj/Debug/lp/12/jl/bin/classes.jar
The raeson for this was subtle (a stupid oversight on my part, really):
the loop fetched values from the input array by using an index into the
array:
crc ^= (ulong)aptr[idx];
However, with `aptr` being declared as `byte* aptr` the indexing
operation returned a single **byte** instead of the required 64-bit
word (8 bytes) …

[crc64] Fix a subtle bug in CRC64 splice-by-8 implementation

---

src/Java.Interop.Tools.TypeNameMappings/Java.Interop.Tools.TypeNameMappings/JavaNativeTypeManager.cs
tests/Java.Interop.Tools.JavaCallableWrappers-Tests/Java.Interop.Tools.JavaCallableWrappers/JavaCallableWrapperGeneratorTests.cs
tests/Java.Interop.Tools.JavaCallableWrappers-Tests/Java.Interop.Tools.JavaCallableWrappers/JavaNativeTypeManagerTests.cs
tests/Java.Interop.Tools.JavaCallableWrappers-Tests/Java.Interop.Tools.JavaCallableWrappers/TypeNameMapGeneratorTests.cs

Context: 9b88ce79f231136a41eca197e0fb154baa6a6a44
Context: 7fe3a11ac3a1c8a3cb47ec86d0daccdc79dfb61d
7fe3a11a fixed the new CRC64 calculation algorithm so that it properly
processes all the data, which had the (expected) effect of generating
the same checksums for the same data as those generated before 9b88ce79
However, 7fe3a11a missed changing the new `c64r2` hash prefix back to
`crc64`, thus this commit to make the change.
The change will remove any backward incompatibility with code that may
rely on the old hash format, including Xamarin.Android tests.

[crc64] Change the hash prefix back to `crc64`

---

Directory.Build.props
build-tools/Java.Interop.BootstrapTasks/Java.Interop.BootstrapTasks/JdkInfo.cs
tests/Xamarin.Android.Tools.Bytecode-Tests/IJavaInterfaceTests.cs
tests/Xamarin.Android.Tools.Bytecode-Tests/JavaAnnotationTests.cs
tests/Xamarin.Android.Tools.Bytecode-Tests/JavaEnumTests.cs
tests/Xamarin.Android.Tools.Bytecode-Tests/JavaType.1Tests.cs
tests/Xamarin.Android.Tools.Bytecode-Tests/JavaType.ASCTests.cs
tests/Xamarin.Android.Tools.Bytecode-Tests/JavaType.PSCTests.cs
tests/Xamarin.Android.Tools.Bytecode-Tests/JavaType.RNC.RPNCTests.cs
tests/Xamarin.Android.Tools.Bytecode-Tests/JavaType.RNCTests.cs
tests/Xamarin.Android.Tools.Bytecode-Tests/JavaTypeTests.cs
tests/Xamarin.Android.Tools.Bytecode-Tests/NonGenericGlobalTypeTests.cs

Context: https://issuetracker.google.com/issues/150189789
Context: https://github.com/xamarin/xamarin-android/pull/4562
Context: https://github.com/xamarin/xamarin-android/pull/4567
Bumps to xamarin/xamarin-android-tools/master@36d7fee5
Changes: https://github.com/xamarin/xamarin-android-tools/compare/bfb66f38b77421ac373c06a5f8407e1f9c793cc8...36d7fee5f7e0ef6ffa28970687db85b36947a3e6
* xamarin/xamarin-android-tools@36d7fee: JetBrains OpenJDK 11 detection (#82)
* xamarin/xamarin-android-tools@12f52ac: Merge pull request #80 from jonpryor/jonp-drop-net461
* xamarin/xamarin-android-tools@c7090d0: [Xamarin.Android.Tools.AndroidSdk] Remove net461
JDK 9 -- released 2017-July-27 -- introduced many new features, but
broke various Android SDK toolchain programs in various inscrutable
ways, so the …

[build] Support building with JetBrains OpenJDK 11

---

Java.Interop.sln

Context: https://github.com/xamarin/java.interop/pull/579
Let VS2019 update the project type guids for SDK-style projects.

[Java.Interop.sln] Commit updated automatically generated guids.

---

tests/generator-Tests/Integration-Tests/Compiler.cs
tests/generator-Tests/generator-Tests.csproj

`generator-Tests` contains a few hacks to get things building on Roslyn back when it was written.  It does this with a package from ASP.Net called [Microsoft.CodeDom.Providers.DotNetCompilerPlatform](https://www.nuget.org/packages/Microsoft.CodeDom.Providers.DotNetCompilerPlatform).
This package uses the MSBuild `CodeTaskFactory` which is not available on .NET Core.  Although it has recently been [fixed](https://github.com/aspnet/RoslynCodeDomProvider/issues/51), there hasn't been a new NuGet package in 1.5 years, so it is unknown when we can expect one.
Luckily we're not afraid to get our hands dirty!  We can reference the `Microsoft.CodeAnalysis.CSharp` package directly and accomplish the same thing for roughly the same amount of effort.
This new version will now build on .NET Core.

[generator-Tests] Run directly with Roslyn as DotNetCompilerPlatform doesn't work on .NET Core.

---

src/Java.Interop.Export/Java.Interop.Export.csproj
src/Java.Interop.Export/Java.Interop/MarshalMemberBuilder.cs
tests/Java.Interop.Export-Tests/Java.Interop/ExportTest.cs
tests/Java.Interop.Export-Tests/Java.Interop/MarshalMemberBuilderTest.cs
tests/Java.Interop.Export-Tests/java/com/xamarin/interop/export/ExportType.java
tools/jnimarshalmethod-gen/App.cs
tools/jnimarshalmethod-gen/Xamarin.Android.Tools.JniMarshalMethodGenerator.csproj

Context: https://github.com/xamarin/xamarin-android/pull/4631
Context: https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=3685184&view=logs&j=b1314ebb-4483-559c-0367-730fc62c4440&t=5022c07e-db44-5ce4-1a38-092215b61c50
Context: 70fc4c0771ca7f7ea346f221eca83fb109732a5d
Commit 70fc4c07 broke use of `jnimarshalmethod-gen.exe` within
xamarin-android and `Mono.Android.dll`, as it allows methods taking
more than 14 parameters to be bound, which results in
`jnimarshalmethod-gen.exe` trying to use an `Action<…>` or
`Func<…>` that takes more than 16 parameters, which isn't allowed:
EXEC : error : jnimarshalmethod-gen: Unable to process assembly '…/xamarin-android/bin/Release/lib/xamarin.android/xbuild-frameworks/MonoAndroid/v10.0/Mono.Android.dll'
An incorrect number of type arguments …

[Java.Interop.Export] Remove Action/Func use.

---

build-tools/automation/azure-pipelines.yaml
build-tools/scripts/PrepareWindows.targets

Creates a `Windows - .NET Core` lane for building and testing Java.Interop.  This builds and runs the same projects and tests as the current Windows build.
Also removed some unnecessary `nuget` work in `/t:Prepare` now that we no longer use `packages.config`.
The `Mac - .NET Core` lane requires more investigation and changes before it succeeds, and I need to focus on other priorities right now, so we'll just start with Windows.

[CI] Set up a .NET Core Windows lane.

---

tests/generator-Tests/Unit-Tests/XmlApiImporterTests.cs
tests/generator-Tests/Unit-Tests/XmlTests.cs
tools/generator/Java.Interop.Tools.Generator.Importers/XmlApiImporter.cs

Today, `generator` provides the ability to assign versions to each bound member that is exposed in its `Register` attribute `ApiSince` field, a la:
```
[Register ("android/view/inspector/IntFlagMapping", DoNotGenerateAcw=true, ApiSince=29)]
```
This is populated via the internal `apiversions=` option, which reads in a Google provided file containing the api version each member for appeared in.  Unfortunately we have found that Google's support of this file isn't guaranteed.  Sometimes it is missing, other times it changes randomly, causing `ApiCompat` breakage.
This PR provides an alternate way to set this `ApiSince` field in the `api.xml`.  The attribute `api-since` in now honored on `package`, `class/interface`, `method`, and `field` elements:
```
<field name='VERSION_CODE' …
```

[generator] Honor 'api-since' attribute to fill ApiAvailableSince property.

---

src/Java.Interop/Java.Interop/JavaArray.cs
src/Java.Interop/Java.Interop/JavaException.cs
src/Java.Interop/Java.Interop/JavaObject.cs
src/Java.Interop/Java.Interop/JavaPrimitiveArrays.cs
src/Java.Interop/Java.Interop/JavaProxyObject.cs
src/Java.Interop/Java.Interop/JniBuiltinMarshalers.cs
src/Java.Interop/Java.Interop/JniEnvironment.cs
src/Java.Interop/Java.Interop/JniObjectReference.cs
src/Java.Interop/Java.Interop/JniPeerMembers.JniInstanceFields.cs
src/Java.Interop/Java.Interop/JniPeerMembers.JniInstanceMethods.cs
src/Java.Interop/Java.Interop/JniPeerMembers.JniStaticFields.cs
src/Java.Interop/Java.Interop/JniPeerMembers.JniStaticMethods.cs
src/Java.Interop/Java.Interop/JniPeerMembers.cs
src/Java.Interop/Java.Interop/JniRuntime.JniMarshalMemberBuilder.cs
src/Java.Interop/Java.Interop/JniRuntime.JniTypeManager.cs
src/Java.Interop/Java.Interop/JniRuntime.JniValueManager.cs
src/Java.Interop/Java.Interop/JniRuntime.cs
src/Java.Interop/Java.Interop/JniTypeSignature.cs
src/Java.Interop/Java.Interop/JniTypeSignatureAttribute.cs
src/Java.Interop/Java.Interop/JniValueMarshaler.cs
src/Java.Interop/Java.Interop/ManagedPeer.cs
tools/jnimarshalmethod-gen/App.cs

- Fixes 43 NRT warnings.
- Fixes 1 `CS0168` warning: (`The variable 'e' is declared but never used`)
- Fixes 6 `CA1307` warnings introduced by targeting `netcoreapp3.1`. (`The behavior of 'string.IndexOf(char)' could vary based on the current user's locale settings.`)

[Java.Interop] Fix C# warnings.

---

tools/logcat-parse/logcat-parse.csproj

Note the assembly name changed from `Mono.Terminal.dll` to `LineEditor.dll` so we will likely need to update the installers when we bump JI.

[logcat-parse.csprj] Update to latest Mono.Terminal nuget with netstandard support.

---

tools/param-name-importer/param-name-importer.csproj

There is an issue with the new NuGet in that the `lib/netcoreapp3.1` directory contains both `SgmlReader.exe` and `SgmlReaderDll.dll` and the `netcoreapp3.1` version of `param-name-importer` tries to take the `.exe`.  
Worked around this by using the `<PackageReference>` to download the NuGet but not reference any assembly.  Then we add a `<Reference>` to the correct `.dll` and use it.  (We use `netstandard2.0` because both frameworks can use it, `netcoreapp3.1` shouldn't even exist in the package.)
Additionally added a `net4*` `Condition` to the reference to `System.IO.Compression` to fix this warning:
```
Warning MSB3243: No way to resolve conflict between "System.IO.Compression, Version=4.2.2.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" and "System.IO.Compression". Choosing …
```

[param-name-importer] Update to latest SgmlReader NuGet which supports netstandard2.0.

---

NuGet.Config
build-tools/automation/azure-pipelines.yaml
src/java-interop/java-interop.csproj
src/java-interop/java-interop.targets

Updates `java-interop.csproj` to SDK style.  This is a bit tricky because this is not a C# assembly, it is just hijacking a `.csproj` and overriding some targets to build a C lib.
It felt cleaner to go with a more "supported" version of doing this, so the project is built on [Microsoft.Build.NoTargets](https://github.com/microsoft/MSBuildSdks/tree/master/src/NoTargets) which is designed to run arbitrary commands without building an assembly.
Also switches to stable Mono.  Not sure if this is necessary but the more modern the `MSBuild` support when working with SDK style projects the better.
The automatic downloading of the `NoTargets` package didn't work with our `globalPackagesFolder` set to `$\..\packages`, so that was changed to `packages`, which is what XA uses and it works.
Ran a XA …

[java-interop] Update to SDK style project.

---

tests/generator-Tests/Unit-Tests/DefaultInterfaceMethodsTests.cs
tools/generator/Java.Interop.Tools.Generator.ObjectModel/GenBase.cs

Fixes #588 
If we cannot bind a method on an interface we mark the interface as unbindable and omit the interface from the generated code (and anything that depends on it).  This is because an interface with a missing method cannot be implemented in C#.
However if the method is `static` we can remove the method but still keep the interface, as the user is not required to implement the static method.  This PR makes this change to keep the interface.
Note we already properly handled DIM, this adds support for `static` methods as well.

[generator] Don't invalidate interface if we invalidate a static method on it.

---

src/utils/EnumMappings.Xml.cs
tests/generator-Tests/Unit-Tests/EnumMappingsTests.cs

Fixes #515.
Our CSV format for specifying enums supports creating enum fields that do not map to a JNI field.  This is often used to add a `None` enum field to a Java `[Flags]` enum:
```
0,,0,Android.AccessibilityServices.AccessibilityServiceCapabilities,None
```
However our XML format does not support this because it considers the `jni-class/jni-interface` and `jni-name` attributes mandatory when translating the XML format to CSV format.
We can lift this restriction and correctly generate the needed CSV format so that users using the XML format can add arbitrary enums that `generator` knows about.
So this is now supported:
```
<mapping clr-enum-type='Android.Support.V4.App.FragmentTagType' bitfield='true'>
<field clr-name='Name' value='0' />
<field clr-name='Id' value='1' />
<field …
```

[generator] Support XML defined enums with no JNI info.

---

tests/generator-Tests/Unit-Tests/DefaultInterfaceMethodsTests.cs
tools/generator/Java.Interop.Tools.Generator.ObjectModel/Method.cs

Fixes #661 
When we `[Register]` the invoker for a `default` method in a nested interface, we are using `.` to denote a nested interface, when it should be a `/`.
For example, in:
```
[Register ("onActivityPostCreated", "(Landroid/app/Activity;Landroid/os/Bundle;)V", "GetOnActivityPostCreated_Landroid_app_Activity_Landroid_os_Bundle_Handler:Android.App.Application.IActivityLifecycleCallbacks, Mono.Android, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null", ApiSince = 29)]
```
`Android.App.Application.IActivityLifecycleCallbacks` should be `Android.App.Application/IActivityLifecycleCallbacks`.
This is causing the nested type to not be found.
Fixed by using `AssemblyQualifiedName` instead of `FullName`, which is explicitly defined to support the correct notation.

[generator] Use proper syntax for nested classes for default interface method invokers.

---

tests/logcat-parse-Tests/Resources/logcat-get_class_ref.txt
tools/logcat-parse/Grefs.cs

Android 10 has changed it's `adb logcat` output to be more
"space delimited", e.g. instead of the previous `I/monodroid-gref(PID)`
seen previously, the ordering has changed and spaces delimit values:
06-15 14:29:08.206 31409 31409 I monodroid-gref: +g+ grefc 20 gwrefc 0 obj-handle 0x89/I -> new-handle 0x3bc6/G from thread '(null)'(1)
Update `Grefs.Prefix` so that it supports this new output format.

[logcat-parse] Support the Android 10 `logcat` format

---

tools/class-parse/Program.cs
tools/generator/CodeGeneratorOptions.cs
tools/jcw-gen/App.cs
tools/jnimarshalmethod-gen/App.cs
tools/logcat-parse/Program.cs
tools/param-name-importer/Program.cs

Fixes #664.
Context: https://github.com/mono/mono/commit/08fb9274e6b378b5edd333efcc1d6dfb04f912eb
Some utilities support *lots* of command-line options, which in turn
presents the *possibility* of having command-line lengths which are
"too long" for a given operating system, which on [Windows is 8KB][0].
[Response files][1] are a widely-supported "alternative"/"workaround":
instead of placing command-line options on the command-line, place
them into a *file*, which can contain command-line options.
A response file is a command-line option that starts with `@`,
followed by a filename:
$ echo " --help" > args.txt
$ mono bin/Debug/generator.exe @args.txt
[0]: https://support.microsoft.com/en-us/help/830473/command-prompt-cmd-exe-command-line-string-limitation
[1]: …

[tools] Add response file support

---

src/Java.Interop/Java.Interop-MonoAndroid.csproj

When building `Java.Interop-MonoAndroid.csproj` we currently get ~100 warnings of the form:
```
Java.Interop\JavaArray.cs(31,4): warning CS0436: The type 'MaybeNullAttribute' in 
'C:\A\vs2019xam00000Z-1\_work\1\s\external\Java.Interop\src\Java.Interop\NullableAttributes.cs' 
conflicts with the imported type 'MaybeNullAttribute' in 'mscorlib, Version=2.0.5.0, Culture=neutral, 
PublicKeyToken=7cec85d7bea7798e'. Using the type defined in 'C:\A\vs2019xam00000Z-1\_work
\1\s\external\Java.Interop\src\Java.Interop\NullableAttributes.cs'. [C:\A\vs2019xam00000Z-1\_work
\1\s\external\Java.Interop\src\Java.Interop\Java.Interop-MonoAndroid.csproj]
```
Exclude `Java.Interop\src\Java.Interop\NullableAttributes.cs` from our source files to eliminate the warnings.

[Java.Interop-MonoAndroid] Remove NullableAttributes.cs to prevent duplicate conflict warnings.

---

tests/generator-Tests/Unit-Tests/SealedProtectedFixupsTests.cs
tools/generator/Java.Interop.Tools.Generator.ObjectModel/GenBase.cs
tools/generator/Java.Interop.Tools.Generator.Transformation/SealedProtectedFixups.cs

In https://github.com/xamarin/java.interop/pull/569 we marked `protected` members in `sealed` classes as `private` to prevent `csc` warnings.  However we did not cover nested types which also cause this warning.
```
sealed class Foo
{
protected interface Bar
{
}
protected class Bar2
{
}
}
```
```
warning CS0628: 'Foo.Bar': new protected member declared in sealed class
warning CS0628: 'Foo.Bar2': new protected member declared in sealed class
```
`Mono.Android.dll` added 28 new protected interfaces in `sealed` classes `CalendarContract` and `ContactContract` which caused new warnings is our builds.
```
obj\Release\monoandroid10\android-30\mcw\Android.Provider.CalendarContract.cs(614,40): warning CS0628: 'CalendarContract.IAttendeesColumns': new protected member declared in sealed class …
```

[generator] Mark protected types nested in sealed classes as private.

---

tests/Java.Interop.Export-Tests/java/com/xamarin/interop/export/ExportType.java
tools/jnimarshalmethod-gen/App.cs
tools/jnimarshalmethod-gen/TypeMover.cs
tools/jnimarshalmethod-gen/Xamarin.Android.Tools.JniMarshalMethodGenerator.csproj

Commits 70fc4c07 and 857b9a94 introduced support for handling methods with 14 and more 
arguments. `jnimarshalmethod-gen` still needed update for handling these correctly and it is 
implemented here.
The IL improvements code was updated to know how to handle new custom delegates code from 
`System.Linq.Expression`.
The `_ALL_THE_ARGUMENTS` define was removed as it is no longer needed.
The test was updated to use the new `staticFuncThisMethodTakesLotsOfParameters` method.
Example generated code:
```
[JniAddNativeMethodRegistration]
public static void __RegisterNativeMembers (JniNativeMethodRegistrationArguments args)
{
args.AddRegistrations (new JniNativeMethodRegistration[11] {
new JniNativeMethodRegistration ("funcIJavaObject", "()Ljava/lang/Object;", new Func<IntPtr, IntPtr, IntPtr> …
```

[jnimarshalmethod-gen] support methods with 14+ arguments

---

build-tools/jnienv-gen/Generator.cs

When building `xamarin-android`, I noticed this always runs when there
are no changes:
Target Name=BuildJniEnvironment_g_cs Project=Java.Interop.csproj
Building target "BuildJniEnvironment_g_cs" completely.
Input file "C:\src\xamarin-android\external\Java.Interop\bin\BuildDebug\jnienv-gen.exe" is newer than output file "Java.Interop/JniEnvironment.g.cs".
...
Exec Task (345ms)
Reviewing the code in `jnienv-gen.exe`, it might not actually update
either of the `Outputs` if there are no changes.
So we can either:
1. Add a `<Touch/>` call in the `BuildJniEnvironment_g_cs` MSBuild
target.
2. Make `jnienv-gen.exe` always update the files.
I think we should just go with option 2, as it was basically doing:
if (!File.Exists (jnienv_g_cs) || !string.Equals (content, File.ReadAllText (jnienv_g_cs))) …

[build] fix BuildJniEnvironment_g_cs so it builds incrementally

---

src/Java.Runtime.Environment/Java.Interop/JreRuntime.cs
src/java-interop/java-interop-jvm.cc
src/java-interop/java-interop-jvm.h

Two problems were found via manual review of `java_interop_jvm_load()`:
1. If `path` is loaded but required symbols cannot be found, the
loaded library is never closed, which could be a resource leak.
2. If `path` *can't* be loaded, there's no easy way to determine
*why* it couldn't be loaded, because **dlerror**(3) isn't called.
Fix (1) by closing the loaded library before freeing `jvm`.
Fix (2) by renaming `java_interop_jvm_load()` to
`java_interop_jvm_load_with_error_message()`, which takes an
"optional" `char**` parameter which will hold the `dlerror()` output
if the library cannot be loaded:
const char *path = …;
char *error;
int status = java_interop_jvm_load_with_error_message (path, &error);
if (status != 0) {
fprintf (stderr, "Could not load `%s`: %s", path, error); …

[Java.Interop, java-interop] java_interop_jvm_load error handling

---

.github/workflows/release-notes.yml

Creates a GitHub action that automatically generates draft release notes from merged PR's that contain the label `release-notes`.
These release notes are placed on the wiki, along with instructions on how to include a PR and how to format the release note message.
https://github.com/xamarin/java.interop/wiki/Release-Notes
This action runs every morning at 06:00 UTC.  Once this workflow is committed to `master`, it should also be available to be run manually via the Actions tab: https://github.blog/changelog/2020-07-06-github-actions-manual-triggers-with-workflow_dispatch/.
PR scanning and release notes generation code is external to this repository, available here: https://github.com/jpobst/noted.

[Actions] Use GitHub actions to automatically generate release notes

---

src/Java.Interop/Java.Interop/JniRuntime.JniValueManager.cs
tests/Java.Interop-Tests/Java.Interop/JavaObjectTest.cs

Context: https://github.com/xamarin/xamarin-android/issues/4989
What happens if you dispose an instance *while disposing the instance*?
// C#
public class MyDisposableObject : JavaObject {
bool _isDisposed;
protected override void Dispose (bool disposing)
{
if (_isDisposed) {
return;
}
_isDisposed = true;
if (this.PeerReference.IsValid)
this.Dispose ();
base.Dispose (disposing);
}
}
// …
void MyTestMethod ()
{
var value = new MyDisposableObject ();
value.Dispose ();
value.Dispose ();
}
Here, `MyDisposableObject.Dispose(bool)` calls `JavaObject.Dispose()`
when `PeerReference` is valid.  This "feels" admittedly unusual, but
`IDisposable.Dispose()` is *supposed to be* Idempotent: it can be
called multiple times with no ill effects.  Shouldn't this be the same?
Unfortunately, it *isn't* the …

[Java.Interop] Avoid double-disposing PeerReferences

---

src/Java.Interop/Properties/AssemblyInfo.cs
src/Java.Runtime.Environment/Properties/AssemblyInfo.cs
src/java-interop/java-interop-dlfcn.cc
src/java-interop/java-interop-dlfcn.h
src/java-interop/java-interop-gc-bridge-mono.cc
src/java-interop/java-interop-gc-bridge.h
src/java-interop/java-interop-jvm.cc
src/java-interop/java-interop-jvm.h
src/java-interop/java-interop-mono.h
src/java-interop/java-interop-util.h
src/java-interop/java-interop.csproj
src/java-interop/java-interop.h
src/java-interop/java-interop.targets

Fixes: https://github.com/xamarin/java.interop/issues/676
Context: https://liquid.microsoft.com/Web/Object/Read/ms.security/Requirements/Microsoft.Security.SystemsADM.10039#guide
The current security guidance is that the
[`System.Runtime.InteropServices.DefaultDllImportSearchPathsAttribute`][0]
attribute should be placed either on the assembly or on `[DllImport]`
methods to control and constrain where [`LoadLibraryEx()`][1] will look
for native libraries, in particular to *prevent* looking for native
libraries within e.g. the current working directory or `%PATH%` or any
other "attacker-controlled" location.
Update `Java.Interop.dll` and `Java.Runtime.Environment.dll` so that
the [`DllImportSearchPath`][2] values `AssemblyDirectory` and
`SafeDirectories` are used:
* `AssemblyDirectory`: …

[java-interop, Java.Interop] Securely load native libs

---

src/Java.Interop.Localization/Resources.Designer.cs
src/Java.Interop.Localization/Resources.resx
src/Java.Interop.Localization/xlf/Resources.cs.xlf
src/Java.Interop.Localization/xlf/Resources.de.xlf
src/Java.Interop.Localization/xlf/Resources.es.xlf
src/Java.Interop.Localization/xlf/Resources.fr.xlf
src/Java.Interop.Localization/xlf/Resources.it.xlf
src/Java.Interop.Localization/xlf/Resources.ja.xlf
src/Java.Interop.Localization/xlf/Resources.ko.xlf
src/Java.Interop.Localization/xlf/Resources.pl.xlf
src/Java.Interop.Localization/xlf/Resources.pt-BR.xlf
src/Java.Interop.Localization/xlf/Resources.ru.xlf
src/Java.Interop.Localization/xlf/Resources.tr.xlf
src/Java.Interop.Localization/xlf/Resources.zh-Hans.xlf
src/Java.Interop.Localization/xlf/Resources.zh-Hant.xlf
src/Java.Interop.Tools.Cecil/Java.Interop.Tools.Cecil.csproj
src/Java.Interop.Tools.Cecil/Java.Interop.Tools.Cecil/DirectoryAssemblyResolver.cs
src/Java.Interop.Tools.JavaCallableWrappers/Java.Interop.Tools.JavaCallableWrappers.csproj
src/Java.Interop.Tools.JavaCallableWrappers/Java.Interop.Tools.JavaCallableWrappers/JavaCallableWrapperGenerator.cs

Updates MSBuild warnings and errors in  `Java.Interop.Tools.JavaCallableWrappers` and `Java.Interop.Tools.Cecil` to be localizable, building on work done in https://github.com/xamarin/java.interop/pull/689.

[jcw-gen] Make MSBuild warning/error strings localizable.

---

tests/generator-Tests/Unit-Tests/CodeGeneratorTests.cs
tools/generator/Java.Interop.Tools.Generator.Importers/XmlApiImporter.cs
tools/generator/Java.Interop.Tools.Generator.ObjectModel/Method.cs
tools/generator/SourceWriters/BoundMethod.cs
tools/generator/SourceWriters/BoundProperty.cs

Fixes: #681 
There are scenarios where `generator` does not correctly find overridden methods, often due to generic parameters.  When these issues happen, the fix is to `<remove-node>` the offending method and add a fully hand-bound version of it as an `Addition`.  This is a very manual fix to simply add `override` to a method.
While we would like to eventually fix all these scenarios to "do the right thing", that will be a complex fix(es), and perhaps we will never be able to handle all cases.
For now, we can at least alleviate the pain by adding a `metadata` attribute that allows the user to override our detection, avoiding the hand-binding.
This new attribute is called `managedOverride` and allows the user to specify the values `virtual` or `override`, forcing us to use the requested …

[generator] Add 'managedOverride' metadata to allow user to force 'override'/'virtual'.

---

tools/generator/CodeGeneratorContext.cs
tools/generator/Java.Interop.Tools.Generator.ObjectModel/Field.cs
tools/generator/Java.Interop.Tools.Generator.ObjectModel/GenericParameterDefinition.cs
tools/generator/Java.Interop.Tools.Generator.ObjectModel/Parameter.cs
tools/generator/Java.Interop.Tools.Generator.ObjectModel/ReturnValue.cs

In #689 we made `generator` localizable.  One of the changes was this pattern:
```
- Report.Warning (0, Report.WarningReturnValue + 0, "Unknown return type {0} {1}.", java_type, context.ContextString);
+ Report.LogCodedWarning (0, Report.WarningUnknownReturnType, java_type, context.ContextString);
where:
Report.WarningUnexpectedFieldType = "Unknown return type '{0}' for member '{1}'."
```
However `context.ContextString` generates a hard to localize string like:
```
in method CreateFromXml in managed type Android.Content.Res.ColorStateList
```
resulting in warnings like this:
```
warning BG8800: Unknown return type 'System.Xml.XmlReader' for member 'in method CreateFromXml in managed type Android.Content.Res.ColorStateList'.
```
Instead, create a `context.ContextTypeMember` method that …

[generator] Fix localization error.

---

src/java-interop/java-interop-gc-bridge-mono.cc
src/java-interop/java-interop-util.cc

When Java.Interop is built with GCC (e.g. on Linux or with MinGW), the
flags Xamarin.Android passes to the compiler cause a handful of warnings
to be shown regarding incomplete field assignment when initializing
structure instances:
java-interop-gc-bridge-mono.cc:259:33: warning: missing initializer for member ‘JavaInteropGCBridge::BridgeProcessing_type’ [-Wmissing-field-initializers]
259 |  JavaInteropGCBridge bridge = {0};
|                                 ^
java-interop-gc-bridge-mono.cc:259:33: warning: missing initializer for member ‘JavaInteropGCBridge::BridgeProcessing_field’ [-Wmissing-field-initializers]
java-interop-gc-bridge-mono.cc:259:33: warning: missing initializer for member ‘JavaInteropGCBridge::BridgeProcessing_vtables_count’ [-Wmissing-field-initializers] …

[C++] Get rid of compiler warnings

---

src/Java.Interop.Localization/Resources.Designer.cs
src/Java.Interop.Localization/Resources.resx
src/Java.Interop.Localization/xlf/Resources.cs.xlf
src/Java.Interop.Localization/xlf/Resources.de.xlf
src/Java.Interop.Localization/xlf/Resources.es.xlf
src/Java.Interop.Localization/xlf/Resources.fr.xlf
src/Java.Interop.Localization/xlf/Resources.it.xlf
src/Java.Interop.Localization/xlf/Resources.ja.xlf
src/Java.Interop.Localization/xlf/Resources.ko.xlf
src/Java.Interop.Localization/xlf/Resources.pl.xlf
src/Java.Interop.Localization/xlf/Resources.pt-BR.xlf
src/Java.Interop.Localization/xlf/Resources.ru.xlf
src/Java.Interop.Localization/xlf/Resources.tr.xlf
src/Java.Interop.Localization/xlf/Resources.zh-Hans.xlf
src/Java.Interop.Localization/xlf/Resources.zh-Hant.xlf
tools/jnimarshalmethod-gen/App.cs
tools/jnimarshalmethod-gen/Message.cs
tools/jnimarshalmethod-gen/TypeMover.cs
tools/jnimarshalmethod-gen/Xamarin.Android.Tools.JniMarshalMethodGenerator.csproj

and warnings messages. Uses the same `Java.Interop.Localization` assembly
as other JI tools use for localizable text.
Change some of the warnings into informational output and also extend
some of the warnings with more information how to possibly avoid
the warning.

[jnimarshalmethod-gen] Localizable errors

---

src/Java.Interop/Java.Interop/JniRuntime.JniValueManager.cs
tests/Java.Interop-Tests/Java.Interop-Tests.csproj
tests/Java.Interop-Tests/Java.Interop/GetThis.cs
tests/Java.Interop-Tests/Java.Interop/JavaObjectTest.cs
tests/Java.Interop-Tests/java/com/xamarin/interop/GetThis.java

Fixes: https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1193891
A bug was found in Xamarin.Android 11.1.0.2, candidate for
Visual Studio 16.8 Preview 3:
1. Create a new "Shell Forms App"
2. Build & Run the app
3. Tap the "Browse" button.
Expected results: it works!
Actual results: A rather abrupt crash:
System.NotSupportedException: Unable to activate instance of type Xamarin.Forms.Platform.Android.PageRenderer from native handle 0x69 (key_handle 0x33efaa1). ---> System.MissingMethodException: No constructor found for Xamarin.Forms.Platform.Android.PageRenderer::.ctor(System.IntPtr, Android.Runtime.JniHandleOwnership) ---> Java.Interop.JavaLocationException: Exception of type 'Java.Interop.JavaLocationException' was thrown.
--- End of inner exception stack trace …

[Java.Interop] Dispose, *then* Remove

---

tools/java-source-utils/Directory.Build.targets

Context: https://github.com/xamarin/xamarin-android/pull/5044#issuecomment-683131462
Context: https://docs.microsoft.com/visualstudio/msbuild/exec-task
An env var can break the build such as running the following powershell:
> $env:FOO="`nFoo.cs(123,1) error: oh dear!"
A `\n` new line in the string is required to hit an issue.
This results in a confusing build error:
(_BuildJava target) ->
EXEC : Foo.cs(123,1) error : oh dear!
`gradlew -d` emits every environment variable, and if there is a line
that looks like an MSBuild error it will emit the error. We can set
`IgnoreStandardErrorWarningFormat="true"` to disable this behavior.
This could commonly happen on CI systems, if a commit message contains
an error message.
In the case of Azure DevOps, `%BUILD_SOURCEVERSIONMESSAGE%` will
contain …

[build] fix env vars causing gradle build error

---

tools/jnimarshalmethod-gen/TypeMover.cs

The TypeMover was crashing, when we cannot resolve the type during
register method optimization.
Like this:
Value cannot be null.
Parameter name: key
System.ArgumentNullException: Value cannot be null.
Parameter name: key
at System.Collections.Generic.Dictionary`2[TKey,TValue].FindEntry (TKey key) [0x00175] in /Users/builder/jenkins/workspace/archive-mono/2020-02/android/debug/external/corefx/src/Common/src/CoreLib/System/Collections/Generic/Dictionary.cs:470
at System.Collections.Generic.Dictionary`2[TKey,TValue].ContainsKey (TKey key) [0x00000] in /Users/builder/jenkins/workspace/archive-mono/2020-02/android/debug/external/corefx/src/Common/src/CoreLib/System/Collections/Generic/Dictionary.cs:286
at Xamarin.Android.Tools.JniMarshalMethodGenerator.TypeMover.Resolve …

[jnimarshalmethod-gen] Fix type resolution crash

---

build-tools/automation/azure-pipelines.yaml

Use the "paths" feature of CI triggers to prevent running CI for PRs that only contain "Documentation" changes.
https://docs.microsoft.com/en-us/azure/devops/pipelines/repos/github?view=azure-devops&tabs=yaml#paths
I wasn't able to verify that this works.  It's possible that it needs to already be on the default branch in order to take effect.  It shouldn't hurt to merge it and then test.

[ci] Don't kick off CI for documentation only changes.

---

tests/generator-Tests/Unit-Tests/XmlApiImporterTests.cs
tools/generator/CodeGenerationOptions.cs
tools/generator/CodeGenerator.cs
tools/generator/Java.Interop.Tools.Generator.CodeGeneration/CodeGenerator.cs
tools/generator/Java.Interop.Tools.Generator.Importers/XmlApiImporter.cs
tools/generator/Java.Interop.Tools.Generator.ObjectModel/ClassGen.cs
tools/generator/Java.Interop.Tools.Generator.ObjectModel/Field.cs
tools/generator/Java.Interop.Tools.Generator.ObjectModel/GenBase.cs
tools/generator/Java.Interop.Tools.Generator.ObjectModel/ISourceLineInfo.cs
tools/generator/Java.Interop.Tools.Generator.ObjectModel/InterfaceGen.cs
tools/generator/Java.Interop.Tools.Generator.ObjectModel/MethodBase.cs
tools/generator/Java.Interop.Tools.Generator.ObjectModel/Parameter.cs
tools/generator/Java.Interop.Tools.Generator.ObjectModel/ReturnValue.cs
tools/generator/SourceWriters/Extensions/SourceWriterExtensions.cs
tools/generator/SourceWriters/InterfaceMemberAlternativeClass.cs
tools/generator/Utilities/Report.cs
tools/generator/generator.slnf

Today, when you get a warning while trying to bind an `api.xml` file, no source information is provided:
```
BINDINGSGENERATOR : warning BG8700: Unknown return type 'com.blah.a.a.a.a' for member 
'Com.Blah.Foo.Sdk.LoggerGetUserLogger ()'. [C:\code\temp\Blah\Blah.csproj]
```
We can make the user experience a tiny bit nicer by adding the file name and line/col information in standard MSBuild format.  This allows users to double click the error in VS and be taken directly to the correct location in the `api.xml` file:
```
BINDINGSGENERATOR : obj\Debug\api.xml(1684, 8) warning BG8700: Unknown return type 'com.blah.a.a.a.a' 
for member 'Com.Blah.Foo.Sdk.LoggerGetUserLogger ()'. [C:\code\temp\Blah\Blah.csproj]
```

[generator] Provide line/col numbers for api.xml warnings.

---

src/Java.Interop/Java.Interop-MonoAndroid.csproj
src/Java.Interop/Java.Interop.csproj

Context: https://github.com/xamarin/xamarin-android/pull/5119
The `Microsoft.Android.Ref` package for .NET 6 needs to contain
reference assemblies for each assembly we ship.
`Java.Interop.dll` is one of these, so we need to set
`$(ProduceReferenceAssembly)` to generate a reference assembly
automatically.
Size difference:
Length Name
------ ----
227328 Java.Interop.dll
94208 ref/Java.Interop.dll

[build] build reference assembly for Java.Interop.dll

---

src/Xamarin.Android.Tools.ApiXmlAdjuster/JavaApiTypeResolverExtensions.cs
tests/Xamarin.Android.Tools.ApiXmlAdjuster-Tests/JavaApiTestHelper.cs
tests/Xamarin.Android.Tools.ApiXmlAdjuster-Tests/TypeResolverTest.cs

Fixes: #717 
A long time ago, we moved our managed binding of `android.app.IntentService` to `mono.android.app.IntentService`.  When a user switches from `jar2xml` to `class-parse` and tries to reference this type it cannot be found because type resolution is now done in C# rather than Java.
We likely can't move the type back due to backwards compatibility issues, so we modify our type resolver to specially case this type and know where it moved to.

[ApiXmlAdjuster] Fix for finding "mono.app.android.IntentService".

---

tools/jnimarshalmethod-gen/App.cs

This is part of making the tool to work on Windows and later also with
NET5. The created `AppDomain` was used to isolate processed assembly,
so that we can unload it and overwrite it with generated changes.
That didn't work on Windows even with .NET framework, which has
the `AppDomain`s API. In NET5 the creation of AppDomains is not even
part of the API.
So instead of using the created `AppDomain`s, we preload the assembly
in memory and load it from there.

[jnimarshalmethod-gen] Avoid creating AppDomains

---

tools/jnimarshalmethod-gen/App.cs

Set parameters to registration method builder, to get rid of exception
we are getting on Windows. Looks like the S.L.E code still differs
between Windows and Mac.
Also report adding registration methods in verbose mode, similar as we
do with marshal methods.
The `ArgumentOutOfRangeException` mentined above:
error JM4006: jnimarshalmethod-gen: Unable to process assembly '.\bin\TestDebug\Java.Interop.Export-Tests.dll'
Specified argument was out of the range of valid values.
Parameter name: The specified parameter index is not in range.
System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
Parameter name: The specified parameter index is not in range.
at System.Reflection.Emit.MethodBuilder.DefineParameter(Int32 position, ParameterAttributes attributes, …

[jnimarshalmethod-gen] Fix registration on Windows

---

tests/generator-Tests/Unit-Tests/CodeGeneratorExpectedResults/JavaInterop1/WriteKotlinUnsignedArrayTypeMethodsClass.txt
tests/generator-Tests/Unit-Tests/CodeGeneratorExpectedResults/JavaInterop1/WriteKotlinUnsignedArrayTypePropertiesClass.txt
tests/generator-Tests/expected.ji/Adapters/Xamarin.Test.AbsSpinner.cs
tests/generator-Tests/expected.ji/Adapters/Xamarin.Test.AdapterView.cs
tests/generator-Tests/expected.ji/Core_Jar2Xml/Android.Text.SpannableString.cs
tests/generator-Tests/expected.ji/Core_Jar2Xml/Android.Text.SpannableStringInternal.cs
tests/generator-Tests/expected.ji/Core_Jar2Xml/Android.Views.View.cs
tests/generator-Tests/expected.ji/GenericArguments/Com.Google.Android.Exoplayer.Drm.FrameworkMediaDrm.cs
tests/generator-Tests/expected.ji/NestedTypes/Xamarin.Test.NotificationCompatBase.cs
tests/generator-Tests/expected.ji/NormalMethods/Xamarin.Test.SomeObject.cs
tests/generator-Tests/expected.ji/NormalProperties/Xamarin.Test.SomeObject.cs
tests/generator-Tests/expected.ji/ParameterXPath/Xamarin.Test.A.cs
tests/generator-Tests/expected.ji/StaticProperties/Xamarin.Test.SomeObject.cs
tests/generator-Tests/expected.ji/Streams/Java.IO.FilterOutputStream.cs
tests/generator-Tests/expected.ji/Streams/Java.IO.InputStream.cs
tests/generator-Tests/expected.ji/Streams/Java.IO.OutputStream.cs
tests/generator-Tests/expected.ji/TestInterface/Test.ME.GenericImplementation.cs
tests/generator-Tests/expected.ji/TestInterface/Test.ME.GenericObjectPropertyImplementation.cs
tests/generator-Tests/expected.ji/TestInterface/Test.ME.GenericStringImplementation.cs
tests/generator-Tests/expected.ji/TestInterface/Test.ME.TestInterfaceImplementation.cs
tests/generator-Tests/expected.ji/java.lang.Enum/Java.Lang.Enum.cs
tools/generator/Java.Interop.Tools.Generator.ObjectModel/Parameter.cs
tools/generator/SourceWriters/BoundConstructor.cs
tools/generator/SourceWriters/Extensions/SourceWriterExtensions.cs

Fixes: #719
Under certain circumstances, it is possible for a method parameter to get GC collected before native code is finished using it.  Add an appropriate `GC.KeepAlive (param)` to ensure the object stays alive until we are done with it.  As an optimization, this is only needed for reference types.

[generator] Use GC.KeepAlive for reference type method parameters.

---

src/Xamarin.SourceWriter/Models/PropertyWriter.cs
tests/generator-Tests/Unit-Tests/CodeGeneratorExpectedResults/Common/WriteDuplicateInterfaceEventArgs.txt
tests/generator-Tests/Unit-Tests/CodeGeneratorTests.cs
tests/generator-Tests/expected.ji/GenericArguments/Com.Google.Android.Exoplayer.Drm.IExoMediaDrm.cs
tools/generator/SourceWriters/BoundInterface.cs
tools/generator/SourceWriters/BoundMethod.cs
tools/generator/SourceWriters/InterfaceEventArgsClass.cs

Fixes: #461 
Given this listener interface:
```
interface AnimatorListener {
void onAnimationEnd (int param1);
void onAnimationEnd (int param1, int param2);
}
```
Today we will generate 2 `partial` `AnimationEndEventArgs` classes:
```
// event args for java.code.AnimatorListener.onAnimationEnd
public partial class AnimationEndEventArgs : global::System.EventArgs {
public AnimationEndEventArgs (int param1)
{
this.param1 = param1;
}
int param1;
public int Param1 {
get { return param1; }
}
}
// event args for java.code.AnimatorListener.onAnimationEnd
public partial class AnimationEndEventArgs : global::System.EventArgs {
public AnimationEndEventArgs (int param1, int param2)
{
this.param1 = param1;
this.param2 = param2;
}
int param1;
public int Param1 {
get { return param1; }
}
int param2; …
```

[generator] Prevent generating duplicate EventArgs classes.

---

tests/generator-Tests/Unit-Tests/CodeGenerationOptionsTests.cs
tools/generator/CodeGenerationOptions.cs
tools/generator/Utilities/ParsedType.cs

Fixes: #728 
In order to prevent namespace clashes we always write non-intrinsic types prefixed with `global::`.
For example:
```
System.Collections.Generic.List<Java.Lang.Object>
```
becomes
```
global::System.Collections.Generic.List<global::Java.Lang.Object>
```
To do this, we have to parse a type into its component types so we can add `global::` to each part.  However our parsing algorithm struggles with generic types with multiple type arguments.  
Thus:
```
System.Collections.Generic.IDictionary<System.Collections.Generic.IList<string>, Kotlin.Pair>
```
becomes
```
global::System.Collections.Generic.IDictionary<global::System.Collections.Generic.IList<string>>
```
and
```
System.Collections.Generic.IDictionary<System.Collections.Generic.IList<string>, …
```

[generator] Fix invalid parsing of complex generic types.

---

src/Java.Interop/Java.Interop.csproj
tools/logcat-parse/logcat-parse.csproj

Suppress some NuGet warnings:
**logcat-parse.csproj**
```
Warning NU1701: Package 'Mono.CSharp 4.0.0.143' was restored using '.NETFramework,Version=v4.6.1, 
.NETFramework,Version=v4.6.2, .NETFramework,Version=v4.7, .NETFramework,Version=v4.7.1, 
.NETFramework,Version=v4.7.2, .NETFramework,Version=v4.8' instead of the project target framework 
'.NETCoreApp,Version=v3.1'. This package may not be fully compatible with your project.
```
**Java.Interop.csproj**
```
Warning NU1702: ProjectReference 'D:\a\1\s\build-tools\jnienv-gen\jnienv-gen.csproj' was resolved using 
'.NETFramework,Version=v4.7.2' instead of the project target framework '.NETStandard,Version=v2.0'. 
This project may not be fully compatible with your project.
```

[build] Suppress NuGet warnings

---

tests/generator-Tests/Unit-Tests/CodeGeneratorExpectedResults/Common/WriteDuplicateInterfaceEventArgs.txt
tests/generator-Tests/expected.ji/GenericArguments/Com.Google.Android.Exoplayer.Drm.IExoMediaDrm.cs
tools/generator/SourceWriters/InterfaceEventArgsClass.cs

In https://github.com/xamarin/java.interop/pull/726, properties in generated EventArgs classes were changed from regular properties to use auto-properties:
From:
```
int param1;
public int Param1 {
get { return param1; }
}
```
To:
```
public int Param1 { get; }
```
However this is technically a breaking change, since users could have hand written code that references the backing field.  Although the usage is likely rare, we have decided to revert the auto-property change for compatibility reasons.

[generator] Revert change to use auto-properties in EventArgs classes.

---

tests/generator-Tests/Unit-Tests/CodeGeneratorContextTests.cs
tools/generator/CodeGeneratorContext.cs

In https://github.com/xamarin/java.interop/commit/d664e90ecf0ed1a08a61acc7708215e678255e95 we refactored some output regarding binding warning messages in order to better support localization.  Unfortunately this refactoring left out a period between some type and member names:
```
warning BG8700: Unknown return type 'Android.App.Admin.AppOpsManagerMode' for member 'Android.App.AppOpsManagerUnsafeCheckOp (java.lang.String, int, java.lang.String)'. 
```
`Android.App.AppOpsManagerUnsafeCheckOp` should be `Android.App.AppOpsManager.UnsafeCheckOp` instead.

[generator] Output correct formatting for binding warnings.

---

tools/logcat-parse/Directory.Build.targets
tools/logcat-parse/logcat-parse.csproj

Context: https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1230070
Changes: https://github.com/mono/LineEditor/compare/5a7e3e24730e5392e2c37eddea3f0833bab5d18f...3fa0c2eb46b79b958a028b063d295a304cdb4842
* mono/LineEditor@3fa0c2e: Fix NuGet publishing errors (#9)
* mono/LineEditor@06a4ddf: Bump `$(PackageVersion)` to 5.4.1.
* mono/LineEditor@bce1b7f: Enable .pdb files for Release config & add AzDO build script (#8)
* mono/LineEditor@4831e1a: Merge pull request #6 from terrajobst/code-of-conduct
* mono/LineEditor@5b4a4aa: Link Code of Conduct
* mono/LineEditor@410ca3d: Merge pull request #2 from VEIT-Electronics/master
* mono/LineEditor@3d802e7: Merge pull request #1 from VEIT-Electronics/bugfix/ENG-232-line-editor-completions
* mono/LineEditor@0d43552: fix: text overriding was only …

Bump to mono/LineEditor/v5.4.1@3fa0c2eb

---

tools/java-source-utils/src/main/java/com/microsoft/android/JavaSourceUtilsOptions.java
tools/java-source-utils/src/test/java/com/microsoft/android/JavaSourceUtilsOptionsTest.java

Add support for ["response files"][0] to `java-source-utils.jar`,
allowing `java-source-utils.jar` options to be present within a plain-
text file, and the file provided as an option:
$ cat >response-file <<EOF
--help
EOF
$ java -jar java-source-utils.jar @response-file
In this case, the "scare quotes" is because of limitations when
parsing the response file: only one value per line.  Blank lines are
ignored, as are lines starting with `#`.
Thus, a response file with contents:
--source
/path/to/source/directory
is fine, while a response file with the contents:
--source /path/to/source/directory
will not be parsed properly.
[0]: https://docs.microsoft.com/en-us/windows/win32/midl/response-files

[java-source-utils] Add response file support

---

src/Java.Interop.Tools.JavaSource/Java.Interop.Tools.JavaSource.csproj
src/Java.Interop.Tools.JavaSource/Java.Interop.Tools.JavaSource/JavaStubParser.cs
src/Xamarin.Android.Tools.ApiXmlAdjuster/JavaApi.RelationAnalysisModel.cs
src/Xamarin.Android.Tools.ApiXmlAdjuster/JavaApi.XmlModel.cs
src/Xamarin.Android.Tools.ApiXmlAdjuster/JavaApiDefectFinderExtensions.cs
src/Xamarin.Android.Tools.ApiXmlAdjuster/JavaApiFixVisibilityExtensions.cs
src/Xamarin.Android.Tools.ApiXmlAdjuster/JavaApiGeneralExtensions.cs
src/Xamarin.Android.Tools.ApiXmlAdjuster/JavaApiGenericInheritanceMapperExtensions.cs
src/Xamarin.Android.Tools.ApiXmlAdjuster/JavaApiNonBindableStripper.cs
src/Xamarin.Android.Tools.ApiXmlAdjuster/JavaApiOverrideMarkerExtensions.cs
src/Xamarin.Android.Tools.ApiXmlAdjuster/JavaApiTypeResolverExtensions.cs
src/Xamarin.Android.Tools.ApiXmlAdjuster/JavaApiXmlGeneratorExtensions.cs
src/Xamarin.Android.Tools.ApiXmlAdjuster/JavaTypeName.cs
src/Xamarin.Android.Tools.ApiXmlAdjuster/JavaTypeReference.cs
src/Xamarin.Android.Tools.ApiXmlAdjuster/JavaTypeResolutionUtil.cs
src/Xamarin.Android.Tools.ApiXmlAdjuster/Log.cs
src/Xamarin.Android.Tools.ApiXmlAdjuster/Xamarin.Android.Tools.ApiXmlAdjuster.csproj
src/Xamarin.Android.Tools.ApiXmlAdjuster/XmlUtil.cs

Update `Java.Interop.Tools.JavaSource.dll` and
`Xamarin.Android.Tools.ApiXmlAdjuster.dll` so that C# 8
[Nullable Reference Types][0] are used.
[0]: https://docs.microsoft.com/dotnet/csharp/nullable-references

[.JavaSource, .ApiXmlAdjuster] Use Nullable Reference Types

---

src/Java.Interop.Tools.JavaCallableWrappers/Java.Interop.Tools.JavaCallableWrappers/JavaCallableWrapperGenerator.cs
tests/Java.Interop.Tools.JavaCallableWrappers-Tests/Java.Interop.Tools.JavaCallableWrappers/JavaCallableWrapperGeneratorTests.cs
tests/Java.Interop.Tools.JavaCallableWrappers-Tests/Java.Interop.Tools.JavaCallableWrappers/SupportDeclarations.cs

Context: https://github.com/xamarin/xamarin-android/issues/5251
When an Java interface contains a `static` method in API-30+, we use C# 8.0's new support for these methods to place them directly on the interface.  When a C# class implements the interface, the Java Callable Wrapper we generate will register every method on the interface during startup.  However, static methods are not `virtual` and cannot be overridden, so they do not have a connector and do not need to be registered.
This results in a case where the register command fails because no connector is specified (nothing after the final colon).
```
__md_methods = "n_comparing:(Ljava/util/function/Function;)Ljava/util/Comparator;:\n" +
...
```
To fix this, when adding methods from implemented interfaces we need to skip `static` …

[jcw-gen] Do not register static methods on an interface.

---

src/Java.Interop/Directory.Build.targets

We have some "clever" code that attempts to determine if it needs to add `Java.Interop/JniEnvironment.g.cs` to our compile items, since it may already be there because of file globs, if this isn't a clean run.  However this code no longer seems to work under MSBuild 16.8.  `$(_AddCompile)` remains `False` and thus the file isn't getting added to the compile on first run.
Instead we're going to use `KeepDuplicates='false'` to do the de-duping for us.
The wrinkle is that this file is added as `Java.Interop/JniEnvironment.g.cs` or `Java.Interop\JniEnvironment.g.cs` depending on OS, so we need to use `Path.Combine` to ensure our added file matches the copy from the glob, so the de-dupe will work.
Without any de-duping, the build produces a `CS2002: Source file 'JniEnvironment.g.cs' specified …

[build] Fix for MSBuild 16.8.

---

src/Java.Interop.Tools.JavaSource/Java.Interop.Tools.JavaSource/JavaStubParser.cs
src/Xamarin.Android.Tools.ApiXmlAdjuster/JavaApi.XmlModel.cs
src/Xamarin.Android.Tools.ApiXmlAdjuster/JavaApiDefectFinderExtensions.cs
src/Xamarin.Android.Tools.ApiXmlAdjuster/JavaApiGenericInheritanceMapperExtensions.cs
src/Xamarin.Android.Tools.ApiXmlAdjuster/JavaApiNonBindableStripper.cs
src/Xamarin.Android.Tools.ApiXmlAdjuster/JavaApiOverrideMarkerExtensions.cs
src/Xamarin.Android.Tools.ApiXmlAdjuster/JavaApiTypeResolverExtensions.cs
src/Xamarin.Android.Tools.ApiXmlAdjuster/JavaApiXmlGeneratorExtensions.cs
src/Xamarin.Android.Tools.ApiXmlAdjuster/JavaApiXmlLoaderExtensions.cs
tests/Java.Interop.Tools.JavaSource-Tests/JavaStubParserTests.cs
tests/Xamarin.Android.Tools.ApiXmlAdjuster-Tests/JavaApiTest.cs
tests/Xamarin.Android.Tools.ApiXmlAdjuster-Tests/OverrideMarkerTest.cs
tests/Xamarin.Android.Tools.ApiXmlAdjuster-Tests/TypeResolverTest.cs
tools/generator/Extensions/JavaApiDllLoaderExtensions.cs
tools/param-name-importer/DroidDocImporter.cs
tools/param-name-importer/JavaApiParameterNamesExporter.cs
tools/param-name-importer/JavaStubSourceImporter.cs

Today, our ApiXmlAdjuster process builds an in-memory model of every Java type we know about, and then queries this model many times in order to ensure we can resolve every needed Java type to build a binding.  The data structure of this model is:
```
public class JavaApi
{
public List<JavaPackage> Packages { get; }
}
public class JavaPackage
{
public List<JavaType> Types { get; }
}
```
Then it is queried using LINQ like this:
```
// Bad
var type = api.Packages.SelectMany (p => p.Types).FirstOrDefault (t => t.Name == type_name);
// Less bad
var type = api.Packages.FirstOrDefault (p => p.Name == pkg_name)?.Types.FirstOrDefault (t => t.Name == type_name);
```
In the random GPS package I used for testing, `JavaApi` contained 310 packages and a total of 5941 types.  Repeatedly looping through …

[ApiXmlAdjuster] Use different data model structures for better performance

---

tools/java-source-utils/build.gradle
tools/java-source-utils/src/main/java/com/microsoft/android/JniPackagesInfoFactory.java
tools/java-source-utils/src/test/java/com/microsoft/android/JavadocXmlGeneratorTest.java
tools/java-source-utils/src/test/resources/com/microsoft/android/Outer.java

Context: https://github.com/xamarin/java.interop/pull/687#issuecomment-727099128
What happens when there's a "regular" Java comment in between a
Javadoc comment and a member?
/* partial */ class Object {
/** Create and return a copy of this object… */
// BEGIN Android-changed: Use native local helper for clone()
// …
protected Object clone() throws CloneNotSupportedException {…}
}
What happens is that the Javadoc becomes *orphaned*.
Commit 69e1b80a attempted to handle such orphaned Javadocs via
heuristic, using the first orphaned Javadoc comment in the parent
scope.  This didn't work reliably, as the parent scope could contain
multiple "*unrelated*" orphaned Javadoc comments:
class Outer {
/** Orphaned #1 */
// cause orphaning
class Inner {}
void m() {}
}
Because containing types are …

[java-source-utils] Better support orphaned Javadocs

---

tests/Xamarin.Android.Tools.Bytecode-Tests/java/com/xamarin/JavaType.java
tools/java-source-utils/src/main/java/com/microsoft/android/JniPackagesInfoFactory.java
tools/java-source-utils/src/test/java/com/microsoft/android/JavadocXmlGeneratorTest.java
tools/java-source-utils/src/test/resources/UnresolvedTypes.txt
tools/java-source-utils/src/test/resources/UnresolvedTypes.xml

Context: https://github.com/xamarin/java.interop/pull/687#issuecomment-668129226
Commit 69e1b80a stated:
> We don't want to *require* that everything be resolvable -- it's painful, and
> possibly impossible, e.g. w/ internal types -- so instead we should "demark"
> the unresolvable types.
>
> `.params.txt` output will use `.*` as a type prefix, e.g.
>
>     method(.*UnresolvableType foo, int bar);
>
> `docs.xml` will output `L.*UnresolvableType;`.
…except this didn't actually happen:
`java-source.utils.jar --output-javadoc` didn't have an `L` prefix
and `;` suffix for the JNI type representation.  Additionally, it
would include generic type parameters!
Thus, a declaration such as:
static UnknownType<String, Integer> method(AnotherUnknownType<Class> p);
would result in:
<method …

[java-source-utils] Properly represent unresolved types

---

src/Xamarin.Android.Tools.Bytecode/XmlClassDeclarationBuilder.cs

There is yet another `@NonNull` annotation: `androidx.annotation.NonNull` that we need to recognize to help create NRT assemblies:
https://developer.android.com/reference/androidx/annotation/NonNull

[class-parse] Support AndroidX's NonNull annotation.

---

tests/generator-Tests/Unit-Tests/ReportTests.cs
tools/generator/Utilities/Report.cs

In #715 we made `generator` warnings/errors give line/col information in more places, however the existing method for formatting the line/col information was wrong:
```
// Correct
C:\code\Metadata.xml(2, 6): warning BG8A04: <attr path="/api/package[@name='androidx.appcompat.widget']/class[@name='RoundRectDrawableWithShadow']"/> matched no nodes.
// Incorrect
C:\code\Metadata.xml(2, 6) warning BG8A04: <attr path="/api/package[@name='androidx.appcompat.widget']/class[@name='RoundRectDrawableWithShadow']"/> matched no nodes.
```
By omitting the colon after the line/col information, VS parses the colon in `C:\` instead, resulting in:
This is actually worse than what we previously had, as double-clicking it does nothing, since `C` is not a valid file on disk.
This commit rewrites the `Format` …

[generator] Fix MSBuild warning/error format for VS.

---

src/Java.Interop.Tools.JavaCallableWrappers/Java.Interop.Tools.JavaCallableWrappers/Crc64.Table.cs
src/Java.Interop.Tools.JavaCallableWrappers/Java.Interop.Tools.JavaCallableWrappers/Crc64Helper.cs
src/Java.Interop.Tools.TypeNameMappings/Java.Interop.Tools.TypeNameMappings/JavaNativeTypeManager.cs

Context: https://github.com/xamarin/xamarin-android/issues/5451
Split the code to static helper class, which can be used from
`Java.Interop.Tools.TypeNameMappings.JavaNativeTypeManager.GetPackageName`.
This way the linker can strip the whole
`System.Security.Cryptography.Primitives` assembly out of simple XA
apps.
The `Crc64` is still needed in XA, so we still keep it based
on `System.Security.Cryptography.HashAlgorithm`.

Refactor Crc64 type

---

src/Java.Interop/Java.Interop/JniPeerMembers.JniFields.cs
src/Java.Interop/Java.Interop/JniPeerMembers.JniFields.tt
src/Java.Interop/Java.Interop/JniPeerMembers.JniInstanceMethods_Invoke.cs
src/Java.Interop/Java.Interop/JniPeerMembers.JniInstanceMethods_Invoke.tt

Context: https://github.com/xamarin/xamarin-android/commit/e88cfbcf9ff4f4e179a60f1e8af2bef3537a66b4
While writing the commit message for xamarin/xamarin-android/@e88cfbcf,
it occurred to me that the same fundamental scenario of:
CallIntoJava (new JavaLangObjectSubclass ().Handle);
// GC collects instance after `.Handle`, before `CallIntoJava()`
could apply to `JniPeerMembers.JniInstanceMethods.Invoke*()`
invocations:
JniArgumentValue* __args = …;
_members.InstanceMethods.InvokeVirtualObjectMethod (__id, this, __args);
// What prevents `this` from being collected "too soon"?
Address this: update `JniPeerMembers.JniInstanceMethods.Invoke*()`
so that there is a `GC.KeepAlive(self)` after accessing
`self.PeerReference`.  This will ensure that `self` isn't collected
"during" …

[Java.Interop] Prevent premature collection w/ JniInstance*

---

tools/generator/Java.Interop.Tools.Generator.Importers/CecilApiImporter.cs

Context: https://github.com/xamarin/AndroidX/pull/235
Given the following API:
```
public interface IMyInterface {
void DoSomething () => throw new Exception ();
}
public abstract class MyClass : IMyInterface { }
```
We need to ensure that `Method.IsInterfaceDefaultMethod` gets set for `DoSomething` so that our `BoundClass.AddInterfaceAbstractMembers` logic knows it does not need to create an `abstract MyClass.DoSomething ()`.  
This works correctly if the interface is in the assembly we are binding (because it uses `XmlApiImporter`).  However if the interface is in a reference assembly it uses `CecilApiImporter`.  Our Cecil importer only marks the DIM if it has `[JavaInterfaceDefaultMethodAttribute]` which we don't appear to ever emit.
So if the interface is in a reference assembly (like …

[generator] Ensure DIM from Cecil imported references get correctly marked.

---

src/Xamarin.Android.Tools.Bytecode/JavaDocumentScraper.cs

Context: https://github.com/xamarin/java.interop/issues/767
Context: https://github.com/xamarin/xamarin-android/blob/a7413a2389886082c3d3422c50a7e6cc84f43d8f/src/Xamarin.Android.Build.Tasks/MSBuild/Xamarin/Android/Xamarin.Android.Bindings.ClassParse.targets#L23
Commit 69e1b80a added `java-source-utils.jar`, which can parse Java
source code to extract parameter names, storing them into a
"`class-parse`-like XML file".
A benefit to a "`class-parse`-like XML file" is that it should be
possible to use this same file with `class-parse --docspath`,
overriding parameter names present in Java bytecode (which typically
*isn't* present, as `javac -parameters` is rarely used).
Unfortunately, this doesn't work: if you attempt to use
`java-source-utils.jar` output w/ `class-parse --docspath`, it …

[Xamarin.Android.Tools.Bytecode] Relax _ApiXml check

---

src/Java.Interop.Tools.JavaSource/Java.Interop.Tools.JavaSource/SourceJavadocToXmldocParser.cs
tools/generator/CodeGeneratorOptions.cs
tools/generator/Java.Interop.Tools.Generator.ObjectModel/JavadocInfo.cs

Context: https://github.com/xamarin/xamarin-android/commit/a7413a2389886082c3d3422c50a7e6cc84f43d8f
Context: https://github.com/xamarin/android-api-docs
Context: https://github.com/xamarin/android-api-docs/blob/035344f961fd391bcad9715ea690afa3b88d6142/docs/Mono.Android/en/Java.Lang/Object.xml#L34-L41
xamarin/xamarin-android@a7413a23 asked:
> What do we want?  Updated documentation!
About that…
Our existing documentation at [xamarin/android-api-docs][0] includes
a copyright notice for every member, e.g.
<remarks>
<para>
<format type="text/html">
<a href="https://developer.android.com/reference/java/lang/Object" title="Reference documentation">Android platform documentation</a>
</format>
</para>
<para>Portions of this page are modifications based on work created and shared by the <format …

[generator] Add `--doc-comment-verbosity=intellisense+extraremarks`

---

global.json
src/java-interop/java-interop.csproj
tools/java-source-utils/java-source-utils.csproj

Java.Interop is using `Microsoft.Build.NoTargets` version `1.0.110`, while Xamarin.Android uses `2.0.1`.  This causes some build warnings when building XA:
```
/Users/builder/azdo/_work/1/s/xamarin-android/external/Java.Interop/tools/java-source-utils/java-source-utils.csproj :
warning MSB4240: Multiple versions of the same SDK "Microsoft.Build.NoTargets" cannot be specified. 
The previously resolved SDK version "2.0.1" from location "/Users/builder/azdo/_work/1/s/xamarin-android/src/
java-runtime/java-runtime.csproj" will be used and the version "1.0.110" will be ignored.
```
Fix this by moving the version number from the individual csproj's and into a `global.json` with a version matching XA's `global.json`.

[global.json] Update Microsoft.Build.NoTargets to 2.0.1.

---

tests/generator-Tests/Unit-Tests/CodeGeneratorTests.cs
tools/generator/Java.Interop.Tools.Generator.ObjectModel/NamespaceMapping.cs
tools/generator/SourceWriters/Attributes/SupportedOSPlatformAttr.cs
tools/generator/SourceWriters/BoundAbstractProperty.cs
tools/generator/SourceWriters/BoundClass.cs
tools/generator/SourceWriters/BoundConstructor.cs
tools/generator/SourceWriters/BoundFieldAsProperty.cs
tools/generator/SourceWriters/BoundInterfaceMethodDeclaration.cs
tools/generator/SourceWriters/BoundInterfacePropertyDeclaration.cs
tools/generator/SourceWriters/BoundMethod.cs
tools/generator/SourceWriters/BoundMethodAbstractDeclaration.cs
tools/generator/SourceWriters/BoundProperty.cs
tools/generator/SourceWriters/Extensions/SourceWriterExtensions.cs
tools/generator/SourceWriters/GenericExplicitInterfaceImplementationProperty.cs
tools/generator/SourceWriters/InterfaceMemberAlternativeClass.cs

Context: https://github.com/xamarin/xamarin-android/issues/5338
.NET 5 provides a new attribute `[SupportedOSPlatform]` to specify when an API is not available on all platforms or platform versions.  This is used to build analyzers to give users warnings if they are trying to use an API when it will not be available on their target platform.  This is fundamentally the same as our existing `ApiSince`, except tooling has actually been built to consume the information.
As such, we need `generator` support to put this information into `Mono.Android.dll`.
```
// Metadata.xml XPath method reference: path="/api/package[@name='android.app']/class[@name='Activity']/method[@name='dismissKeyboardShortcutsHelper' and count(parameter)=0]"
[global::System.Runtime.Versioning.SupportedOSPlatformAttribute …
```

Add [SupportedOSPlatform] attributes to assemblies using ApiSince.

---

Directory.Build.props
src/Java.Interop/Java.Interop-MonoAndroid.csproj
src/Java.Interop/Java.Interop.csproj
src/Java.Interop/Java.Interop/JniEnvironment.Errors.cs
src/Java.Interop/Java.Interop/JniEnvironment.References.cs
src/Java.Interop/Java.Interop/JniEnvironment.Strings.cs
src/Java.Interop/Java.Interop/JniObjectReferenceOptions.cs
src/Java.Interop/Java.Interop/JniPeerMembers.JniInstanceMethods.cs
src/Java.Interop/Java.Interop/JniPeerMembers.cs
src/Java.Interop/Java.Interop/JniRuntime.JniTypeManager.cs
src/Java.Interop/Java.Interop/JniRuntime.cs
src/Java.Interop/Java.Interop/JniType.cs

Context: https://github.com/xamarin/xamarin-android/issues/5400
Context: https://github.com/xamarin/xamarin-android/pull/5444
Driven by `XA_JI_EXCLUDE`, which will be defined
in `XAConfig.props` in `$(JavaInteropDefineConstants)`, when
building for XA. The file is generated by XA's `xaprep`
in `bin/Build$(Configuration)`.
Also clean old `XA_INTEGRATION` #if's, they are not used anymore.

Conditionally call ManagedPeer.Init()

---

Directory.Build.props

Context: https://natemcmaster.com/blog/2019/01/09/netcore-primitives-3/
Context: https://github.com/dotnet/designs/blob/main/accepted/2019/runtime-binding.md#rollforward
I've seen an error on a CI machine that *only* has .NET 5 & 6
installed:
Task "BindingsGenerator"
...
It was not possible to find any compatible framework version
The framework 'Microsoft.NETCore.App', version '3.1.0' was not found.
- The following frameworks were found:
5.0.1 at [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
6.0.0-alpha.1.20560.10 at [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]
You can resolve the problem by installing the specified framework and/or SDK.
- https://aka.ms/dotnet-core-applaunch?framework=Microsoft.NETCore.App&framework_version=3.1.0&arch=x64&rid=osx.10.15-x64 …

[build] use $(RollForward) Major for console apps

---

tools/generator/Java.Interop.Tools.Generator.ObjectModel/NamespaceMapping.cs

Context: Fixes https://github.com/xamarin/java.interop/issues/777
Looks like this define will not be added, so check for `NET` instead.

Do not check for NET5_0_OR_GREATER

---

tests/generator-Tests/Unit-Tests/CodeGeneratorTests.cs
tools/generator/Java.Interop.Tools.Generator.ObjectModel/NamespaceMapping.cs
tools/generator/SourceWriters/Attributes/SupportedOSPlatformAttr.cs

Context: https://github.com/xamarin/xamarin-android/pull/5497
We cannot currently build `net5.0` or `net6.0` assemblies in our XA tree and instead do some workaround that involves compiling with `netcoreapp3.1` but referencing 5.0 BCL.  This creates a conflict between the local `[SupportedOSPlatform]` we create in `netcoreapp3.1` `Mono.Android.dll`, and the real one in the 5.0 BCL.
```
error CS0433: The type 'SupportedOSPlatformAttribute' exists in both 'Mono.Android, Version=0.0.0.0, 
Culture=neutral, PublicKeyToken=84e04ff9cfb79065' and 'System.Runtime, Version=5.0.0.0, Culture=neutral, 
PublicKeyToken=b03f5f7f11d50a3a' [/Users/runner/work/1/s/tests/Mono.Android-Tests/Java.Interop-Tests/
Java.Interop-Tests.NET.csproj] [/Users/runner/work/1/s/tests/Mono.Android-Tests/Runtime-Microsoft.And …
```

[generator] Disable [SupportedOSPlatform] until we can build with .NET 5/6.

---

src/Java.Interop/Java.Interop/JniNativeMethodRegistrationArguments.cs

To fix this error and improve performance a bit:
error CA1802: Field 'invalidStateMessage' is declared as 'readonly' but is initialized with a constant value. Mark this field as 'const' instead.
Context: https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1802

Use `const` instead of `static readonly`

---

tests/generator-Tests/Unit-Tests/InterfaceConstantsTests.cs
tools/generator/CodeGenerationOptions.cs
tools/generator/Java.Interop.Tools.Generator.CodeGeneration/CodeGenerator.cs
tools/generator/Java.Interop.Tools.Generator.ObjectModel/InterfaceGen.cs
tools/generator/SourceWriters/BoundClass.cs
tools/generator/SourceWriters/BoundInterface.cs

Fixes #752 
The Android API has an "interesting" pattern where they have an interface with some static constants, and then they inherit that interface in other types to inherit those constants.
Example: https://developer.android.com/reference/android/provider/BaseColumns
```
public interface BaseColumns {
public static final String _COUNT = "_count";
public static final String _ID = "_id";
}
```
This interface is inherited by ~115 other types, including other interfaces that only have static constant fields, like [CalendarContract.CalendarSyncColumns ](https://developer.android.com/reference/android/provider/CalendarContract.CalendarSyncColumns?hl=en).  This made a very messy API when we bound it due the constants being copied into our alternative `IBaseColumnsConsts` and …

[generator] Only apply ConstSugar to Mono.Android.dll.

---

build-tools/automation/azure-pipelines.yaml

Update `azure-pipelines.yaml` to look for the `main` branch instead of the `master` branch, in preparation for renaming the default branch.

[AzDO] Switch default branch from master to main.

---

src/Java.Interop/Java.Interop/JniRuntime.cs

Context: https://github.com/xamarin/xamarin-android/issues/5455
This is motivated by reducing the XA's HelloWorld apk size. It results
in dropping `System.Collections.Concurrent.dll` from linked assemblies
set and saving another 1.32% of assemblies size.
apk size comparison - XA's BuildReleaseArm64False/net6 test:
Size difference in bytes ([*1] apk1 only, [*2] apk2 only):
+          22 assemblies/Java.Interop.dll
-         316 assemblies/System.Private.CoreLib.dll
-         702 assemblies/System.Linq.dll
-       8,471 assemblies/System.Collections.Concurrent.dll *1
Summary:
-       9,467 Assemblies -1.32% (of 719,277)
-      15,872 Uncompressed assemblies -1.06% (of 1,491,456)

Use locking instead of ConcurrentDictionary

---

NuGet.Config
build-tools/automation/azure-pipelines.yaml
build-tools/automation/templates/install-dependencies.yaml

Context: https://medium.com/@alex.birsan/dependency-confusion-4a5d60fec610
Context: https://azure.microsoft.com/en-us/resources/3-ways-to-mitigate-risk-using-private-package-feeds/
Context: https://devdiv.visualstudio.com/DevDiv/_wiki/wikis/DevDiv.wiki/12676/ncident-help-for-Substitution-attack-risk-from-multiple-package-feeds
Changes: https://github.com/xamarin/xamarin-android-tools/compare/26d65d95943b18bb9575d75c8c60ce36180a0db9...63510cfc6cc30da0d2ee6290ff3c225d60f8c2ad
* xamarin/xamarin-android-tools@63510cf: [ci] Update packageSources in NuGet.config (#105)
* xamarin/xamarin-android-tools@83ed0a4: Bump ta xamarin/LibZipSharp/1.0.22@9f563dd1 (#104)
* xamarin/xamarin-android-tools@8ea78a4: Add Microsoft.Android.Build.BaseTasks project (#101)
* xamarin/xamarin-android-tools@b2d9fdf: …

Bump to xamarin/xamarin-android-tools/main@63510cfc; packageSources

---

Java.Interop.sln
src/Java.Interop/Java.Interop/ManagedPeer.cs
src/Java.Runtime.Environment/Java.Interop/JreRuntime.cs
src/Java.Runtime.Environment/Java.Interop/MonoRuntimeValueManager.cs
src/java-interop/java-interop.csproj
tests/invocation-overhead/Directory.Build.targets
tests/invocation-overhead/Makefile
tests/invocation-overhead/README.md
tests/invocation-overhead/invocation-overhead.cs
tests/invocation-overhead/invocation-overhead.csproj
tests/invocation-overhead/test-overheads.exe.config

`tests/invocation-overhead` partially bitrot since it was last
touched in 8602581: it insta-crashes:
% make run
mono64 --debug=casts test-overheads.exe
2021-02-11 17:33:49.479 mono64[90565:6542595] CheckForInstalledJavaRuntimes: Please visit http://www.java.com for information on installing java.
make: *** [run] Error 97
The primary "cause" is d1cce190: it was never a good idea to P/Invoke
into `jvm.dll`, as:
* The name for `jvm.dll` differs between platforms!  It's `jvm`
some places, `jre` others, and `jli` in still others!
If we want (eventual) .NET Framework/.NET Core support, this
is a non-starter.
* The actual on-disk path is also highly variable.
The solution to this conundrum was to update the `java-interop`
native library to have a new `java_interop_jvm_load()` export, and
use …

[invocation-overhead] Fix; .NET Core support

---

tests/generator-Tests/Unit-Tests/CodeGeneratorTests.cs
tools/generator/SourceWriters/BoundInterface.cs

Fixes #797.
In #780 we made a change to only apply the ConstSugar logic to `Mono.Android.dll`. However there are of course other libraries written by Google that use the same pattern, namely AndroidX.  I still think removing ConstSugar is the correct move for libraries other than `Mono.Android` because it causes more problems than it solves.  (Also ConstSugar is irrelevant in the DIM world we want to move the ecosystem to.)
However, there is an issue when other libraries try to create interfaces that inherit `Mono.Android`'s `Android.Provider.BaseColumns`.
Mono.Android contains:
```
[Register ("android.provider.BaseColumns")] public abstract class BaseColumns
[Register ("android.provider.BaseColumns")] public interface IBaseColumns
```
When we build our Java -> C# typemap, we only support …

[generator] Fix NRE when interfaces appear to implement classes.

---

tests/invocation-overhead/invocation-overhead.cs

Context: https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=4466540&view=logs&j=f31c9f97-4411-58e7-49ac-fc73f645e6b6&t=cbeb8522-7b64-5cc0-7bee-eff0e164a409
Commit 2a299eb1 accidentally introduced ~650 warnings to the build:
tests\invocation-overhead\jni.cs(5756,24): Warning CS0436:
The type 'JniFieldInfo' in 'D:\a\1\s\tests\invocation-overhead\invocation-overhead.cs' conflicts with the
imported type 'JniFieldInfo' in 'Java.Interop, Version=0.1.0.0, Culture=neutral, PublicKeyToken=84e04ff9cfb79065'.
Using the type defined in 'D:\a\1\s\tests\invocation-overhead\invocation-overhead.cs'.
This was because commit 2a299eb1 added a declaration for `JniFieldInfo`
and `JniMethodInfo` in the `Java.Interop` namespace within
`invocation-overhead.cs`.
Fix the warnings by moving the …

[invocation-overhead] Fix CS0436 warnings

---

build-tools/automation/azure-pipelines.yaml
build-tools/automation/templates/core-tests.yaml

We originally did not enable native tests on our Mac .NET Core build lane because they didn't work.  However with recent improvements (https://github.com/xamarin/java.interop/pull/801) they now succeed, so we should enable them to ensure they do not break.

[CI] Enable native tests for Mac - .NET Core.

---

build-tools/automation/azure-pipelines.yaml
build-tools/automation/templates/core-tests.yaml
src/Java.Interop.Export/Java.Interop/MarshalMemberBuilder.cs
src/Java.Interop/Java.Interop/JniEnvironment.Types.cs
src/Java.Runtime.Environment/Java.Interop/JreRuntime.cs
src/Java.Runtime.Environment/Java.Interop/ManagedObjectReferenceManager.cs
src/Java.Runtime.Environment/Java.Interop/ManagedValueManager.cs
src/Java.Runtime.Environment/Java.Interop/MonoRuntimeObjectReferenceManager.cs
src/Java.Runtime.Environment/Java.Interop/MonoRuntimeValueManager.cs
src/Java.Runtime.Environment/Java.Runtime.Environment.csproj
tests/Java.Interop-Tests/Java.Interop-Tests.csproj
tests/Java.Interop-Tests/Java.Interop/JavaObjectTest.cs
tests/Java.Interop-Tests/Java.Interop/JavaVMFixture.cs
tests/Java.Interop-Tests/Java.Interop/JniValueMarshalerContractTests.cs
tests/Java.Interop-Tests/Java.Interop/TestType.cs
tests/Java.Interop.Export-Tests/Java.Interop/MarshalMemberBuilderTest.cs
tests/TestJVM/TestJVM.cs

Enable C#8 [Nullable Reference Types][0] for
`Java.Runtime.Environment.dll`.
Add partial support for a "non-bridged backend", so that a
`JniRuntime.JniValueManager` exists for .NET Core.  This new
"managed" backed is used if the Mono runtime is *not* used.
To work, `ManagedValueManager` holds *strong* references to
`IJavaPeerable` instances.  As such, tests which required the use of
GC integration are now "optional", conditional on the
`!NO_GC_BRIDGE_SUPPORT` define.
The `ManagedValueManager.CollectPeers()` method calls
`IJavaPeerable.Dispose()` on all currently referenced peers, then
stops referencing the managed peers.
This causes all GREFs to be dropped, allowing Java peers to be
collected, and then allows the .NET GC to collect the `IJavaPeerable`
values.
Any and all exceptions thrown …

[Java.Runtime.Environment] Partial support for .NET Core

---

tools/param-name-importer/JavaStubSourceImporter.cs

In https://github.com/xamarin/java.interop/pull/756, we switched from using `List<JavaPackage>` to `Dictionary<string, JavaPackage>` for better performance.  To minimize the diffs needed with existing code, we created an accessor for the `Dictionary.Values`:
```
public IDictionary<string, JavaPackage>Packages { get; }
public ICollection<JavaPackage> AllPackages => Packages.Values;
```
However if you attempt to modify this collection directly, you get an exception.  
```
System.NotSupportedException: Mutating a value collection derived from a dictionary is not allowed.
at System.ThrowHelper.ThrowNotSupportedException(ExceptionResource resource)
at Xamarin.Android.ApiTools.JavaStubImporter.JavaStubSourceImporter.ParseJava(String javaSourceText) in …
```

[param-name-importer] Fix crash trying to modify a Dictionary.Values collection directly

---

build-tools/jnienv-gen/Generator.cs

In addition to generating a .c file, generate a .h one with declarations
of all the functions defined in the .c file.  The header will be used by
the NET6 build of Xamarin.Android's native runtime.
Additionally, make it possible to not export symbols by defining the
`JI_NO_VISIBILITY` preprocessor macro.  This will also be used by the
NET6 build of Xamarin.Android native runtime (which will no longer need
to make the symbols visible for `p/invoke` to work)

[jnienv-gen] Generate a header file for the native functions

---

src/Xamarin.Android.Tools.Bytecode/ClassFile.cs
src/Xamarin.Android.Tools.Bytecode/Kotlin/KotlinFixups.cs
src/Xamarin.Android.Tools.Bytecode/Methods.cs
src/Xamarin.Android.Tools.Bytecode/XmlClassDeclarationBuilder.cs
tests/Xamarin.Android.Tools.Bytecode-Tests/KotlinFixupsTests.cs
tests/generator-Tests/Unit-Tests/XmlApiImporterTests.cs
tools/generator/Java.Interop.Tools.Generator.Importers/XmlApiImporter.cs

Fixes #790.
Modify `class-parse` to emit Kotlin `internal` types/members so that users can use `metadata` to change them to `public` if they wish, giving them the same access they would have if consumed from Java.  If `visibility` is not changed to `public` by the user, `generator` will ignore importing these types/members, resulting in the same bindings as today.
Format is the same as existing metadata visibility fixup:
```
<attr path="/api/package[@name='com.example']/class[@name='MyClass']" name="visibility">public</attr>
```
`class-parse` now emits all `private` **_types_** as `visibility="private"` because the existing `generator` behavior will ignore any `private` types, which is what we want.  Kotlin `internal` types were already being changed to `private`, so they fall into this …

[class-parse, generator] Allow users to expose Kotlin internal types/members with metadata.

---

src/Java.Interop.Localization/Java.Interop.Localization.csproj
src/Java.Interop/Java.Interop/JavaArray.cs
src/Java.Interop/Java.Interop/JniEnvironment.Types.cs
src/Java.Interop/Java.Interop/JniRuntime.JniMarshalMemberBuilder.cs
src/Java.Interop/Java.Interop/JniType.cs
src/Java.Runtime.Environment/Java.Runtime.Environment.csproj

Fix some NRT warnings that have crept in.
---
Also add `<NeutralLanguage>en</NeutralLanguage>` to fix:
```
Warning CA1824: Mark assemblies with NeutralResourcesLanguageAttribute
```
Basically this says that the "neutral" language this assembly contains is also the English translations, so we don't need to spend time probing for satellite resource assemblies when the English language is requested.
---
Also add `<MSBuildWarningsAsMessages>NU1702</MSBuildWarningsAsMessages>` to suppress:
```
Warning NU1702: ProjectReference 'D:\a\1\s\src\java-interop\java-interop.csproj' was resolved using 
'.NETFramework,Version=v4.7.2' instead of the project target framework '.NETStandard,Version=v2.0'. 
This project may not be fully compatible with your project.
```

Fix compiler warnings.

---

build-tools/scripts/NativeToolchain.targets
src/java-interop/Directory.Build.targets
tests/NativeTiming/Directory.Build.targets

Context: https://github.com/xamarin/xamarin-android/pull/5757
Turns Out™ that the xamarin-android Windows CI machine *doesn't* have
Visual C++ installed, and thus *can't* build `src/java-interop` with
the changes in 3824b974.  (Rephrased: 3824b974 broke the Windows
build for xamarin-android!)
Update `NativeToolchain.targets`, `src/java-interop`, and
`tests/NativeTiming` so that native files are *optional* when building
on Windows.  This should allow xamarin-android CI to work.

[ci] Make VC++ toolchain optional

---

build-tools/automation/azure-pipelines.yaml
build-tools/automation/templates/core-build.yaml
build-tools/scripts/Prepare.targets
tests/TestJVM/TestJVM.cs

Context: https://developercommunity.visualstudio.com/t/illegal-character-exception-in-xamarinandroid-afte/1363149
Changes: https://github.com/xamarin/xamarin-android-tools/compare/554d45a166a02da0ca1d0d9ca895eaa650fb648a...d92fc3e3a27e8240551baa813b15d6bf006a5620
* xamarin/xamarin-android-tools@d92fc3e: [Xamarin.Android.Tools.AndroidSdk] Probe for AdoptOpenJDK Locations (#115)
* xamarin/xamarin-android-tools@dca30d9: [Xamarin.Android.Tools.AndroidSdk] Probe for Zulu JDK (#114)
* xamarin/xamarin-android-tools@237642c: [Xamarin.Android.Tools.AndroidSdk] Probe for Microsoft OpenJDK dirs (#113)
* xamarin/xamarin-android-tools@e618e00: [Xamarin.Android.Tools.AndroidSdk] Fix quotes in %PATH% or %PATHEXT% (#112)

Bump to xamarin/xamarin-android-tools/main@d92fc3e3

---

src/Java.Interop.Tools.JavaCallableWrappers/Java.Interop.Tools.JavaCallableWrappers/JavaTypeScanner.cs

Java typemaps have never included interfaces because, till very
recently, they couldn't contain methods so they couldn't have been used
as method invocation targets.  With the addition of DIM (Default
Interface Methods) to C# this is no longer true.  Exclusion of
interfaces from typemaps can lead to errors similar to:
---- DEBUG ASSERTION FAILED ----
---- Assert Short Message ----
ManagedPeerType <=> JniTypeName Mismatch! javaVM.GetJniTypeInfoForType(typeof(Android.App.Application+IActivityLifecycleCallbacks)).JniTypeName="" != "android/app/Application$ActivityLifecycleCallbacks"
---- Assert Long Message ----
at System.Diagnostics.DebugProvider.Fail(String message, String detailMessage) in System.Private.CoreLib.dll:token 0x6005586+0x0
at System.Diagnostics.Debug.Fail(String message, …

Include interfaces in type maps

---

tools/jcw-gen/App.cs

Context: ebd7d76161ac60ce7ad3bfee87789f08a333ae78
ebd7d761 introduced support for interfaces in typemaps, but it failed
to update the `jcw-gen` utility to ignore them when generating Java
Code Wrappers.  This, in turn, made Xamarin.Android fail to build.
Fix the issue by ignoring interfaces in `jcw-gen`

Update jcw-gen to work with interfaces in typemaps

---

src/Java.Interop/Properties/AssemblyInfo.cs

Context: https://github.com/xamarin/xamarin-android/issues/5638
Context: https://github.com/xamarin/xamarin-android/pull/5879
Going forward in .NET 6, we shouldn't use the `%(IsTrimmable)`
metadata anymore, but use the following C# attribute in each assembly
instead:
[assembly: AssemblyMetadata ("IsTrimmable", "True")]
Similar changes on the iOS side here:
https://github.com/xamarin/xamarin-macios/commit/289053b1e3bdf3b8c3cc3839384811f6018bba48
This adds `AssemblyMetadataAttribute` for `Java.Interop.dll`.

[One .NET] specify AssemblyMetadataAttribute for IsTrimmable

---

tools/java-source-utils/build.gradle

Context: https://blog.gradle.org/jcenter-shutdown
Context: https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/
JCenter is shutting down.  It is no longer browsable as of May 1,
and artifacts hosted on JCenter will not be accessible as of
February 1, 2022.
Stop using JCenter, and instead use [Maven Central][0].
[0]: https://search.maven.org/

[java-source-utils] Use mavenCentral, not jcenter

---

Directory.Build.props
build-tools/Java.Interop.BootstrapTasks/Java.Interop.BootstrapTasks/JdkInfo.cs
build-tools/automation/azure-pipelines.yaml
build-tools/automation/templates/install-dependencies.yaml
build-tools/jnienv-gen/jnienv-gen.csproj
build-tools/scripts/Prepare.targets
build-tools/scripts/jdk.mk
build-tools/scripts/jdk.targets
global.json
src/Java.Interop.Export/Java.Interop.Export.csproj
src/Java.Interop.GenericMarshaler/Java.Interop.GenericMarshaler.csproj
src/Java.Interop/Java.Interop.csproj
src/java-interop/java-interop.csproj
tests/Java.Interop-PerformanceTests/Java.Interop-PerformanceTests.csproj
tests/Java.Interop-Tests/Java.Interop-Tests.csproj
tests/TestJVM/TestJVM.csproj
tests/invocation-overhead/Directory.Build.targets
tests/invocation-overhead/invocation-overhead.csproj
tools/class-parse/class-parse.csproj
tools/generator/generator.csproj
tools/jcw-gen/jcw-gen.csproj
tools/logcat-parse/logcat-parse.csproj
tools/param-name-importer/param-name-importer.csproj

Context: https://github.com/xamarin/xamarin-android/pull/5891
Context: https://github.com/xamarin/xamarin-android/commit/e59f6493fedd789cbd3157d369104516cfffd3f0
xamarin-android should imminently be building libraries targeting `net6.0` instead of `netcoreapp3.1`.
We should be able to do this now, because Mono 6.12.0.137 supports building both .NET 5.0 and .NET 6.0.

[build] target net6.0 instead of netcoreapp3.1

---

tests/generator-Tests/Unit-Tests/CodeGeneratorExpectedResults/Common/WriteInterfaceEventArgsWithParamArray.txt
tests/generator-Tests/Unit-Tests/CodeGeneratorExpectedResults/XAJavaInterop1-NRT/WriteInterfaceEventArgsWithParamArray.txt
tests/generator-Tests/Unit-Tests/CodeGeneratorTests.cs
tools/generator/Java.Interop.Tools.Generator.CodeGeneration/CodeGenerator.cs

Fixes: #817
If we are creating an `EventArgs` class for a method that has a parameter array like this:
```
public interface SomeListener {
void onSomeNotification (Object... args);
}
```
We are generating the following invalid C# code:
```
public partial class SomeEventArgs : global::System.EventArgs {
params global::Java.Lang.Object[] args;
public params global::Java.Lang.Object[] Args {
get { return args; }
}
}
```
This commit removes the extraneous `params` output.

[generator] Fix invalid code generated for EventArgs classes with parameter arrays.

---

tests/generator-Tests/Unit-Tests/CodeGeneratorExpectedResults/JavaInterop1/ObsoleteInterfaceAlternativeClass.txt
tests/generator-Tests/Unit-Tests/CodeGeneratorExpectedResults/JavaInterop1/WriteInterfaceFieldAsDimProperty.txt
tests/generator-Tests/Unit-Tests/CodeGeneratorExpectedResults/XAJavaInterop1/ObsoleteInterfaceAlternativeClass.txt
tests/generator-Tests/Unit-Tests/CodeGeneratorExpectedResults/XAJavaInterop1/WriteInterfaceFieldAsDimProperty.txt
tests/generator-Tests/Unit-Tests/DefaultInterfaceMethodsTests.cs
tools/generator/Java.Interop.Tools.Generator.ObjectModel/InterfaceGen.cs
tools/generator/SourceWriters/BoundInterface.cs

Fixes: #821 
Context: https://github.com/xamarin/xamarin-android/issues/5818
Context: https://github.com/xamarin/java.interop/pull/459
Context: https://github.com/xamarin/java.interop/pull/509
When we began generating static methods and properties on interfaces when running with DIM enabled, it looks like we did not include static fields that cannot be treated as constants. 
Thus, given the following example from https://github.com/xamarin/xamarin-android/issues/5818:
```
public interface EGL10 {
public static final int EGL_ALPHA_FORMAT = 12424;
public static final EGLSurface EGL_NO_SURFACE;
}
```
we only generate:
```
public partial interface IEGL10 {
public const int EglAlphaFormat = (int) 12424;
}
```
This is an issue because we `[Obsolete]`'d the version in the \***class**\* `EGL10` …

[generator] Ensure non-constant static interface fields are generated as interface properties.

---

src/Java.Interop.Tools.JavaSource/Java.Interop.Tools.JavaSource/SourceJavadocToXmldocGrammar.BlockTagsBnfTerms.cs
tests/Java.Interop.Tools.JavaSource-Tests/SourceJavadocToXmldocParserTests.cs

Context: https://github.com/xamarin/xamarin-android/pull/5485
In an attempt to generate updated documentation for API 30 I've noticed
a minor issue in generator.  When a `<javadoc>` element contains
multiple @return values, we will generate multiple `<returns>` elements
in our C# documentation.  This results in invalid C# documentation with
partially missing return information, and the second `<returns>` element
value is not displayed in IDE intellisense.  This also causes an issue
when the xml is processed by `mdoc`.  These extra return lines will
continue to be appended to the `mdoc` output every time the tool is ran
against the invalid `Mono.Android.xml`.

[generator] Handle multiple @return javadoc values

---

tests/generator-Tests/Unit-Tests/XmlApiImporterTests.cs
tools/generator/Java.Interop.Tools.Generator.Importers/XmlApiImporter.cs

Fixes: https://github.com/xamarin/java.interop/issues/835
Somehow Google has compiled `firebase-firestore.aar` to contain a class with a dollar sign in its name:
```
<class
abstract="false"
deprecated="not deprecated"
jni-extends="Ljava/lang/Object;"
extends="java.lang.Object"
extends-generic-aware="java.lang.Object"
final="false"
name="Document."
jni-signature="Lcom/google/firebase/firestore/model/Document$;"
source-file-name="Document.java"
static="false"
visibility="public" />
```
This causes an `IndexOutOfRangeException` for `generator` when it tries to parse `Document.` into a parent class name and nested class name.
```
Unhandled Exception: (TaskId:666)
System.IndexOutOfRangeException: Index was outside the bounds of the array. (TaskId:666)
at …
```

[generator] Ignore types without names.

---

tests/generator-Tests/expected.ji/Adapters/Xamarin.Test.AbsSpinner.cs
tests/generator-Tests/expected.ji/Adapters/Xamarin.Test.AdapterView.cs
tests/generator-Tests/expected.ji/NormalMethods/Xamarin.Test.A.cs
tests/generator-Tests/expected.ji/NormalMethods/Xamarin.Test.C.cs
tests/generator-Tests/expected.ji/TestInterface/Test.ME.IGenericPropertyInterface.cs
tests/generator-Tests/expected/Adapters/Xamarin.Test.AbsSpinner.cs
tests/generator-Tests/expected/Adapters/Xamarin.Test.AdapterView.cs
tests/generator-Tests/expected/NormalMethods/Xamarin.Test.A.cs
tests/generator-Tests/expected/NormalMethods/Xamarin.Test.C.cs
tests/generator-Tests/expected/TestInterface/Test.ME.IGenericPropertyInterface.cs
tools/generator/Java.Interop.Tools.Generator.ObjectModel/Symbols/GenericTypeParameter.cs

Context: https://github.com/xamarin/xamarin-android/issues/5894
When creating the cast from a generic type parameter (which is currently always JLO), `global::` is not prepended to the type cast.  
```
return (Java.Lang.Object) global::Java.Lang.Object.GetObject<global::Java.Lang.Object> (__rm.Handle, JniHandleOwnership.TransferLocalRef);
```
This creates a compilation error if the bound type is in a namespace that ends in "Java", like "MyProduct.Java".
```
Error CS0234: The type or namespace name 'Lang' does not exist in the namespace 'MyProduct.Java'.
```
Fix this by ensuring the cast output goes through our standard type formatting method which adds `global::` when needed.

[generator] Ensure "global::" is prepended to generic return casts.

---

tests/generator-Tests/Unit-Tests/CodeGeneratorTests.cs
tools/generator/SourceWriters/BoundMethodAbstractDeclaration.cs

Fixes: https://github.com/xamarin/xamarin-android/issues/5921
For the following generic-laden Java:
```
public interface MyInterface<R> {
R Next (int count);
}
public abstract class MyClass<T> implements MyInterface<T> {
public T Next (int count);
}
```
We need to generate an explicit method declaration:
```
Java.Lang.Object Com.Example.IMyInterface.Next (int count)
{
throw new NotImplementedException ();
}
```
However when we did the `generator` refactor this code code path was not tested, and the code short-circuits, bypassing setting the `ReturnType` and `Parameters` collection.
Attempting to generate the method results in an NRE:
```
ReturnType.WriteTypeReference (writer);
at Xamarin.SourceWriter.MethodWriter.WriteReturnType(CodeWriter writer) in …
```

[generator] Fix NRE from return type not getting set for abstract methods with generics.

---

src/Java.Interop/Java.Interop/JniRuntime.JniTypeManager.cs
src/Java.Interop/Java.Interop/JniRuntime.JniValueManager.cs
src/Java.Interop/Java.Interop/JniStringValueMarshaler.cs
src/Java.Interop/Java.Interop/JniValueMarshaler.cs

In https://github.com/xamarin/java.interop/pull/829 we began targeting `net6.0` instead of `netcoreapp3.1`.  This framework contains additional nullable annotations that resulted in new warnings.

[Java.Interop] Fix NRT warnings introduced by targeting 'net6.0'.

---

tests/generator-Tests/Unit-Tests/CodeGeneratorTests.cs
tools/generator/Java.Interop.Tools.Generator.ObjectModel/NamespaceMapping.cs
tools/generator/SourceWriters/Attributes/SupportedOSPlatformAttr.cs

This reverts commit 00862adaf1f5447f2dcbff7b957083076da31a7b.
Now that we are properly building with the `net6.0` TF we can re-enable the `[SupportedOSPlatform]` support.
XA companion test bump to ensure this works: https://github.com/xamarin/xamarin-android/pull/5932

Revert "[generator] Disable [SupportedOSPlatform] until .NET 5/6."

---

src/Java.Interop.Tools.Cecil/Java.Interop.Tools.Cecil/MethodDefinitionRocks.cs
src/Java.Interop.Tools.Cecil/Java.Interop.Tools.Cecil/TypeDefinitionCache.cs
src/Java.Interop.Tools.Cecil/Java.Interop.Tools.Cecil/TypeDefinitionRocks.cs
src/Java.Interop.Tools.JavaCallableWrappers/Java.Interop.Tools.JavaCallableWrappers/JavaCallableWrapperGenerator.cs
src/Java.Interop.Tools.JavaCallableWrappers/Java.Interop.Tools.JavaCallableWrappers/JavaTypeScanner.cs
src/Java.Interop.Tools.JavaCallableWrappers/Java.Interop.Tools.JavaCallableWrappers/TypeNameMapGenerator.cs
src/Java.Interop.Tools.TypeNameMappings/Java.Interop.Tools.TypeNameMappings/JavaNativeTypeManager.cs

Context: b81cfbb9ab8efa647a3bfcc2b2b97a5f1b1fa71e
Context: https://github.com/xamarin/xamarin-android/pull/5748
Context: https://github.com/xamarin/xamarin-android/pull/5748#discussion_r634716239
Commit b81cfbb9 introduced `TypeDefinitionCache`, which caches
`TypeReference.Resolve()` invocations so as to speed things up.
Enter xamarin/xamarin-android#5748: we want to adopt some linker API
changes, and mono/linker's [`LinkContext` API][0] *also* has a
`TypeDefinition` cache construct.
Consequently, to "fully embrace" the new `LinkContext` API changes,
*large portions* of `Java.Interop.Tools.Cecil.dll` are copied so that
`LinkContext`'s caching can be used instead of `TypeDefinitionCache`'s
caching, because mono/linker doesn't use Java.Interop, and thus
can't use `TypeDefinitionCache`. …

[Java.Interop.Tools.*] IMetadataResolver not TypeDefinitionCache

---

Makefile
build-tools/automation/azure-pipelines.yaml

We've been seeing a NuGet restore issue when running prepare on a macOS
system with .NET 6 Preview 4 (or greater) installed:
Restoring packages for /Users/peter/source/java.interop/tools/logcat-parse/logcat-parse.csproj...
NU1202: Package Mono.CSharp 4.0.0.143 is not compatible with net6.0 (.NETCoreApp,Version=v6.0). Package Mono.CSharp 4.0.0.143 supports: net45 (.NETFramework,Version=v4.5)
...
Errors in /Users/peter/source/java.interop/tools/logcat-parse/logcat-parse.csproj
NU1202: Package Mono.CSharp 4.0.0.143 is not compatible with net6.0 (.NETCoreApp,Version=v6.0). Package Mono.CSharp 4.0.0.143 supports: net45 (.NETFramework,Version=v4.5)
This issue is no longer present in a newer version of Mono 6.12 which
includes MSBuild 16.10.

[build] Bump to Mono with MSBuild 16.10

---

tools/generator/Java.Interop.Tools.Generator.ObjectModel/JavadocInfo.cs

Context: #850 
When a parsing issue is hit when importing Javadoc info, an "error" is printed out like this:
```
Error (31:41): Syntax error, expected: #PCDATA, <tt>, <TT>, <i>, <I>, {@code, {@docRoot}, {@inheritDoc}, {@link, {@linkplain, {@literal, {@value}, {@value, UnknownHtmlElementStart, </tt>, </TT>, </i>, </I>, </p>, </P>, <p>, <P>, <pre>, <PRE>, @author, @apiSince, @deprecated, @deprecatedSince, @exception, @param, @return, @see, @serialData, @serialField, @since, @throws, @[unknown], @version
{@link #getCurrentTrackSelections()}}.</li>
```
This is intended to be informational, but this output format triggers the MSBuild error parsing regex, and is interpreted as an actual error, causing the build to fail.
Instead, we are going to prepend it as `JavadocImport-Error` so that …

[generator] Prepend 'JavadocImport-Error' so MSBuild doesn't pick it up as an actual error.

---

tests/generator-Tests/Unit-Tests/CodeGenerationOptionsTests.cs
tests/generator-Tests/Unit-Tests/ManagedTests.cs
tools/generator/CodeGenerationOptions.cs
tools/generator/Extensions/ManagedExtensions.cs
tools/generator/Java.Interop.Tools.Generator.Importers/CecilApiImporter.cs

Context: https://github.com/xamarin/java.interop/issues/850
When a user binds a library that contains an interface that implements another interface, we pull in all invokable members from both interfaces to create the `Invoker` type for the user's interface.  If the base interface is a referenced assembly, the information we are working from has been read in via Cecil.  Due to a bug caused by the combination of Cecil-read info and NRT generation, we will interpret the return types on the imported methods as always `nullable`, even for types like `void`, which results in the uncompilable `void?`.
Example from `AndroidX.Core.Core`:
```csharp
// In AndroidX.Core.Core
public interface AndroidX.Core.Internal.View.ISupportMenu : Android.Views.IMenu { ... }
// In Mono.Android.dll
public …
```

[generator] Ensure we don't generate unexpected NRT types, like 'void?'.

---

Directory.Build.props

Context: https://github.com/dotnet/sdk/issues/19050
xamarin-android is hitting this build error with .NET 6 Preview 7:
C:\src\xamarin-android\external\Java.Interop\src\Java.Interop\obj\Debug\net6.0\Java.Interop.ImplicitNamespaceImports.cs(2,1):
error CS8400: Feature 'global using directive' is not available in C# 8.0. Please use language version 10.0 or greater.
[C:\src\xamarin-android\external\Java.Interop\src\Java.Interop\Java.Interop.csproj]
In fact, you can reproduce this by doing:
dotnet new console
dotnet build -p:LangVersion=8.0
It seems like `@(Import)` item group should not be present unless the
project is C# 10 or higher?
For now, we can set `$(DisableImplicitNamespaceImports)` to workaround
the issue.

[build] set $(DisableImplicitNamespaceImports) by default

---

build-tools/scripts/cecil.projitems

Context: https://github.com/xamarin/xamarin-android/pull/6131
Changes: Unknown; can't find commit which matches 0.11.2.
xamarin/xamarin-android#6131 is currently failing to build due to a
Mono.Cecil version mismatch:
CSC : error CS1705: Assembly 'illink' with identity 'illink, Version=6.0.100.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'
uses 'Mono.Cecil, Version=0.11.4.0, Culture=neutral, PublicKeyToken=50cebf1cceb9d05e'
which has a higher version than referenced assembly
'Mono.Cecil' with identity 'Mono.Cecil, Version=0.11.3.0, Culture=neutral, PublicKeyToken=50cebf1cceb9d05e'
We thus need to bump all use of Mono.Cecil 0.11.2 to 0.11.4.
Unfortunately, at this point in time there's no way for
xamarin/xamarin-android to explicitly control which Mono.Cecil
NuGet package version is …

Bump to mono/linker/main@b888d67 Mono.Cecil 0.11.4

---

src/Java.Interop.Localization/Java.Interop.Localization.csproj
src/Java.Interop.Tools.Cecil/Java.Interop.Tools.Cecil.csproj
src/Java.Interop.Tools.Diagnostics/Java.Interop.Tools.Diagnostics.csproj
src/Java.Interop.Tools.JavaCallableWrappers/Java.Interop.Tools.JavaCallableWrappers.csproj
src/Xamarin.Android.Tools.Bytecode/Xamarin.Android.Tools.Bytecode.csproj

Fixes #862
Add StrongNames to the projects which are used by Xamarin.Android.Build.Tasks. This includes the dependencies.

Add StrongName to Projects used by Xamarin.Android.Build.Tasks

---

Directory.Build.props
tools/generator/SourceWriters/Attributes/RegisterAttr.cs

Context: https://github.com/dotnet/roslyn/issues/55564
Context: https://discord.com/channels/732297728826277939/732297837953679412/874959446747533323
Context: https://github.com/dotnet/runtime/issues/55992
Context: https://github.com/dotnet/sdk/issues/19653#issuecomment-896676414
Fix the Java.Interop build when .NET 6 Preview 7 is installed.
.NET 6 Preview 7 introduced a C# compiler regression: use of
[C#6 string interpolation][0] with `StringBuilder.Append()` when
`$(LangVersion)` < 10.0 results in a CS8400 error:
error CS8400: Feature 'interpolated string handlers' is not available in C# 8.0. Please use language version 10.0 or greater.
Because `azure-pipelines.yaml` specifies `DotNetCoreVersion: 6.0.x`,
our CI machines get auto-bumped to .NET 6 Preview 7, causing *all*
PR builds to now …

[build] .NET 6 P7 Support (#869)

---

src/Java.Interop/Java.Interop/JniRuntime.JniMarshalMemberBuilder.cs

Context: https://github.com/xamarin/xamarin-android/issues/5652
If you build a .NET 6 Android app:
dotnet new android
dotnet build -c Release -bl -p:SuppressTrimAnalysisWarnings=false
You get warnings like:
external\Java.Interop\src\Java.Interop\Java.Interop\JniRuntime.JniMarshalMemberBuilder.cs(53,4): warning IL2026: Java.Interop.JniRuntime.SetMarshalMemberBuilder(JniRuntime.CreationOptions): Using method 'System.Reflection.Assembly.GetType(String)' which has 'RequiresUnreferencedCodeAttribute' can break functionality when trimming application code. Types might be removed.
Adding this is not sufficient to fix the warning:
[DynamicDependency (DynamicallyAccessedMemberTypes.PublicParameterlessConstructor, "Java.Interop.MarshalMemberBuilder", "Java.Interop.Export")]
You also need to …

[Java.Interop] fix .NET 6 linker warnings

---

Directory.Build.props
src/Java.Interop/Directory.Build.targets
src/Java.Interop/Java.Interop-MonoAndroid.csproj

The commit 3e6a6232 added a new target 'BuildVersionInfo_g_cs' which is
responsible for generating the `BuildVersionInfo_g_cs` in the
`$(IntermediateOutputPath)`.
However it turns out the `$(IntermediateOutputPath)` has not been created when the target is
run, so we end up with the following error.
```
/mnt/vss/_work/1/s/xamarin-android/external/Java.Interop/src/Java.Interop/Directory.Build.targets(44,5): error MSB4018: The "GenerateVersionFile" task failed unexpectedly. [/mnt/vss/_work/1/s/xamarin-android/external/Java.Interop/src/Java.Interop/Java.Interop-MonoAndroid.csproj]
/mnt/vss/_work/1/s/xamarin-android/external/Java.Interop/src/Java.Interop/Directory.Build.targets(44,5): error MSB4018: System.IO.DirectoryNotFoundException: Could not find a part of the path …
```

[build] Fix 'BuildVersionInfo_g_cs' build target.

---

src/Xamarin.Android.Tools.AnnotationSupport/Objects/AnnotatedItem.cs
src/Xamarin.Android.Tools.AnnotationSupport/Objects/AnnotationData.cs

Context: https://github.com/xamarin/xamarin-android/pull/6300
A confluence of several "funny" things happened with
xamarin/xamarin-android#6300, which attempts to use the Android SDK
platform-tools 31.0.3 package, up from 30.0.2:
1. The new platform-tools package *removes* the file
`platform-tools/api/annotations.zip`.  To work around that, we
need to instead use the `data/annotations.zip` file from the
Android platform directory, e.g.
`$ANDROID_SDK_ROOT/platforms/android-30/data/annotations.zip`.
2. Between API-28 and API-29, `annotations.zip` changes the package
name used for annotations, from e.g.
`android.support.annotation.RequiresPermission` to
`androidx.annotation.RequiresPermission`.
In isolation, okay, but then we hit:
3. `AnnotationData` *removes* the "known" package-prefix of …

[generator] Remove androidx.annotation from Annotation names

---

src/Java.Interop.Localization/Java.Interop.Localization.csproj
tools/class-parse/class-parse.csproj
tools/generator/generator.csproj
tools/jcw-gen/jcw-gen.csproj
tools/jnimarshalmethod-gen/Xamarin.Android.Tools.JniMarshalMethodGenerator.csproj
tools/logcat-parse/logcat-parse.csproj
tools/param-name-importer/param-name-importer.csproj

- Bump `XliffTasks` to `1.0.0-beta.20420.1` to match [`xamarin-android-tools`](https://github.com/xamarin/xamarin-android-tools/blob/main/src/Xamarin.Android.Tools.AndroidSdk/Xamarin.Android.Tools.AndroidSdk.csproj#L37).
- Bump `Mono.Options` to `6.6.0.161` to match [`xamarin-android`](https://github.com/xamarin/xamarin-android/blob/bcc315857f2cd61351ba469973043d91c902c50e/Directory.Build.props#L36).

Bump various NuGets to match related repositories.

---

src/Xamarin.Android.Tools.AnnotationSupport/Objects/AnnotationData.cs
tools/generator/ManagedTypeFinderGeneratorTypeSystem.cs

Context: #885 
When updating to the latest `annotations.zip` file, some `Mono.Android.dll` members are getting multiple `[RequiresPermission]` attributes applied.  This is because the `.zip` contains the following entries:
```xml
<item name="android.os.Vibrator void vibrate(android.os.VibrationEffect)">
<annotation name="androidx.annotation.RequiresPermission">
<val name="value" val="&quot;android.permission.VIBRATE&quot;" />
</annotation>
</item>
<item name="android.os.Vibrator void vibrate(long)">
<annotation name="androidx.annotation.RequiresPermission">
<val name="value" val="&quot;android.permission.VIBRATE&quot;" />
</annotation>
</item>
```
Which correspond to these overloads:
```csharp
public virtual void Vibrate (Android.OS.VibrationEffect vibe);
public virtual void Vibrate (long …
```

[generator] Remove buggy annotation loose match.

---

build-tools/scripts/AssemblyInfo.g.cs.in
build-tools/scripts/VersionInfo.targets

Context: #894 
Setting `<Version>0.1.0.0</Version>` causes us to generate:
```chsarp
[assembly: AssemblyVersion("0.1.0.0")]
[assembly: AssemblyFileVersion("0.1.0.0.0")]
```
because of the extra tuple added to `AssemblyFileVersion` in `AssemblyInfo.g.cs.in`:
```csharp
[assembly: System.Reflection.AssemblyFileVersionAttribute("@VERSION@.0")]
[assembly: System.Reflection.AssemblyVersionAttribute("@VERSION@")]
```
This is fine from an assembly reference standpoint because it uses `[AssemblyVersion]`, but `[AssemblyFileVersion]` isn't a valid file version and Windows can't parse it:
Instead, set `@VERSION@` to always use a 4-tuple, and remove the extra tuple added to `AssemblyFileVersion`.
This creates the expected information for both hard-coded version assemblies:
and auto-versioned …

[Java.Interop{,Export}] Set <Version> to 0.1.0.

---

tests/generator-Tests/expected.ji/Adapters/Java.Interop.__TypeRegistrations.cs
tests/generator-Tests/expected.ji/Android.Graphics.Color/Java.Interop.__TypeRegistrations.cs
tests/generator-Tests/expected.ji/Arrays/Java.Interop.__TypeRegistrations.cs
tests/generator-Tests/expected.ji/Constructors/Java.Interop.__TypeRegistrations.cs
tests/generator-Tests/expected.ji/InterfaceMethodsConflict/Java.Interop.__TypeRegistrations.cs
tests/generator-Tests/expected.ji/NestedTypes/Java.Interop.__TypeRegistrations.cs
tests/generator-Tests/expected.ji/NonStaticFields/Java.Interop.__TypeRegistrations.cs
tests/generator-Tests/expected.ji/NormalMethods/Java.Interop.__TypeRegistrations.cs
tests/generator-Tests/expected.ji/NormalProperties/Java.Interop.__TypeRegistrations.cs
tests/generator-Tests/expected.ji/ParameterXPath/Java.Interop.__TypeRegistrations.cs
tests/generator-Tests/expected.ji/StaticFields/Java.Interop.__TypeRegistrations.cs
tests/generator-Tests/expected.ji/StaticMethods/Java.Interop.__TypeRegistrations.cs
tests/generator-Tests/expected.ji/StaticProperties/Java.Interop.__TypeRegistrations.cs
tests/generator-Tests/expected.ji/Streams/Java.Interop.__TypeRegistrations.cs
tests/generator-Tests/expected.ji/TestInterface/Java.Interop.__TypeRegistrations.cs
tests/generator-Tests/expected.ji/java.lang.Enum/Java.Interop.__TypeRegistrations.cs
tests/generator-Tests/expected.ji/java.lang.Object/Java.Interop.__TypeRegistrations.cs
tests/generator-Tests/expected.ji/java.util.List/Java.Interop.__TypeRegistrations.cs
tests/generator-Tests/expected/EnumerationFixup/Java.Interop.__TypeRegistrations.cs
tests/generator-Tests/expected/InterfaceMethodsConflict/Java.Interop.__TypeRegistrations.cs
tests/generator-Tests/expected/java.lang.Object/Java.Interop.__TypeRegistrations.cs
tools/generator/Java.Interop.Tools.Generator.ObjectModel/ClassGen.cs

Building a .NET MAUI app with `-p:SuppressTrimAnalysisWarnings=false
-p:TrimmerSingleWarn=false` shows the warning:
src\Compatibility\Android.FormsViewGroup\src\obj\Release\net6.0-android\generated\src\Java.Interop.__TypeRegistrations.cs(35,4):
error IL2057: Java.Interop.__TypeRegistrations.Lookup(String[],String): Unrecognized value passed to the parameter 'typeName' of method 'System.Type.GetType(String)'. It's not possible to guarantee the availability of the target type.
This code path should not even be used normally. It is only called
when running inside the Android designer.
For now, let's simply emit an extra attribute to ignore the warning:
[System.Diagnostics.CodeAnalysis.UnconditionalSuppressMessage("Trimming", "IL2057")]
This attribute was added in .NET 5, so we can always …

[generator] emit UnconditionalSuppressMessage in __TypeRegistrations

---

src/Xamarin.Android.Tools.Bytecode/Methods.cs
tests/Xamarin.Android.Tools.Bytecode-Tests/JavaTypeNoParametersTests.cs
tests/Xamarin.Android.Tools.Bytecode-Tests/Resources/JavaTypeNoParameters.xml
tests/Xamarin.Android.Tools.Bytecode-Tests/Xamarin.Android.Tools.Bytecode-Tests.csproj
tests/Xamarin.Android.Tools.Bytecode-Tests/Xamarin.Android.Tools.Bytecode-Tests.targets
tests/Xamarin.Android.Tools.Bytecode-Tests/java/com/xamarin/JavaTypeNoParameters.java

Context: 8ccb8374d242490d8d1b032f2c8ca7a813fd40f3
Context: https://github.com/xamarin/AndroidX/pull/413
Context: https://discord.com/channels/732297728826277939/732297837953679412/902301741159182346
Context: https://repo1.maven.org/maven2/org/jetbrains/kotlin/kotlin-stdlib/1.5.31/kotlin-stdlib-1.5.31.jar
Context: https://discord.com/channels/732297728826277939/732297837953679412/902554256035426315
xamarin/AndroidX#413 ran into an issue:
D:\a\1\s\generated\org.jetbrains.kotlin.kotlin-stdlib\obj\Release\net6.0-android\generated\src\Kotlin.Coroutines.AbstractCoroutineContextElement.cs(100,8):
error CS1002: ; expected
The offending line:
var this = Java.Lang.Object.GetObject<Java.Lang.Object> (native_this, JniHandleOwnership.DoNotTransfer);
(Assigning to `this` makes for a very weird error …

[class-parse] Loosely match parameter names, backwards

---

tools/generator/Java.Interop.Tools.Generator.ObjectModel/JavadocInfo.cs
tools/generator/Java.Interop.Tools.Generator.Transformation/JavadocFixups.cs
tools/generator/SourceWriters/BoundProperty.cs

Fixes: https://github.com/xamarin/java.interop/issues/905
Property getters and setters will no longer automatically include
copyright info in their generated `<remarks>` elements.  Instead, this
copyright data will be appended to the `<remarks>` element after
`<remarks>` merging is complete.
The custom `<summary>` and `<remarks>` merging that happens for
properties will now also use Nodes instead of DescendantNodes to avoid
content duplication.

[generator] Improve Javadoc remarks on properties

---

build-tools/automation/azure-pipelines.yaml

Now that VS2019 doesn't ***officially*** support .NET 6, we are getting lots of warnings trying to build out `net6.0` assemblies on VS2019 build agents:
```
Warning NETSDK1182: Targeting .NET 6.0 in Visual Studio 2019 is not supported.
Warning CS8032: An instance of analyzer System.Text.Json.SourceGeneration.JsonSourceGenerator cannot be created from C:\hostedtoolcache\windows\dotnet\packs\Microsoft.NETCore.App.Ref\6.0.0\analyzers\dotnet\cs\System.Text.Json.SourceGeneration.dll : Could not load file or assembly 'Microsoft.CodeAnalysis, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified..
```
[DevOps now offers VS2022 build agents](https://docs.microsoft.com/en-us/azure/devops/pipelines/agents/hosted) we …

[ci] Update to VS2022 build agents.

---

src/Java.Interop.Tools.Cecil/Java.Interop.Tools.Cecil/NullableReferenceTypesRocks.cs
tests/generator-Tests/Unit-Tests/ManagedTests.cs
tests/generator-Tests/generator-Tests.csproj
tools/generator/Extensions/ManagedExtensions.cs
tools/generator/Java.Interop.Tools.Generator.Importers/CecilApiImporter.cs

Fixes: https://github.com/xamarin/java.interop/issues/857
Implement enough of [decoding C# NRT attributes](https://github.com/dotnet/roslyn/blob/main/docs/features/nullable-metadata.md) to support our use case.
This will allow us to better generate members that match nullability of members they are overriding/implementing when the base member is coming from a managed assembly.

[generator] Import NRT data from managed assemblies.

---

src/Java.Interop.Tools.JavaTypeSystem/Adapters/JavaXmlApiImporter.cs

While testing the new JavaTypeSystem on AndroidX, the api-diff was reporting various constructors had been removed:
Removed constructor:
```csharp
public Registry.NoModelLoaderAvailableException (Java.Lang.Object model, System.Collections.IList matchingButNotHandlingModelLoaders);
```
Investigating let to realizing Java constructors can have generic type parameters:
```java
public static class NoModelLoaderAvailableException extends MissingComponentException {
public <M> NoModelLoaderAvailableException(
@NonNull M model, @NonNull List<ModelLoader<M, ?>> matchingButNotHandlingModelLoaders) {
super(
"Found ModelLoaders for model class: "
+ matchingButNotHandlingModelLoaders
+ ", but none that handle this specific model instance: "
+ model);
}
``` …

[JavaTypeSystem] Support importing constructor generic type parameters from class-parse XML files.

---

src/Xamarin.Android.Tools.Bytecode/ClassPath.cs
src/Xamarin.Android.Tools.Bytecode/JavaDocumentScraper.cs
src/Xamarin.Android.Tools.Bytecode/JavaParameterNamesLoader.cs
tests/Xamarin.Android.Tools.Bytecode-Tests/ParameterFixupTests.cs
tests/Xamarin.Android.Tools.Bytecode-Tests/Resources/ParameterFixup_JavaInterfaceNoParameters.xml
tests/Xamarin.Android.Tools.Bytecode-Tests/Resources/ParameterFixup_JavaInterfaceNoParameters_JavaSourceUtils.xml
tests/Xamarin.Android.Tools.Bytecode-Tests/Xamarin.Android.Tools.Bytecode-Tests.csproj
tests/Xamarin.Android.Tools.Bytecode-Tests/java/com/xamarin/JavaInterfaceNoParameters.java
tools/java-source-utils/src/main/java/com/microsoft/android/JniPackagesInfoFactory.java
tools/java-source-utils/src/test/resources/UnresolvedTypes.txt
tools/java-source-utils/src/test/resources/UnresolvedTypes.xml

Fixes: https://github.com/xamarin/java.interop/issues/920
Context: 69e1b80afd81ac502494e4bc2a2de75f5171c73f
`java-source-utils.jar` isn't always able to fully resolve types.
When it is unable to do so, it uses an "alternate encoding":
> In some scenarios, types won't be resolvable.  What should output be?
>
> We don't want to *require* that everything be resolvable -- it's painful, and
> possibly impossible, e.g. w/ internal types -- so instead we should "demark"
> the unresolvable types.
>
> `.params.txt` output will use `.*` as a type prefix, e.g.
>
>         method(.*UnresolvableType foo, int bar);
>
> `docs.xml` will output `L.*UnresolvableType;`.
The problem is that `class-parse --parameter-names=PATH` didn't check
for this "unresolvable type" pattern, so if you had a method which …

[class-parse] Import parameter names for unresolvable types

---

src/Xamarin.Android.Tools.Bytecode/ClassPath.cs
src/Xamarin.Android.Tools.Bytecode/JavaDocumentScraper.cs

Context: 77c9c5fa617f50817eda3d358e881f437165c07d
Commit 77c9c5fa inadvertently introduced nullability warnings:
…\Xamarin.Android.Tools.Bytecode\ClassPath.cs(308,89): warning CS8600: Converting null literal or possible null value to non-nullable type.
…\Xamarin.Android.Tools.Bytecode\ClassPath.cs(308,54): warning CS8604: Possible null reference argument for parameter 'jniType' in 'JavaMethodParameterTypeInfo.JavaMethodParameterTypeInfo(string jniType, string javaType)'.
…\Xamarin.Android.Tools.Bytecode\ClassPath.cs(308,89): warning CS8604: Possible null reference argument for parameter 'javaType' in 'JavaMethodParameterTypeInfo.JavaMethodParameterTypeInfo(string jniType, string javaType)'.
…\Xamarin.Android.Tools.Bytecode\ClassPath.cs(318,8): warning CS8600: Converting null literal or …

[Xamarin.Android.Tools.Bytecode] Fix Nullability warnings

---

src/Java.Interop.Tools.JavaTypeSystem/JavaModels/JavaTypeModel.cs
tests/Java.Interop.Tools.JavaTypeSystem-Tests/Java.Interop.Tools.JavaTypeSystem-Tests.csproj
tests/Java.Interop.Tools.JavaTypeSystem-Tests/JavaTypeCollectionTests.cs

Fixes #815.
Given Java like this:
```java
public class MyClass<T>
{
public class MyNestedClass<U>
{
public void DoT (T value) { }
public void DoU (U value) { }
}
}
```
`ApiXmlAdjuster` does not look for generic parameter types on parent types, resulting in the method `DoT` being removed:
```
api.xml.class-parse : warning BG8605: The Java type 'T' could not be found (are you missing a Java reference jar/aar or a Java binding library NuGet?)
```
java-resolution-report.log:
```
==== Cycle 1 ====
The method '[Method] void DoT(T p0)' was removed because the Java parameter type 'T' could not be found.
```
`JavaTypeSystem` supports this, but it was initially disabled to help ensure that it was producing the same output as `ApiXmlAdjuster` for testing purposes.  We can now enable it.

[JavaTypeSystem] Enable resolving generic types on declaring types.

---

tools/logcat-parse/Program.cs

`logcat-parse` didn't properly deal with execution on Windows; when
specifying a Windows-style path on Windows:
> cd "%ProgramFiles(x86)%\Microsoft Visual Studio\2019\Enterprise\MSBuild\Xamarin\Android"
> .\logcat-parse.exe \path\to\my\grefs.txt
var grefs = Grefs.Parse("\path\to\my\grefs.txt");
(1,52): error CS1009: Unrecognized escape sequence `\p'
(1,60): error CS1009: Unrecognized escape sequence `\m'
(1,63): error CS1009: Unrecognized escape sequence `\g'
`logcat-parse` could still be used, but you'd either have to use `/`
instead of `\`, or invoke `logcat-parse` from where `grefs.txt` is:
> cd \path\to\my
> "%ProgramFiles(x86)%\Microsoft Visual Studio\2019\Enterprise\MSBuild\Xamarin\Android\logcat-parse.exe" ^
grefs.txt
// `adb logcat` GREF parsing utility
//
// Use …

[logcat-parse] Use C# verbatim strings for paths

---

build-tools/automation/azure-pipelines.yaml
build-tools/automation/templates/core-tests.yaml
build-tools/automation/templates/publish-test-results.yaml
build-tools/scripts/RunNUnitTests.targets
tools/java-source-utils/src/main/java/com/microsoft/android/JavadocXmlGenerator.java
tools/java-source-utils/src/main/resources/transform-style.xsl
tools/java-source-utils/src/test/java/com/microsoft/android/JavadocXmlGeneratorTest.java
tools/java-source-utils/src/test/java/com/microsoft/android/ParameterNameGeneratorTest.java

I've seen inconsistent XML output from java-source-utils when running on
macOS vs. Windows, or JDK 8 vs. JDK 11.  On Windows I've seen extra
carriage returns in CDATA blocks, and when using JDK 9+ we've seen
additional new lines added between XML elements.
An XSL style sheet can be used to improve the formatting consistency of
the XML that is produced.  This should prevent us from generating
inconsistent API docs across macOS and Windows.
There is still [an outstanding issue][0] concerning CDATA blocks between
JDK 8 and JDK 11 that I have not yet been able to sort out.  This issue
has seemingly been "fixed" in JDK 14.
[0]: https://stackoverflow.com/questions/55853220/handling-change-in-newlines-by-xml-transformation-for-cdata-from-java-8-to-java

[java-source-utils] Transform XML using XSLT

---

Directory.Build.props

Turn on `<TreatWarningsAsErrors>` for `Release` builds only.
Also, Mono's `net6.0` (MSBuild 16) support causes warnings so we aren't going to enable it there.
```
warning NETSDK1182: Targeting .NET 6.0 in Visual Studio 2019 is not supported. 
warning CS8032: An instance of analyzer System.Text.Json.SourceGeneration.JsonSourceGenerator cannot be created from /Users/runner/hostedtoolcache/dotnet/packs/Microsoft.NETCore.App.Ref/6.0.0/analyzers/dotnet/cs/System.Text.Json.SourceGeneration.dll : Could not resolve type with token 01000027 from typeref (expected class 'Microsoft.CodeAnalysis.IIncrementalGenerator' in assembly 'Microsoft.CodeAnalysis, Version=4.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35') assembly:Microsoft.CodeAnalysis, Version=4.0.0.0, Culture=neutral, …
```

[Java.Interop] Treat warnings as errors.

---

src/Java.Interop.Tools.Generator/Enumification/ConstantEntry.cs
src/Java.Interop.Tools.Generator/Enumification/MethodAction.cs
src/Java.Interop.Tools.Generator/Enumification/MethodMapEntry.cs
src/Java.Interop.Tools.Generator/Enumification/MethodMapParser.cs
src/Java.Interop.Tools.Generator/Utilities/NamingConverter.cs

A few helper methods used for dealing with the enumification process.
The main function is a reader/writer for "Method Maps", ie: https://github.com/xamarin/xamarin-android/blob/main/src/Mono.Android/methodmap.csv.
Implemented to allow sharing logic between `generator` and [BindingStudio](https://github.com/jpobst/BindingStudio).  Currently `generator` does not use this logic, but the idea is to eventually standardize it on this common implementation.

Add some enumification helper methods.

---

Makefile
build-tools/automation/azure-pipelines.yaml
build-tools/automation/templates/core-tests.yaml
build-tools/automation/templates/publish-test-results.yaml

Add `testRunTitle` information to our .NET tests so they are easier to read in the Azure Pipelines Test tab.
Additionally, auditing the test suites we run revealed we are not currently running `Java.Interop.Tools.JavaTypeSystem-Tests`, so this test suite was also added to CI.

[ci] Use descriptive test run titles.

---

tools/generator/Java.Interop.Tools.Generator.Transformation/JavadocFixups.cs

Fixes: https://github.com/xamarin/java.interop/issues/933
Fixes a bug when attempting to find the `<javadoc/>` element that is
associated with a specific member name and jni-signature.  When a type
contained multiple members with the same name, we would always return
the first `<javadoc/>` that matched the member name, rather than the
one that matched both the name and signature.

[generator] Use the correct javadoc element

---

tools/generator/Java.Interop.Tools.Generator.ObjectModel/JavadocInfo.cs

Fixes: https://github.com/xamarin/java.interop/issues/931
Fixes: https://github.com/xamarin/java.interop/issues/932
We have a handful of issues in the https://developer.android.com/ links
that are generated for various type members with complex parameters.
Collections, varargs, and generics are some examples of items that are
not translated correctly when generating the parameter portion of the
reference documentation URL.
The javadoc that we generate for Mono.Android contains `<parameter/>`
elements under all relevant methods.  These elements contain attributes
with additional type data; for instance:
```xml
<method jni-return="Landroid/animation/ObjectAnimator;" jni-signature="(Ljava/lang/Object;Landroid/util/Property;Landroid/util/Property;Landroid/graphics/Path;)Landroid/animation/Obje …
```

[generator] Fix parameter string in ref doc links

---

build-tools/jnienv-gen/Generator.cs
tests/invocation-overhead/invocation-overhead.cs
tests/invocation-overhead/invocation-overhead.csproj
tests/invocation-overhead/jni.cs

Context: 926e4bc46ede2cad861d199a5f4290195488a5af
Context: https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/proposals/csharp-9.0/function-pointers
Context? https://github.com/xamarin/java.interop/issues/666
Commit 926e4bc4 allowed `jnienv-gen` to emit multiple different
JNIEnv invocation strategies at the same time, allowing
`tests/invocation-overhead` to try them "all at once" for side-by-
side comparisons.
Add support for JNIEnv invocation strategy which relies on
C#9 Function Pointers, a'la:
partial struct JNIEnv {
public  delegate* unmanaged <IntPtr /* env */, jobject> ExceptionOccurred;
}
partial class JniEnvironment {
partial class Exceptions {
public static unsafe JniObjectReference ExceptionOccurred ()
{
IntPtr __env = JniEnvironment.EnvironmentPointer;
var tmp = …

[jnienv-gen] Add possible C#9 function pointer backend

---

src/Java.Interop.Tools.JavaSource/Java.Interop.Tools.JavaSource/SourceJavadocToXmldocGrammar.InlineTagsBnfTerms.cs
tests/Java.Interop.Tools.JavaSource-Tests/SourceJavadocToXmldocGrammar.InlineTagsBnfTermsTests.cs

Partially fixes: https://github.com/xamarin/java.interop/issues/907
Replaces `[TODO: @tag]` values in generated docs with `To be added` to
better mirror mdoc behavior for missing elements.
Inline `{@value }` tags that contain an argument have been updated to
display the argument in a `<c/>` block.  These should be fixed to use
an appropriate CREF element in the future, see https://github.com/xamarin/java.interop/issues/843.
The last remaining `[TODO: @{docRoot}]` output will be fixed as part of
https://github.com/xamarin/java.interop/pull/930.

[Java.Interop.Tools.JavaSource] Replace TODO with To be added

---

src/Java.Interop.Tools.JavaSource/Java.Interop.Tools.JavaSource/SourceJavadocToXmldocGrammar.HtmlBnfTerms.cs
src/Java.Interop.Tools.JavaSource/Java.Interop.Tools.JavaSource/SourceJavadocToXmldocGrammar.InlineTagsBnfTerms.cs
src/Java.Interop.Tools.JavaSource/Java.Interop.Tools.JavaSource/SourceJavadocToXmldocGrammar.cs
src/Java.Interop.Tools.JavaSource/Java.Interop.Tools.JavaSource/SourceJavadocToXmldocParser.cs
src/Java.Interop.Tools.JavaSource/Java.Interop.Tools.JavaSource/XmldocSettings.cs
tests/Java.Interop.Tools.JavaSource-Tests/SourceJavadocToXmldocGrammar.HtmlBnfTermsTests.cs
tests/Java.Interop.Tools.JavaSource-Tests/SourceJavadocToXmldocGrammar.InlineTagsBnfTermsTests.cs
tests/Java.Interop.Tools.JavaSource-Tests/SourceJavadocToXmldocGrammarFixture.cs
tests/Java.Interop.Tools.JavaSource-Tests/SourceJavadocToXmldocParserTests.cs
tools/generator/Java.Interop.Tools.Generator.ObjectModel/JavadocInfo.cs
tools/java-source-utils/src/main/java/com/microsoft/android/App.java
tools/java-source-utils/src/main/java/com/microsoft/android/JavaSourceUtilsOptions.java
tools/java-source-utils/src/main/java/com/microsoft/android/JavadocXmlGenerator.java

Context: https://docs.microsoft.com/en-us/dotnet/api/android.app.backup.backupagent.onrestore?view=xamarin-android-sdk-12#Android_App_Backup_BackupAgent_OnRestore_Android_App_Backup_BackupDataInput_System_Int64_Android_OS_ParcelFileDescriptor_
Context: https://docs.microsoft.com/en-us/dotnet/api/android.animation.animatorlisteneradapter.onanimationend?view=xamarin-android-sdk-12#definition
Partially fixes: https://github.com/xamarin/java.interop/issues/907
Support for `{@ docRoot}` has been added, and an additional
parser for `<a href/>` elements has been added to convert
these to `<see/>` elements.

[Java.Interop.Tools.JavaSource] Add {@ docRoot} support

---

src/Xamarin.Android.Tools.Bytecode/JavaDocumentScraper.cs

Context: https://github.com/xamarin/xamarin-android/pull/6662
The `@(JavaSourceJar)` item supports the following metadata:
<JavaSourceJar Include="javasourcejartest-sources.jar" >
<CopyrightFile>$(MSBuildThisFileDirectory)javadoc-copyright.xml</CopyrightFile>
<UrlPrefix>https://developer.android.com/reference</UrlPrefix>
<UrlStyle>developer.android.com/reference@2020-Nov</UrlStyle>
<DocRootUrl>https://developer.android.com</DocRootUrl>
</JavaSourceJar>
If a copyright file is provided which contains more than 500 characters
the type of the documentation file will not be correctly identified.
This results in the following build error:
Task "ClassParse" (TaskId:143)
Task Parameter:ToolPath=C:\Users\cloudtest\android-toolchain\dotnet\packs\Microsoft.Android.Sdk.Windows\31.0.200-ci.pr.gh6662.38 …

[Xamarin.Android.Tools.Bytecode] Extend api xml doc type detection

---

build-tools/automation/azure-pipelines.yaml

Context: https://eng.ms/docs/initiatives/executive-order/executive-order-requirements/executiveorderoncybersecurity/buildinfraops
As part of ongoing security and compliance efforts:
- Move our official macOS build to the `internal-macos-11` build pool
- Move our official Windows build to the `AzurePipelinesWindows2022compliant` build pool

[ci] Move CI builds to 1ES's hardened images.

---

src/Java.Interop/Java.Interop-MonoAndroid.csproj

Context: https://github.com/xamarin/xamarin-android/pull/6799
xamarin/xamarin-android#6799 is missing `Java.Interop.pdb` when
building in `Release` mode. I suspect this is due to `$(DebugType)`
set to `full`. This creates `Java.Interop.dll.mdb`!
The modern approach is to use `portable` for both `Debug` and
`Release` builds, so we should just use that.

[Java.Interop] use $(DebugType) portable

---

tests/generator-Tests/Unit-Tests/CodeGenerationOptionsTests.cs
tools/generator/CodeGenerationOptions.cs

Context: https://github.com/xamarin/java.interop/issues/955
Primitive types are not nullable in Java, thus we do not default them to nullable when using NRT in `generator`.  However, when we added Kotlin's unsigned primitive types we did not special case them to not-nullable like the existing primitive types.
This causes compilation errors when trying to enable `nullable` when binding Kotlin stdlib:
```csharp
// Metadata.xml XPath method reference: path="/api/package[@name='kotlin.random']/class[@name='URandomKt']/method[@name='nextUInt-qCasIEU' and count(parameter)=2 and parameter[1][@type='kotlin.random.Random'] and parameter[2][@type='uint']]"
[Register ("nextUInt-qCasIEU", "(Lkotlin/random/Random;I)I", "")]
public static unsafe uint? NextUInt (global::Kotlin.Random.Random obj, uint? …
```

[generator] Unsigned primitive types should not be nullable.

---

build-tools/Java.Interop.BootstrapTasks/Java.Interop.BootstrapTasks.targets

Context: cbd966686e2a3179cf3e6285990302c6b7afab21
Context: http://aka.ms/maui-schedule
Context: https://github.com/xamarin/xamarin-android-tools/commit/f0b3abdb7600bc47be8696bab2c170d849283f06
The hope with commit cbd96668 was that we could "fix" an oversight
in our ".NET 6 Story": `Java.Interop.dll` *should* have a version
which matches the .NET SDK version, or at least *doesn't* match the
"Classic" Xamarin.Android version, to better support future expected
API changes to `Java.Interop.dll`.
Unfortunately, this change didn't make it before .NET 6 went stable
in [2021-November][0], meaning the `net6.0-android` and
`net6.0-android31.0` target frameworks are "set in stone" to target
API-31.
My *hope* had been that we could implicitly "pull a mulligan",
fix the `Java.Interop.dll` assembly …

[Java.Interop] net6.0 is Version=v0.1.0.0

---

src/Java.Interop/Java.Interop-MonoAndroid.csproj

We are setting `<Version>0.1.0.0</Version>` in `Java.Interop-MonoAndroid.csproj`, which is correct.  However immediately after that we `<Import Project="..\..\Directory.Build.props" />` which defaults projects to `<Version>$(JIUtilityVersion)</Version>`.
This commit reorders the `.csproj` to set the `<Version>` in the project *after* the import.

[Java.Interop-MonoAndroid.csproj] Set Version after Directory.Build.props

---

tests/generator-Tests/Unit-Tests/CodeGeneratorExpectedResults/Common/WriteInterfaceMethodInvokers.txt
tests/generator-Tests/Unit-Tests/CodeGeneratorExpectedResults/Common/WriteInterfaceMethodInvokersWithSkips.txt
tests/generator-Tests/Unit-Tests/CodeGeneratorExpectedResults/Common/WriteInterfacePropertyInvokers.txt
tests/generator-Tests/Unit-Tests/CodeGeneratorExpectedResults/Common/WriteInterfacePropertyInvokersWithSkips.txt
tests/generator-Tests/Unit-Tests/CodeGeneratorExpectedResults/XAJavaInterop1-NRT/WriteClass.txt
tests/generator-Tests/Unit-Tests/CodeGeneratorExpectedResults/XAJavaInterop1-NRT/WriteInterface.txt
tests/generator-Tests/Unit-Tests/CodeGeneratorExpectedResults/XAJavaInterop1/WriteClass.txt
tests/generator-Tests/Unit-Tests/CodeGeneratorExpectedResults/XAJavaInterop1/WriteInterface.txt
tests/generator-Tests/Unit-Tests/CodeGeneratorExpectedResults/XamarinAndroid/WriteClass.txt
tests/generator-Tests/Unit-Tests/CodeGeneratorExpectedResults/XamarinAndroid/WriteClassConstructors.txt
tests/generator-Tests/Unit-Tests/CodeGeneratorExpectedResults/XamarinAndroid/WriteClassMethods.txt
tests/generator-Tests/Unit-Tests/CodeGeneratorExpectedResults/XamarinAndroid/WriteClassProperties.txt
tests/generator-Tests/Unit-Tests/CodeGeneratorExpectedResults/XamarinAndroid/WriteFieldSetBody.txt
tests/generator-Tests/Unit-Tests/CodeGeneratorExpectedResults/XamarinAndroid/WriteFieldString.txt
tests/generator-Tests/Unit-Tests/CodeGeneratorExpectedResults/XamarinAndroid/WriteInterface.txt
tests/generator-Tests/Unit-Tests/CodeGeneratorExpectedResults/XamarinAndroid/WriteInterfaceInvoker.txt
tests/generator-Tests/expected.xaji/CSharpKeywords/Xamarin.Test.CSharpKeywords.cs
tests/generator-Tests/expected.xaji/GenericArguments/Com.Google.Android.Exoplayer.Drm.FrameworkMediaCrypto.cs
tests/generator-Tests/expected.xaji/GenericArguments/Com.Google.Android.Exoplayer.Drm.IExoMediaCrypto.cs
tests/generator-Tests/expected.xaji/NormalMethods/Xamarin.Test.SomeObject.cs
tests/generator-Tests/expected.xaji/NormalProperties/Xamarin.Test.SomeObject.cs
tests/generator-Tests/expected.xaji/StaticProperties/Xamarin.Test.SomeObject.cs
tests/generator-Tests/expected.xaji/TestInterface/Test.ME.GenericStringPropertyImplementation.cs
tests/generator-Tests/expected/CSharpKeywords/Xamarin.Test.CSharpKeywords.cs
tests/generator-Tests/expected/NormalMethods/Xamarin.Test.SomeObject.cs
tests/generator-Tests/expected/NormalProperties/Xamarin.Test.SomeObject.cs
tests/generator-Tests/expected/StaticProperties/Xamarin.Test.SomeObject.cs
tests/generator-Tests/expected/TestInterface/Test.ME.GenericStringPropertyImplementation.cs
tools/generator/Java.Interop.Tools.Generator.ObjectModel/Symbols/StringSymbol.cs

Fixes: #967 
Context: https://github.com/xamarin/AndroidX/pull/512
If you need to change a `string` to JLO for a method parameter, the generated code produces a CS1503 error because it generates this code:
```csharp
// Metadata.xml XPath method reference: path="/api/package[@name='androidx.activity.result.contract']/class[@name='ActivityResultContracts.RequestPermission']/method[@name='createIntent' and count(parameter)=2 and parameter[1][@type='android.content.Context'] and parameter[2][@type='java.lang.String']]"
[Register ("createIntent", "(Landroid/content/Context;Ljava/lang/String;)Landroid/content/Intent;", "")]
public override unsafe global::Android.Content.Intent CreateIntent (global::Android.Content.Context context, global::Java.Lang.Object input)
{
const string __id = …
```

[generator] Add string cast to prevent CS1503.

---

Directory.Build.props
tools/generator/generator.slnf

Context: https://github.com/NuGet/Home/issues/6461
Trying to build `Java.Interop.csproj` in Visual Studio currently fails with several errors like:
```
Error NETSDK1005 Assets file 'C:\code\xamarin-android\external\Java.Interop\tools\generator\obj\project.assets.json' 
doesn't have a target for 'net6.0'. Ensure that restore has run and that you have included 'net6.0' in the 
TargetFrameworks for your project.
```
Even though we don't build NuGet packages, it still attempts to calculate the NuGet package name, which includes the assembly `$(Version)` if `$(PackageVersion)` isn't specified. Because our assemblies have different versions per-TFM, that causes a problem because the package can't have multiple versions in it.  
We can set a dummy `$(PackageVersion)` because we don't actually …

[Directory.Build.props] Set a dummy PackageVersion to work around VS/NuGet issue

---

tests/generator-Tests/Unit-Tests/CodeGeneratorExpectedResults/JavaInterop1/WriteMethodWithCharSequenceArrays.txt
tests/generator-Tests/Unit-Tests/CodeGeneratorExpectedResults/JavaInterop1/WriteObjectField.txt
tests/generator-Tests/Unit-Tests/CodeGeneratorExpectedResults/XAJavaInterop1-NRT/WriteMethodWithCharSequenceArrays.txt
tests/generator-Tests/Unit-Tests/CodeGeneratorExpectedResults/XAJavaInterop1-NRT/WriteObjectField.txt
tests/generator-Tests/Unit-Tests/CodeGeneratorExpectedResults/XAJavaInterop1/WriteMethodWithCharSequenceArrays.txt
tests/generator-Tests/Unit-Tests/CodeGeneratorExpectedResults/XAJavaInterop1/WriteObjectField.txt
tests/generator-Tests/Unit-Tests/CodeGeneratorExpectedResults/XamarinAndroid/WriteMethodWithCharSequenceArrays.txt
tests/generator-Tests/Unit-Tests/CodeGeneratorExpectedResults/XamarinAndroid/WriteObjectField.txt
tests/generator-Tests/Unit-Tests/CodeGeneratorTests.cs
tests/generator-Tests/Unit-Tests/SupportTypes.cs
tools/generator/SourceWriters/BoundFieldAsProperty.cs
tools/generator/SourceWriters/Extensions/SourceWriterExtensions.cs

[generator] Fix xamarin-android/src/Mono.Android build
Context: a65d6fb4d79041c959435c15dc3dcf5331e5d715
Context: https://github.com/xamarin/xamarin-android/pull/6939
xamarin/xamarin-android#6939 attempted to bump to 05eddd9a, which
promptly broke the build of src/Mono.Android, e.g.
`src/Mono.Android/obj/Debug/net6.0/android-32/mcw/Android.Widget.GridLayout.cs`:
/*       */ partial class GridLayout {
/*       */     partial class partial class LayoutParams {
/*       */         [Register ("rowSpec")]
/*       */         public Android.Widget.GridLayout.Spec? RowSpec {
/*       */             get {
/*       */                 const string __id = "rowSpec.Landroid/widget/GridLayout$Spec;";
/*       */                 var __v = _members.InstanceFields.GetObjectValue (__id, this);
/*       */ …

[generator] Fix xamarin-android/src/Mono.Android build

---

tests/generator-Tests/Unit-Tests/CodeGenerationOptionsTests.cs
tests/generator-Tests/Unit-Tests/TypeNameUtilitiesTests.cs
tools/generator/CodeGenerationOptions.cs
tools/generator/Utilities/TypeNameUtilities.cs

I was having trouble building Xamarin.Android on my PC because the generated C# code wouldn't compile. The identifiers `checked`, `decimal`, and `delegate` wheren't prefixed with `@`. I later found out that this was happening because Windows on my PC had Region format set to Czech. We have this weird _letter_ "ch" which is actually the 9th letter of our alphabet. Therefore, the `required_keywords` array isn't sorted correctly when the culture is `cs-CZ` since it contains the word `"checked"` and `Array.BinarySearch` wasn't working correctly for me because it utilized the default culture-specific string comparer. This PR explicitly sets the string comparer for binary search to `Ordinal` which solves the problem.

[generator] Fix reserved keywords binary search

---

tests/Java.Base-Tests/Java.Base-Tests.targets

Context: https://github.com/xamarin/xamarin-android/pull/6984
While attempting to bump Java.Interop, the **nunit Java.Interop tests**
job is failing on Windows, because it can't find `jcw-gen.dll`:
C:\a\_work\2\s\external\Java.Interop\tests\Java.Base-Tests\Java.Base-Tests.targets(27,5):
error MSB3073: The command "C:\a\_work\2\s\bin\Release\dotnet\dotnet "C:\a\_work\2\s\external\Java.Interop\bin\Release-net6.0\/jcw-gen.dll" …"" exited with code 1.
The `jcw-gen.dll` invocation needs to use `$(UtilityOutputFullPath)`,
not `$(ToolOutputFullPath)`, as the `jcw-gen.dll` output path is
altered within xamarin/xamarin-android.  `$(UtilityOutputFullPath)`
allows customization by xamarin-android, not `$(ToolOutputFullPath)`.

[Java.Base-Tests] Use $(UtilityOutputFullPath)/jcw-gen.dll

---

src/Java.Interop.Dynamic/Java.Interop.Dynamic.csproj
src/Java.Interop.Dynamic/Java.Interop.Dynamic/DynamicJavaClass.cs
src/Java.Interop.Dynamic/Java.Interop.Dynamic/DynamicJavaInstance.cs
src/Java.Interop.Dynamic/Java.Interop.Dynamic/JavaClassInfo.cs
src/Java.Interop.Dynamic/Java.Interop.Dynamic/JavaConstructorInfo.cs
src/Java.Interop.Dynamic/Java.Interop.Dynamic/JavaFieldInfo.cs
src/Java.Interop.Dynamic/Java.Interop.Dynamic/JavaMemberInfo.cs
src/Java.Interop.Dynamic/Java.Interop.Dynamic/JavaMethodBase.cs
src/Java.Interop.Dynamic/Java.Interop.Dynamic/JavaMethodInfo.cs
src/Java.Interop.Dynamic/Java.Interop.Dynamic/JniMetaObject.cs
src/Java.Interop.Export/Java.Interop.Export.csproj
src/Java.Interop.Export/Java.Interop/JavaCallableAttribute.cs
src/Java.Interop.Export/Java.Interop/MarshalMemberBuilder.cs

Annotate `Java.Interop.Dynamic.dll` and `Java.Interop.Export.dll` to
support C#8 [Nullable Reference Types][0].
[0]: https://docs.microsoft.com/en-us/dotnet/csharp/nullable-references

[Java.Interop.{Dynamic,Export}] Nullable Reference Type support

---

src/Java.Interop.Tools.Cecil/Java.Interop.Tools.Cecil/TypeDefinitionRocks.cs
src/Java.Interop.Tools.JavaCallableWrappers/Java.Interop.Tools.JavaCallableWrappers/JavaCallableWrapperGenerator.cs

Context: fb94d598bddf7818d841914dd4f565cf5cd0bbac
fb94d598 added code to collect all overriden method descriptors in
a list, so that the future marshal methods code generator can generate
correct code for them.  However, not all gathered descriptors contained
name of the managed type which declares the overridden methods.  This
commit fixes the problem.

Fix marshal method descriptors

---

samples/Hello/Program.cs
src/Java.Interop/Java.Interop.csproj
src/Java.Interop/Java.Interop/JavaArray.cs
src/Java.Interop/Java.Interop/JniEnvironment.Types.cs
src/Java.Interop/Java.Interop/JniMemberSignature.cs
src/Java.Interop/Java.Interop/JniMethodInfo.cs
src/Java.Interop/Java.Interop/JniPeerMembers.JniInstanceMethods.cs
src/Java.Interop/Java.Interop/JniPeerMembers.JniInstanceMethods_Invoke.cs
src/Java.Interop/Java.Interop/JniPeerMembers.JniInstanceMethods_Invoke.tt
src/Java.Interop/Java.Interop/JniPeerMembers.JniStaticMethods.cs
src/Java.Interop/Java.Interop/JniPeerMembers.cs
src/Java.Interop/Java.Interop/JniRuntime.JniTypeManager.cs
src/Java.Interop/Java.Interop/JniRuntime.JniValueManager.cs
src/Java.Interop/Java.Interop/JniType.cs
src/Java.Interop/Java.Interop/JniTypeSignatureAttribute.cs
tests/Java.Interop-Tests/Java.Interop-Tests.csproj
tests/Java.Interop-Tests/Java.Interop/JavaVMFixture.cs
tests/Java.Interop-Tests/Java.Interop/JniPeerMembersTests.cs
tests/Java.Interop-Tests/java/com/xamarin/interop/ObjectHelper.java
tests/Java.Interop-Tests/java/com/xamarin/interop/RenameClassBase1.java
tests/Java.Interop-Tests/java/com/xamarin/interop/RenameClassBase2.java
tests/Java.Interop-Tests/java/com/xamarin/interop/RenameClassDerived.java
tests/TestJVM/TestJVM.cs
tests/TestJVM/TestJVM.csproj

Context: https://github.com/xamarin/java.interop/issues/867
There are two scenarios for which a "generalized" type & member
remapping solution would be useful:
1. Desugaring
2. Microsoft Intune MAM
Note: this new support is only present when targeting .NET 6+,
and will not (currently) be present in Classic Xamarin.Android.
~~ Desugaring ~~
Context: https://github.com/xamarin/xamarin-android/issues/4574#issuecomment-615363285
Context: https://github.com/xamarin/xamarin-android/issues/6142#issuecomment-889435599
The [Android Runtime][0] is responsible for running the Dalvik
bytecode within e.g. `classes.dex`.  The Android runtime and Dalvik
bytecode formats have apparently changed over time in order to
support newer Java language features, such as support for static
interface methods: …

[Java.Interop] Type & Member Remapping Support

---

src/Java.Interop/Java.Interop-MonoAndroid.csproj

Fixes a parallel build issue in Xamarin.Android by adding a project reference to `jnienv-gen.csproj` from `Java.Interop-MonoAndroid.csproj`.  This ensures `jnienv-gen.exe` is available when building `Java.Interop-MonoAndroid.csproj`.
`Java.Interop-MonoAndroid.csproj` is built via the `<MSBuild>` task and was previously called with global properties specifying `MonoAndroid1.0` target framework.  
```xml
<PropertyGroup>
<_GlobalProperties>
JavaInteropProfile=Net45;
XAInstallPrefix=$(XAInstallPrefix);
TargetFrameworkIdentifier=MonoAndroid;
TargetFrameworkVersion=v1.0;
TargetFrameworkRootPath=$(XAInstallPrefix)xbuild-frameworks;
</_GlobalProperties>
</PropertyGroup>
<MSBuild
Projects="$(JavaInteropFullPath)\src\Java.Interop\Java.Interop-MonoAndroid.csproj"
Properties="$(_GlobalProperties)"
/> …
```

[Java.Interop-MonoAndroid.csproj] Add ProjectReference to 'jnienv-gen'.

---

tools/generator/SourceWriters/BoundProperty.cs

Context: https://developer.android.com/reference/android/animation/Keyframe#setInterpolator(android.animation.TimeInterpolator)
The Java source for `Keyframe.setInterpolator` incidentally includes a
`@return` tag, even though the return type is void:
```java
/**
* Sets the optional interpolator for this Keyframe. A value of <code>null</code> indicates
* that there is no interpolation, which is the same as linear interpolation.
*
* @return The optional interpolator for this Keyframe.
*/
public void setInterpolator(TimeInterpolator interpolator) {
mInterpolator = interpolator;
}
```
This causes us to generate multiple `<returns>` C# doc comment tags on
the `Android.Animation.Keyframe.Interpolator` property, as the setter
and getter both include the same `@return` tag:
```csharp
/// …
```

[Javadoc] Merge return values on bound properties

---

tools/generator/Java.Interop.Tools.Generator.ObjectModel/JavadocInfo.cs
tools/generator/Java.Interop.Tools.Generator.Transformation/JavadocFixups.cs

Fixes: https://github.com/xamarin/java.interop/issues/992
Looking at the latest set of API docs for [a nested type][0] I noticed
that we were missing a lot of content that should have been produced by
the Mono.Android build when translating Javadoc to C# doc comments.
After further investigation, we realized that we were not attempting to
process and translate Javadoc for _any_ nested types.  This has been
fixed by adding a missing Javadoc processing iteration over each types
nested type.
Additionally, Java documentation URLs for nested types have been fixed
by replacing '$' with '.' in both the URL and text for the URL.
[0]: https://github.com/xamarin/android-api-docs/blame/b4084443c0354661e2257eb698e03d3fe1d86f1b/docs/Mono.Android/en/Android.AccessibilityServices/AccessibilityButtonContr …

[generator] Process javadoc for nested types

---

src/Java.Interop/Java.Interop/JniRuntime.JniTypeManager.cs

We noticed `dotnet trace` output was showing:
21.28ms (0.45%) java.interop!Java.Interop.JniRuntime.JniTypeManager.AssertSimpleReference(string,string)
This code path was introduced by a new feature in 1f27ab55.
For now, I think we can rewrite this to use the `char` overload of
`IndexOf`, as well as the regular indexer on `string`.
After these changes, I get a better time:
1.21ms java.interop!Java.Interop.JniRuntime.JniTypeManager.AssertSimpleReference(string,string)
We may have just *moved* the location that ICU is loaded, but this
change is good regardless.

[Java.Interop] optimize JniTypeManager.AssertSimpleReference()

---

src/Java.Interop/Java.Interop/JniTypeSignature.cs
tests/Java.Interop-Tests/Java.Interop/JniTypeSignatureTest.cs

Fixes: https://github.com/xamarin/java.interop/issues/335
Context: 920ea6482f7252412d626c4a2ecff0df6de6d428
Commit 920ea648 optimized `JniTypeManager.AssertSimpleReference()` by
using `string.IndexOf(char)`.
This dovetails with Issue #335, which wanted to optimize
`JniTypeSignature` by removing calls to `string.Contains(string)`.
Fix #335, and update the `JniTypeSignature` constructor to use
`string.IndexOf(char)` instead of `string.Contains(string)`, and use
string indexers instead of `string.StartsWith()` and
`string.EndsWith()`.
`Java.Interop.dll` has no remaining usage of `string.StartsWith()`
and `string.EndsWith()`.
Additionally, update `JniTypeSignature` so that the empty string `""`
is *not* treated as a valid type signature.  This is arguably a
breaking change, but the empty …

[Java.Interop] JniTypeSignature & CultureInfo, empty strings

---

src/Java.Interop.Tools.JavaSource/Java.Interop.Tools.JavaSource/SourceJavadocToXmldocGrammar.BlockTagsBnfTerms.cs
src/Java.Interop.Tools.JavaSource/Java.Interop.Tools.JavaSource/SourceJavadocToXmldocGrammar.InlineTagsBnfTerms.cs
src/Java.Interop.Tools.JavaSource/Java.Interop.Tools.JavaSource/SourceJavadocToXmldocParser.cs
tests/Java.Interop.Tools.JavaSource-Tests/SourceJavadocToXmldocGrammar.BlockTagsBnfTermsTests.cs
tests/Java.Interop.Tools.JavaSource-Tests/SourceJavadocToXmldocGrammar.InlineTagsBnfTermsTests.cs
tests/Java.Interop.Tools.JavaSource-Tests/SourceJavadocToXmldocParserTests.cs

The number of "## Unable to translate remarks for ..." errors have been
cut nearly in half, from 740 to 391.
The rules for `@param`, `@return`, `@throws`, and `@unknown` have been
updated to handle more variations of these tags.  In some cases, these
tags are only followed by a single word or no content at all.
New line character filters have been added to `nonSpaceTerm` to fix
instances where an "empty" tag would be merged with the tag on the
following line.
See [`Android.Database.DatabaseUtils.GetCollationKey(String)`][0] as
an example.
Before `nonSpaceTerm` change:
```xml
<param name="name">To be added.</param>
<param name="name&#xA;@return&#xA;@return">the collation key</param>
<summary>return the collation key</summary>
<returns>To be added.</returns>
```
After `nonSpaceTerm` change: …

[Java.Interop.Tools.JavaSource] Fix tag parsing errors

---

src/Java.Interop.Tools.Generator/Metadata/FixupXmlDocument.cs
tests/generator-Tests/Unit-Tests/FixupXmlDocumentTests.cs

Fixes #976.
Given an `api.xml` element like:
```xml
<package name='my.package'>
<class name='MyClass' api-since='29' />
</package>
```
You would expect to be able to remove the `api-since` attribute with this metadata:
```xml
<remove-attr path='/api/package[@name='my.package']/class[@name='MyClass']' name='api-since' />
```
However, even though `generator` reads the `name` attribute, it then proceeds to ignore it and remove *all* attributes on the matched node, resulting in:
```xml
<package name='my.package'>
<class />
</package>
```
This seems unintuitive, and I'm not sure how this could ever be successfully used in a binding project, since leaving an empty `<class>`, etc. node causes `generator` to crash.
Fix `<remove-attr>` to work as expected.

[generator] Fix <remove-attr> metadata.

---

tests/generator-Tests/Unit-Tests/CodeGeneratorTests.cs
tools/generator/SourceWriters/BoundInterfaceMethodDeclaration.cs
tools/generator/SourceWriters/BoundInterfacePropertyDeclaration.cs
tools/generator/SourceWriters/BoundMethod.cs
tools/generator/SourceWriters/BoundProperty.cs

Fixes #981 
Add support for the `managedOverride = none` value:
```xml
<attr path="//method[@name='example']" name="managedOverride">none</attr>
```
This value ensures that the member is not marked as `virtual` or `override`, useful for `sealed` classes.
```csharp
public sealed class MyClass {
public void DoThing () => ...
}
```
---
Additionally add support for the `managedOverride = reabstract` value:
```xml
<attr path="//method[@name='example']" name="managedOverride">reabstract</attr>
```
This only affects interfaces, and allows an interface member to be "reabstracted":
```csharp
public partial interface IAnnotatedType {
// Contains default interface method
virtual IAnnotatedType? AnnotatedOwnerType => null;
}
public partial interface IAnnotatedArrayType : IAnnotatedType {
// Contains …
```

[generator] Add `managedOverride` values `none` and `reabstract`.

---

src/Java.Interop.NamingCustomAttributes/Android.Runtime/RegisterAttribute.cs
src/Java.Interop.Tools.JavaCallableWrappers/Java.Interop.Tools.JavaCallableWrappers/JavaCallableWrapperGenerator.cs

Add code which classifies methods selected by `JavaCallableWrapperGenerator`
and decides whether they are to be registered dynamically or using the
future native code marshal methods.
If a type `JavaCallableWrapperGenerator` is processing is found to not
have any dynamically registered methods, then the code to register them
is no longer generated.

[marshal-methods] Add marshal methods classification code

---

tests/generator-Tests/Unit-Tests/CodeGeneratorTests.cs
tools/generator/Java.Interop.Tools.Generator.Importers/XmlApiImporter.cs
tools/generator/Java.Interop.Tools.Generator.ObjectModel/Method.cs
tools/generator/Java.Interop.Tools.Generator.ObjectModel/Property.cs
tools/generator/SourceWriters/BoundAbstractProperty.cs
tools/generator/SourceWriters/BoundInterfaceMethodDeclaration.cs
tools/generator/SourceWriters/BoundInterfacePropertyDeclaration.cs
tools/generator/SourceWriters/BoundMethod.cs
tools/generator/SourceWriters/BoundMethodAbstractDeclaration.cs
tools/generator/SourceWriters/BoundProperty.cs

Fixes https://github.com/xamarin/java.interop/issues/1005.
In order to fully support "reabstraction", we need to emit member names with explicit interface names.  
```csharp
public partial interface ICloseable : global::Java.Lang.IAutoCloseable {
abstract void IAutoCloseable.Close ();
}
```
This isn't something we have enough information to figure out automatically, so we should allow it to be specified with metadata using a new `explicitInterface` attribute.
```xml
<attr path="/api/package[@name='java.io']/interface[@name='Closeable']/method[@name='Close']" name="explicitInterface">
IAutoCloseable
</attr>
```
Note this is not really a concept that `generator` "understands", it will simply output whatever is specified in this attribute.  Thus the value is the *C#* interface name, not the …

[generator] Add support for @explicitInterface metadata.

---

src/Java.Base-ref.cs
src/Java.Base/Java.Base.csproj
src/Java.Base/Transforms/Metadata.xml

Context: a65d6fb4d79041c959435c15dc3dcf5331e5d715
Context: 22d5687bc5c572ea0eadbd1a23f02f424af782d1
Context: fadbb82c3b8ab7979c19e9f139bdf2589e47549e
Commit a65d6fb4 added [warning CS0108][0] to `$(NoWarn)`, as there
was no way to fix this warning on `IAnnotatedArrayType`.
With commits 22d5687b and fadbb82c, it is now possible to fix the
CS0108 warning on `IAnnotatedArrayType`, among others.
Remove CS0108 from `$(NoWarn)`, and use `Metadata.xml` to fix/avoid
the constructs which caused the CS0108 warnings.
One CS0108 which *isn't* fixed by [reabstraction][1] of
Interface Default Members is for the
[`java.io.ByteArrayInputStream.mark`][2] field, which has the same
name -- and thus hides -- the [`InputStream.mark()` method][3].
This isn't a problem for Java -- context disambiguates between …

[Java.Base] Fix CS0108 Warnings

---

src/Xamarin.Android.Tools.Bytecode/Kotlin/KotlinFixups.cs
tests/Xamarin.Android.Tools.Bytecode-Tests/KotlinFixupsTests.cs

Fixes: https://github.com/xamarin/java.interop/issues/984
There exists a scenario in Kotlin where an instance method and an extension method can have the same *Kotlin* parameter signature:
```kotlin
class UByteArray {
fun contains(element: UByte): Boolean
}
// Extension method
operator fun <T> Array<out T>.contains(element: T): Boolean
```
This results in 2 different Java methods:
```java
class UByteArray {
public boolean contains-7apg3OU(byte element) {
return contains-WZ4Q5Ns(this.storage, element);
}
public static boolean contains-7apg3OU(byte [] arg0, byte element) {
Intrinsics.checkNotNullParameter(arg0, "arg0");
return ArraysKt.contains(arg0, element);
}
}
```
In this case, Kotlin only generates 1 metadata entry:
Today we find that the `JvmSignature` of `([BB)Z` matches the `static` …

[generator] Handle Kotlin metadata when only one metadata exists for multiple Java methods.

---

tests/generator-Tests/Unit-Tests/CodeGeneratorTests.cs
tools/generator/SourceWriters/BoundMethodAbstractDeclaration.cs

Fixes: https://github.com/xamarin/java.interop/issues/969
If you have a Java `abstract` method which is deprecated:
```java
public abstract class Example {
@Deprecated
public abstract void m();
}
```
then the C# binding is *not* `[Obsolete]`, *and* the `*Invoker` override *is* `[Obsolete]`:
```csharp
// Binding
public abstract partial class Example : Java.Lang.Object {
[Register (…)]
public abstract void M();
}
internal partial class ExampleInvoker : Example {
[Obsolete]
public override void M() => …
}
```
This state of affairs results in a [CS0809 warning](https://docs.microsoft.com/en-us/dotnet/csharp/misc/cs0809):
```
Error CS0809: Obsolete member 'ExampleInvoker.M()' overrides non-obsolete member 'Example.M()'
```
Expand the fix from https://github.com/xamarin/java.interop/pull/968 to …

[generator] Mark abstract methods as [Obsolete] if needed.

---

src/Java.Interop.Localization/Resources.Designer.cs
src/Java.Interop.Localization/Resources.resx
src/Java.Interop.Localization/xlf/Resources.cs.xlf
src/Java.Interop.Localization/xlf/Resources.de.xlf
src/Java.Interop.Localization/xlf/Resources.es.xlf
src/Java.Interop.Localization/xlf/Resources.fr.xlf
src/Java.Interop.Localization/xlf/Resources.it.xlf
src/Java.Interop.Localization/xlf/Resources.ja.xlf
src/Java.Interop.Localization/xlf/Resources.ko.xlf
src/Java.Interop.Localization/xlf/Resources.pl.xlf
src/Java.Interop.Localization/xlf/Resources.pt-BR.xlf
src/Java.Interop.Localization/xlf/Resources.ru.xlf
src/Java.Interop.Localization/xlf/Resources.tr.xlf
src/Java.Interop.Localization/xlf/Resources.zh-Hans.xlf
src/Java.Interop.Localization/xlf/Resources.zh-Hant.xlf
src/Java.Interop.Tools.Generator/Utilities/Report.cs
tests/generator-Tests/Unit-Tests/CodeGeneratorTests.cs
tools/generator/Extensions/StringExtensions.cs
tools/generator/Java.Interop.Tools.Generator.CodeGeneration/JavaInteropCodeGenerator.cs
tools/generator/SourceWriters/Extensions/SourceWriterExtensions.cs

Fixes: https://github.com/xamarin/java.interop/issues/982
As explained in the [Framework Design Guidelines](https://docs.microsoft.com/en-us/dotnet/standard/design-guidelines/names-of-namespaces):
> ❌ DO NOT use the same name for a namespace and a type in that namespace.
> For example, do not use Debug as a namespace name and then also provide a class named Debug in the same namespace. Several compilers require such types to be fully qualified.
Since this is not a warning in Roslyn, and bindings code is autogenerated, it can be hard for bindings authors to notice that they are making this mistake.  We can help surface this by emitting a warning if a type name matches its enclosing namespace.
This warning is `BG8403`.
Example:
```
warning BG8403: Type `Android.Graphics.Drawable.Drawable` …
```

[generator] Warn if type name matches enclosing namespace name.

---

src/Java.Interop.NamingCustomAttributes/Android.Runtime/RegisterAttribute.cs
src/Java.Interop.NamingCustomAttributes/Java.Interop/ExportAttribute.cs
src/Java.Interop.Tools.Diagnostics/Java.Interop.Tools.Diagnostics/Diagnostic.cs
src/Java.Interop.Tools.JavaCallableWrappers/Java.Interop.Tools.JavaCallableWrappers.csproj
src/Java.Interop.Tools.JavaCallableWrappers/Java.Interop.Tools.JavaCallableWrappers/IdentifierValidator.cs
src/Java.Interop.Tools.JavaCallableWrappers/Java.Interop.Tools.JavaCallableWrappers/JavaCallableWrapperGenerator.cs
src/Java.Interop.Tools.JavaCallableWrappers/Java.Interop.Tools.JavaCallableWrappers/JavaTypeScanner.cs
src/Java.Interop.Tools.JavaCallableWrappers/Java.Interop.Tools.JavaCallableWrappers/TypeNameMapGenerator.cs
src/Java.Interop.Tools.TypeNameMappings/Java.Interop.Tools.TypeNameMappings/JavaNativeTypeManager.cs
tests/Java.Interop.Tools.JavaCallableWrappers-Tests/Java.Interop.Tools.JavaCallableWrappers-Tests.csproj
tools/jnimarshalmethod-gen/Xamarin.Android.Tools.JniMarshalMethodGenerator.csproj

Context: 3226a4b57ad84574a69a151a310b077cfe69ee19
Context: 7068f4b2df94f5171e3f44e817a84e99d494cc2d
Enable [C# 8 Nullable Reference Types][0] for
`Java.Interop.Tools.JavaCallableWrappers.dll`.
[0]: https://docs.microsoft.com/en-us/dotnet/csharp/nullable-references

[Java.Interop.Tools.JavaCallableWrappers] NRT Support

---

Localize/LocProject.json
build-tools/automation/azure-pipelines.yaml

A new job has been added to run the `OneLocBuild@2` task on every commit
to main.  This task produces files needed by the localization team.  For
more details on this process, see the [OneLocBuild documentation][0].
Onboarding for this repo is still pending, and a workflow for automatic
"handback" of localized files will need to be established in a future
PR once onboarding is complete.
[0]: https://aka.ms/OneLocBuild

[Localization] Add OneLocBuild job

---

src/Java.Interop/Java.Interop.targets

Context: https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=6496140
Due to multitargeting of `Java.Interop.csproj` and parallel builds (no `-m:1`), we can write the file `Java.Interop/JniEnvironment.g.cs` twice in a build:
```
// net7.0
Command = /Users/builder/azdo/_work/1/s/xamarin-android/bin/Release/dotnet/dotnet "/Users/builder/azdo/_work/1/s/xamarin-android/external/Java.Interop/bin/BuildRelease-net7.0/jnienv-gen.dll" Java.Interop/JniEnvironment.g.cs obj/Release/net7.0/jni.c
// netstandard2.0
Command = mono "/Users/builder/azdo/_work/1/s/xamarin-android/external/Java.Interop/bin/BuildRelease/jnienv-gen.exe" Java.Interop/JniEnvironment.g.cs obj/Release/netstandard2.0/jni.c
```
As a race condition, this can cause the generation invocations to clobber each other, or to …

[Java.Interop] Place `JniEnvironment.g.cs` in `$(IntermediateOutputPath)` to support parallel builds.

---

tools/generator/SourceWriters/BoundClass.cs
tools/generator/SourceWriters/BoundConstructor.cs
tools/generator/SourceWriters/BoundField.cs
tools/generator/SourceWriters/BoundFieldAsProperty.cs
tools/generator/SourceWriters/BoundInterface.cs
tools/generator/SourceWriters/BoundInterfaceMethodDeclaration.cs
tools/generator/SourceWriters/BoundMethod.cs
tools/generator/SourceWriters/BoundMethodAbstractDeclaration.cs
tools/generator/SourceWriters/BoundMethodExtensionStringOverload.cs
tools/generator/SourceWriters/BoundMethodStringOverload.cs
tools/generator/SourceWriters/BoundProperty.cs
tools/generator/SourceWriters/Extensions/SourceWriterExtensions.cs
tools/generator/SourceWriters/MethodCallback.cs

Refactor `generator` logic for applying `[Obsolete]` attributes to a single common method.  This method will later be extended to add support for [`[ObsoletedOSPlatform]`](https://github.com/xamarin/xamarin-android/issues/7234).
Doing this piece first and separately allows us to verify that the refactor does not break anything, as the existing logic is a bit tricky. A future PR will also remove the temporary hacks used to preserve stylistic compatibility for the large `generator` [refactor](https://github.com/xamarin/java.interop/pull/674).
Test XA bump to ensure no changes to ApiCompat: https://github.com/xamarin/xamarin-android/pull/7240.

[generator] Refactor generation logic for applying [Obsolete] attributes.

---

tests/generator-Tests/Unit-Tests/CodeGeneratorExpectedResults/XAJavaInterop1-NRT/WriteInterface.txt
tests/generator-Tests/Unit-Tests/CodeGeneratorExpectedResults/XAJavaInterop1/ObsoleteInterfaceAlternativeClass.txt
tests/generator-Tests/Unit-Tests/CodeGeneratorExpectedResults/XAJavaInterop1/WriteInterface.txt
tests/generator-Tests/Unit-Tests/CodeGeneratorExpectedResults/XAJavaInterop1/WriteInterfaceFieldAsDimProperty.txt
tests/generator-Tests/Unit-Tests/CodeGeneratorExpectedResults/XAJavaInterop1/WriteStaticInterfaceMethod.txt
tests/generator-Tests/Unit-Tests/CodeGeneratorTests.cs
tests/generator-Tests/expected.ji/Constructors/Xamarin.Test.SomeObject.cs
tests/generator-Tests/expected.ji/NormalMethods/Xamarin.Test.SomeObject.cs
tests/generator-Tests/expected.ji/StaticMethods/Xamarin.Test.SomeObject.cs
tests/generator-Tests/expected.xaji/Constructors/Xamarin.Test.SomeObject.cs
tests/generator-Tests/expected.xaji/NormalMethods/Xamarin.Test.SomeObject.cs
tests/generator-Tests/expected.xaji/StaticMethods/Xamarin.Test.SomeObject.cs
tests/generator-Tests/expected.xaji/TestInterface/Test.ME.ITestInterface.cs
tools/generator/SourceWriters/Attributes/ObsoleteAttr.cs
tools/generator/SourceWriters/BoundClass.cs
tools/generator/SourceWriters/BoundField.cs
tools/generator/SourceWriters/BoundFieldAsProperty.cs
tools/generator/SourceWriters/BoundInterface.cs
tools/generator/SourceWriters/Extensions/SourceWriterExtensions.cs
tools/generator/SourceWriters/InterfaceMemberAlternativeClass.cs

Traditionally `generator` was inconsistent with the style in which it generated `[Obsolete]` attributes, such as:
```csharp
[Obsolete]
[Obsolete ("")]
[Obsolete (@"")]
[ObsoleteAttribute]
[global::System.Obsolete]
```
We wrote a temporary compatibility layer to preserve these differences when we [refactored](https://github.com/xamarin/java.interop/pull/674) `generator`.  This allowed us to do a source code level text compare against a large corpus of generated code (`Mono.Android`/AndroidX/GPS) to ensure there were no changes.
Now that we are passed this phase, we can remove these hacks and standardize on `[global::System.Obsolete]` and `[global::System.Obsolete (@"message")]`.
XA test build to ensure there were no actual changes via ApiCompat testing: …

[generator] Remove [Obsolete] style compatibility hacks.

---

src/utils/XmlExtensions.cs
tests/generator-Tests/Unit-Tests/CodeGeneratorTests.cs
tools/generator/CodeGenerationOptions.cs
tools/generator/CodeGenerator.cs
tools/generator/CodeGeneratorOptions.cs
tools/generator/Java.Interop.Tools.Generator.Importers/XmlApiImporter.cs
tools/generator/Java.Interop.Tools.Generator.ObjectModel/Field.cs
tools/generator/Java.Interop.Tools.Generator.ObjectModel/GenBase.cs
tools/generator/Java.Interop.Tools.Generator.ObjectModel/GenBaseSupport.cs
tools/generator/Java.Interop.Tools.Generator.ObjectModel/MethodBase.cs
tools/generator/SourceWriters/Attributes/ObsoleteAttr.cs
tools/generator/SourceWriters/Attributes/ObsoletedOSPlatformAttr.cs
tools/generator/SourceWriters/BoundClass.cs
tools/generator/SourceWriters/BoundConstructor.cs
tools/generator/SourceWriters/BoundField.cs
tools/generator/SourceWriters/BoundFieldAsProperty.cs
tools/generator/SourceWriters/BoundInterface.cs
tools/generator/SourceWriters/BoundInterfaceMethodDeclaration.cs
tools/generator/SourceWriters/BoundMethod.cs
tools/generator/SourceWriters/BoundMethodAbstractDeclaration.cs
tools/generator/SourceWriters/BoundMethodExtensionStringOverload.cs
tools/generator/SourceWriters/BoundMethodStringOverload.cs
tools/generator/SourceWriters/BoundProperty.cs
tools/generator/SourceWriters/Extensions/SourceWriterExtensions.cs
tools/generator/SourceWriters/InterfaceMemberAlternativeClass.cs
tools/generator/SourceWriters/MethodCallback.cs

Context: https://github.com/xamarin/xamarin-android/issues/7234
Add support for a new `lang-features=obsoleted-platform-attributes` `generator` option.
When used, for API that was obsoleted in API levels greater than our .NET 7 minimum (API 21), we will generate .NET 7's new `[ObsoletedOSPlatform]` attribute *instead of* `[Obsolete]`:
```csharp
// New
[global::System.Runtime.Versioning.ObsoletedOSPlatform ("android22.0", @"This class is obsoleted in this android platform")]
public partial class CookieSpecParamBean : Org.Apache.Http.Params.HttpAbstractParamBean { ... }
// Previous
[global::System.Obsolete (@"This class is obsoleted in this android platform")]
public partial class CookieSpecParamBean : Org.Apache.Http.Params.HttpAbstractParamBean { ... }
```
This is useful for a .NET 7+ …

[generator] Add support for `[ObsoletedOSPlatform]`.

---

src/Java.Interop/Java.Interop/JniEnvironment.Types.cs

Context: https://github.com/xamarin/xamarin-android/pull/7285#discussion_r951760448
`Java.Inteorp.JniEnvironment.Types.RegisterNatives()` is overloaded:
namespace Java.Interop {
partial class JniEnvironment {
partial class Types {
public static void RegisterNatives (JniObjectReference type, JniNativeMethodRegistration[] methods);
public static void RegisterNatives (JniObjectReference type, JniNativeMethodRegistration[] methods, int numMethods);
}
}
}
If the `int numMethods` overload is used, then:
1. it should be possible to pass an array which contains *more* than
`numMethods` elements, and
2. Passing such an array shouldn't throw an exception.
For example:
var methods = new JniNativeMethodRegistration [10];
JniEnvironment.Types.RegisterNatives (type, methods, 0);
Instead, when using a …

[Java.Interop] RegisterNatives() shouldn't exceed numMethods

---

Directory.Build.targets
src/Java.Base/Java.Base.csproj
src/Java.Interop.Dynamic/Java.Interop.Dynamic.csproj
src/Java.Interop.Export/Java.Interop.Export.csproj
src/Java.Interop.GenericMarshaler/Java.Interop.GenericMarshaler.csproj
src/Java.Interop.Localization/Java.Interop.Localization.csproj
src/Java.Interop.Tools.Cecil/Java.Interop.Tools.Cecil.csproj
src/Java.Interop.Tools.Diagnostics/Java.Interop.Tools.Diagnostics.csproj
src/Java.Interop.Tools.Generator/Java.Interop.Tools.Generator.csproj
src/Java.Interop.Tools.JavaCallableWrappers/Java.Interop.Tools.JavaCallableWrappers.csproj
src/Java.Interop.Tools.JavaSource/Java.Interop.Tools.JavaSource.csproj
src/Java.Interop.Tools.JavaTypeSystem/Java.Interop.Tools.JavaTypeSystem.csproj
src/Java.Interop/Java.Interop-MonoAndroid.csproj
src/Java.Interop/Java.Interop.csproj
src/Java.Runtime.Environment/Java.Runtime.Environment.csproj
src/Xamarin.Android.Tools.AnnotationSupport.Cecil/Xamarin.Android.Tools.AnnotationSupport.Cecil.csproj
src/Xamarin.Android.Tools.AnnotationSupport/Xamarin.Android.Tools.AnnotationSupport.csproj
src/Xamarin.Android.Tools.ApiXmlAdjuster/Xamarin.Android.Tools.ApiXmlAdjuster.csproj
src/Xamarin.Android.Tools.Bytecode/Xamarin.Android.Tools.Bytecode.csproj
src/Xamarin.SourceWriter/Xamarin.SourceWriter.csproj
src/java-interop/java-interop.csproj
tools/class-parse/class-parse.csproj
tools/generator/generator.csproj
tools/jcw-gen/jcw-gen.csproj
tools/jnimarshalmethod-gen/Xamarin.Android.Tools.JniMarshalMethodGenerator.csproj
tools/logcat-parse/logcat-parse.csproj
tools/param-name-importer/param-name-importer.csproj

Context: https://github.com/xamarin/xamarin-android/commit/7b4d4b8c235b22b688db13e59771722da89f37cb
Context: https://github.com/dotnet/sourcelink#githubcom-and-github-enterprise
Context: https://www.hanselman.com/blog/exploring-net-cores-sourcelink-stepping-into-the-source-code-of-nuget-packages-you-dont-own
Changes: http://github.com/xamarin/xamarin-android-tools/compare/fc3c2ac191a47715bc58e110ef28f38009158416...7cfe68373f959b8d08b49dd89e2c874ebde38bda
* xamarin/xamarin-android-tools@7cfe683: [ci] Use Microsoft.SourceLink.GitHub (#192)
* xamarin/xamarin-android-tools@01a0dde: [Localization] Import translated resx files (#189)
* xamarin/xamarin-android-tools@cc715d9: [Xamarin.Android.Tools.AndroidSdk] Permit NDK r25 (#190)
* xamarin/xamarin-android-tools@3c55e9a: Avoid …

[ci] Use Microsoft.SourceLink.GitHub

---

src/Java.Interop.Tools.JavaTypeSystem/JavaModels/JavaClassModel.cs
src/Java.Interop.Tools.JavaTypeSystem/Utilities/JavaUnresolvableModel.cs
tests/Java.Interop.Tools.JavaTypeSystem-Tests/JavaTypeCollectionTests.cs

Fixes #1031 
There apparently exists a Java obfuscator that attempts to break tools by setting the base class of a class to itself.  This breaks us with a `StackOverflowException`:
```java
public class c5<BaseHandler> extends c5<BaseHandler> { ... }
```
```
Stack overflow: IP: 0x11ae88918, fault addr: 0x30d984fd8
Stacktrace:
at Java.Interop.Tools.JavaTypeSystem.Models.JavaClassModel.PrepareGenericInheritanceMapping () [0x00038] in <9ad2a4b0fd014215b74d06fce5575b7a>:0
<...>
at Java.Interop.Tools.JavaTypeSystem.Models.JavaClassModel.get_GenericInheritanceMapping () [0x00000] in <9ad2a4b0fd014215b74d06fce5575b7a>:0
at Java.Interop.Tools.JavaTypeSystem.Models.JavaMethodModel/<>c__DisplayClass47_0.<FindBaseMethod>b__0 (Java.Interop.Tools.JavaTypeSystem.Models.JavaMethodModel) [0x00018] in …
```

[generator] Handle Java class with base class set to itself.

---

tools/java-source-utils/CGManifest.json

This pull request adds the JSON schema for `cgmanifest.json`.
A JSON schema helps you to ensure that your `cgmanifest.json` file is valid.
JSON schema validation is a build-in feature in most modern IDEs like Visual Studio and Visual Studio Code.
Most modern IDEs also provide code-completion for JSON schemas.
Most modern IDEs like Visual Studio and Visual Studio Code have a built-in feature to validate JSON files.
You can also use [this small script](https://github.com/JamieMagee/verify-cgmanifest) to validate your `cgmanifest.json` file.
Component Detection is able to read camel case and pascal case properties.
However, the JSON schema doesn't have a case-insensitive mode.
We therefore suggest camel case as it's the most common format for JSON.
To deserialize the `cgmanifest.json` file, …

Add `$schema` to `cgmanifest.json`

---

src/Java.Interop.Tools.JavaSource/Java.Interop.Tools.JavaSource/SourceJavadocToXmldocGrammar.BlockTagsBnfTerms.cs
src/Java.Interop.Tools.JavaSource/Java.Interop.Tools.JavaSource/SourceJavadocToXmldocGrammar.HtmlBnfTerms.cs
src/Java.Interop.Tools.JavaSource/Java.Interop.Tools.JavaSource/SourceJavadocToXmldocGrammar.InlineTagsBnfTerms.cs
tests/Java.Interop.Tools.JavaSource-Tests/SourceJavadocToXmldocGrammar.BlockTagsBnfTermsTests.cs
tests/Java.Interop.Tools.JavaSource-Tests/SourceJavadocToXmldocGrammar.HtmlBnfTermsTests.cs
tests/Java.Interop.Tools.JavaSource-Tests/SourceJavadocToXmldocParserTests.cs
tools/generator/Java.Interop.Tools.Generator.ObjectModel/JavadocInfo.cs

Fixes: https://github.com/xamarin/java.interop/issues/850
All 431 instances of `JavadocImport-Error` that would occur when
generating API docs for Mono.Android.dll have been fixed.  Problematic
scenarios that have been fixed include:
* `@hide` and `@inheritDoc` tags with trailing content
* `<tt>` or `<i>` elements with no closing tag
* `<pre>` elements with an attribute and/or no closing elements
* `<a name="">` or `<a id="">` elements inside of an unclosed `<p>` element
* `<a href="">` elements with mixed casing or spacing
* `{https://github.com/link foo` tags without a closing bracket
* Any extra occurances of `@`, `{`, or `}`

[Java.Interop.Tools.JavaSource] Fix remaining parsing errors 

---

src/Java.Interop.Tools.JavaSource/Java.Interop.Tools.JavaSource/SourceJavadocToXmldocGrammar.HtmlBnfTerms.cs
tests/Java.Interop.Tools.JavaSource-Tests/SourceJavadocToXmldocGrammar.HtmlBnfTermsTests.cs
tests/Java.Interop.Tools.JavaSource-Tests/SourceJavadocToXmldocParserTests.cs

Fixes: https://github.com/xamarin/java.interop/issues/1041
Translates `<code/>` tags into `<c/>` tags, which should clean up thousands of illegible `&lt;code&gt;foo&lt;/code&gt;` instances.

[Java.Interop.Tools.JavaSource] Parse <code/> tags

---

src/Java.Interop.Tools.JavaSource/Java.Interop.Tools.JavaSource/SourceJavadocToXmldocGrammar.InlineTagsBnfTerms.cs
tests/Java.Interop.Tools.JavaSource-Tests/SourceJavadocToXmldocGrammar.InlineTagsBnfTermsTests.cs
tests/Java.Interop.Tools.JavaSource-Tests/SourceJavadocToXmldocParserTests.cs

Fixes: https://github.com/xamarin/java.interop/issues/1042
Translates `{@param foo}` into `<paramref>foo</paramref>`, which should fix ~70 instances of broken summary/remarks/param elements.

[Java.Interop.Tools.JavaSource] Parse {@param} tags

---

src/Java.Interop/Java.Interop/JavaProxyObject.cs
src/Java.Interop/Java.Interop/ManagedPeer.cs

Context: https://learn.microsoft.com/en-us/dotnet/csharp/whats-new/csharp-11#improved-method-group-conversion-to-delegate Context: https://github.com/xamarin/java.interop/issues/1034 Context: https://github.com/dotnet/roslyn/issues/62832
C#11 introduced a "slight semantic" change with "Improved method group conversion to delegate":
> The C# 11 compiler caches the delegate object created from a method
> group conversion and reuses that single delegate object.
The result of optimization is that for current `generator`-emitted code such as:
static Delegate GetFooHandler ()
{
if (cb_foo == null)
cb_foo = JNINativeWrapper.CreateDelegate ((_JniMarshal_PP_V) n_Foo);
return cb_foo;
}
The `(_JniMarshal_PP_V) n_Foo` expression is a "method group conversion", and under C#11 the generated IL is …

[Java.Interop] Avoid some method group conversions

---

tests/generator-Tests/expected.xaji/AccessModifiers/__NamespaceMapping__.cs
tests/generator-Tests/expected.xaji/Adapters/__NamespaceMapping__.cs
tests/generator-Tests/expected.xaji/Android.Graphics.Color/__NamespaceMapping__.cs
tests/generator-Tests/expected.xaji/Arrays/__NamespaceMapping__.cs
tests/generator-Tests/expected.xaji/CSharpKeywords/__NamespaceMapping__.cs
tests/generator-Tests/expected.xaji/Constructors/__NamespaceMapping__.cs
tests/generator-Tests/expected.xaji/Core_ClassParse/__NamespaceMapping__.cs
tests/generator-Tests/expected.xaji/Core_Jar2Xml/__NamespaceMapping__.cs
tests/generator-Tests/expected.xaji/GenericArguments/__NamespaceMapping__.cs
tests/generator-Tests/expected.xaji/InterfaceMethodsConflict/__NamespaceMapping__.cs
tests/generator-Tests/expected.xaji/NestedTypes/__NamespaceMapping__.cs
tests/generator-Tests/expected.xaji/NonStaticFields/__NamespaceMapping__.cs
tests/generator-Tests/expected.xaji/NormalMethods/__NamespaceMapping__.cs
tests/generator-Tests/expected.xaji/NormalProperties/__NamespaceMapping__.cs
tests/generator-Tests/expected.xaji/ParameterXPath/__NamespaceMapping__.cs
tests/generator-Tests/expected.xaji/StaticFields/__NamespaceMapping__.cs
tests/generator-Tests/expected.xaji/StaticMethods/__NamespaceMapping__.cs
tests/generator-Tests/expected.xaji/StaticProperties/__NamespaceMapping__.cs
tests/generator-Tests/expected.xaji/Streams/__NamespaceMapping__.cs
tests/generator-Tests/expected.xaji/TestInterface/__NamespaceMapping__.cs
tests/generator-Tests/expected.xaji/java.lang.Enum/__NamespaceMapping__.cs
tests/generator-Tests/expected.xaji/java.util.List/__NamespaceMapping__.cs
tools/generator/Java.Interop.Tools.Generator.ObjectModel/NamespaceMapping.cs

Context: https://github.com/xamarin/java.interop/pull/1052
Context: https://github.com/buyaa-n/runtime/blob/7a62a22db186fda42dad6cbd681cf056fcf6aee6/src/libraries/System.Private.CoreLib/src/System/Runtime/Versioning/PlatformAttributes.cs#L52-L62
In order to compile classic MonoAndroid bindings that contain the new .NET `[SupportedOSPlatform]` attributes, we have a dummy copy that we can compile against.  However this copy does not allow `AttributeTargets.Field`, so compiling with #1052 causes:
```
/Users/builder/azdo/_work/1/s/xamarin-android/src/Mono.Android/obj/Release/monoandroid10/android-33
/mcw/Dalvik.Bytecode.IOpcodes.cs(646,4): error CS0592: Attribute 
global::System.Runtime.Versioning.SupportedOSPlatformAttribute' 
is not valid on this declaration type. It is only valid on …
```

[generator] Add additional AttributeTargets to our dummy SupportedOSPlatformAttribute.

---

Directory.Build.targets
samples/Hello-Java.Base/Hello-Java.Base.csproj
tests/Java.Interop.Tools.JavaTypeSystem-Tests/Java.Interop.Tools.JavaTypeSystem-Tests.csproj

[build] Update Microsoft.* NuGet package versions
Context: c936d09aec8171fa99a37fd99dba253e41fec05d
Context: https://devdiv.visualstudio.com/DevDiv/_componentGovernance/112825/alert/7082457?typeId=12393424
[Component Governance][0] is a Microsoft internal tool which checks
for known security issues in product dependencies.  It is currently
reporting a defect in Java.Interop because of Newtonsoft.Json 9.0.1
and [GHSA-5crp-9r3c-p9vr][1].  This is a tad odd because Java.Interop
*does not use* Newtonsoft.Json.
Apparently the [Microsoft.NET.Test.Sdk 16.11.0 package][2] pulls in
Newtonsoft.Json 9.0.1 when `$(TargetFramework)`=UAP10.0, which is
also something that Java.Interop does not use.
Regardless!  Take this as a reminder and opportunity to update some
NuGet packages.  Update all of the …

[build] Update Microsoft.* NuGet package versions

---

build-tools/automation/azure-pipelines.yaml

Enable `CodeQL` static code analysis on this repository to help catch potential issues.
This will only run on the `Windows - .NET Core` build lane, as we do not want to run it on all 4 builds.
Note the analysis only runs on `main` builds, so it will not show up in *this* CI build.

[ci] Enable CodeQL static analysis.

---

build-tools/jnienv-gen/Generator.cs
samples/Hello-Core/Hello-Core.csproj
samples/Hello-Java.Base/Program.cs
src/Java.Interop/Java.Interop.csproj
src/Java.Interop/Java.Interop/JniEnvironment.Types.cs
src/Java.Interop/Java.Interop/JniEnvironment.cs
src/Java.Interop/Java.Interop/JniRuntime.cs
src/Java.Interop/Java.Interop/JniType.cs
src/Java.Runtime.Environment/Java.Interop/JreRuntime.cs
tests/Java.Interop-Tests/Java.Interop/JniRuntimeTest.cs
tests/invocation-overhead/invocation-overhead.cs
tests/invocation-overhead/jni.cs

Context: 16e1ecd47caf02fefb2130f28c5894323f46c63a
Context: 312fbf439ed874bb5f4f25ee6d2c9a2b3c2f5a8b
It occurs to me that it would be easier for "external" developers to
use `Java.Interop.dll` if it didn't require building and distributing
any native libraries.  Furthermore, as of commit 312fbf43 (C#9
function pointer backend), it's *plausible* to make that work.
Let's do so.
Add new "pseudo" `Standalone-Debug` and `Standalone-Release`
build configurations to `Java.Interop.csproj` which set the
`FEATURE_JNIENVIRONMENT_JI_FUNCTION_POINTERS` compiler define instead
of the `FEATURE_JNIENVIRONMENT_JI_PINVOKES` define.  This enables
`JniEnvironment` to use C#9 function pointers instead of P/Invokes to
invoke the `JNIEnv` function pointers.  They're "pseudo"
configurations because they don't …

[Java.Interop] Optional "Standalone" Build Config

---

build-tools/automation/azure-pipelines.yaml

CodeQL was added in https://github.com/xamarin/java.interop/pull/1057, however it does not complete within our current 20 minute timeout.  The documentation recommends tripling the timeout, so set it to 60.

[ci] Increase timeout to 60 mins for CodeQL

---

src/Java.Interop.Tools.JavaSource/Java.Interop.Tools.JavaSource/SourceJavadocToXmldocGrammar.BlockTagsBnfTerms.cs
src/Java.Interop.Tools.JavaSource/Java.Interop.Tools.JavaSource/SourceJavadocToXmldocGrammar.HtmlBnfTerms.cs
tests/Java.Interop.Tools.JavaSource-Tests/SourceJavadocToXmldocGrammar.HtmlBnfTermsTests.cs

Fixes the 91 instances of exceptions being thrown when generating API
docs for the API 33 version of Mono.Android.  The two most common
instances were:
System.IndexOutOfRangeException: Index was outside the bounds of the array.
at Java.Interop.Tools.JavaSource.UnknownHtmlElementStartTerminal.TryMatch (Irony.Parsing.ParsingContext context, Irony.Parsing.ISourceStream source) [0x0003e] in /Users/builder/azdo/_work/4/s/external/Java.Interop/src/Java.Interop.Tools.JavaSource/Java.Interop.Tools.JavaSource/SourceJavadocToXmldocGrammar.HtmlBnfTerms.cs:390
System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
at System.Collections.Generic.List`1[T].get_Item (System.Int32 index) [0x00009] in …

[Java.Interop.Tools.JavaSource] Handle common parsing exceptions

---

src/Java.Interop.Tools.TypeNameMappings/Java.Interop.Tools.TypeNameMappings/JavaNativeTypeManager.cs

Reviewing `dotnet-trace` output:
dotnet trace collect --format speedscope -- C:\src\xamarin-android\bin\Release\dotnet\dotnet.exe build -bl --no-restore bar.csproj
On a `dotnet new maui` application, I noticed:
79.40ms java.interop.tools.javacallablewrappers!Java.Interop.Tools.TypeNameMappings.JavaNativeTypeManager.ToJniNameFromAttribute
This method just appears to be called *a lot*, and so things I changed:
* Check `type.HasCustomAttributes`, `attributeType.HasInterfaces`, and `attr.HasProperties` where appropriate.
* Unroll the `System.Linq` usage one level, and use plain `foreach`
* Create a `IsIJniNameProviderAttribute` method that checks against a list of known attribute types as a "fast path".
* The "slow path" can continue to check for the `IJniNameProviderAttribute` interface …

[Java.Interop.Tools.TypeNameMappings] improve `ToJniNameFromAttributesForAndroid`

---

src/Java.Interop.Tools.Generator/Enumification/ConstantEntry.cs
src/Xamarin.SourceWriter/Models/EnumMemberWriter.cs
src/Xamarin.SourceWriter/Models/EnumWriter.cs
tests/generator-Tests/Unit-Tests/EnumGeneratorTests.cs
tests/generator-Tests/Unit-Tests/EnumMappingsTests.cs
tools/generator/Java.Interop.Tools.Generator.CodeGeneration/EnumGenerator.cs
tools/generator/Java.Interop.Tools.Generator.Transformation/EnumMappings.cs
tools/generator/SourceWriters/Attributes/FlagsAttr.cs
tools/generator/SourceWriters/Attributes/IntDefinitionAttr.cs

Refactor `EnumGenerator` to use SourceWriters instead of a direct `TextWriter`.  This will make it possible to use our existing code to apply `[PlatformOSSupported]` attributes to enums in a future PR.
This is a separate PR to help verify there was no output changed from the refactor.
Tested with ApiCompat on https://github.com/xamarin/xamarin-android/pull/7619 to help ensure no changes.

[generator] Refactor enum writing to use SourceWriters.

---

Directory.Build.targets
tests/Java.Interop.Dynamic-Tests/Java.Interop.Dynamic-Tests.csproj

Each CI job reports the following warnings:
```
C:\hostedtoolcache\windows\dotnet\sdk\7.0.100-rc.1.22431.12\Microsoft.Common.CurrentVersion.targets(2350,5): warning MSB3245: Could not resolve this reference. Could not locate the assembly "Microsoft.CSharp". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors. [D:\a\_work\1\s\tests\Java.Interop.Dynamic-Tests\Java.Interop.Dynamic-Tests.csproj::TargetFramework=net7.0]
C:\hostedtoolcache\windows\dotnet\sdk\7.0.100-rc.1.22431.12\Microsoft.Common.CurrentVersion.targets(2350,5): warning MSB3243: No way to resolve conflict between "Microsoft.CSharp, Version=7.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" and "Microsoft.CSharp". Choosing "Microsoft.CSharp, …
```

[Dynamic-Tests] Replace Microsoft.CSharp reference with NuGet package.

---

tests/generator-Tests/Unit-Tests/CodeGeneratorTests.cs
tests/generator-Tests/Unit-Tests/XmlApiImporterTests.cs
tools/generator/Java.Interop.Tools.Generator.Importers/XmlApiImporter.cs

Imagine a type is deprecated in API-25 but its members are not explicitly marked as deprecated:
```java
@Deprecated
public class TabActivity extends ActivityGroup {
public void setDefaultTab(String tag) { ... }
}
```
Then in API-29 the member is explicitly marked as deprecated:
```java
@Deprecated
public class TabActivity extends ActivityGroup {
@Deprecated
public void setDefaultTab(String tag) { ... }
}
```
Due to the way `api-merge` calculates `deprecated-since`, these would end up with different values, and the resulting C# API would look like:
```csharp
[ObsoletedOSPlatform("android25.0")]
public class TabActivity : ActivityGroup
{
[ObsoletedOSPlatform("android29.0")]
public void SetDefaultTab (string tag) { ... }
}
```
While technically "fine", it is confusing that the method says it …

[generator] Inherit declaring type's 'deprecated-since' if lower than member's.

---

tests/generator-Tests/Unit-Tests/EnumGeneratorTests.cs
tools/generator/Java.Interop.Tools.Generator.CodeGeneration/EnumGenerator.cs
tools/generator/SourceWriters/Extensions/SourceWriterExtensions.cs

Fixes: https://github.com/xamarin/java.interop/issues/1037
Adds support for `[Obsolete]`/`[ObsoletedOSPlatform]` and `[SupportedOSPlatform]` attributes on enum members.
The data for `[SupportedOSPlatform]` comes from the values provided in the enum-mapping file:
```
// src/Mono.Android/map.csv
E,29,android/media/MediaRecorder$AudioEncoder.OPUS,7,Android.Media.AudioEncoder,Opus,keep,
```
The `29` is the API in which we added the enum, which becomes `[SupportedOSPlatform ("android-29.0")]`.
The data for the "obsolete" attributes comes from the `deprecated` and `deprecated-since` attributes on the original field in the `api.xml` (if it can be found):
```xml
<field deprecated='deprecated' deprecated-since='31' api-since='30' final='true' name='BIND_CHOOSER_TARGET_SERVICE' …
```

[generator] Support [Obsolete]/[SupportedOSPlatform] attributes for enum members.

---

tests/generator-Tests/Unit-Tests/CodeGeneratorTests.cs
tools/generator/Java.Interop.Tools.Generator.ObjectModel/Property.cs
tools/generator/SourceWriters/BoundProperty.cs

Fixes: https://github.com/xamarin/java.interop/issues/1033
When we are converting Java getter/setter pairs to C# properties, we can hit an interesting scenario where a getter may be `@Deprecated` and the setter is not, or vice versa:
```java
public boolean hasOptionsMenu () { ... }
@Deprecated
public void setHasOptionsMenu (boolean hasMenu) { ... }
```
C# has traditionally not allowed `[Obsolete]` to be placed on just a `get` or a `set`, it can only be placed on the entire property.
```csharp
[Obsolete]
public bool HasOptionsMenu { get; set; }
```
This can lead to confusion because using the getter will report an obsolete warning when it is not obsolete.  Thus, for properties, we only add `[Obsolete]` in 2 cases:
- The `get` is obsolete and there is no `set`
- Both the `get` and `set` are …

[generator] Better support deprecated property getter/setters.

---

src/Java.Interop.Tools.Cecil/Java.Interop.Tools.Cecil/MethodDefinitionRocks.cs
src/Java.Interop.Tools.Cecil/Java.Interop.Tools.Cecil/TypeDefinitionRocks.cs
src/Java.Interop.Tools.JavaCallableWrappers/Java.Interop.Tools.JavaCallableWrappers/JavaCallableWrapperGenerator.cs
src/Java.Interop.Tools.JavaCallableWrappers/Java.Interop.Tools.JavaCallableWrappers/JavaTypeScanner.cs
src/Java.Interop.Tools.JavaTypeSystem/Adapters/ManagedApiImporter.cs
src/Java.Interop.Tools.TypeNameMappings/Java.Interop.Tools.TypeNameMappings/JavaNativeTypeManager.cs
tools/generator/CodeGenerator.cs
tools/generator/Java.Interop.Tools.Generator.Transformation/JavaTypeResolutionFixups.cs

Reviewing code in `JavaCallableWrapperGenerator`, I found places we weren't using the supplied `TypeDefinitionCache` or `IMetadataResolver`. Thus we appeared to be calling `TypeReference.Resolve()` potentially on the same types.
For example, `dotnet trace` output of an incremental build of a `dotnet new maui` project:
41.65ms xamarin.android.cecil!Mono.Cecil.TypeReference.Resolve()
I created a new `TypeDefinitionRocks.ResolveCached()` method to be used everywhere instead. Resulting with:
23.89ms xamarin.android.cecil!Mono.Cecil.TypeReference.Resolve()
Additionally, I updated to places to use plain `foreach` loops instead of System.Linq.
Before:
1.03s xamarin.android.build.tasks!Xamarin.Android.Tasks.GenerateJavaStubs.RunTask()
After:
944.48ms …

[Java.Interop.Tools.JavaCallableWrappers] fix more places to use TypeDefinitionCache

---

build-tools/Java.Interop.BootstrapTasks/Java.Interop.BootstrapTasks/DownloadUri.cs
src/java-interop/java-interop-util.cc
tools/java-source-utils/src/main/java/com/microsoft/android/JavaSourceUtilsOptions.java
tools/java-source-utils/src/main/java/com/microsoft/android/JavadocXmlGenerator.java

Remember CodeQL (5a0097b5)?  CodeQL basically runs [GitHub LGTM][0] on source code, looking for possible security issues.
Now that CodeQL is running, we can begin addressing reported issues.
Problems found include:
* Result of call that may return NULL dereferenced unconditionally
* HttpClient created with CheckCertificateRevocationList disabled
* Arbitrary file write during archive extraction ("Zip Slip")
* Local-user-controlled data in path expression
~~ Result of call that may return NULL dereferenced unconditionally ~~
If **calloc**(3) returns `nullptr`, we shouldn't pass it on to `MultiByteToWideChar()` or `WideCharToMultiByte()` without validation.
~~ HttpClient created with CheckCertificateRevocationList disabled ~~
Apparently the `HttpClient` default constructor is "bad"; we …

[src] Fix LGTM-reported issues.

---

src/Java.Interop.Tools.JavaCallableWrappers/Java.Interop.Tools.JavaCallableWrappers/JavaTypeScanner.cs

I found a couple places we didn't add `[Obsolete (error: true)]`, but luckily this requires no code changes in xamarin/xamarin-android.
I did a quick search, and I'm not finding anymore of these.

[Java.Interop.Tools.JavaCallableWrappers] require TypeDefinitionCache in more places

---

src/Java.Interop.Tools.JavaCallableWrappers/Java.Interop.Tools.JavaCallableWrappers/JavaTypeScanner.cs

Context: https://github.com/xamarin/xamarin-android/pull/7694
Add an overload of `JavaTypeScanner.GetJavaTypes()` that takes in a `Mono.Cecil.AssemblyDefinition` to be more easily consumed by linker steps.

[Java.Interop.Tools.JavaCallableWrappers] add overload for `JavaTypeScanner`

---

tools/java-source-utils/src/main/java/com/microsoft/android/JavaSourceUtilsOptions.java
tools/java-source-utils/src/main/java/com/microsoft/android/JavadocXmlGenerator.java

Context: e11d0242441210ac006d86ccf21c4d4dc2db3a28
Commit e11d0242 attempted to fix LGTM-reported
[`java/path-injection-local`][0] warnings by using the comment `// lgtm [java/path-injection-local]`.
Unfortunately, this is insufficient: the comment *also* needs to provide a 25+ character justification for why the offending statement can be ignored.  This justification was not provided.
Update the `// lgtm [java/path-injection-local]` comments to provide a justification, as required by tooling.
Copying the longer justification from e11d0242:
> LGTM is complaining that `tools/java-source-utils` (69e1b80a) accepts
> user-controlled data.  These warnings will be *ignored* because the
> app is *unusable* without "user-controlled data"
> …
> These are all user-controlled, and they are necessary …

[java-source-utils] Fix lgtm java/path-injection-local

---

Directory.Build.props
Java.Interop.sln
Makefile
TargetFrameworkDependentValues.props
build-tools/automation/templates/core-tests.yaml
src/Java.Base-ref.cs
src/Java.Interop.Export/Java.Interop.Export.csproj
src/Java.Interop.Export/Java.Interop/MarshalMemberBuilder.cs
src/Java.Interop.Tools.Expressions/Java.Interop.Tools.Expressions.csproj
src/Java.Interop.Tools.Expressions/Java.Interop.Tools.Expressions/CecilCompilerExpressionVisitor.cs
src/Java.Interop.Tools.Expressions/Java.Interop.Tools.Expressions/ExpressionAssemblyBuilder.cs
src/Java.Interop.Tools.Expressions/Java.Interop.Tools.Expressions/ExpressionMethodRegistration.cs
tests/Java.Interop.Export-Tests/Java.Interop/MarshalMemberBuilderTest.cs
tests/Java.Interop.Tools.Expressions-Tests/Java.Interop.Tools.Expressions-Tests.csproj
tests/Java.Interop.Tools.Expressions-Tests/Java.Interop.Tools.ExpressionsTests/ExpressionAssemblyBuilderTests.cs
tests/Java.Interop.Tools.Expressions-Tests/Usings.cs
tools/jnimarshalmethod-gen/App.cs
tools/jnimarshalmethod-gen/Xamarin.Android.Tools.JniMarshalMethodGenerator.csproj

Fixes: https://github.com/xamarin/java.interop/issues/616
Context: https://github.com/xamarin/java.interop/issues/14
Context: ff4053cb1e966ebec1c16f97211b9ded936f2707
Context: da5d1b8103bb90f156b93ebac9caa16cfc85764e
Context: 4787e0179b349ab5ee0d0dd03d08b694acea4971
Context: 41ba34856ab119ea6e22ab103320180143fdf03d
Remember `jnimarshalmethod-gen` (176240d2)?  And it's crazy idea to
use the `System.Linq.Expressions`-based custom marshaling
infrastructure (ff4053cb, da5d1b81) to generate JNI marshal methods
at build/packaging time.  And how we had to back burner it because
it depended upon `System.Reflection.Emit` being able to write
assemblies to disk, which is a feature that never made it to
.NET Core, and is still lacking as of .NET 7?
Add `src/Java.Interop.Tools.Expressions`, which …

[Java.Interop.Tools.Expressions] Add Java.Interop.Tools.Expressions

---

src/Xamarin.SourceWriter/Models/MethodWriter.cs
tests/generator-Tests/Unit-Tests/CodeGeneratorTests.cs
tools/generator/Java.Interop.Tools.Generator.Importers/XmlApiImporter.cs
tools/generator/Java.Interop.Tools.Generator.ObjectModel/ClassGen.cs
tools/generator/SourceWriters/BoundMethodAbstractDeclaration.cs
tools/generator/SourceWriters/ClassInvokerClass.cs

Context: https://github.com/xamarin/xamarin-android/pull/7796
Imagine the following construct, which is new in `android.jar` API-34:
```java
public abstract class CharBuffer extends Buffer {
public abstract CharBuffer duplicate ();
}
public abstract class Buffer  {
public abstract Buffer duplicate ();
}
```
Generating the subclass's `abstract` method causes:
```
error CS0533: 'CharBuffer.Duplicate()' hides inherited abstract member 'Buffer.Duplicate()'
```
C# supports this construct if we make the subclass's `abstract` method with `override`:
```csharp
public abstract class CharBuffer : Buffer {
public override abstract CharBuffer Duplicate ();
}
```
Theoretically we can tell `generator` how to fix this thanks [to our addition](https://github.com/xamarin/java.interop/pull/701) of the …

[generator] Allow 'managedOverride' metadata to support 'abstract' methods.

---

tests/generator-Tests/Unit-Tests/CodeGeneratorTests.cs
tests/generator-Tests/Unit-Tests/DefaultInterfaceMethodsTests.cs
tools/generator/Java.Interop.Tools.Generator.Importers/XmlApiImporter.cs
tools/generator/Java.Interop.Tools.Generator.ObjectModel/Method.cs
tools/generator/SourceWriters/Extensions/SourceWriterExtensions.cs

Fixes: https://github.com/xamarin/java.interop/issues/810
When a new `abstract` method is added to an existing class, that is a breaking change that we do not wish to inflict upon our users.  Instead, we will change it to a "normal" method that catches a Java `NoSuchMethodError` if the `abstract` method is not implemented.  If the method does not exist, we throw a `AbstractMethodError` instead.
This is accomplished by using metadata to set `compatVirtualMethod` on a method to `true`.
API-34 adds:
```csharp
public abstract Java.Nio.ByteBuffer Slice (int index, int length);
```
Setting `compatVirtualMethod` to `true`:
```xml
<attr path="/api/package[@name='java.nio']/class[@name='ByteBuffer']/method[@name='slice']" name="compatVirtualMethod">true</attr>
```
Changes the method to:
```csharp …
```

[generator] Add support for 'compatVirtualMethod'.

---

tests/generator-Tests/Unit-Tests/GenBaseTests.cs
tools/generator/Java.Interop.Tools.Generator.ObjectModel/Method.cs

Context: https://github.com/xamarin/java.interop/pull/1080
When running the latest `generator` against `GooglePlayServices`, it hits an NRE when attempting to `Method.Clone (...)` a method with generic arguments while building `com.google.firebase.firebase-components.csproj`:
```
BINDINGSGENERATOR error BG0000: System.NullReferenceException: Object reference not set to an instance of an object. [c:\g\generated\com.google.firebase.firebase-components\com.google.firebase.firebase-components.csproj]
error BG0000: System.NullReferenceException: Object reference not set to an instance of an object.
at MonoDroid.Generation.Method.Clone(GenBase declaringType) in C:\code\xamarin-android\external\Java.Interop\tools\generator\Java.Interop.Tools.Generator.ObjectModel\Method.cs:line 131
at …
```

[generator] Fix an NRE when cloning a method with generic arguments.

---

src/Xamarin.SourceWriter/Models/MethodWriter.cs
tests/generator-Tests/Unit-Tests/CodeGeneratorTests.cs
tools/generator/Java.Interop.Tools.Generator.Importers/XmlApiImporter.cs
tools/generator/Java.Interop.Tools.Generator.ObjectModel/ClassGen.cs
tools/generator/SourceWriters/BoundClass.cs
tools/generator/SourceWriters/ConstructorPartialMethod.cs
tools/generator/SourceWriters/JavaLangObjectConstructor.cs

Context: https://github.com/xamarin/java.interop/issues/1085
Context: https://github.com/dotnet/runtime/pull/82121
Some Java objects are *big*, e.g. [`Bitmap`][0] instances, but as
far as MonoVM is concerned, the `Bitmap` instances are *tiny*: a
few pointers, and that's it.  MonoVM doesn't know that it could be
referencing several MB of data in the Java VM.
MonoVM is gaining support for [`GC.AddMemoryPressure()`][1] and
[`GC.RemoveMemoryPressure()`][2], which potentially allows for the
parent of all cross-VM GC integrations: using the `GC` methods to
inform MonoVM of how much non-managed memory has been allocated.
This could allow MonoVM to collect more frequently when total process
memory is low.
How should we call `GC.AddMemoryPressure()` and
`GC.RemoveMemoryPressure()`? …

[generator] Add support for peerConstructorPartialMethod

---

src/Xamarin.Android.Tools.Bytecode/Methods.cs

Fixes: https://github.com/xamarin/java.interop/issues/1090
Attempting to parse [TensorFlow 1.13.1][0] with a Debug build of `class-parse` results in an assertion failure:
% curl -o tensorflow-android-1.13.1.aar https://repo1.maven.org/maven2/org/tensorflow/tensorflow-android/1.13.1/tensorflow-android-1.13.1.aar
% unzip tensorflow-android-1.13.1.aar classes.jar
% dotnet bin/Debug-net7.0/class-parse.dll classes.jar
Unexpected number of method parameters; expected 0, got 1
at Xamarin.Android.Tools.Bytecode.MethodInfo.UpdateParametersFromMethodParametersAttribute(ParameterInfo[] parameters)
at Xamarin.Android.Tools.Bytecode.MethodInfo.GetParameters()
at Xamarin.Android.Tools.Bytecode.XmlClassDeclarationBuilder.GetMethodParameters(MethodInfo method)+MoveNext()
at …

[Xamarin.Android.Tools.Bytecode] Ignore synthetic ctor params

---

src/Xamarin.Android.Tools.Bytecode/ClassPath.cs

While building `AndroidX.sln`, `class-parse` is taking up a considerable amount of time.  After some quick profiling, this seems to be caused by reading from a `ZipStream` one or two bytes at a time.  Wrapping the `ZipStream` in a `BufferedStream` makes the `class-parse` process about 10x faster on larger test cases.
|   | `main` | This PR |
| - | - | - |
| `class-parse` on API-33 `android.jar` (26.5 MB) | 16.675s | 2.759s |
| `class-parse` on `androidx.compose.runtime.runtime` (1.044 MB) | 9.713s | .893s |
| Total `class-parse` time building `AndroidX.sln` | 5:48.46m | 2:09.73m |
| Total time building `AndroidX.sln` | 7:40.19m | 4:42.34m |

[class-parse] Use `BufferedStream` for up to 10x performance gain

---

src/Xamarin.Android.Tools.Bytecode/ClassPath.cs

Some AndroidX packages contain a file called `module-info.class` that is not a standard `.class` file.  Rather, this file is a metadata file for Java Modules ([documentation](https://www.oracle.com/corporate/features/understanding-java-9-modules.html)).
`class-parse` emit this for the file:
```xml
<package
name=""
jni-name="">
<class
abstract="false"
deprecated="not deprecated"
final="false"
name="module-info"
jni-signature="Lmodule-info;"
source-file-name="module-info.java"
static="false"
visibility="" />
</package>
```
When we try to resolve this type, `generator` emits the following warning:
```
warning BG8605: The Java type '' could not be found (are you missing a Java reference jar/aar or a Java binding library NuGet?)
```
This is neither useful nor actionable.  Instead, we should …

[class-parse] Ignore `module-info.class` file.

---

src/Java.Interop.Tools.JavaTypeSystem/Adapters/JavaXmlApiExporter.cs
src/Java.Interop.Tools.JavaTypeSystem/Adapters/JavaXmlApiImporter.cs
src/Java.Interop.Tools.JavaTypeSystem/Adapters/ManagedApiImporter.cs
src/Java.Interop.Tools.JavaTypeSystem/JavaModels/JavaConstructorModel.cs
src/Java.Interop.Tools.JavaTypeSystem/JavaModels/JavaFieldModel.cs
src/Java.Interop.Tools.JavaTypeSystem/JavaModels/JavaMemberModel.cs
src/Java.Interop.Tools.JavaTypeSystem/JavaModels/JavaMethodModel.cs
src/Xamarin.Android.Tools.Bytecode/XmlClassDeclarationBuilder.cs
tests/generator-Tests/Unit-Tests/CodeGeneratorTests.cs
tools/generator/CodeGenerationOptions.cs
tools/generator/CodeGenerator.cs
tools/generator/CodeGeneratorOptions.cs
tools/generator/Java.Interop.Tools.Generator.Importers/XmlApiImporter.cs
tools/generator/Java.Interop.Tools.Generator.ObjectModel/Field.cs
tools/generator/Java.Interop.Tools.Generator.ObjectModel/GenBase.cs
tools/generator/Java.Interop.Tools.Generator.ObjectModel/GenBaseSupport.cs
tools/generator/Java.Interop.Tools.Generator.ObjectModel/MethodBase.cs
tools/generator/SourceWriters/Attributes/RestrictToAttr.cs
tools/generator/SourceWriters/BoundClass.cs
tools/generator/SourceWriters/BoundConstructor.cs
tools/generator/SourceWriters/BoundField.cs
tools/generator/SourceWriters/BoundFieldAsProperty.cs
tools/generator/SourceWriters/BoundInterface.cs
tools/generator/SourceWriters/BoundInterfaceMethodDeclaration.cs
tools/generator/SourceWriters/BoundMethod.cs
tools/generator/SourceWriters/BoundMethodAbstractDeclaration.cs
tools/generator/SourceWriters/BoundMethodExtensionStringOverload.cs
tools/generator/SourceWriters/BoundMethodStringOverload.cs
tools/generator/SourceWriters/BoundProperty.cs
tools/generator/SourceWriters/Extensions/SourceWriterExtensions.cs

Fixes: https://github.com/xamarin/java.interop/issues/1081
Android has an [annotation](https://developer.android.com/reference/androidx/annotation/RestrictTo) `androidx.annotation.RestrictTo` (`@RestrictTo`) that essentially means "this API is implemented as `public`, but we do not consider it public API".  This means that Google reserves the right to change it at any time (see https://github.com/xamarin/AndroidX/issues/690).  Because we simply bind the API as `public`, it misleads our users into thinking this is a stable API they can rely on.
In `androidx.appcompat.appcompat-resources` `1.6.0`, Google [decided to promote classes](https://android-review.googlesource.com/c/platform/frameworks/support/+/2120177) that were previously marked as …

[generator] Add support for `@RestrictTo`.

---

src/Xamarin.Android.Tools.Bytecode/AttributeInfo.cs
src/Xamarin.Android.Tools.Bytecode/ClassFile.cs
src/Xamarin.Android.Tools.Bytecode/ClassPath.cs
src/Xamarin.Android.Tools.Bytecode/Kotlin/KotlinFixups.cs
src/Xamarin.Android.Tools.Bytecode/Modules.cs
src/Xamarin.Android.Tools.Bytecode/Xamarin.Android.Tools.Bytecode.csproj
src/Xamarin.Android.Tools.Bytecode/XmlClassDeclarationBuilder.cs
tests/Xamarin.Android.Tools.Bytecode-Tests/ExpectedTypeDeclaration.cs
tests/Xamarin.Android.Tools.Bytecode-Tests/ModuleInfoTests.cs
tests/Xamarin.Android.Tools.Bytecode-Tests/Xamarin.Android.Tools.Bytecode-Tests.csproj
tests/Xamarin.Android.Tools.Bytecode-Tests/Xamarin.Android.Tools.Bytecode-Tests.targets
tests/Xamarin.Android.Tools.Bytecode-Tests/java/com/xamarin/internal/PublicClassNotInModuleExports.java
tests/Xamarin.Android.Tools.Bytecode-Tests/java/com/xamarin/module-info.java
tools/class-parse/Program.cs

Fixes: https://github.com/xamarin/java.interop/issues/1096
Context: https://stackoverflow.com/questions/57358750/module-info-class-file-is-different-in-the-module-jar-file-and-compiled-module-i
Context: 678c4bd2c838141be0e18b23690da8dcdd94e0ec
JDK 9 adds support for [modules][0], which are (kinda sorta) like
.NET Assemblies: modules can depend upon other modules, export
packages, etc.
In particular:
> **exports and exports…to.** An exports module directive specifies
> one of the module’s packages whose `public` types (and their nested
> `public` and `protected` types) should be accessible to code in all
> other modules.
This allows an equivalent to the [C# `internal` access modifier][1]:
`public` types in a *non-`export`ed package* should be treated as
"internal", while `public` types in …

[class-parse] support Module AttributeInfo

---

src/Java.Interop.Tools.JavaTypeSystem/Adapters/JavaXmlApiExporter.cs
src/Java.Interop.Tools.JavaTypeSystem/Adapters/JavaXmlApiImporter.cs
src/Java.Interop.Tools.JavaTypeSystem/Adapters/ManagedApiImporter.cs
src/Java.Interop.Tools.JavaTypeSystem/JavaModels/JavaBuiltInType.cs
src/Java.Interop.Tools.JavaTypeSystem/JavaModels/JavaClassModel.cs
src/Java.Interop.Tools.JavaTypeSystem/JavaModels/JavaInterfaceModel.cs
src/Java.Interop.Tools.JavaTypeSystem/JavaModels/JavaTypeModel.cs
tests/Java.Interop.Tools.JavaTypeSystem-Tests/Java.Interop.Tools.JavaTypeSystem-Tests.csproj
tests/Java.Interop.Tools.JavaTypeSystem-Tests/JavaApiTestHelper.cs
tests/Java.Interop.Tools.JavaTypeSystem-Tests/JavaTypeModelsTests.cs

Context: https://github.com/xamarin/java.interop/pull/1094
When adding support for Android's `@RestrictTo` annotation in https://github.com/xamarin/java.interop/pull/1094, the XML Adjuster step was accidentally only modified to pass through the `annotated-visibility` attribute for members and not for types.
Fix this by storing and emitting the `annotated-visibility` attribute for types.

[Java.Interop.Tools.JavaTypeSystem] Add 'annotated-visibility' for types.

---

src/Java.Interop.Tools.Cecil/Java.Interop.Tools.Cecil/DirectoryAssemblyResolver.cs

Context: https://github.com/dotnet/linker/pull/1130
Context: https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1783420
In dotnet/linker#1130, their version of `DirectoryAssemblyResolver` was reworked to use `MemoryMappedFile` in the .NET 6 timeframe. This commit ports these changes here, as we have MSBuild tasks in xamarin/xamarin-android that use `DirectoryAssemblyResolver`.
Primarily, the `<GenerateJavaStubs />` MSBuild task uses `DirectoryAssemblyResolver` to iterate over types in assembly to emit Java source code and generate `AndroidManifest.xml`.
The results of these changes in a `dotnet new maui` project, an initial clean build:
GenerateJavaStubs = 1.318 s, 1 calls.
GenerateJavaStubs = 1.254 s, 1 calls.
Saving ~64ms or about ~5% in this example.
The current version of the …

[Java.Interop.Tools.Cecil] use MemoryMappedFile in DirectoryAssemblyResolver

---

tests/generator-Tests/Unit-Tests/CodeGeneratorExpectedResults/Common/WriteDuplicateInterfaceEventArgs.txt
tests/generator-Tests/Unit-Tests/CodeGeneratorExpectedResults/JavaInterop1/WriteDuplicateInterfaceEventArgs.txt
tests/generator-Tests/expected.xaji/Core_Jar2Xml/Android.Views.View.cs
tests/generator-Tests/expected.xaji/GenericArguments/Com.Google.Android.Exoplayer.Drm.IExoMediaDrm.cs
tools/generator/SourceWriters/InterfaceEventHandlerImplClass.cs

Context: https://github.com/dotnet/maui/issues/12130
Context: https://github.com/angelru/CvSlowJittering
Profiling a .NET MAUI customer sample while scrolling on a Pixel 5, I see ~2.2% of the time spent in:
(2.2%) mono.android!Android.Views.View.IOnFocusChangeListenerImplementor..ctor()
https://github.com/dotnet/maui/blob/2041476e78452891029f4d2bd806c45be42f4878/src/Core/src/Handlers/View/ViewHandler.Android.cs#L14
MAUI subscribes to `Android.Views.View.FocusChange` for every view placed on the screen -- which happens while scrolling in this sample.
Reviewing, the generated code for this constructor still uses the outdated `JNIEnv` APIs:
public IOnFocusChangeListenerImplementor () : base (global::Android.Runtime.JNIEnv.StartCreateInstance …

[generator] improve *Implementor constructors

---

src/Xamarin.Android.Tools.Bytecode/Kotlin/KotlinMetadata.cs

Fixes: https://github.com/xamarin/java.interop/issues/1106
We started seeing warnings when parsing newer Kotlin metadata annotations:
```
% dotnet class-parse.dll classes.jar
class-parse: warning: Unable to parse Kotlin metadata on 'Utf8("com/devtodev/analytics/external/DTDLogLevel")': System.FormatException: The input string '' was not in a correct format.
at System.Number.ThrowOverflowOrFormatException(ParsingStatus status, ReadOnlySpan`1 value, TypeCode type)
at System.Int32.Parse(String s)
at Xamarin.Android.Tools.Bytecode.KotlinMetadata.ParseInteger(String value) in …/xamarin/Java.Interop/src/Xamarin.Android.Tools.Bytecode/Kotlin/KotlinMetadata.cs:line 148
at Xamarin.Android.Tools.Bytecode.KotlinMetadata.<>c.<ParseVersion>b__26_0(String v) in …
```

[Xamarin.Android.Tools.Bytecode] Handle empty `bv` values.

---

src/Java.Interop.Tools.JavaTypeSystem/JavaModels/JavaMethodModel.cs
tests/Java.Interop.Tools.JavaTypeSystem-Tests/BaseMethodTests.cs

Context: https://github.com/xamarin/AndroidX/pull/723
Imagine we have the following Java:
```java
public final class AesGcmHkdfStreamingKey extends StreamingAeadKey {
@Override
public AesGcmHkdfStreamingParameters getParameters() { ... }
}
public abstract class StreamingAeadKey extends Key {
@Override
public abstract StreamingAeadParameters getParameters();
}
public abstract class Key {
public abstract Parameters getParameters();
}
```
The reabstraction in `StreamingAeadKey` causes an additional synthetic method to be generated:
```xml
<class abstract="true" deprecated="not deprecated" jni-extends="Lcom/google/crypto/tink/Key;" extends="com.google.crypto.tink.Key" extends-generic-aware="com.google.crypto.tink.Key" final="false" name="StreamingAeadKey" …
```

[Java.Interop.Tools.JavaTypeSystem] Prefer matching to non-synthetic base methods.

---

Directory.Build.props
Directory.Build.targets
Directory.Packages.props
NuGet.Config
build-tools/scripts/cecil.projitems
tests/Java.Interop.Tools.Expressions-Tests/Java.Interop.Tools.Expressions-Tests.csproj

Context: https://learn.microsoft.com/en-us/nuget/consume-packages/central-package-management
Context: https://learn.microsoft.com/en-us/nuget/consume-packages/package-source-mapping
Switch to [NuGet's Central Package Management](https://learn.microsoft.com/en-us/nuget/consume-packages/central-package-management).  Although this is very similar to the "homegrown" central package management we currently have, using the "official" version means that there is additional tooling support available, such as being supported by `dotnet add package`, Visual Studio, and dependabot.
Central Package Management also requires [Package Source Mapping](https://learn.microsoft.com/en-us/nuget/consume-packages/package-source-mapping), so we also add that information to our `NuGet.config`.

[build] Switch to NuGet's Central Package Management.

---

tests/generator-Tests/Unit-Tests/CodeGeneratorExpectedResults/JavaInterop1/WriteDuplicateInterfaceEventArgs.txt
tests/generator-Tests/Unit-Tests/CodeGeneratorExpectedResults/XAJavaInterop1/WriteDuplicateInterfaceEventArgs.txt
tests/generator-Tests/Unit-Tests/CodeGeneratorTests.cs
tools/generator/SourceWriters/InterfaceEventHandlerImplClass.cs

When building API-33 `Mono.Android.dll`, there are 227 instances of the warning:
```
warning CS8618: Non-nullable field 'sender' must contain a non-null value when exiting constructor. Consider declaring the field as nullable.
```
This is caused by the following generated code:
```csharp
internal sealed partial class IAnimatorUpdateListenerImplementor : global::Java.Lang.Object, IAnimatorUpdateListener {
object sender;
public unsafe IAnimatorUpdateListenerImplementor (object sender) : base (IntPtr.Zero, JniHandleOwnership.DoNotTransfer)
{
const string __id = "()V";
if (((global::Java.Lang.Object) this).Handle != IntPtr.Zero)
return;
var h = JniPeerMembers.InstanceMethods.StartCreateInstance (__id, ((object) this).GetType (), null);
SetHandle (h.Handle, …
```

[generator] Add missing nullable annotation.

---

build-tools/scripts/Prepare.targets

Context: https://github.com/xamarin/java.interop/pull/1120
When multiple JDK's are found, a JDK 8 might be chosen.  Specify `MinimumJdkVersion` as `11` to ensure we get JDK 11 or newer.

[Prepare.targets] Specify JDK 11 as our minimum.

---

tests/generator-Tests/Unit-Tests/CodeGeneratorTests.cs
tools/generator/Java.Interop.Tools.Generator.ObjectModel/GenBase.cs

There are several warnings when building `Mono.Android.dll` related to `Obsolete` methods:
```
warning CS0672: Member 'MediaRouteActionProvider.OnCreateActionView()' overrides obsolete member 'ActionProvider.OnCreateActionView()'. Add the Obsolete attribute to 'MediaRouteActionProvider.OnCreateActionView()'
```
Technically, `MediaRouteActionProvider.onCreateActionView` is marked as `deprecated` in the [docs](https://developer.android.com/reference/android/app/MediaRouteActionProvider?hl=en#onCreateActionView()), but not in the compiled `android.jar`:
```java
public class MediaRouteActionProvider extends ActionProvider {
public View onCreateActionView() {
throw new RuntimeException("Stub!");
}
}
```
Regardless, any method that overrides a deprecated method should itself be marked as …

[generator] Override methods should match base method's deprecated info.

---

src/Java.Interop.Tools.JavaSource/Java.Interop.Tools.JavaSource/SourceJavadocToXmldocGrammar.HtmlBnfTerms.cs
src/Java.Interop.Tools.JavaSource/Java.Interop.Tools.JavaSource/SourceJavadocToXmldocGrammar.InlineTagsBnfTerms.cs
tests/Java.Interop.Tools.JavaSource-Tests/SourceJavadocToXmldocGrammar.HtmlBnfTermsTests.cs

Parsing for `<a/>` elements has been improved to fix all 83 cases where
conversion to a `<see/>` element would fail.  Some examples of such
failures include:
System.Xml.XmlException: 'https' is an unexpected token. The expected token is '"' or '''. Line 1, position 11.
System.Xml.XmlException: '<', hexadecimal value 0x3C, is an invalid attribute character. Line 1, position 67.
Progress & activity</see>
System.Xml.XmlException: An error occurred while parsing EntityName. Line 2, position 11.
System.Xml.XmlException: '#' is an unexpected token. The expected token is '"' or '''. Line 1, position 11.
System.Xml.XmlException: 'http' is an unexpected token. The expected token is '"' or '''. Line 1, position 11.
When we encounter an `<a/>` element that points to code or a local path
we will now …

[Java.Interop.Tools.JavaSource] Improve `<a>` parsing

---

tests/Java.Interop-Tests/Java.Interop/JniValueMarshalerContractTests.cs

Context: https://github.com/dotnet/runtime/issues/89190

[tests] add category for tests that fail under LLVM

---

src/Java.Interop.Tools.Generator/Metadata/FixupXmlDocument.cs

As part of the NRT work in https://github.com/xamarin/java.interop/pull/1099, we added a warning when the `path` attribute of a "metadata" element isn't provided.  However, metadata files can also contain `<ns-replace>` elements, which do not have a `path` attribute, and thus erroneously trigger this warning:
```
generated\msbuild-metadata.xml(3,4): warning BG8A08: Metadata.xml element '<ns-replace source="com.google.androidx" replacement="Xamarin.AndroidX" />' is missing the 'path' attribute. 
```
Skip running any of the standard "metadata" logic when we hit a `<ns-replace>` element, as they are handled elsewhere.

[generator] Prevent BG8A08 warning when using `ns-replace`.

---

Directory.Build.props

As we consume nightly .NET 8 builds, they sometimes depend on nightly .NET 7 builds.
One error you can run into is:
error NU1102: Unable to find package Microsoft.AspNetCore.App.Ref with version (= 7.0.11)
error NU1102: Unable to find package Microsoft.WindowsDesktop.App.Ref with version (= 7.0.11)
For projects that are not even ASP.NET or Windows desktop apps! To even be able to access these feeds, they would be something like:
<add key="darc-pub-dotnet-aspnetcore-[SHA]" value="https://pkgs.dev.azure.com/dnceng/public/_packaging/darc-pub-dotnet-aspnetcore-[SHA]/nuget/v3/index.json" />
<add key="darc-pub-dotnet-windowsdesktop-[SHA]" value="https://pkgs.dev.azure.com/dnceng/public/_packaging/darc-pub-dotnet-windowsdesktop-[SHA]/nuget/v3/index.json" />
We don't currently track these …

[build] set `$(DisableTransitiveFrameworkReferenceDownloads)`

---

build-tools/Java.Interop.BootstrapTasks/Java.Interop.BootstrapTasks/JdkInfo.cs
build-tools/scripts/Prepare.targets
src/Java.Base/Java.Base.targets
src/Java.Base/Java.Lang/Class.cs
src/Java.Base/Java.Lang/Double.cs
src/Java.Base/Java.Lang/Float.cs
src/Java.Base/Java.Lang/Integer.cs
src/Java.Base/Java.Lang/Long.cs
src/Java.Base/Java.Lang/String.cs
src/Java.Base/Transforms/Metadata.xml

Update `<JdkInfo/>` task to emit new `$(Java*MajorVersion)` and `$(JavaApi*DefineConstants)` MSBuild properties.  These are used by `src/Java.Base` so that it knows which JDK version it's binding.
Update `src/Java.Base` to support binding the `java.base.jmod` from JDK 17.
Note: This "JDK-17 Java.Base binding" was a "time limited" effort.
To build against JDK-17:
1. Install JDK-17.
2. Prepare and override `$(JdksRoot)`:
dotnet build -t:Prepare Java.Interop.sln -p:JdksRoot=/Library/Java/JavaVirtualMachines/microsoft-17.jdk/Contents/Home
will use the Microsoft OpenJDK 17 installation on macOS.
3. Build:
dotnet build Java.Interop.sln

[build] Add support for JDK 17

---

src/Java.Interop.Tools.JavaTypeSystem/JavaModels/JavaFieldModel.cs

Context: https://discord.com/channels/732297728826277939/732297837953679412/1151531791069499524
A user reported the following output in their `java-resolution-report.log`:
```
The field 'Java.Interop.Tools.JavaTypeSystem.Models.JavaFieldModel' was removed because its name contains a dollar sign.
The class '[Class] com.google.android.libraries.navigation.internal.aac.ad' was removed because the Java base type 'com.google.android.libraries.navigation.internal.aad.ar<com.google.android.libraries.navigation.internal.aac.af<K, V>>' could not be found.
```
We should be providing the user with the name of the removed field rather than the `JavaFieldModel` type name.  To do this, add an appropriate `JavaFieldModel.ToString ()`.

[JavaTypeSystem] Add JavaFieldModel.ToString ().

---

external/xamarin-android-tools.override.props

Context: https://github.com/xamarin/xamarin-android/pull/8360
When .NET 8 RC 2 took a dependency on dotnet/runtime 7.0.12 and 6.0.23, we added a `xamarin-android-tools.override.props` with the contents:
<Project>
<PropertyGroup>
<RestoreAdditionalProjectSources>
https://pkgs.dev.azure.com/dnceng/public/_packaging/darc-pub-dotnet-runtime-26e0f822/nuget/v3/index.json;
https://pkgs.dev.azure.com/dnceng/public/_packaging/darc-pub-dotnet-runtime-301ba1ee/nuget/v3/index.json;
</RestoreAdditionalProjectSources>
</PropertyGroup>
</Project>
Unfortunately, this still broke for the submodule:
external/java.interop/external/xamarin-android-tools
This led to the error during the `prepare java.interop Debug` stage:
external/Java.Interop/external/xamarin-android-tools/src/Xamarin.Android.Tools.AndroidSdk …

[build] introduce `xamarin-android-tools.override.props`

---

tests/generator-Tests/Unit-Tests/CodeGeneratorTests.cs
tools/generator/CodeGenerationOptions.cs
tools/generator/CodeGenerator.cs
tools/generator/CodeGeneratorOptions.cs
tools/generator/Java.Interop.Tools.Generator.ObjectModel/GenBase.cs

Fixes: https://github.com/xamarin/java.interop/issues/1142
Context: https://github.com/xamarin/java.interop/pull/1130
In https://github.com/xamarin/java.interop/pull/1130 we added a feature to automatically mark a method as "deprecated" if it overrides a "deprecated" method.
However, there can be instances where this is undesirable for a user, and there is currently no way to opt out on a global or `metadata` level.
Add a global opt-out for this feature, usable via:
```
--lang-features=do-not-fix-obsolete-overrides
```
This will be made available to users via an MSBuild property in an additional PR.

[generator] Provide opt-out for obsolete override fixup.

---

tests/generator-Tests/Unit-Tests/CodeGeneratorExpectedResults/Common/WriteDuplicateInterfaceEventArgs.txt
tests/generator-Tests/Unit-Tests/CodeGeneratorExpectedResults/JavaInterop1/WriteDuplicateInterfaceEventArgs.txt
tests/generator-Tests/Unit-Tests/CodeGeneratorExpectedResults/XAJavaInterop1/WriteDuplicateInterfaceEventArgs.txt
tests/generator-Tests/expected.xaji/Core_Jar2Xml/Android.Views.View.cs
tests/generator-Tests/expected.xaji/GenericArguments/Com.Google.Android.Exoplayer.Drm.IExoMediaDrm.cs
tools/generator/SourceWriters/InterfaceEventHandlerImplClass.cs

Fixes: https://github.com/xamarin/xamarin-android/issues/8337
A customer's app with the code:
SetContentView(Resource.Layout.activity_main);
FindViewById<Button>(Resource.Id.asd).Click += MainActivity_Click;
Crashes with `-c Release -p:AndroidLinkMode=r8` with:
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.companyname.New_folder/crc64abe8cc9139195b67.MainActivity}: java.lang.ClassNotFoundException: android.view.View_IOnClickListenerImplementor
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3644)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3781)
at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:101)
at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionEx …

[generator] restore `[RegisterAttribute]` for *Implementor types

---

tools/class-parse/Program.cs

For initial "why did `class-parse` mark this function as `kotlin-internal`" type questions, it would be helpful if `class-parse -dump` could output a parsed Kotlin metadata blob.  
Unfortunately, the Kotlin metadata blob is pretty raw, but if we start adding our logic to it then the output will be incorrect if our assumptions about how the data works are incorrect.  Thus this PR is up for debate if it actually improves the situation or not.
Example:
```
class-parse -dump EmojiPickerView.class
--- cut normal content ---
Kotlin Class Metadata [1.8.0]:
{
"$id": "1",
"CompanionObjectName": "Companion",
"Constructors": { ... },
"EnumEntries": {
"$id": "14",
"$values": []
},
"Flags": 6,
"FullyQualifiedName": null,
"Inheritability": 0,
"NestedClassNames": {
"$id": "15",
"$values": [
"Companion" …
```

[class-parse] Add Kotlin metadata to `-dump`.

---

src/Java.Interop/Java.Interop/JniRuntime.cs
src/Java.Runtime.Environment/Java.Interop/JreRuntime.cs
tests/Java.Interop-Tests/Java.Interop/JniRuntimeTest.cs

Context: https://github.com/xamarin/java.interop/pull/1153
[JNI][0] supports *two* modes of operation:
1. Native code creates the JVM, e.g. via [`JNI_CreateJavaVM()`][1]
2. The JVM already exists, and when Java code calls [`System.loadLibrary()`][3], the JVM calls the [`JNI_OnLoad()`][2] function on the specified library.
Java.Interop samples and unit tests rely on the first approach, e.g. `TestJVM` subclasses `JreRuntime`, which is responsible for calling `JNI_CreateJavaVM()` so that Java code can be used.
PR #1153 is exploring the use of [.NET Native AOT][4] to produce a native library which is used with Java-originated initialization.
In order to make Java-originated initialization *work*, we need to be able to initialize `JniRuntime` and `JreRuntime` around existing JVM-provided …

[Java.Interop] Allow JniRuntime init from JavaVM* and JNIEnv*

---

src/Java.Interop.Tools.JavaCallableWrappers/Java.Interop.Tools.JavaCallableWrappers/JavaCallableWrapperGenerator.cs
tests/Java.Interop.Tools.JavaCallableWrappers-Tests/Java.Interop.Tools.JavaCallableWrappers/JavaCallableWrapperGeneratorTests.cs

Fixes: https://github.com/xamarin/xamarin-android/issues/7554
Placing `[Export]` on a constructor with parameters did not work as expected.  Consider:
public class Example : Java.Lang.Object
{
[Export(SuperArgumentsString = "")]
public Example (int value)
{
this.value = value;
}
int value;
}
This *does* generate a Java Callable Wrapper with the desired constructor, but it *doesn't* invoke the correct C# constructor, because of the `TypeManager.Activate()` invocation:
// Java JCW
/* partial */ class Example extends java.lang.Object {
public Example(int p0) {
super ();
if (getClass () == Example.class) {
mono.android.TypeManager.Activate (
/* typeName */      "Namespace.Example, Assembly",
/* signature */     "",
/* instance */      this,
/* parameterList */ new java.lang.Object[] { p0 }); …

[Java.Interop.Tools.JavaCallableWrappers] [Export]+params

---

src/Java.Interop.Export/Java.Interop/JavaCallableAttribute.cs
src/Java.Interop.Export/Java.Interop/JavaCallableConstructorAttribute.cs
src/Java.Interop.Export/Java.Interop/MarshalMemberBuilder.cs
src/Java.Interop.Tools.Expressions/Java.Interop.Tools.Expressions/ExpressionAssemblyBuilder.cs
src/Java.Interop.Tools.JavaCallableWrappers/Java.Interop.Tools.JavaCallableWrappers/JavaCallableWrapperGenerator.cs
src/Java.Interop/Java.Interop/JniRuntime.JniTypeManager.cs
src/Java.Interop/Java.Interop/JniTypeSignatureAttribute.cs
src/Java.Interop/Java.Interop/ManagedPeer.cs
src/Java.Runtime.Environment/Java.Interop/JreTypeManager.cs
tests/Java.Interop.Export-Tests/Java.Interop.Export-Tests.csproj
tests/Java.Interop.Export-Tests/Java.Interop.Export-Tests.targets
tests/Java.Interop.Export-Tests/Java.Interop/JavaCallableExample.cs
tests/Java.Interop.Export-Tests/Java.Interop/JavaCallableExampleTests.cs
tests/Java.Interop.Export-Tests/Java.Interop/MarshalMemberBuilderTest.cs
tests/Java.Interop.Export-Tests/java/com/xamarin/interop/export/ExportType.java
tests/Java.Interop.Export-Tests/java/net/dot/jni/test/UseJavaCallableExample.java
tests/Java.Interop.Tools.JavaCallableWrappers-Tests/Java.Interop.Tools.JavaCallableWrappers-Tests.csproj
tests/Java.Interop.Tools.JavaCallableWrappers-Tests/Java.Interop.Tools.JavaCallableWrappers/JavaCallableWrapperGeneratorTests.cs
tests/Java.Interop.Tools.JavaCallableWrappers-Tests/Java.Interop.Tools.JavaCallableWrappers/SupportDeclarations.cs
tools/jnimarshalmethod-gen/App.cs

Context: https://github.com/xamarin/java.interop/pull/1153
Context: 4787e0179b349ab5ee0d0dd03d08b694acea4971
Context: 77800dda83c2db4d90b501c00069abc9880caaeb
PR #1153 is exploring the use of [.NET Native AOT][0] to produce a
native library which is used *within* a `java`-originated process:
% java -cp … com/microsoft/hello_from_jni/App
As NativeAOT has no support for `System.Reflection.Emit`, the only
way for Java code to invoke managed code -- in a Desktop Java.Base
environment! [^0] see 4787e01 -- would be to pre-generate the
required marshal methods via `jnimarshalmethod-gen`.
This in turn requires updating `jcw-gen` to support the pre-existing
`Java.Interop.JavaCallableAttribute`, so that C# code could
reasonably declare methods visible to Java, along with the
introduction of, and …

[jcw-gen, jnimarshalmethod-gen] Native method consistency

---

src/Java.Interop.Tools.JavaCallableWrappers/Java.Interop.Tools.JavaCallableWrappers/JavaCallableWrapperGenerator.cs
src/Java.Interop/Java.Interop/JniConstructorSignatureAttribute.cs
tests/Java.Base-Tests/Java.Base-Tests.targets
tests/Java.Interop.Export-Tests/Java.Interop/JavaCallableExampleTests.cs
tests/generator-Tests/Unit-Tests/CodeGeneratorExpectedResults/JavaInterop1/WriteClass.txt
tests/generator-Tests/expected.ji/AccessModifiers/Xamarin.Test.ExtendPublicClass.cs
tests/generator-Tests/expected.ji/AccessModifiers/Xamarin.Test.PublicClass.cs
tests/generator-Tests/expected.ji/AccessModifiers/Xamarin.Test.TestClass.cs
tests/generator-Tests/expected.ji/Constructors/Xamarin.Test.SomeObject.cs
tests/generator-Tests/expected.ji/Constructors/Xamarin.Test.SomeObject2.cs
tests/generator-Tests/expected.ji/Streams/Java.IO.FilterOutputStream.cs
tests/generator-Tests/expected.ji/Streams/Java.IO.InputStream.cs
tests/generator-Tests/expected.ji/Streams/Java.IO.OutputStream.cs
tests/generator-Tests/expected.ji/TestInterface/ClassWithoutNamespace.cs
tests/generator-Tests/expected.ji/TestInterface/Test.ME.GenericImplementation.cs
tests/generator-Tests/expected.ji/TestInterface/Test.ME.GenericObjectPropertyImplementation.cs
tests/generator-Tests/expected.ji/TestInterface/Test.ME.GenericStringImplementation.cs
tests/generator-Tests/expected.ji/TestInterface/Test.ME.GenericStringPropertyImplementation.cs
tests/generator-Tests/expected.ji/TestInterface/Test.ME.TestInterfaceImplementation.cs
tools/generator/SourceWriters/Attributes/RegisterAttr.cs
tools/generator/SourceWriters/BoundConstructor.cs

Context: 3043d890239cf53eb42633430faa417c140c8952
Constructors, how do they work?
Commit 3043d890 goes into some details about the interaction between Java constructors and managed-side constructors when the Java constructor is invoked first.
What happens when the managed-side constructor is invoked first?
class JavaInteropExample : Java.Lang.Object {
[JavaCallableConstructor(SuperConstructorExpression="")]
public JavaInteropExample (int a, int b) {}
}
*Before* that code runs (ideally), `jcw-gen` (or equivalent) will run, creating a Java Callable Wrapper for `JavaInteropExample`, and that Java Callable Wrapper (JCW) will contain a constructor:
// JCW
/* partial */ class JavaInteropExample extends java.lang.Object {
public JavaInteropExample(int p0, int p1) {
super ();
if (getClass () == …

[generator] `[JniConstructorSignature]` on bound constructors

---

build-tools/automation/templates/core-tests.yaml
tools/jnimarshalmethod-gen/App.cs

Fixes: https://github.com/xamarin/java.interop/issues/1159
Context: c93fea090be9bd76f477496d4c9d4ab353ba73f1
`jnimarshalmethod-gen` is intended to generate marshal methods for any type that that:
* Has `[JavaCallable]` (tested in `Java.Interop.Export-Tests.dll` and c93fea09), or
* Overrides a `virtual` method which has `[JniMethodSignature]`, or
* Implements an interface method which has `[JniMethodSignature]`.
Thus, the intention was that it should generate marshal methods for `Java.Base-Tests`:
% dotnet bin/Debug-net7.0/jnimarshalmethod-gen.dll -v bin/TestDebug-net7.0/Java.Base-Tests.dll
Unable to read assembly 'bin/TestDebug-net7.0/Java.Base-Tests.dll' with symbols. Retrying to load it without them.
Preparing marshal method assembly 'Java.Base-Tests-JniMarshalMethods'
Processing …

[jnimarshalmethod-gen] JavaInterop1 marshal methods

---

src/Java.Base-ref.cs

Context: f998c4224e4f5925e18e817edac011aa40a72ebc
Context: 1adb7964a2033c83c298c070f2d1ab896d92671b
Commit 1adb7964 added bindings for `java.util.function`.
Commit f998c422 added `[JniConstructorSignature]` to bound constructors.
Update `src/Java.Base-ref.cs` to contain these changes, so that `git diff` doesn't constantly show this file as having changed.

[Java.Base] Update reference API

---

build-tools/jnienv-gen/Generator.cs
src/Java.Interop/Java.Interop.csproj
src/Java.Interop/Java.Interop/JavaObjectArray.cs
src/Java.Interop/Java.Interop/JniEnvironment.Types.cs
src/Java.Interop/Java.Interop/JniValueMarshaler.cs
src/Java.Interop/PublicAPI.Shipped.txt
src/Java.Interop/PublicAPI.Unshipped.txt
tests/invocation-overhead/jni.cs

Fixes: #1169 
Context: https://github.com/xamarin/xamarin-android/pull/8171
Like `Mono.Android.dll`, we consider the `Java.Interop.dll` public API of each target framework to be an immutable contract.  For example, this prevents an issue where a user on `.NET 8.0.300` uses a method that isn't available to their coworker or CI on `.NET 8.0.100`.
Thus we should enable [PublicApiAnalyzer](https://github.com/dotnet/roslyn-analyzers/tree/main/src/PublicApiAnalyzers) on `Java.Interop.dll` to ensure we do not break our contract.
Additionally, disable [`RS0041`](https://github.com/dotnet/roslyn-analyzers/blob/main/src/PublicApiAnalyzers/Microsoft.CodeAnalysis.PublicApiAnalyzers.md#rs0041-public-members-should-not-use-oblivious-types) ("Public members should not use oblivious types") as …

[Java.Interop] Enable PublicApiAnalyzers to prevent API contract breakage.

---

build-tools/automation/azure-pipelines.yaml

Context: https://devdiv.visualstudio.com/DevDiv/_wiki/wikis/DevDiv.wiki/25351/APIScan-step-by-step-guide-to-setting-up-a-Pipeline
The ApiScan task has been added to pipeline runs against `main`.  This
task should help us identify related issues earlier, rather than having
to wait for a full scan of VS.

[ci] Add API Scan job

---

src/Java.Interop.Dynamic/Java.Interop.Dynamic/JavaInstanceProxy.cs
src/Java.Interop.Tools.Cecil/Java.Interop.Tools.Cecil/TypeDefinitionRocks.cs
src/Java.Interop.Tools.JavaCallableWrappers/Java.Interop.Tools.JavaCallableWrappers/JavaCallableWrapperGenerator.cs
src/Java.Interop.Tools.JavaCallableWrappers/Java.Interop.Tools.JavaCallableWrappers/JavaTypeScanner.cs
src/Java.Interop.Tools.TypeNameMappings/Java.Interop.Tools.TypeNameMappings/JavaNativeTypeManager.cs
src/Java.Interop/Java.Interop/JavaException.cs
src/Java.Interop/Java.Interop/JavaObject.cs
src/Java.Interop/Java.Interop/JavaPrimitiveArrays.cs
src/Java.Interop/Java.Interop/JavaPrimitiveArrays.tt
src/Java.Interop/Java.Interop/JavaProxyObject.cs
src/Java.Interop/Java.Interop/JavaProxyThrowable.cs
src/Java.Interop/Java.Interop/ManagedPeer.cs
tests/Java.Interop-PerformanceTests/Java.Interop/JavaTiming.cs
tests/Java.Interop-Tests/Java.Interop-Tests.csproj
tests/Java.Interop-Tests/Java.Interop-Tests.targets
tests/Java.Interop-Tests/Java.Interop/CallNonvirtualBase.cs
tests/Java.Interop-Tests/Java.Interop/CallNonvirtualDerived.cs
tests/Java.Interop-Tests/Java.Interop/CallNonvirtualDerived2.cs
tests/Java.Interop-Tests/Java.Interop/CallVirtualFromConstructorBase.cs
tests/Java.Interop-Tests/Java.Interop/CallVirtualFromConstructorDerived.cs
tests/Java.Interop-Tests/Java.Interop/GetThis.cs
tests/Java.Interop-Tests/Java.Interop/JavaManagedGCBridgeTests.cs
tests/Java.Interop-Tests/Java.Interop/JavaObjectTest.cs
tests/Java.Interop-Tests/Java.Interop/JavaVMFixture.cs
tests/Java.Interop-Tests/Java.Interop/JniPeerMembersTests.cs
tests/Java.Interop-Tests/Java.Interop/JniTypeManagerTests.cs
tests/Java.Interop-Tests/Java.Interop/TestType.cs
tests/Java.Interop.Export-Tests/Java.Interop/ExportTest.cs

Context: https://github.com/xamarin/xamarin-android/pull/8543
Context: https://github.com/xamarin/xamarin-android/pull/8625
Context: https://github.com/xamarin/java.interop/pull/1168
Context: def5bc0df68a5908fac85e5dd4f02f1e27c75882
Context: 005c914170a0af9069ff18fd4dd9d45463dd5dc6
xamarin/xamarin-android#8543 tested PR #1168, was Totally Green™ -- finding no issues -- and so we merged PR #1168 into 005c9141.
Enter xamarin/xamarin-android#8625, which bumps xamarin-android to use def5bc0d, which includes 005c9141.  xamarin/xamarin-android#8625 contains *failing unit tests* (?!), including
`Java.InteropTests.InvokeVirtualFromConstructorTests()`:
Java.Lang.LinkageError : net.dot.jni.test.CallVirtualFromConstructorDerived
----> System.NotSupportedException : Could not find System.Type …

[Java.Interop] Typemap support for JavaObject & `[JniTypeSignature]`

---

src/Java.Interop.Tools.Cecil/Java.Interop.Tools.Cecil/DirectoryAssemblyResolver.cs
tests/Java.Interop.Tools.JavaCallableWrappers-Tests/Java.Interop.Tools.JavaCallableWrappers/DirectoryAssemblyResolverTests.cs

Context: https://github.com/xamarin/java.interop/commit/7d42864d
Context: https://github.com/xamarin/xamarin-android/pull/8571
While debugging xamarin/xamarin-android#8571, I found the usage of `MemoryMappedFile` (from 7d42864d) broke `.pdb` symbol loading. This is OK, because we'll likely disable symbol loading anyway, but we should at least address our bugs here for the future.
In order for the following code to load symbols:
AssemblyDefinition result = ModuleDefinition.ReadModule (viewStream, options).Assembly;
You would need the following `ReaderParameters`:
* `ReadSymbols=true`
* `SymbolStream` containing a valid `Stream` to the `.pdb` file
To make this work, I had to:
* Create a `List<IDisposable>` for bookkeeping.
* When successful, we transfer ownership of the `MemoryMappedFile` …

[Java.Interop.Tools.Cecil] fix symbol loading in `DirectoryAssemblyResolver`

---

Directory.Build.props
build-tools/automation/azure-pipelines.yaml

Context: https://github.com/xamarin/java.interop/pull/1153
*Actually* building *and running* NativeAOT artifacts requires .NET 8.
Update `$(DotNetTargetFramework)` so that .NET 8 is used.

[build] Target `net8.0`

---

src/Java.Interop/Java.Interop.csproj
src/Java.Interop/Java.Interop/JavaArray.cs
src/Java.Interop/Java.Interop/JavaObject.cs
src/Java.Interop/Java.Interop/JavaObjectArray.cs
src/Java.Interop/Java.Interop/JavaPrimitiveArrays.cs
src/Java.Interop/Java.Interop/JavaPrimitiveArrays.tt
src/Java.Interop/Java.Interop/JniBuiltinMarshalers.cs
src/Java.Interop/Java.Interop/JniBuiltinMarshalers.tt
src/Java.Interop/Java.Interop/JniRuntime.JniMarshalMemberBuilder.cs
src/Java.Interop/Java.Interop/JniRuntime.JniTypeManager.cs
src/Java.Interop/Java.Interop/JniRuntime.JniValueManager.cs
src/Java.Interop/Java.Interop/JniRuntime.cs
src/Java.Interop/Java.Interop/JniStringValueMarshaler.cs
src/Java.Interop/Java.Interop/JniValueMarshaler.cs
src/Java.Interop/Java.Interop/JniValueMarshalerAttribute.cs
src/Java.Interop/Java.Interop/ManagedPeer.cs

Context: https://github.com/xamarin/java.interop/issues/1157
On the path to enabling `IsAotCompatible`, we can enable some settings
to get started:
<IsTrimmable>true</IsTrimmable>
<EnableSingleFileAnalyzer>true</EnableSingleFileAnalyzer>
<EnableAotAnalyzer>true</EnableAotAnalyzer>
This opts into the analyzers without declaring the assembly is fully AOT-compatible.
Starting out, I got 33 warnings: this is an attempt to address the ones that don't require too much thinking. Unfortunately, solving 1 warning likely will create dozens more -- as you have to update all callers.
This results in 24 warnings remaining. Since `Release` builds have `$(TreatWarningsAsErrors)`, I will wait to enable the analyzers until all warnings are addressed.
`System.Linq.Expression` usage: …

[java.interop] address some "easy" trimmer warnings

---

src/Java.Interop/Java.Interop.csproj
src/Java.Interop/Java.Interop/JniRuntime.JniMarshalMemberBuilder.cs
src/Java.Interop/Java.Interop/JniRuntime.JniTypeManager.cs
src/Java.Interop/Java.Interop/JniRuntime.JniValueManager.cs
src/Java.Interop/Java.Interop/JniValueMarshalerAttribute.cs
src/Java.Interop/Java.Interop/ManagedPeer.cs
src/Java.Interop/Properties/AssemblyInfo.cs

Fixes: https://github.com/xamarin/java.interop/issues/1157
The remaining trimmer warnings are around usage of System.Reflection such as:
* Create an `Invoker` type from an original type via `Type.Assembly.GetType()`
* Create a `Type` based on a `ParameterInfo.ParameterType` and/or create instances
* Use `Type.MakeGenericType()`
* Use `Type.MakeArrayType()`
The trimming warnings themselves all indicate that these types "might be trimmed", in that nothing explicitly preserves them. However, we have a plethora of custom trimmer steps that work to preserve these types involved in Java interop, such as:
* https://github.com/xamarin/xamarin-android/blob/main/src/Microsoft.Android.Sdk.ILLink/PreserveApplications.cs
* https://github.com/xamarin/xamarin-android/blob/main/src/Microsoft.Android.Sdk.I …

[Java.Interop] ignore remaining trimming warnings

---

src/Java.Interop/Java.Interop/JniRuntime.JniMarshalMemberBuilder.cs

Context: https://github.com/xamarin/java.interop/pull/1184#discussion_r1487482713
Previously we were using `Assembly.Load()` and `Assembly.GetType()`, which require us to ignore various trimmer warnings.
If we use `Type.GetType()` with a constant string instead, the trimmer knows how to handle this properly. (The code is also simpler.)

[Java.Interop] use `Type.GetType()` for `Java.Interop.MarshalMemberBuilder`

---

src/Java.Interop/Java.Interop/JniRuntime.JniMarshalMemberBuilder.cs

c6e38933 introduced build warning(s) in Android projects:
external/Java.Interop/src/Java.Interop/Java.Interop/JniRuntime.JniMarshalMemberBuilder.cs(33,4): warning IL2035: Java.Interop.JniRuntime.SetMarshalMemberBuilder(JniRuntime.CreationOptions): Unresolved assembly 'Java.Interop.Export' in 'DynamicDependencyAttribute'.
external/Java.Interop/src/Java.Interop/Java.Interop/JniRuntime.JniMarshalMemberBuilder.cs(33,4): warning IL2035: Java.Interop.JniRuntime.SetMarshalMemberBuilder(JniRuntime.CreationOptions): Unresolved assembly 'Java.Interop.Export' in 'DynamicDependencyAttribute'.
external/Java.Interop/src/Java.Interop/Java.Interop/JniRuntime.JniMarshalMemberBuilder.cs(33,4): warning IL2035: Java.Interop.JniRuntime.SetMarshalMemberBuilder(JniRuntime.CreationOptions): Unresolved assembly …

[Java.Interop] restore `IL2035` suppression

---

src/Java.Interop.Tools.JavaCallableWrappers/Java.Interop.Tools.JavaCallableWrappers.Adapters/CecilImporter.cs
src/Java.Interop.Tools.JavaCallableWrappers/Java.Interop.Tools.JavaCallableWrappers.CallableWrapperMembers/CallableWrapperType.cs
src/Java.Interop.Tools.JavaCallableWrappers/Java.Interop.Tools.JavaCallableWrappers.csproj
src/Java.Interop.Tools.JavaCallableWrappers/Java.Interop.Tools.JavaCallableWrappers/CecilExtensions.cs
src/Java.Interop.Tools.JavaCallableWrappers/Java.Interop.Tools.JavaCallableWrappers/TypeNameMapGenerator.cs
src/Java.Interop.Tools.TypeNameMappings/Java.Interop.Tools.TypeNameMappings/JavaNativeTypeManager.cs

Context: https://github.com/xamarin/xamarin-android/blob/e987ac458536e59a8329a06d5c5d5f4d4ea2c6b6/src/Mono.Android/Mono.Android.csproj#L69-L71
In xamarin/xamarin-android, we import the source for `Java.Interop.Tools.TypeNameMappings\JavaNativeTypeManager.cs`, and unfortunately there are some trimmer warnings:
external\Java.Interop\src\Java.Interop.Tools.TypeNameMappings\Java.Interop.Tools.TypeNameMappings\JavaNativeTypeManager.cs(182,9):
error IL2070: 'this' argument does not satisfy 'DynamicallyAccessedMemberTypes.Interfaces' in call to 'System.Type.GetInterfaces()'. The parameter 'type' of method 'Java.Interop.Tools.TypeNameMappings.JavaNativeTypeManager.ToJniName(Type, ExportParameterKind)' does not have matching annotations. The source value must declare at least the same requirements …

[Java.Interop.Tools.TypeNameMappings] fix trimmer warnings

---

src/Java.Interop.Tools.JavaCallableWrappers/Java.Interop.Tools.JavaCallableWrappers.csproj

xamarin/xamarin-android's build began failing with:
Xamarin.Android.Build.Tasks\Utilities\MamJsonParser.cs(92,43): error CS0122: 'NotNullWhenAttribute' is inaccessible due to its protection level [Xamarin.Android.Build.Tasks\Xamarin.Android.Build.Tasks.csproj]
Xamarin.Android.Build.Tasks\Utilities\MamJsonParser.cs(92,81): error CS0122: 'NotNullWhenAttribute' is inaccessible due to its protection level [Xamarin.Android.Build.Tasks\Xamarin.Android.Build.Tasks.csproj]
Xamarin.Android.Build.Tasks\Utilities\MavenExtensions.cs(26,32): error CS0122: 'NotNullWhenAttribute' is inaccessible due to its protection level [Xamarin.Android.Build.Tasks\Xamarin.Android.Build.Tasks.csproj]
This was happening because the `net8.0` build of
`Java.Interop.Tools.JavaCallableWrappers.dll` …

[Java.Interop.Tools.JavaCallableWrappers] fix net8.0 targeting in XA

---

src/Java.Interop.Tools.TypeNameMappings/Java.Interop.Tools.TypeNameMappings/JavaNativeTypeManager.cs
tests/Java.Interop.Tools.JavaCallableWrappers-Tests/Java.Interop.Tools.JavaCallableWrappers/JavaNativeTypeManagerTests.cs

The following test in xamarin/xamarin-android:
[Test]
public void NewObjectArrayWithNonJavaTypeAndEmptyArray ()
{
//empty array gives the right type
var array = JNIEnv.NewObjectArray<Type> (new Type [0]);
Throws with:
Java.Lang.ClassNotFoundException : crc64d04135c992393d83.Type
----> Java.Lang.ClassNotFoundException : Didn't find class "crc64d04135c992393d83.Type" on path: DexPathList[[zip file "/data/app/Mono.Android.NET_Tests-VrfrXDHT2r32zDG95kFOiw==/base.apk", zip file "/data/app/Mono.Android.NET_Tests-VrfrXDHT2r32zDG95kFOiw==/split_config.x86_64.apk", zip file "/data/app/Mono.Android.NET_Tests-VrfrXDHT2r32zDG95kFOiw==/split_config.xxhdpi.apk"],nativeLibraryDirectories=[/data/app/Mono.Android.NET_Tests-VrfrXDHT2r32zDG95kFOiw==/lib/x86_64, …

[Java.Interop.Tools.TypeNameMappings] fix `ToJniName()`

---

Java.Interop.sln
src/Java.Interop.Tools.TypeNameMappings/Java.Interop.Tools.TypeNameMappings.csproj

Context: https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=9137456&view=logs&j=96fd57f5-f69e-53c7-3d47-f67e6cf9b93e&s=1afc3bfe-122c-538b-e9ad-2a86c2efcfef&t=38f83f46-bc21-5edd-1614-e44f20babf10&l=29658
xamarin/xamarin-android now has a random build failure:
"Xamarin.Android.sln" (default target) (1:2) ->
"src/Xamarin.Android.Build.Tasks/Xamarin.Android.Build.Tasks.csproj" (default target) (28:9) ->
src/Xamarin.Android.Build.Tasks/Utilities/MamJsonParser.cs(92,43): error CS0122: 'NotNullWhenAttribute' is inaccessible due to its protection level [src/Xamarin.Android.Build.Tasks/Xamarin.Android.Build.Tasks.csproj]
src/Xamarin.Android.Build.Tasks/Utilities/MamJsonParser.cs(92,81): error CS0122: 'NotNullWhenAttribute' is inaccessible due to its protection …

[Java.Interop.Tools.TypeNameMappings] introduce project for net8.0

---

tests/generator-Tests/Unit-Tests/CodeGeneratorTests.cs
tools/generator/Java.Interop.Tools.Generator.Importers/XmlApiImporter.cs
tools/generator/Java.Interop.Tools.Generator.ObjectModel/ClassGen.cs
tools/generator/Java.Interop.Tools.Generator.ObjectModel/GenBase.cs
tools/generator/Java.Interop.Tools.Generator.ObjectModel/GenBaseSupport.cs
tools/generator/Java.Interop.Tools.Generator.ObjectModel/Method.cs
tools/generator/SourceWriters/ClassInvokerClass.cs
tools/generator/SourceWriters/InterfaceInvokerClass.cs

Context: https://github.com/xamarin/java.interop/pull/1086
https://github.com/xamarin/java.interop/pull/1086 added the metadata attribute `skipInvokerMethods` to allow us to suppress generation of invoker methods for a class.
The [AndroidX Media3 binding](https://github.com/xamarin/AndroidX/pull/779) hits an issue where we generate incorrect generics in an invoker type.  However this is an invoker type for an `interface` instead of a `class`.
Extend our `skipInvokerMethods` support to cover interfaces as well.

[generator] Extend `skipInvokerMethods` support to interfaces.

---

tests/generator-Tests/Unit-Tests/CodeGeneratorTests.cs
tools/generator/Java.Interop.Tools.Generator.Importers/XmlApiImporter.cs
tools/generator/Java.Interop.Tools.Generator.ObjectModel/ClassGen.cs
tools/generator/Java.Interop.Tools.Generator.ObjectModel/GenBase.cs
tools/generator/Java.Interop.Tools.Generator.ObjectModel/GenBaseSupport.cs
tools/generator/Java.Interop.Tools.Generator.ObjectModel/Method.cs
tools/generator/SourceWriters/ClassInvokerClass.cs
tools/generator/SourceWriters/InterfaceInvokerClass.cs

Context: 73ebad2496a0d6df251fd24e216248da70e3fea9
Context: https://github.com/xamarin/AndroidX/pull/779
Commit 73ebad24 added support for the metadata attribute `//class[@skipInvokerMethods]`, which allowed us to suppress generation of invoker methods for a class.
The AndroidX Media3 binding in xamarin/AndroidX#779 hits a similar issue wherein we generate incorrect generics on an invoker type. However, this is an invoker type for an *`interface`*, not a `class`.
Extend our `skipInvokerMethods` support so that it can be used as `//interface[@skipInvokerMethods]` as well.

[generator] Extend `skipInvokerMethods` support to interfaces. (#1202)

---

src/Java.Interop/Java.Interop/JniRuntime.JniTypeManager.cs
src/Java.Interop/Java.Interop/JniRuntime.JniValueManager.cs

Context: https://github.com/xamarin/xamarin-android/pull/8758#discussion_r1503086757
Context: https://github.com/xamarin/java.interop/issues/1192
In 7d1e7057 and b8f6f8884, we suppressed IL3050, an AOT-related warning with:
// FIXME: https://github.com/xamarin/java.interop/issues/1192
[UnconditionalSuppressMessage ("AOT", "IL3050")]
// Problematic code here
We don't immediately *plan* to support NativeAOT on Android in .NET 9, so it would be nice if we could suppress the warning *for now*. But if anyone tried to use this code in a NativeAOT context, they could get a warning.
So instead we should use:
// FIXME: https://github.com/xamarin/java.interop/issues/1192
#pragma warning disable IL3050
// Problematic code here
#pragma warning restore IL3050
This will prevent us from introducing new …

[Java.Interop] suppress IL3050 with `#pragma`

---

Directory.Build.targets
src/Java.Interop.Localization/Java.Interop.Localization.csproj
src/Java.Interop.Tools.Cecil/Java.Interop.Tools.Cecil.csproj
src/Java.Interop.Tools.Diagnostics/Java.Interop.Tools.Diagnostics.csproj
src/Java.Interop.Tools.JavaCallableWrappers/Java.Interop.Tools.JavaCallableWrappers.csproj
src/Java.Interop.Tools.Maven/Java.Interop.Tools.Maven.csproj
src/Java.Interop/Java.Interop.csproj

`netstandard2.0` doesn't have "built-in" compiler support for NRT attributes.  Thus when we enable NRT on `netstandard2.0` projects we are responsible for providing the attributes ourselves.
Rather than manually repeat this info in each `netstandard2.0` `.csproj`, we can use `Directory.Build.targets` to automatically set the attributes up in projects that need it.
Additionally, we can mark it as `Visible="false"` so the file doesn't show up in Visual Studio Solution Explorer, just like the "real" "built-in" attributes.

Automatically add NullableAttributes support to netstandard2.0 projects that enable NRT.

---

src/Java.Interop/Java.Interop/JniRuntime.JniValueManager.cs

Context: https://github.com/xamarin/xamarin-android/pull/8805
When testing new defaults for `TrimMode=full` in xamarin/xamarin-android:
dotnet new android
dotnet build -c Release -r android-arm64
Results in a single warning:
external\Java.Interop\src\Java.Interop\Java.Interop\JniRuntime.JniValueManager.cs(890,4): Trim analysis warning IL2072: Java.Interop.ProxyValueMarshaler.CreateGenericObjectReferenceArgumentState(Object, ParameterAttributes): 'type' argument does not satisfy 'DynamicallyAccessedMemberTypes.Interfaces' in call to 'Java.Interop.JniRuntime.JniValueManager.GetValueMarshaler(Type)'. The return value of method 'System.Object.GetType()' does not have matching annotations. The source value must declare at least the same requirements as those declared on the target location it …

[Java.Interop] suppress one instance of IL2072

---

build-tools/automation/azure-pipelines.yaml

I've configured a new [managed identity][0] (MSI) for API Scan, which
allows us to enable a more modern authentication approach when running
API Scan on the `MAUI-1ESPT` agent pool.
A new `$(ApiScanMAUI1ESPTManagedId)` variable has been configured in the
pipeline settings to pass the app ID for this MSI to the API Scan task.
[0]: https://ms.portal.azure.com/#@microsoft.onmicrosoft.com/resource/subscriptions/cd4829e2-e38b-43d2-8316-2f2009f36f97/resourcegroups/1esobjects/providers/microsoft.managedidentity/userassignedidentities/maui1esptapiscanidentity/overview

[ci] Use managed identity for API Scan

---

.github/workflows/locker.yml

Context: https://github.com/xamarin/xamarin-android/pull/8655
Context: https://github.com/dotnet/maui/pull/19145
Copy GitHub action script from `xamarin-android` that locks comments on closed issues/PRs after 30 days of inactivity. 
This rule is useful because comments on old, closed issues rarely will be seen or responded to, making us seem unresponsive to users.
Unfortunately there isn't a way to test a GitHub Action without it already being in `main`, so this is untested.  😦

[.github] Lock closed issues and PRs after 30 days of inactivity.

---

tools/java-source-utils/src/main/java/com/microsoft/android/JavaSourceUtilsOptions.java
tools/java-source-utils/src/main/java/com/microsoft/android/JavadocXmlGenerator.java

Fixes: https://codeql.microsoft.com/issues/5011e9f8-1b9e-4735-b9c5-89d78d9c04b2
Fixes: https://codeql.microsoft.com/issues/a9013ebf-d97c-41d8-aa62-92da7f8ea1c7
Fixes: https://codeql.microsoft.com/issues/b42d4728-2ce4-4599-b5cb-4d2affb86985
Fixes: https://codeql.microsoft.com/issues/bafce9a0-95ae-4aac-95e0-5ba8af1f3944
Fixes: https://codeql.microsoft.com/issues/bcc73986-161f-40b4-96a4-1c7e52959941
Fixes: https://codeql.microsoft.com/issues/dd199e97-a989-4f18-9fc7-a23a497eba32
Fixes: https://codeql.microsoft.com/issues/e844028d-77d8-4e04-9bfd-24005727ea84
Context: 5fa7ac458ec225cf58396d015ebb9aa6a538062d
Context: https://codeql.microsoft.com/issues/repository?Uri=https%3A%2F%2Fgithub.com%2Fxamarin%2Fjava.interop#
Context: https://eng.ms/docs/cloud-ai-platform/devdiv/one-engineering-system-1e …

[java-source-utils] Ignore CodeQL SM00697 java/path-injection-local

---

.gitmodules
Directory.Build.props
Java.Interop.sln
Makefile
build-tools/Java.Interop.BootstrapTasks/Java.Interop.BootstrapTasks.sln
tools/generator/generator.slnf

This reverts commit 25a06f659a060ebf9d1de2a222fe647733c98f8b.
There are some additional considerations to be made around
`xamarin-android-tools.override.props` that I didn't account for, we can
revisit moving the submodule path at some point in the future.

Revert "Update dotnet/android-tools submodule (#1228)"

---

build-tools/automation/azure-pipelines.yaml

The macOS-11 Big Sur image was retired June 28, 2024.

[ci] Use macOS 13 Ventura build agents

---

src/Java.Interop/Documentation/Java.Interop/JavaPeerableExtensions.xml
src/Java.Interop/Java.Interop/JavaObject.cs
src/Java.Interop/Java.Interop/JavaPeerableExtensions.cs
src/Java.Interop/Java.Interop/JniRuntime.JniValueManager.cs
src/Java.Interop/Java.Interop/ManagedPeer.cs
src/Java.Interop/PublicAPI.Unshipped.txt
tests/Java.Interop-Tests/Java.Interop-Tests.csproj
tests/Java.Interop-Tests/Java.Interop/JavaPeerableExtensionsTests.cs
tests/Java.Interop-Tests/Java.Interop/JavaVMFixture.cs
tests/Java.Interop-Tests/Java.Interop/JniPeerMembersTests.cs
tests/Java.Interop-Tests/java/net/dot/jni/test/JavaInterface.java
tests/Java.Interop-Tests/java/net/dot/jni/test/MyJavaInterfaceImpl.java

Fixes: https://github.com/dotnet/java-interop/issues/10
Fixes: https://github.com/dotnet/android/issues/9038
Context: 1adb7964a2033c83c298c070f2d1ab896d92671b
Imagine the following Java type hierarchy:
// Java
public abstract class Drawable {
public static Drawable createFromStream(IntputStream is, String srcName) {…}
// …
}
public interface Animatable {
public void start();
// …
}
/* package */ class SomeAnimatableDrawable extends Drawable implements Animatable {
// …
}
Further imagine that a call to `Drawable.createFromStream()` returns
an instance of `SomeAnimatableDrawable`.
What does the *binding* `Drawable.CreateFromStream()` return?
// C#
var drawable = Drawable.CreateFromStream(input, name);
The binding `Drawable.CreateFromStream()` look at the runtime type
of the value returned, …

[Java.Interop] Add `.JavaAs()` extension method

---

.devcontainer/devcontainer.json
README.md
build-tools/Java.Interop.BootstrapTasks/Java.Interop.BootstrapTasks.targets
tests/Java.Interop-Tests/Java.Interop/JniPeerMembersTests.cs
tests/TestJVM/TestJVM.cs

There are two issues when trying to build `Java.Interop.sln` within a [GitHub Codespace][0]:
1. `dotnet build -t:Prepare Java.Interop.sln` fails.
2. `mono` was required on Linux environments.
`dotnet build -t:Prepare` fails because `Java.Interop.sln` references `Xamarin.Android.Tools.AndroidSdk.csproj`, which does not exist immediately after checkout:
/usr/share/dotnet/sdk/8.0.303/NuGet.targets(414,5): error MSB3202:
The project file "…/java-interop/external/xamarin-android-tools/src/Xamarin.Android.Tools.AndroidSdk/Xamarin.Android.Tools.AndroidSdk.csproj"
was not found.
This apparently happens *before* the `Prepare` target executes, so the only solution is to update `README.md` and explicitly checkout submodules *before* trying to prepare:
git submodule update --init --recursive
dotnet …

[build] Improve support for building on GitHub Codespaces

---

build-tools/automation/azure-pipelines.yaml

Beginning in .NET 8 '8.0.400', we hit the following error on CI:
```
/var/folders/cy/09t6wxdj6qn64c5q9_kr6czr0000gn/T/MSBuildTemprunner/tmp58b6b197481a4eb7b080ec79e70515ad.exec.
cmd: line 2:  7199 Bus error: 10           "/Users/runner/hostedtoolcache/dotnet/dotnet" 
"/Users/runner/work/1/s/bin/Release-net8.0//jnimarshalmethod-gen.dll" "/Users/runner/work/1/s/samples/Hello-
NativeAOTFromJNI/bin/Release/Hello-NativeAOTFromJNI.dll" -v -v --keeptemp -L "/Users/runner/work/1/s/samples/Hello-
NativeAOTFromJNI/bin/Release/"
##[error]samples/Hello-NativeAOTFromJNI/Hello-NativeAOTFromJNI.targets(44,5): Error MSB3073: The command 
""/Users/runner/hostedtoolcache/dotnet/dotnet" "/Users/runner/work/1/s/bin/Release-net8.0//jnimarshalmethod-gen.dll" …
```

Pin .NET 8 to '8.0.303'.

---

src/Java.Interop.GenericMarshaler/Java.Interop.GenericMarshaler/JniPeerInstanceMethodsExtensions.cs
src/Java.Interop.GenericMarshaler/Java.Interop.GenericMarshaler/JniPeerInstanceMethodsExtensions.tt
src/Java.Interop/Java.Interop/JniPeerMembers.JniInstanceMethods.cs
src/Java.Interop/Java.Interop/JniRuntime.cs

Context: 972c5bc605bd87526f3ddd7735d21f47d9f2d4aa
Context: https://github.com/dotnet/android/pull/9146
As our minimum Android API level is now API-21 (Android 5.0), and .NET for Android only sets
`Java.Interop.JniRuntime.CreationOptions.NewObjectRequired`=true on API-10 and lower, we can remove the support for this option. This has the added benefit of removing the TLS lookup that `JniEnvironment.Runtime` requires, and thus *should* improve perf.
Add `[Obsolete]` to `JniRuntime.CreationOptions.NewObjectRequired`.

[Java.Interop] Remove support for NewObjectRequired

---

src/Java.Interop/Java.Interop/JavaPrimitiveArrays.cs
src/Java.Interop/Java.Interop/JniBuiltinMarshalers.cs
src/Java.Interop/Java.Interop/JniRuntime.JniMarshalMemberBuilder.cs
src/Java.Interop/Java.Interop/JniRuntime.JniValueManager.cs
src/Java.Interop/Java.Interop/JniStringValueMarshaler.cs
src/Java.Interop/Java.Interop/JniValueMarshaler.cs

Context: https://github.com/dotnet/android/pull/9311
Usage of `System.Linq.Expressions` in latest .NET 9 builds can trigger AOT warnings like:
src/Mono.Android/Android.Runtime/IJavaObjectValueMarshaler.cs(40,11): error IL3050:
Using member 'System.Linq.Expressions.Expression.Call(Type, String, Type[], params Expression[])' which has 'RequiresDynamicCodeAttribute' can break functionality when AOT compiling. Calling a generic method requires dynamic code generation. This can be suppressed if the method is not generic.
src/Mono.Android/Android.Runtime/IJavaObjectValueMarshaler.cs(54,7): error IL3050:
Using member 'System.Linq.Expressions.Expression.Call(Type, String, Type[], params Expression[])' which has 'RequiresDynamicCodeAttribute' can break functionality when AOT compiling. Calling a …

[Java.Interop] Add `[RequiresDynamicCode]` attribute

---

tests/generator-Tests/Unit-Tests/CodeGeneratorTests.cs
tools/generator/Java.Interop.Tools.Generator.Importers/XmlApiImporter.cs
tools/generator/Java.Interop.Tools.Generator.ObjectModel/ClassGen.cs
tools/generator/SourceWriters/BoundClass.cs

Context: https://github.com/dotnet/java-interop/issues/1264
The scenario described in https://github.com/dotnet/java-interop/issues/1264 seems very complex to fix, as we would have to determine if each interface method has a compatible DIM on any other interface in scope.
As a workaround, we can mimic [`skipInvokerMethods`](https://github.com/dotnet/java-interop/pull/1086) with a new `skipInterfaceMethods` metadata that allows us to suppress generation of an `abstract` method in an `abstract class` that implements the interface.
The example in https://github.com/dotnet/java-interop/issues/1264 would be fixed with:
```xml
<attr
path="/api/package[@name='kotlin.collections']/class[@name='AbstractList']"
name="skipInterfaceMethods"> …
```

[generator] Add support for `skipInterfaceMethods`.

---

tests/generator-Tests/Unit-Tests/ManagedTests.cs
tools/generator/Java.Interop.Tools.Generator.Importers/CecilApiImporter.cs

Context: https://github.com/dotnet/java-interop/pull/1266
While the issue described in https://github.com/dotnet/java-interop/pull/1266 is definitely an issue (types should not be added to the `generator` symbol table with a JNI type specification), that example was merely setting up the scenario needed to expose another bug.
When a JLO type has a `public` or `internal` field whose type is a nested type:
```csharp
namespace Com.Mypackage;
[Register ("com/mypackage/FieldClass")]
public class FieldClass : Java.Lang.Object
{
public NestedFieldClass field;
public class NestedFieldClass : Java.Lang.Object { }
}
```
We correctly import the `Field.TypeName` as `Com.Mypackage.FieldClass.NestedFieldClass`, however we also create `Field.SetterParameter` with the same type, but we do not replace the …

[generator] Fix exception caused by incorrect nested type name.

---

src/Java.Interop.Tools.JavaTypeSystem/Adapters/ApiImporterOptions.cs
src/Java.Interop.Tools.JavaTypeSystem/Adapters/ManagedApiImporter.cs
src/Java.Interop.Tools.JavaTypeSystem/Java.Interop.Tools.JavaTypeSystem.csproj
tests/generator-Tests/Unit-Tests/ManagedTests.cs
tools/generator/CodeGenerator.cs
tools/generator/Java.Interop.Tools.Generator.Importers/CecilApiImporter.cs
tools/generator/Java.Interop.Tools.Generator.Transformation/JavaTypeResolutionFixups.cs

Registering types that are annotated with `[JniTypeSignatureAttribute]` to add to the `generator` type symbol table causes issues, as the `Java*Array` types from `Java.Interop` get added:
```csharp
[JniTypeSignature ("B", ArrayRank = 1, IsKeyword = true, GenerateJavaPeer = false)]
public class JavaSByteArray { ... }
```
This type is added to the type symbol table with a key of `B` for the JNI `Byte` type, but the symbol table doesn't deal in JNI types, thus this type will get chosen when a method parameter or return type has a generic type named `"B"` (or a global package type `"B"`).
When binding AndroidX with .NET 9, this causes the error:
```
System.NotSupportedException: Unable to generate setter parameter list in method SetId in managed type Java.Interop.JavaSByteArray
```
[Java …

[generator] Only use `[JniTypeSignatureAttribute]` for `JavaInterop1`.

---

src/Java.Interop/Java.Interop/JavaException.cs
src/Java.Interop/Java.Interop/JavaObject.cs
src/Java.Interop/Java.Interop/JavaPrimitiveArrays.cs
src/Java.Interop/Java.Interop/JavaPrimitiveArrays.tt
src/Java.Interop/Java.Interop/JniEnvironment.cs
src/Java.Interop/Java.Interop/JniPeerMembers.cs

Context: https://github.com/dotnet/android/issues/9039
Context: https://github.com/dotnet/android/commit/32495f36905d0e5f203c0ed581824038286c58e2
@jonpryor suspects that the `ObjectDisposedException` being thrown within dotnet/android#9039 *may* be due to a GC-related bug.
A problem with diagnosing this is tracking object lifetimes: yes, an `Android.Runtime.InputStreamInvoker` is throwing
`ObjectDisposedException`, but in local reproductions, there are *multiple* `InputStreamInvoker` instances created!  Which one is throwing?
A local answer to that was "Update `InputStreamInvoker.Read()` to log `BaseInputStream.JniIdentityHashCode`", which *was* useful, but is not a "scalable" solution.
Review all `throw new ObjectDisposedException()` calls within `Java.Interop.dll`, and update all sites …

[Java.Interop] Add JniIdentityHashCode to ObjectDisposedException

---

build-tools/Java.Interop.BootstrapTasks/Java.Interop.BootstrapTasks.csproj
build-tools/Java.Interop.BootstrapTasks/Java.Interop.BootstrapTasks/JdkInfo.cs

@jonpryor's developer machines are a "weird", with a macOS arm64 box containing the directories:
* `$HOME/android-toolchain/jdk-17`
* `$HOME/android-toolchain/jdk-17.x64`
Meanwhile, `XAPrepareJdkLocations.GetXAPrepareJdks()` within dotnet/android-tools looks for all directories matching the glob `$HOME/android-toolchains/jdk*`, and thus finds both.
For some reason, the JDK that `dotnet build -t:Prepare *.sln` winds up using by default is the the `jdk-17.x64` directory (😱), which cannot be loaded into an arm64 process.  This results in errors from `dotnet build`:
EXEC : error JM4003: jnimarshalmethod-gen: Unable to create Java VM […/dotnet/java-interop/samples/Hello-NativeAOTFromJNI/Hello-NativeAOTFromJNI.csproj]
System.DllNotFoundException: Unable to load shared library …

[Java.Interop.BootstrapTasks] Filter out invalid JDKs

---

tests/generator-Tests/expected.xaji/AccessModifiers/__NamespaceMapping__.cs
tests/generator-Tests/expected.xaji/Adapters/__NamespaceMapping__.cs
tests/generator-Tests/expected.xaji/Android.Graphics.Color/__NamespaceMapping__.cs
tests/generator-Tests/expected.xaji/CSharpKeywords/__NamespaceMapping__.cs
tests/generator-Tests/expected.xaji/Core_Jar2Xml/__NamespaceMapping__.cs
tests/generator-Tests/expected.xaji/GenericArguments/__NamespaceMapping__.cs
tests/generator-Tests/expected.xaji/InterfaceMethodsConflict/__NamespaceMapping__.cs
tests/generator-Tests/expected.xaji/NestedTypes/__NamespaceMapping__.cs
tests/generator-Tests/expected.xaji/NormalMethods/__NamespaceMapping__.cs
tests/generator-Tests/expected.xaji/NormalProperties/__NamespaceMapping__.cs
tests/generator-Tests/expected.xaji/ParameterXPath/__NamespaceMapping__.cs
tests/generator-Tests/expected.xaji/Streams/__NamespaceMapping__.cs
tests/generator-Tests/expected.xaji/TestInterface/__NamespaceMapping__.cs
tests/generator-Tests/expected.xaji/java.lang.Enum/__NamespaceMapping__.cs
tools/generator/Java.Interop.Tools.Generator.ObjectModel/NamespaceMapping.cs

Fixes: https://github.com/dotnet/java-interop/issues/1262
Context: 2197579478152fbc815eb15195977f808cd6bde4
> NativeAOT doesn't like this by default.  In order to convince
> NativeAOT to support this, every delegate instance provided to
> `JniNativeMethodRegistration.Delegate` must be of a delegate type
> which has [`UnmanagedFunctionPointerAttribute`][6].  This coerces
> NativeAOT to emit "stubs" for the referenced method, allowing things
> to work with fewer changes.
>
> [6]: https://learn.microsoft.com/dotnet/api/system.runtime.interopservices.unmanagedfunctionpointerattribute?view=net-8.0
For possible future NativeAOT support, every `_JniMarshal_*` delegate emitted by `generator` needs to have `[UnmanagedFunctionPointer]`, a'la:
```csharp
[UnmanagedFunctionPointer …
```

[generator] Add `[UnmanagedFunctionPointer]` to marshal delegate declarations.

---

build-tools/trim-analyzers/trim-analyzers.props
src/Java.Interop.Tools.TypeNameMappings/Java.Interop.Tools.TypeNameMappings.csproj
src/Java.Interop/Java.Interop.csproj
src/Java.Interop/Java.Interop/JavaArray.cs
src/Java.Interop/Java.Interop/JavaObject.cs
src/Java.Interop/Java.Interop/JavaObjectArray.cs
src/Java.Interop/Java.Interop/JavaPrimitiveArrays.cs
src/Java.Interop/Java.Interop/JniBuiltinMarshalers.cs
src/Java.Interop/Java.Interop/JniRuntime.JniMarshalMemberBuilder.cs
src/Java.Interop/Java.Interop/JniRuntime.JniTypeManager.cs
src/Java.Interop/Java.Interop/JniRuntime.JniValueManager.cs
src/Java.Interop/Java.Interop/JniStringValueMarshaler.cs
src/Java.Interop/Java.Interop/JniValueMarshaler.cs
src/Java.Interop/Java.Interop/JniValueMarshalerAttribute.cs

Context: https://github.com/dotnet/android/pull/9630
As #9630 required new declarations of
`DynamicallyAccessedMemberTypes.Interfaces`, we intestigated to see *why* these were needed in Java.Interop.
There are two cases:
var listIface   = typeof (IList<>);
var listType    =
(from iface in type.GetInterfaces ().Concat (new[]{type})
where (listIface).IsAssignableFrom (iface.IsGenericType ? iface.GetGenericTypeDefinition () : iface)
select iface)
.FirstOrDefault ();
This first one, if `IList<>` were trimmed away. We don't actually care, as everything in this code path would still work. We can suppress the warning instead.
The second case:
JniValueMarshalerAttribute? ifaceAttribute = null;
foreach (var iface in type.GetInterfaces ()) {
marshalerAttr = …

[Java.Interop] remove `DynamicallyAccessedMemberTypes.Interfaces`

---

src/Java.Interop.Tools.JavaSource/Java.Interop.Tools.JavaSource/SourceJavadocToXmldocGrammar.HtmlBnfTerms.cs
tests/Java.Interop.Tools.JavaSource-Tests/SourceJavadocToXmldocGrammar.HtmlBnfTermsTests.cs

A recent attempt to import API docs for API 35 produced the following:
The following issues were found, review the build log for more details:
>   ## Unable to translate remarks for android/app/admin/DevicePolicyManager:
>   JavadocImport-Error (31:39): Syntax error, expected: </p>, </P>, #PCDATA, <tt>, <TT>, <i>, <I>, <a attr=, <code>, {@code, {@docRoot}, {@inheritDoc}, {@link, {@linkplain, {@literal, {@see, {@value}, {@value, IgnorableDeclaration, {@param, UnknownHtmlElementStart, <p>, <P>, <pre , @author, @apiSince, @deprecated, @deprecatedSince, @exception, @inheritDoc, @hide, @param, @return, @see, @serialData, @serialField, @since, @throws, @[unknown], @version
<li>A <i id="deviceowner">Device Owner</i>, which only ever exists on the
^
Parsing logic fails here because the `<i>` tag …

[Tools.JavaSource] Support html tags with attributes

---

build-tools/gradle/gradle/wrapper/gradle-wrapper.properties
src/Java.Base/Java.Lang/StringBuffer.cs
src/Java.Base/Java.Lang/StringBuilder.cs
src/Java.Base/Java.Lang/Thread.cs
src/Xamarin.Android.Tools.Bytecode/Methods.cs

Context: 5bb0d24b97c54648ba13fa8ad3abf9c2405baa79
Context: 4273e5cee65c0e8a951702d47cd9f0d96f32a14a
Context: 0355acf8c16eedb78545cdd0d58f623b5486ed73
Context: https://github.com/dotnet/android/pull/9651
Does dotnet/android build with JDK-21?  We don't know!  But in order to answer that question, dotnet/java-interop needs to be able to build under JDK-21; a'la 5bb0d24b:
1. [Install JDK-21][0]
2. Run `dotnet build -t:Prepare`, overriding `$(JdksRoot)`:
dotnet build -t:Prepare Java.Interop.sln -p:JdksRoot=/Library/Java/JavaVirtualMachines/microsoft-21.jdk/Contents/Home
3. Build: `dotnet build`
Unfortunately, this *fails* for three reasons:
1. `class-parse` crashes when processing `java.base.jmod`.
2. `src/Java.Base` needs updates to bind JDK-21's `java.base.jmod`.
3. On Linux and Windows, …

[build] Add support for JDK 21

---

tools/java-source-utils/.classpath
tools/java-source-utils/.project

Every time VSCode opens tools/java-source-utils, it changes the .classpath and .project files.
Flush these changes so that `git status` stops reporting them.
@jonpryor has no idea what they're for.

[java-source-utils] Flush VSCode changes

---

Directory.Build.props
build-tools/scripts/Prepare.targets
tests/Xamarin.Android.Tools.Bytecode-Tests/JavaEnumTests.cs
tests/Xamarin.Android.Tools.Bytecode-Tests/JavaTypeTests.cs
tests/Xamarin.Android.Tools.Bytecode-Tests/ModuleInfoTests.cs
tools/java-source-utils/src/test/java/com/microsoft/android/JavaSourceUtilsOptionsTest.java
tools/java-source-utils/src/test/java/com/microsoft/android/JavadocXmlGeneratorTest.java
tools/java-source-utils/src/test/resources/UnresolvedTypes.xml
tools/java-source-utils/src/test/resources/com/microsoft/android/DemoInfo.xml
tools/java-source-utils/src/test/resources/com/microsoft/android/JavaType.xml
tools/java-source-utils/src/test/resources/com/microsoft/android/Outer.xml

Context: https://github.com/dotnet/android/commit/df68c208ad02d09ebb9e6a87053343985dfc1e36
dotnet/android requires JDK-17, as of dotnet/android@df68c208.
Update the dotnet/java-interop build to prefer JDK-17, for consistency.
Additionally, *replace* use of `javac -source X -target X` with `javac --release X`, as this removes a build warning:
EXEC : warning : [options] system modules path not set in conjunction with -source 11

[build] Prefer JDK-17

---

build-tools/automation/azure-pipelines.yaml
build-tools/automation/templates/fail-on-dirty-tree.yaml
src/Java.Base/Java.Base.targets

Context: https://github.com/dotnet/android/pull/9661
Scenarios where the build unintentionally modifies git tracked files on some platforms are frustrating, so let's prevent them from happening in the first place.
Add a CI check to fail a build if any git tracked files were modified.
Also contains a fix for `<GenAPITask/>` task always generates files with Windows line endings, which causes `git status` to show the file as modified on other platforms.

[ci] Fail build if any git tracked files were modified.

---

src/Java.Interop/Java.Interop/JavaException.cs
src/Java.Interop/Java.Interop/JavaObject.cs
src/Java.Interop/Java.Interop/JniRuntime.JniValueManager.cs
src/Java.Interop/PublicAPI.Unshipped.txt

Context: https://github.com/dotnet/android/pull/9640
Context: 25de1f38bb6b3ef2d4c98d2d95923a4bd50d2ea0
dotnet/android#9640 completes "unification" with dotnet/java-interop, updating `Java.Lang.Object` to inherit `Java.Interop.JavaObject`, just like `src/Java.Base`.
The biggest impediment with this unification step is that the semantics for referring to a Java instance are quite different:
* .NET for Android née Xamarin.Android née Mono for Android uses an `(IntPtr, JniHandleOwnership)` pair to specify the JNI object reference pointer value and what should be done with it. The *type* of the JNI object reference is *inferred* by the `JniHandleOwnership` value, e.g. `JniHandleOwnership.TransferLocalRef` means that the `IntPtr` value is a JNI local reference.
* dotnet/java-interop uses a …

[Java.Interop] JavaException supports param override

---

build-tools/automation/azure-pipelines.yaml

Adds dev branches to the CI trigger to kick off builds on these branches
automatically now that PR build restrictions are in place for GitHub
repos.

[ci] Add dev/* branches to CI trigger

---

src/Java.Interop/Java.Interop/JniRuntime.JniValueManager.cs
src/Java.Interop/PublicAPI.Unshipped.txt
tests/Java.Interop-Tests/Java.Interop-Tests.csproj
tests/Java.Interop-Tests/Java.Interop/JniRuntimeJniValueManagerContract.cs
tests/TestJVM/TestJVM.csproj

Context: https://github.com/dotnet/android/pull/9630/files#r1891090085
Context: https://github.com/dotnet/android/pull/9716
As part of NativeAOT prototyping within dotnet/android, we need to update `Java.Lang.Object.GetObject<T>()` so that it uses `Java.Interop.JniRuntime.JniValueManager` APIs instead of its own `TypeManager.CreateInstance()` invocation, as
`TypeManager.CreateInstance()` hits P/Invokes which don't currently work in the NativeAOT sample environment.
However, updated it to *what*?  The obvious thing to do would be to use `JniRuntime.JniValueManager.GetValue()`:
partial class Object {
internal static IJavaPeerable? GetObject (IntPtr handle, JniHandleOwnershipt ransfer, Type? type = null)
{
var r = PeekObject (handle, type);
if (r != null) {
JNIEnv.DeleteRef (handle, …

[Java.Interop] Add JniRuntime.JniValueManager.GetPeer()

---

src/Java.Interop.Tools.JavaCallableWrappers/Java.Interop.Tools.JavaCallableWrappers.Adapters/CecilImporter.cs
src/Java.Interop.Tools.TypeNameMappings/Java.Interop.Tools.TypeNameMappings/JavaNativeTypeManager.cs
tests/Java.Interop.Export-Tests/Java.Interop.Export-Tests.csproj
tests/Java.Interop.Tools.JavaCallableWrappers-Tests/Java.Interop.Tools.JavaCallableWrappers/JavaCallableWrapperGeneratorTests.cs
tests/Java.Interop.Tools.JavaCallableWrappers-Tests/Java.Interop.Tools.JavaCallableWrappers/SupportDeclarations.cs
tests/Java.Interop.Tools.JavaCallableWrappers-Tests/Java.Interop.Tools.JavaCallableWrappers/TypeNameMapGeneratorTests.cs
tools/generator/Java.Interop.Tools.Generator.ObjectModel/ClassGen.cs

TODO: full explanation.
dotnet/java-interop#1302 and dotnet/android#9750 has turned into a bit of a boondoggle.  Maybe the better approach is to just update `jcw-gen` to use `+` instead of `/` for nested types, instead of *both* `jcw-gen` *and* `generator`, because the `generator` changes just require changes *everywhere*.
Will this smaller fix work?

[jcw-gen] Use `+` for nested types, not `/`

---

tests/Java.Interop.Dynamic-Tests/Java.Interop.Dynamic-Tests.csproj

Context: https://github.com/NuGet/NuGet.Client/pull/6239
.NET 10 Preview 1 enables `$(RestoreEnablePackagePruning)=true` by default.
This produces multiple warnings as errors in dotnet/android:
external\Java.Interop\tests\Java.Interop.Dynamic-Tests\Java.Interop.Dynamic-Tests.csproj :
error NU1510: Warning As Error: PackageReference Microsoft.CSharp will not be pruned. Consider removing this package from your dependencies, as it is likely unnecessary.
The `Microsoft.CSharp` package does seem like it can just be removed.

[tests] fix `NU1510` warning as error

---

src/Java.Interop/Java.Interop/JavaArray.cs
src/Java.Interop/Java.Interop/JavaObjectArray.cs
src/Java.Interop/Java.Interop/JniRuntime.JniTypeManager.cs
tests/Java.Interop-Tests/Java.Interop/JniTypeManagerTests.cs

Context: https://github.com/dotnet/android/pull/9768
dotnet/android#9768 attempts to add types from `Java.Interop.dll` to the .NET for Android typemaps, in order to fix Debug warnings like:
I monodroid-assembly: typemap: unable to find mapping to a Java type from managed type 'Java.Interop.ManagedPeer, Java.Interop'
Unfortunately, this causes the assertion:
AssertGetJniTypeInfoForType (typeof (JavaArray<JavaObject>),    "[Ljava/lang/Object;",  false,  1);
within `Java.InteropTests.JniTypeManagerTests.GetTypeSignature_Type()` to fail:
Expected string length 19 but was 33. Strings differ at index 0.
Expected: "[Ljava/lang/Object;"
But was:  "crc64d5d92128469ae06d/JavaArray_1"
-----------^
The immediate cause of the failure is that
`JniRuntime.JniTypeManager.GetTypeSignature()` called …

[Java.Interop] GetSimpleReferences():fallback for GetTypeSignatures()

---

src/Java.Interop/Java.Interop/JniRuntime.JniValueManager.cs
tests/Java.Interop-Tests/Java.Interop-Tests.csproj
tests/Java.Interop-Tests/Java.Interop/JavaVMFixture.cs
tests/Java.Interop-Tests/Java.Interop/JniRuntimeJniValueManagerContract.cs
tests/Java.Interop-Tests/java/net/dot/jni/test/AnotherJavaInterfaceImpl.java

Context: https://github.com/dotnet/android/pull/9747
Context: https://discord.com/channels/732297728826277939/732297837953679412/1339638847864176640
Context: https://discord.com/channels/732297728826277939/732297837953679412/1340011105510101063
While trying to get a MAUI sample running atop NativeAOT, we're observing the following crash:
E AndroidRuntime: net.dot.jni.internal.JavaProxyThrowable: System.InvalidCastException: Arg_InvalidCastException
E AndroidRuntime:    at Java.Lang.Object._GetObject[T](IntPtr, JniHandleOwnership) + 0x64
E AndroidRuntime:    at Microsoft.Maui.WindowOverlay.Initialize() + 0x168
Further investigation shows that the crash is from accessing the `Activity.WindowManager` property:
namespace Android.App;
partial class Activity {
public virtual unsafe …

[Java.Interop] CreatePeer() must satisfy targetType

---

tests/generator-Tests/Unit-Tests/CodeGeneratorTests.cs
tests/generator-Tests/Unit-Tests/XmlApiImporterTests.cs
tools/generator/ApiVersionsSupport.cs
tools/generator/Java.Interop.Tools.Generator.Importers/XmlApiImporter.cs
tools/generator/Java.Interop.Tools.Generator.ObjectModel/Field.cs
tools/generator/Java.Interop.Tools.Generator.ObjectModel/GenBase.cs
tools/generator/Java.Interop.Tools.Generator.ObjectModel/MethodBase.cs
tools/generator/SourceWriters/Attributes/UnsupportedOSPlatformAttr.cs
tools/generator/SourceWriters/Extensions/SourceWriterExtensions.cs

Fixes: https://github.com/dotnet/java-interop/issues/1309
Sometimes, Android *removes* APIs.  For example, API-23 *removed* the `android.Manifest.permission.CLEAR_APP_USER_DATA` field.
We still list this field, though: [`Android.Manifest.Permission.ClearAppUserData` field](https://learn.microsoft.com/en-us/dotnet/api/android.manifest.permission.clearappuserdata?view=net-android-34.0)
We modified `api-merge` to add `removed-since` in https://github.com/dotnet/android/pull/8897.
Here is the excerpt from https://github.com/dotnet/android/blob/main/src/Mono.Android/Profiles/api-Baklava.xml:
```xml
<field deprecated="not deprecated" final="true" name="CLEAR_APP_USER_DATA" jni-signature="Ljava/lang/String;" static="true" transient="false" type="java.lang.String" …
```

[generator] Add support for emitting `[UnsupportedOSPlatform]`.

---

src/Java.Interop/Java.Interop/JniBuiltinMarshalers.cs
src/Java.Interop/Java.Interop/JniBuiltinMarshalers.tt
src/Java.Interop/Java.Interop/JniRuntime.JniTypeManager.cs
tests/Java.Interop-Tests/Java.Interop/JniTypeManagerTests.cs

Context: https://github.com/dotnet/android/pull/9747
Context: https://github.com/dotnet/android/pull/9812
In the ongoing epic to get MAUI running atop NativeAOT, we hit our longstanding NativeAOT nemesis: P/Invoke:
E AndroidRuntime: net.dot.jni.internal.JavaProxyThrowable: System.InvalidProgramException: InvalidProgram_Specific, IntPtr Android.Runtime.JNIEnv.monodroid_typemap_managed_to_java(System.Type, Byte*)
E AndroidRuntime:    at Internal.Runtime.TypeLoaderExceptionHelper.CreateInvalidProgramException(ExceptionStringID, String) + 0x4c
E AndroidRuntime:    at Android.Runtime.JNIEnv.monodroid_typemap_managed_to_java(Type, Byte*) + 0x18
E AndroidRuntime:    at Android.Runtime.JNIEnv.TypemapManagedToJava(Type) + 0x104
E AndroidRuntime:    at Android.Runtime.JNIEnv.GetJniName(Type) + 0x1c …

[Java.Interop] Support System.Byte, somewhat

---

src/Java.Interop.GenericMarshaler/Java.Interop.GenericMarshaler.csproj
src/Java.Interop.GenericMarshaler/Java.Interop.GenericMarshaler/JniPeerInstanceMethodsExtensions.cs
src/Java.Interop.GenericMarshaler/Java.Interop.GenericMarshaler/JniPeerInstanceMethodsExtensions.tt

Context: https://github.com/dotnet/android/pull/9846
When trying to build `Mono.Android-Tests` for NativeAOT, I get many warnings like this (that are upgraded to errors):
src\Java.Interop.GenericMarshaler\Java.Interop.GenericMarshaler\JniPeerInstanceMethodsExtensions.cs(10874,17):
error IL2091: 'T' generic argument does not satisfy 'DynamicallyAccessedMemberTypes.PublicConstructors', 'DynamicallyAccessedMemberTypes.NonPublicConstructors' in 'Java.Interop.JniRuntime.JniValueManager.GetValueMarshaler<T>()'. The generic parameter 'T16' of 'Java.Interop.GenericMarshaler.JniPeerInstanceMethodsExtensions.InvokeGenericVirtualObjectMethod<T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16>(JniInstanceMethods, String, IJavaPeerable, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, …

[Java.Interop.GenericMarshaler] fix trimmer warnings

---

build-tools/Java.Interop.Sdk/Sdk/Sdk.targets
samples/Hello-Java.Base/Hello-Java.Base.csproj
samples/Hello-Java.Base/Program.cs
src/Java.Runtime.Environment/Java.Interop/JreRuntime.cs
src/Java.Runtime.Environment/Java.Interop/JreTypeManager.cs
tests/TestJVM/TestJVM.cs

Update Hello-Java.Base to use Java.Interop.Sdk, so that it (kinda, sorta) "automagically" gets support for generating Java Callable Wrappers as part of its build.
Add a custom `Java.Lang.Object` subclass and use it.
…which in turn requires creating a new `JreTypeManager` subclass to provide the typemap information, because "Java.Interop.Sdk" is not fleshed out enough to provide that information itself.

[Hello-Java.Base] Add support for Java Callable Wrappers

---

tests/Java.Interop-Tests/Java.Interop-Tests.csproj
tests/Java.Interop-Tests/Java.Interop/JavaExceptionTests.cs
tests/Java.Interop-Tests/Java.Interop/JavaObjectArrayTest.cs
tests/Java.Interop-Tests/Java.Interop/JniEnvironmentTests.cs
tests/Java.Interop-Tests/Java.Interop/JniRuntimeJniValueManagerContract.cs
tests/Java.Interop-Tests/Java.Interop/JniValueMarshalerContractTests.cs

Context: https://github.com/dotnet/android/pull/9846
When building `Mono.Android.NET-Tests.csproj` for NativeAOT, you end up with many warnings (that are upgraded to errors):
external/Java.Interop/tests/Java.Interop-Tests/Java.Interop/JniEnvironmentTests.cs(92,4): error IL2026: Using member 'System.Reflection.Assembly.GetType(String, Boolean)' which has 'RequiresUnreferencedCodeAttribute' can break functionality when trimming application code. Types might be removed by trimming. If the type name is a string literal, consider using Type.GetType instead.
external/Java.Interop/tests/Java.Interop-Tests/Java.Interop/JniEnvironmentTests.cs(93,4): error IL2026: Using member 'System.Reflection.Assembly.GetType(String, Boolean)' which has 'RequiresUnreferencedCodeAttribute' can break functionality …

[tests] fix trimmer warnings in Java.Interop-Tests

---

samples/Hello-Java.Base/Program.cs

Context: a5b229daa3538ea9ad06d22541e7bfa0ae747d9d
Now that MonoVM can be used on the desktop (a5b229da), let's show it in action!
Update `samples/Hello-Java.Base` to call `GC.Collect()` and `GC.WaitForPendingFinalizers()` to help cause the `MyJLO` instance to be collected before app exit.
Which is fine, but what we also need are *GREF logs*.  Unfortunately, we can't use `JreRuntimeOptions.JniGlobalReferenceWriter` for that purpose, because `libjava-interop.dylib` is native code and we want both managed and native code to write GREF logs to the same place.
Instead, set the `JAVA_INTEROP_GREF_LOG` environment variable to a file path:
% JAVA_INTEROP_GREF_LOG=g.txt  ./samples/Hello-Java.Base/bin/Release/osx-x64/publish/Hello-Java.Base
MonoVM support enabled
WARNING in native method: JNI call …

[Hello-Java.Base] MonoVM + peer collection

---

Directory.Build.targets
build-tools/Java.Interop.BootstrapTasks/Java.Interop.BootstrapTasks.csproj
src/Java.Interop.Localization/Java.Interop.Localization.csproj
src/Java.Interop.Tools.Cecil/Java.Interop.Tools.Cecil.csproj
src/Java.Interop.Tools.Diagnostics/Java.Interop.Tools.Diagnostics.csproj
src/Java.Interop.Tools.JavaCallableWrappers/Java.Interop.Tools.JavaCallableWrappers.csproj
src/Java.Interop.Tools.JavaSource/Java.Interop.Tools.JavaSource.csproj
src/Java.Interop.Tools.Maven/Java.Interop.Tools.Maven.csproj
src/Java.Interop/Java.Interop.csproj

The default `<LangVersion>` for `netstandard2.0` projects is `7.3`, which does not contain many of the niceties we would like to use.  Throughout our history we have updated individual projects to use the latest language features, but this has led to inconsistencies.
Instead, standardize this in `Directory.Build.targets` to use a common C# language version for `netstandard2.0` projects.
Note we standardized on `13.0` (the one that ships with .NET 9) instead of `latest`, as `latest` is discouraged because it can change based on what versions are installed on a machine.

Centralize `<LangVersion>` for `netstandard2.0` projects.

---

src/Java.Interop.Tools.JavaCallableWrappers/Extensions/XmlExtensions.cs
src/Java.Interop.Tools.JavaCallableWrappers/Java.Interop.Tools.JavaCallableWrappers.Adapters/XmlExporter.cs
src/Java.Interop.Tools.JavaCallableWrappers/Java.Interop.Tools.JavaCallableWrappers.Adapters/XmlImporter.cs

Context: https://github.com/dotnet/android/pull/9893
Create XML import/export adapters for `JavaCallableWrappers`.  This allows us to serialize the JCWs we find in the `FindJavaObjectsStep` linker step to disk that is later used in `_GenerateJavaStubs`.  This file also allows us to cache the assembly scanning to disk so we don't need to rerun it on incremental builds.
This format is likely a "work in progress".  As we move other JLO related scanning to linker steps we will likely find additional data they require that needs to go into this file, or that this format isn't even suitable and we use something else instead.

[JavaCallableWrappers] Add XML import/export.

---

src/Java.Interop/Java.Interop/JniEnvironment.Types.cs
src/Java.Interop/Java.Interop/JniRuntime.cs

Fixes: https://github.com/dotnet/java-interop/issues/23
Context: https://github.com/dotnet/android/commit/aba272691f96fa179e7ea29196760d0dcb82cf16
Context: b4d44e4b3590a6a5a5e9bf4a0044eb2acf17bef6
Context: https://github.com/xamarin/monodroid/commit/ed984a3a0bfbe71f6499a7855c647b5bc2b28466
Context: https://github.com/dotnet/android/issues/7616
Commit b4d44e4b noted:
> Android is..."special", in that not all threads get the same
> ClassLoader behavior. Specifically, *managed* threads --
> System.Threading.Thread instances -- get a different ClassLoader than
> the main/UI thread on Android. (Untested, but the ClassLoader *may*
> behave sanely if you use a java.lang.Thread instance instead. But who
> wants to use java.lang.Thread instances...?)
dotnet/android#7616 provided additional …

[Java.Interop] Use `Class.forName()` as fallback to load Java classes

---

src/Java.Interop/Java.Interop/JniRuntime.JniValueManager.cs
tests/Java.Base-Tests/Java.Base/JavaVMFixture.cs
tests/Java.Base-Tests/Java.Base/JniRuntimeJniValueManagerContractExtras.cs
tests/Java.Interop-Tests/Java.Interop/JniTypeManagerTests.cs
tests/Java.Interop.Export-Tests/Java.Interop/ExportTest.cs
tests/Java.Interop.Export-Tests/Java.Interop/MarshalMemberBuilderTest.cs
tests/Java.Interop.Export-Tests/java/net/dot/jni/test/ExportType.java

The `JniValueManager.CreatePeerInstance` method did not work correctly when the input was an object of type `java/lang/Float`. In this case, the `Runtime.TypeManager.GetType (sig)` call returned `System.Single?`, which is not assignable from the target type (`Java.Lang.Object`).
The problem was that `GetType (sig)` was implemented in such a way that it would return the first value of `GetTypes (sig)`. For built-in types, such as floats, we have a dictionary with mapping to their .NET counterparts in `JniRuntime.JniBuiltinSimpleReferenceToType`. This caused that `GetType (sig)` returned `float?`, while `GetTypes (sig)` returns also `Java.Lang.Float`. Only the latter is suitable for `CreatePeerInstance`.

[Java.Interop] Skip irrelevant types returned from TypeManager.GetTypes (sig)

---

src/Java.Interop.Tools.JavaCallableWrappers/Java.Interop.Tools.JavaCallableWrappers.Adapters/XmlExporter.cs
src/Java.Interop.Tools.JavaCallableWrappers/Java.Interop.Tools.JavaCallableWrappers.Adapters/XmlImporter.cs

Context: https://github.com/dotnet/android/pull/9930
Make a few tweaks to JCW serialization for https://github.com/dotnet/android/pull/9930:
- We no longer need `was_scanned`, we now write a zero byte file to indicate a file was not scanned.
- Add an overload to import from an `XElement`, as the full `.jlo.xml` file now contains additional non-JCW data.

﻿[JavaCallableWrappers] Remove `was_scanned` from `XmlImporter`/`XmlExporter`.

---

src/Java.Interop/Java.Interop/JniRuntime.JniValueManager.cs
src/Java.Interop/PublicAPI.Unshipped.txt
src/Java.Runtime.Environment/Java.Interop/ManagedValueManager.cs
tests/Java.Interop-Tests/Java.Interop/CallVirtualFromConstructorBase.cs
tests/Java.Interop-Tests/Java.Interop/CallVirtualFromConstructorDerived.cs
tests/Java.Interop-Tests/Java.Interop/InvokeVirtualFromConstructorTests.cs
tests/Java.Interop-Tests/Java.Interop/JniRuntimeJniValueManagerContract.cs

[Java.Interop] JNIEnv::NewObject and Replaceable instances (#1323)
Context: 3043d890239cf53eb42633430faa417c140c8952
Context: dec35f5453e7452acd00c84eaa91d578e39c710b
Context: https://github.com/dotnet/android/issues/9862
Context: https://github.com/dotnet/android/issues/9862#issuecomment-2705027573
Context: https://github.com/dotnet/android/pull/10004
Context: https://github.com/xamarin/monodroid/commit/326509e56d4e582c53bbe5dfe6d5c741a27f1af5
Context: https://github.com/xamarin/monodroid/commit/940136ebf1318a7c57a855e2728ce2703c0240af
Ever get the feeling that everything is inextricably related?
JNI has two pattens for create an instance of a Java type:
1. [`JNIEnv::NewObject(jclass clazz, jmethodID methodID, const jvalue* args)`][0]
2. [`JNIEnv::AllocObject(jclass clazz)`][1] + …

[Java.Interop] JNIEnv::NewObject and Replaceable instances

---

tests/Java.Interop-Tests/Java.Interop/JavaManagedGCBridgeTests.cs

Fixes a failure on NativeAOT such as:
05-01 16:44:12.720  9955  9974 I NUnit   : JavaManagedGCBridgeTests
05-01 16:44:12.721  9955  9974 I NUnit   : CrossReferences
--------- beginning of crash
05-01 16:44:12.723  9955  9999 F libc    : Fatal signal 6 (SIGABRT), code -1 (SI_QUEUE) in tid 9999 (Thread-13), pid 9955 (droid.NET_Tests)
05-01 16:44:12.753 10002 10002 I crash_dump64: obtaining output fd from tombstoned, type: kDebuggerdTombstone
05-01 16:44:12.754  1875  1875 I /system/bin/tombstoned: received crash request for pid 9999
05-01 16:44:12.755 10002 10002 I crash_dump64: performing dump of process 9955 (target tid = 9999)
05-01 16:44:12.758 10002 10002 F DEBUG   : *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
05-01 16:44:12.759 10002 10002 F DEBUG   : Build …

[Java.Interop-Tests] use `#if !NO_GC_BRIDGE_SUPPORT` for some tests

---

src/utils/NullableAttributes.cs

Context: https://github.com/dotnet/runtime/blob/2a1595eb83ec3b520d18b44236ae265d5a433640/src/libraries/System.Private.CoreLib/src/System/Diagnostics/CodeAnalysis/NullableAttributes.cs
Pull in a newer copy of `NullableAttributes.cs` from [`dotnet/runtime`](https://github.com/dotnet/runtime/blob/2a1595eb83ec3b520d18b44236ae265d5a433640/src/libraries/System.Private.CoreLib/src/System/Diagnostics/CodeAnalysis/NullableAttributes.cs) that contains `[MemberNotNull]` and `[MemberNotNullWhen]`.

Pull in updated `NullableAttributes` from `dotnet/runtime`.

---

src/Java.Interop/Java.Interop/JavaObject.cs
src/Java.Interop/Java.Interop/JniRuntime.JniTypeManager.cs
tests/Java.Interop-Tests/Java.Interop/JniTypeManagerTests.cs

Context: https://github.com/dotnet/android/pull/9913
Context: https://github.com/dotnet/android/pull/9913/commits/de49d96abbdb66debdafd241980416d475539163
Fixes: https://github.com/dotnet/java-interop/issues/1324
dotnet/android#9913 updated `JNIEnv.GetJniName(Type)` to use `JniRuntime.JniTypeManager.GetTypeSignature(Type)`.
It promptly failed on CI:
E NUnit   :  : System.NotSupportedException : 'Java.InteropTests.GenericHolder`1[T]' contains a generic type definition. This is not supported.
E NUnit   :    at Java.Interop.JniRuntime.JniTypeManager.GetTypeSignature(Type )
E NUnit   :    at Android.Runtime.JNIEnv.GetJniName(Type )
E NUnit   :    at Java.Interop.TypeManager.RegisterType(String , Type )
E NUnit   :    at Android.Runtime.JNIEnvInit.RegisterJniNatives(IntPtr , Int32 , IntPtr , …

[Java.Interop] Generic Type Definitions are allowed

---

tests/Java.Interop-Tests/Java.Interop-Tests.csproj
tests/Java.Interop-Tests/Java.Interop/JavaObjectTest.cs

I made this change locally to make unit tests pass with CoreCLR + GC Bridge build of dotnet/android. I'm still looking into ways of making this simpler and more reliable.

Best effort to await GC bridge processing in CoreCLR

---

src/Java.Interop/Java.Interop/IJavaPeerable.cs
src/Java.Interop/Java.Interop/JavaException.cs
src/Java.Interop/Java.Interop/JavaObject.cs
src/Java.Interop/Java.Interop/JniManagedPeerStates.cs
src/Java.Interop/Java.Interop/JniObjectReferenceControlBlock.cs
src/Java.Interop/PublicAPI.Unshipped.txt
src/Java.Runtime.Environment/Java.Interop/MonoRuntimeValueManager.cs
src/java-interop/java-interop-gc-bridge-mono.cc
src/java-interop/java-interop-gc-bridge.h
tests/Java.Interop-Tests/Java.Interop/JavaObjectArrayTest.cs
tests/Java.Interop-Tests/Java.Interop/JavaObjectTest.cs

Originally from: https://github.com/dotnet/java-interop/pull/1334
Context: https://github.com/dotnet/runtime/pull/114184
Context: https://github.com/dotnet/android/pull/10125
Context: https://github.com/dotnet/android/pull/10125#issuecomment-2864434118
Part of adding a GC bridge to CoreCLR are the new APIs:
namespace System.Runtime.InteropServices.Java;
public struct ComponentCrossReference {
public nint SourceGroupIndex, DestinationGroupIndex;
}
public unsafe struct StronglyConnectedComponent {
public nint Count;
public IntPtr* Context;
}
public static partial class JavaMarshal {
public static unsafe void Initialize(
delegate* unmanaged<
System.IntPtr,                  // sccsLen
StronglyConnectedComponent*,    // sccs
System.IntPtr,                  // ccrsLen
ComponentCrossReference*, …

[Java.Interop] JNI handles are now in a "control block"

---

src/Java.Interop.Tools.JavaCallableWrappers/Java.Interop.Tools.JavaCallableWrappers.Adapters/CecilImporter.cs

Context: https://github.com/dotnet/java-interop/issues/1347
A combination of NuGet packages can result in the error:
C:\Program Files\dotnet\packs\Microsoft.Android.Sdk.Windows\35.0.78\tools\Xamarin.Android.Common.targets(1503,3): error XAGJS7000:
System.AggregateException: One or more errors occurred. (Object reference not set to an instance of an object.)
---> System.NullReferenceException: Object reference not set to an instance of an object.
at Java.Interop.Tools.Cecil.CustomAttributeProviderRocks.GetCustomAttributes(ICustomAttributeProvider item, String attribute_fullname)+MoveNe
xt() in /Users/runner/work/1/s/xamarin-android/external/Java.Interop/src/Java.Interop.Tools.Cecil/Java.Interop.Tools.Cecil/CustomAttributeProvid
erRocks.cs:line 30
at …

[Java.Interop.Tools.JavaCallableWrappers] check if type cannot be resolved

---

tests/generator-Tests/expected.ji/NonStaticFields/NonStaticField.xml
tests/generator-Tests/expected.ji/NonStaticFields/Xamarin.Test.SomeObject.cs
tests/generator-Tests/expected.ji/StaticFields/StaticField.xml
tests/generator-Tests/expected.ji/StaticFields/Xamarin.Test.SomeObject.cs
tests/generator-Tests/expected.xaji/NonStaticFields/Xamarin.Test.SomeObject.cs
tests/generator-Tests/expected.xaji/StaticFields/Xamarin.Test.SomeObject.cs
tools/generator/SourceWriters/BoundFieldAsProperty.cs

Fixes: https://github.com/dotnet/android/issues/10404
Context: 57f7bc849f36ec7c3159cc7729c7276b8dcd3ca4
Commit 57f7bc84 updated `generator` to "avoid non-blittable types" in native callback methods, for which there were two non-blittables:
* System.Boolean, which should be marshaled as a System.SByte, and
* System.Char, which should be marshaled as a System.UInt16.
The problem is that this hit a codepath which was *not* "for native callback methods": field bindings.
Consider [`android.widget.RelativeLayout.LayoutParams.alignWithParent`][0]:
package android.widget;
public /* partial */ class RelativeLayout {
public /* partial */ class LayoutParams {
public boolean alignWithParent;
}
}
which is bound as [`RelativeLayout.LayoutParams.AlignWithParent`][1]:
namespace Android.Widget;
public …

[generator] Don't avoid blittable types for fields

---

src/Java.Interop.Tools.Generator/Enumification/ConstantEntry.cs
src/Java.Interop.Tools.Generator/Enumification/MethodMapEntry.cs
src/Java.Interop.Tools.Generator/Extensions/XmlExtensions.cs
src/Java.Interop.Tools.Generator/Metadata/FixupXmlDocument.cs
src/Java.Interop.Tools.Generator/Utilities/AndroidSdkVersion.cs
src/Java.Interop.Tools.Generator/Utilities/CsvParser.cs
src/Java.Interop.Tools.Generator/Utilities/NamingConverter.cs
src/utils/XmlExtensions.cs
tests/Java.Interop.Tools.Generator-Tests/Enumification/ConstantEntryTests.cs
tests/Java.Interop.Tools.Generator-Tests/Utilities/AndroidSdkVersionTests.cs
tests/Java.Interop.Tools.Generator-Tests/Utilities/NamingConverterTests.cs
tests/generator-Tests/Unit-Tests/CodeGeneratorTests.cs
tests/generator-Tests/Unit-Tests/EnumGeneratorTests.cs
tests/generator-Tests/Unit-Tests/EnumMappingsTests.cs
tests/generator-Tests/Unit-Tests/XmlApiImporterTests.cs
tools/generator/ApiVersionsProvider.cs
tools/generator/ApiVersionsSupport.cs
tools/generator/GenerationInfo.cs
tools/generator/Java.Interop.Tools.Generator.Importers/XmlApiImporter.cs
tools/generator/Java.Interop.Tools.Generator.ObjectModel/Field.cs
tools/generator/Java.Interop.Tools.Generator.ObjectModel/GenBase.cs
tools/generator/Java.Interop.Tools.Generator.ObjectModel/GenBaseSupport.cs
tools/generator/Java.Interop.Tools.Generator.ObjectModel/MethodBase.cs
tools/generator/Java.Interop.Tools.Generator.Transformation/EnumMap.cs
tools/generator/Java.Interop.Tools.Generator.Transformation/EnumMappings.cs
tools/generator/SourceWriters/Attributes/ObsoletedOSPlatformAttr.cs
tools/generator/SourceWriters/Attributes/SupportedOSPlatformAttr.cs
tools/generator/SourceWriters/Attributes/UnsupportedOSPlatformAttr.cs
tools/generator/SourceWriters/Extensions/SourceWriterExtensions.cs
tools/generator/Utilities/CsvParser.cs

[generator] Support major.minor API levels
Context: https://github.com/dotnet/android/pull/10438
Context: https://github.com/dotnet/android/pull/10438#issuecomment-3246300570
Android 16 Quarterly Platform Release 2 (QPR2) (API-CANARY) Beta 1
has been released.  What makes API_CANARY unique in the history of
Android is that it is a "minor" SDK version:
* [`<uses-sdk/>`][3]:
> It's not possible to specify that an app either targets or requires a minor SDK version.
* [Using new APIs with major and minor releases][4]:
> The new [`SDK_INT_FULL`][5] constant can be used for API checks…
>
>     if (SDK_INT_FULL >= VERSION_CODES_FULL.[MAJOR or MINOR RELEASE]) {
>       // Use APIs introduced in a major or minor release
>     }
>
> You can also use the [`Build.getMinorSdkVersion()`][6] method to
> …

[generator] Support major.minor API levels

---

src/Java.Interop.Tools.Generator/Utilities/NamingConverter.cs
tests/Java.Interop.Tools.Generator-Tests/Utilities/NamingConverterTests.cs

Context: f07b53855063a297a4b4d3d3b96900dd3729e82c
Context: https://github.com/jpobst/BindingStudio
While using jpobst/BindingStudio to enumify API-36.1, it would crash:
System.NotSupportedException: Could not parse `W` as an ApiLevel.
at Java.Interop.Tools.Generator.AndroidSdkVersion.Parse(String value) in W:\src\jpobst\BindingStudio\external\Java.Interop\src\Java.Interop.Tools.Generator\Utilities\AndroidSdkVersion.cs:line 124
at Java.Interop.Tools.Generator.NamingConverter.ParseApiLevel(String value) in W:\src\jpobst\BindingStudio\external\Java.Interop\src\Java.Interop.Tools.Generator\Utilities\NamingConverter.cs:line 21
at Java.Interop.Tools.Generator.NamingConverter.ParseApiLevel(XElement element) in W:\src\jpobst\BindingStudio\external\Java.Interop\src\Java.Interop.Tools.Generator\Util …

[Java.Interop.Tools.Generator] Improve ExtractApiLevel() resiliency
