dotnet/java-interop

- README.md
Java.Interop should be discussed on the xamarin-android channel.
> [README] Add link to gitter.im discussion channel.

- src/Xamarin.Android.NamingCustomAttributes/Android.App/ActivityAttribute.cs
- src/Xamarin.Android.NamingCustomAttributes/Android.App/ApplicationAttribute.cs
- src/Xamarin.Android.NamingCustomAttributes/Android.Content/BroadcastReceiverAttribute.cs
DO NOT MERGE THIS without merging another xamarin-android PR that I'm going to make.
This also depends on https://github.com/xamarin/xamarin-android/pull/127
> Add new manifest attributes for Android N API.

- .gitmodules
Fixes: https://bugzilla.xamarin.com/show_bug.cgi?id=56808
> Bump to cecil/mono-2017-04/1003fcb3

- build-tools/scripts/jdk.mk
Added java path finder to allow other java versions and other linux distributions.
> Added java path finder

- gendarme-ignore.txt
Added the attribute type to the list and added a description.
> [Java.Interop] Ignore unsealed attribute

- src/Java.Interop/Java.Interop/JniRuntime.JniMarshalMemberBuilder.cs
Catched by Gendarme's
https://github.com/spouliot/gendarme/wiki/Gendarme.Rules.Exceptions.UseObjectDisposedExceptionRule(2.10)
> [Java.Interop] Check for disposed state in JniMarshalMemberBuilder

- .gitmodules
> Bump to cecil/master/dfee11e

- src/java-interop/java-interop.csproj
This should fix this particular issue: https://github.com/xamarin/xamarin-android/issues/1848#issuecomment-398335920
> Fix Linux -D arguments in java-interop.csproj.

- tools/jnimarshalmethod-gen/TypeMover.cs
We were breaking some of the array types references. Some examples:
`uint8[]` became `uint8[][]` and sometimes we lost the `ArrayType`, so
array type became element type instead.
That led to breakage like this:
Error: jnimarshalmethod-gen: Unable to process assembly '/Users/rodo/git/xa3/bin/Release/lib/xamarin.android/xbuild-frameworks/MonoAndroid/v8.1/Mono.Android.dll'
VTable setup of type Org.Apache.Http.Impl.IO.AbstractSessionOutputBufferInvoker failed
System.TypeLoadException: VTable setup of type Org.Apache.Http.Impl.IO.AbstractSessionOutputBufferInvoker failed
at (wrapper managed-to-native) System.RuntimeType.GetMethodsByName_native(System.RuntimeType,intptr,System.Reflection.BindingFlags,bool)
at System.RuntimeType.GetMethodsByName (System.String name, …
> [jnimarshalmethod-gen] Fix moved array type references

- tools/jnimarshalmethod-gen/App.cs
To be able to write updated assemblies in specified directory
> [jnimarshalmethod-gen] Added -o option

- src/java-interop/java-interop-gc-bridge-mono.cc
- src/java-interop/java-interop-gc-bridge.h
- src/java-interop/java-interop-mono.h
- src/java-interop/java-interop.targets
So that we can use the sources in XA without build errors.
> [java-interop] Fix c++ related build issues

- src/Xamarin.Android.Tools.ApiXmlAdjuster/JavaApiTypeResolverExtensions.cs
When `JavaApiTypeResolverExtensions.FindNonGenericType()` is invoked, it searches through every type in every package to try to find a match.  This is ~5,000 types to search on each invocation for a default bindings project.
Since we have the full Java type name, like `java.lang.Object`, we can use that information to only look in packages that could potentially have the type:
* java
* java.lang
This helps speed up the `class-parse` case:
Scenario | Original | This PR
------------ | ------------- | -
class-parse | 13278ms | 7914ms
> [ApiXmlAdjuster] Look for types in packages more efficiently.

- tools/jnimarshalmethod-gen/App.cs
Added `-r` `--reference` option to add information about processed
assemblies references.
Also make it possible to use response file with additional command
line arguments. The file can be specified by @response_file at the
command line.
That might help with https://github.com/xamarin/xamarin-android/pull/3359
> [jnimarshalmethod-gen] New reference option and response file

- .gitmodules
Context: https://github.com/xamarin/xamarin-android/pull/3959#issuecomment-558358410
Changes: https://github.com/jbevain/mono.linq.expressions/compare/e3372fbb49c59d9616b22333fb22045acad110c1...7973f862ddfea552457c7b2bc457fb87c481a791
* jbevain/mono.linq.expressions@7973f862: Port to .NET SDK style projects
> Bump to jbevain/mono.linq.expressions/master@7973f862

- build-tools/automation/azure-pipelines.yaml
Had to add an explicit NuGet restore to build it on Windows because 🤷‍♂.
(Project changed from legacy .csproj to short-form .csproj.)
> Bump to xamarin/xamarin-android-tools/master@bfb66f38

- build-tools/automation/azure-pipelines.yaml
It appears the one specified in the AzDO UI is no longer functioning.
> [CI] Specify our PR build trigger in YAML.

- src/Java.Interop.Tools.Generator/Java.Interop.Tools.Generator.csproj
Specify `$(UtilityOutputFullPath)` as the `<OutputPath>` for `Java.Interop.Tools.Generator.dll`.
> [J.I.T.Generator] Specify "OutputPath".

- build-tools/scripts/RunNUnitTests.targets
- tests/Java.Interop-PerformanceTests/Java.Interop-PerformanceTests.csproj
- tests/Java.Interop-Tests/Java.Interop-Tests.csproj
- tests/Java.Interop.Dynamic-Tests/Java.Interop.Dynamic-Tests.csproj
- tests/Java.Interop.Export-Tests/Java.Interop.Export-Tests.csproj
- tests/Java.Interop.Tools.Generator-Tests/Java.Interop.Tools.Generator-Tests.csproj
- tests/Java.Interop.Tools.JavaCallableWrappers-Tests/Java.Interop.Tools.JavaCallableWrappers-Tests.csproj
- tests/Java.Interop.Tools.JavaSource-Tests/Java.Interop.Tools.JavaSource-Tests.csproj
- tests/TestJVM/TestJVM.csproj
- tests/Xamarin.Android.Tools.ApiXmlAdjuster-Tests/Xamarin.Android.Tools.ApiXmlAdjuster-Tests.csproj
- tests/Xamarin.Android.Tools.Bytecode-Tests/Xamarin.Android.Tools.Bytecode-Tests.csproj
- tests/generator-Tests/generator-Tests.csproj
- tests/logcat-parse-Tests/logcat-parse-Tests.csproj
Update NUnit libraries to latest:
* nunit - 3.12.0
* NUnit.ConsoleRunner - 3.11.1
* NUnit3TestAdapter - 3.16.1
> Update NUnit to latest.

- .gitmodules
- build-tools/automation/azure-pipelines.yaml
Changes: https://github.com/xamarin/xamarin-android-tools/compare/f2af06f...26d65d9
> Bump to xamarin/xamarin-android-tools@26d65d9

- tools/logcat-parse/logcat-parse.csproj
Changes: https://github.com/mono/LineEditor/compare/3fa0c2eb46b79b958a028b063d295a304cdb4842...5d67d34ec26527eb30db067c614dfa0d29bc8739
* mono/LineEditor@5d67d34: Use the new signing features for RealSigning (#10)
> Bump to mono/LineEditor/v5.4.2@5d67d34e

- Documentation/Architecture.md
- Documentation/BuildConfiguration.md
- Documentation/Motivation.md
- README.md
Update and modernize `README.md`:
- Update build instructions for the `dotnet` era.
- Prioritize general content: explanation, building, contributing.
- Move advanced content to `Documentation` pages and provide links.
> Modernize README.

- Localize/loc/cs/src/Java.Interop.Localization/Resources.resx.lcl
- Localize/loc/de/src/Java.Interop.Localization/Resources.resx.lcl
- Localize/loc/es/src/Java.Interop.Localization/Resources.resx.lcl
- Localize/loc/fr/src/Java.Interop.Localization/Resources.resx.lcl
- Localize/loc/it/src/Java.Interop.Localization/Resources.resx.lcl
- Localize/loc/ja/src/Java.Interop.Localization/Resources.resx.lcl
- Localize/loc/ko/src/Java.Interop.Localization/Resources.resx.lcl
- Localize/loc/pl/src/Java.Interop.Localization/Resources.resx.lcl
- Localize/loc/pt-BR/src/Java.Interop.Localization/Resources.resx.lcl
- Localize/loc/ru/src/Java.Interop.Localization/Resources.resx.lcl
- Localize/loc/tr/src/Java.Interop.Localization/Resources.resx.lcl
- Localize/loc/zh-Hans/src/Java.Interop.Localization/Resources.resx.lcl
- Localize/loc/zh-Hant/src/Java.Interop.Localization/Resources.resx.lcl
LEGO: Pull request from juno/hb_1b3ab5ae-8597-41e0-a524-66435235e34c_20220725205302830 to main with localized lcls
> LEGO: Pull request from juno/hb_1b3ab5ae-8597-41e0-a524-66435235e34c_20220725205302830 to main

- Localize/loc/pt-BR/src/Java.Interop.Localization/Resources.resx.lcl
LEGO: Pull request from juno/hb_1b3ab5ae-8597-41e0-a524-66435235e34c_20220728073242049 to main with localized lcls
> LEGO: Pull request from juno/hb_1b3ab5ae-8597-41e0-a524-66435235e34c_20220728073242049 to main

- Localize/loc/de/src/Java.Interop.Localization/Resources.resx.lcl
- Localize/loc/es/src/Java.Interop.Localization/Resources.resx.lcl
- Localize/loc/fr/src/Java.Interop.Localization/Resources.resx.lcl
- Localize/loc/it/src/Java.Interop.Localization/Resources.resx.lcl
- Localize/loc/ko/src/Java.Interop.Localization/Resources.resx.lcl
- Localize/loc/ru/src/Java.Interop.Localization/Resources.resx.lcl
- Localize/loc/zh-Hans/src/Java.Interop.Localization/Resources.resx.lcl
- Localize/loc/zh-Hant/src/Java.Interop.Localization/Resources.resx.lcl
LEGO: Pull request from juno/hb_1b3ab5ae-8597-41e0-a524-66435235e34c_20220729073258885 to main with localized lcls
> LEGO: Pull request from juno/hb_1b3ab5ae-8597-41e0-a524-66435235e34c_20220729073258885 to main

- Localize/loc/cs/src/Java.Interop.Localization/Resources.resx.lcl
- Localize/loc/ja/src/Java.Interop.Localization/Resources.resx.lcl
- Localize/loc/pl/src/Java.Interop.Localization/Resources.resx.lcl
- Localize/loc/tr/src/Java.Interop.Localization/Resources.resx.lcl
LEGO: Pull request from juno/hb_1b3ab5ae-8597-41e0-a524-66435235e34c_20220730073325962 to main with localized lcls
> LEGO: Pull request from juno/hb_1b3ab5ae-8597-41e0-a524-66435235e34c_20220730073325962 to main

- src/Java.Interop.Tools.JavaCallableWrappers/Java.Interop.Tools.JavaCallableWrappers/JavaCallableWrapperGenerator.cs
Running PerfView on Windows in a .NET MAUI app, I can see this taking up time inside the `<GenerateJavaStubs/>` MSBuild task:
| Name | Inc % |   Inc |
| --- | --: | --: |
| java.interop.tools.javacallablewrappers!Java.Interop.Tools.JavaCallableWrappers.JavaCallableWrapperGenerator..ctor() |   1.4 |    51 |
| mscorlib.ni!String.Format | 1.0 | 35 |
Around ~35ms appear to be spent inside `JavaCallableWrapperGenerator` doing `string.Format()`.
Reviewing the code, there is quite a bit of `WriteLine()` used along with format arguments. I could rework this to use string interpolation, which would be slightly better -- as the C# compiler could replace many of these with `string.Concat()`.
However, the best case is to just call `Write()` with individual strings, so we don't do extra work creating …
> [JavaCallableWrappers] avoid `string.Format()`

- Localize/loc/cs/src/Java.Interop.Localization/Resources.resx.lcl
- Localize/loc/es/src/Java.Interop.Localization/Resources.resx.lcl
- Localize/loc/it/src/Java.Interop.Localization/Resources.resx.lcl
- Localize/loc/ru/src/Java.Interop.Localization/Resources.resx.lcl
- Localize/loc/zh-Hant/src/Java.Interop.Localization/Resources.resx.lcl
LEGO: Pull request from juno/hb_1b3ab5ae-8597-41e0-a524-66435235e34c_20230522073539732 to main with localized lcls
> LEGO: Pull request from juno/hb_1b3ab5ae-8597-41e0-a524-66435235e34c_20230522073539732 to main

- Localize/loc/pl/src/Java.Interop.Localization/Resources.resx.lcl
LEGO: Pull request from juno/hb_1b3ab5ae-8597-41e0-a524-66435235e34c_20230523073720616 to main with localized lcls
> LEGO: Pull request from juno/hb_1b3ab5ae-8597-41e0-a524-66435235e34c_20230523073720616 to main

- Localize/loc/de/src/Java.Interop.Localization/Resources.resx.lcl
- Localize/loc/fr/src/Java.Interop.Localization/Resources.resx.lcl
- Localize/loc/ja/src/Java.Interop.Localization/Resources.resx.lcl
- Localize/loc/ko/src/Java.Interop.Localization/Resources.resx.lcl
- Localize/loc/pt-BR/src/Java.Interop.Localization/Resources.resx.lcl
- Localize/loc/tr/src/Java.Interop.Localization/Resources.resx.lcl
- Localize/loc/zh-Hans/src/Java.Interop.Localization/Resources.resx.lcl
LEGO: Pull request from juno/hb_1b3ab5ae-8597-41e0-a524-66435235e34c_20230530073509785 to main with localized lcls
> LEGO: Pull request from juno/hb_1b3ab5ae-8597-41e0-a524-66435235e34c_20230530073509785 to main

- src/Java.Interop.Localization/Resources.cs.resx
- src/Java.Interop.Localization/Resources.de.resx
- src/Java.Interop.Localization/Resources.es.resx
- src/Java.Interop.Localization/Resources.fr.resx
- src/Java.Interop.Localization/Resources.it.resx
- src/Java.Interop.Localization/Resources.ja.resx
- src/Java.Interop.Localization/Resources.ko.resx
- src/Java.Interop.Localization/Resources.pl.resx
- src/Java.Interop.Localization/Resources.pt-BR.resx
- src/Java.Interop.Localization/Resources.ru.resx
- src/Java.Interop.Localization/Resources.tr.resx
- src/Java.Interop.Localization/Resources.zh-Hans.resx
- src/Java.Interop.Localization/Resources.zh-Hant.resx
This is the pull request automatically created by the OneLocBuild task in the build process to check-in localized files generated based upon translation source files (.lcl files) handed-back from the downstream localization pipeline. If there are issues in translations, visit https://aka.ms/icxLocBug and log bugs for fixes. The OneLocBuild wiki is https://aka.ms/onelocbuild and the localization process in general is documented at https://aka.ms/AllAboutLoc.
> Localized file check-in by OneLocBuild Task: Build definition ID 12262: Build ID 7838962

- src/Java.Interop.Localization/Resources.cs.resx
- src/Java.Interop.Localization/Resources.de.resx
- src/Java.Interop.Localization/Resources.es.resx
- src/Java.Interop.Localization/Resources.fr.resx
- src/Java.Interop.Localization/Resources.it.resx
- src/Java.Interop.Localization/Resources.ja.resx
- src/Java.Interop.Localization/Resources.ko.resx
- src/Java.Interop.Localization/Resources.pl.resx
- src/Java.Interop.Localization/Resources.pt-BR.resx
- src/Java.Interop.Localization/Resources.ru.resx
- src/Java.Interop.Localization/Resources.tr.resx
- src/Java.Interop.Localization/Resources.zh-Hans.resx
- src/Java.Interop.Localization/Resources.zh-Hant.resx
This is the pull request automatically created by the OneLocBuild task in the build process to check-in localized files generated based upon translation source files (.lcl files) handed-back from the downstream localization pipeline. If there are issues in translations, visit https://aka.ms/icxLocBug and log bugs for fixes. The OneLocBuild wiki is https://aka.ms/onelocbuild and the localization process in general is documented at https://aka.ms/AllAboutLoc.
> Localized file check-in by OneLocBuild Task: Build definition ID 12262: Build ID 7873259

- src/Xamarin.SourceWriter/Models/MethodWriter.cs
- tests/generator-Tests/Unit-Tests/CodeGeneratorTests.cs
- tests/generator-Tests/Unit-Tests/DefaultInterfaceMethodsTests.cs
- tools/generator/Java.Interop.Tools.Generator.Importers/XmlApiImporter.cs
- tools/generator/Java.Interop.Tools.Generator.ObjectModel/ClassGen.cs
- tools/generator/Java.Interop.Tools.Generator.ObjectModel/Method.cs
- tools/generator/SourceWriters/BoundMethodAbstractDeclaration.cs
- tools/generator/SourceWriters/ClassInvokerClass.cs
- tools/generator/SourceWriters/Extensions/SourceWriterExtensions.cs
CP commits of `generator` changes needed by API-34 to .NET 7 release branch:
- https://github.com/xamarin/java.interop/pull/1128/commits/7c18f80fb52e5a4113078702dc2da32f81c1bc3d
- https://github.com/xamarin/java.interop/pull/1128/commits/73a1d550503b053780eaf1c174e99b75638751a2
> Cherry pick commits needed for backporting API-34 to .NET 7
